### ISSUE TITLE
LARMOR: Add additional Galil IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1002]
As a scientist, I need up to 10 Galil IOCs, so that I can control all the motors needed on LARMOR.

#### Acceptance Criteria
1. Support for 10 Galil IOCs is added to LARMOR's configuration
1. Table of Motors view supports at least 10 Galil IOCs.
1. I can control any of 10 x 8 motors.

#### Notes
1. In principle, the ToM view can support any number of Galil IOCs.  This is simply be a matter of configuration, no changes are needed to the GUI; provided the new motors have PV names such as IN:LARMOR:MOT:MTR901 then everything will just work.
1. Check for name clashes (e.g. is another type (non-Galil) of motor in use).
1. Increased number of Galil IOCs from 9 to 10 after discussion with Gareth (daily stand-up meeting 1st April 2016).  See the following:

> If Rob wheels up an additional Galil crate – he needs to be able to add the Galil 
> to the system.  We just need a little scope for expansion. This has happened once already.

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 1004.  Created by skn09965 on 2015-12-08T10:58:32, last modified: 2016-01-28T10:09:55_

**Comment by IsabellaRey** [comment]
See pull request ISISComputingGroup/EPICS-ioc#36

###############################

To test:
Get the branch changes.
Make sure the macros for Galil 9 and 10 are set in your global.txt file, as described in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motor-Galil-SetPoints
Before starting your instrument, you'll need to add the new IOCs to the list of IOCs that the instrument knows about: to do this, open an EPICS terminal and run:
      make iocstartups

Start the instrument
Verify that the new IOCs are known with the command:
    console -M localhost -x

Start the GUI
Start the new IOCs and verify that you can access the corresponding motors in the motors view, rows 9 and 10 (that's the second tab!)

###############################

Regarding the naming conflict:
As there are other motor IOCs, I have found two potential naming conflicts:

1. The PIMOT IOC had a macro MTRCTRL hard-coded to 10 in its st.cmd file (this would have conflicted with galil 10). I have removed this line and added a comment that this macro should be set in the globals.txt file, which is consistent with what is done in SMC100 and CONEXAGP.  Freddie says the PIMOT IOC is not in use right now anyway, because they were still trying to get it to work properly, so this change doesn't affect anyone.

2. In the LARMOR globals.txt file, there was a line setting the MTRCTRL macro of CONEXAGP to 10 (again, this would conflict with galil 10), but this line was commented out. I have changed the macro value to something higher, and left a note in a comment just above that line that it has been changed and why.

Freddie confirmed that apart from SMC100, PIMOT and CONEXAGP there are no other motor IOCs.

**Comment by KathrynBaker** [comment]
One query regarding the naming conflict, just to be aware of for releasing - were there any references in any synoptics, configurations or components to the existing MTR10?

**Comment by IsabellaRey** [comment]
Hmmmm... good point. I haven't checked that. Is that relevant only for LARMOR?

**Comment by KathrynBaker** [comment]
Possibly IMAT as well, same for the globals.txt, but most likely on LARMOR

**Comment by IsabellaRey** [comment]
OK, thanks, I'll move the ticket back in progress

**Comment by KathrynBaker** [comment]
As I was part way through, I have finished looking at the underlying code changes, and so long as those don't change it works and as far as I can tell is ready for merging. At the moment the globals.txt files, synoptics, configs and components as things we can edit manually - just with a note to do so in relation to a release, and hopefully #1217 will provide a better long term solution

**Comment by IsabellaRey** [comment]
I have checked IMAT and LARMOR, and found a couple of files where MTR09 was used. I have entered details in a TODO section for the next release: https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_v2.0.0
