### ISSUE TITLE
Package the genie_python simulator

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1104]
Rob's suggestion was to have the simulator run in a separate cmd line from "real" genie_python, to avoid confusion.
We need to create a `start_genie_python_simulator.bat` and it needs to be clear that it is a simulation, not a real instance.
We need to ensure that when  we load a user script that imports genie_python it still uses the simulation genie_python API - this might require some thinking about to get correct.

``` python
from genie_python.genie import *

def myscript():
    change(title="Test title")    
    begin()
    waitfor(uamps=50)
    abort()

```

**Comment by ChrisM-S** [comment]
I can’t remember from previous discussions, but do/should simulated commands have an ability to log their own calls and parameters as they run (and expected time taken to execute – e.g. waitfor) so that the scientist checking can look at the timeline and commands actually issued in a simulation log somewhere – even on the screen?
e.g. from below

2016 09:05:45     change title=”Test title”
2016 09:05:46     begin     run=00004567
2016 09:05:45     waitfor uamps=50 (beamcurrent assumed 5uA/min)
2016 09:15:46     abort     run=00004567
…

I’m assuming that the script simulations run separately from the back end but could make some useful assumptions or even allow some initialization at the beginning of the simulation from default or even real instrument parameters available from PVs in real time (e.g. run number, beam current at the time).  Unwinding loops in this way could definitely help people spot off by one errors etc.

Chris
