### ISSUE TITLE
GUI - Hackathon: Dialogue for editing device screens

### ISSUE THREAD

**Issue by ianbush** [ISISComputingGroup/IBEX#1125]
Add a dialogue for editing the device screens. Can continue from changes on this branch - https://github.com/ISISComputingGroup/ibex_gui/commits/Ticket1083_opening_an_OPI_oustide_of_a_synoptic.

**Comment by AdrianPotter** [comment]
For design notes:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Hackathon---Opening-an-OPI-Outside-of-a-Synoptic

**Comment by AdrianPotter** [comment]
Rather than having an "edit list" button, @John-Holt-Tessella has suggested having an edit and delete icon at the right of each item on the list allowing them to be edited individually. The list would then have an add button somewhere to add new devices. This removes the need for a self-enclosed edit list dialogue. Worth having a quick design discussion with developers before embarking on implementation.

**Comment by John-Holt-Tessella** [comment]
See #1724
