### ISSUE TITLE
MUON FRONT END: Recover setpoints, and ensure they are applied

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1209]
NEEDED SEPTEMBER 2016 CYCLE

As a support person involved in supporting the muon front end I want to be able to easily recover and reapply the settings of the power supplies controlling the magnets on the beamline

**Acceptance Criteria**
1. Make sure the reset commands are available for each PSU in use
2. The setpoint values should be autosaved
3. On computer startup the saved setpoint values should be applied to the PSUs
4. There should be an obvious button/command that would allow these values to be set 

**Notes**
1. The setpoints to recall, and re=apply are Voltage, Current and Power
2. These reset commands (criteria 1) should all be in place already in the protocol/db files
3. Should there be a power dip, then the power supplies could reset to incorrect values (or to being off), a power dip is unlikely to effect the control server. The recovery procedure is sometimes undertaken by the people on site (MCR), and as such an easy method to reapply the default settings is needed, ideally with one simple command or a button to press

**Comment by IsabellaRey** [comment]
Following discussion with Freddie, Kathryn and Chris:

The more generic problem is about being able to save and restore snapshots of a set of PVs: this has been captured in a separate ticket ISISComputingGroup/IBEX#1449

For the current ticket, a fairly quick solution is to give the user access to a macro (for the each relevant IOCs) they can set which means "Apply last set points at startup", and have a way to re-load the current configuration from scratch (so that IOCs get stopped and re-started).
This boils down to:
* Make sure the relevant PVs are being autosaved with an info field (the IOCs in question are TDKLambdaGenesis and Danfisik)
* Set the PINI fields of these PVs as macros that can be bubbled up all the way to the OPI through the config.xml file (default PINI value should be NO)
* Make sure we can re-load the current configuration

**Comment by kjwoodsISIS** [comment]
@IsabellaRey - do we have an estimate for this story?

**Comment by IsabellaRey** [comment]
I'll give it a 2, just because there are some parts I haven't touched, so I might need to dig slightly into it

**Comment by IsabellaRey** [comment]
Moving back to ready just while I finish reviewing two other stories which have been reworked.

**Comment by IsabellaRey** [comment]
I'm un-assigning myself from this one while I still have to review other more urgent tickets. Anyone who gets here before me feel free to pick this up!

**Comment by IsabellaRey** [comment]
QUESTION:   I have a configuration setup, then I start an IOC that is not set to start as part of the configuration. If I re-load the configuration or load other ones, this IOC just keeps running. Is this a problem for the scenario of this ticket? Worth checking with Kathryn and Freddie.

**Comment by kjwoodsISIS** [comment]
It doesn't sound like a problem to me.  The user can always stop the IOC, if he/she wishes.
We don't currently have a requirement that says that all running IOCs have to be halted when the user changes configuration.  In fact, if we did implement such a requirement, it would slow down the process of switching configuration, which would probably irritate many (if not all) users.

**Comment by KathrynBaker** [comment]
Not a problem as far as I’m concerned.

**Comment by IsabellaRey** [comment]
For the current ticket, it is enough to be able to reload the current config with a python script.
Ability to do this from the GUI is a nice-to-have, captured in ISISComputingGroup/IBEX#1497

**Comment by IsabellaRey** [comment]
Pull requests (to be tested in this order):
* ISISComputingGroup/EPICS-ioc#67
* ISISComputingGroup/EPICS-inst_servers#69
* ISISComputingGroup/EPICS-genie_python#43

Details on each pull request
