### ISSUE TITLE
MUON FRONT END: Remotely start/stop runs on an instrument

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1211]
NEEDED SEPTEMBER 2016 CYCLE

As a scientist on the muon beamlines I want to tune my front end magnets, in order to do this I need to start/stop runs on HIFI, MUSR and EMU from a system which has control of the front end magnets

**Acceptance Criteria**
1. A run can be started and stopped remotely from a script

**Notes**
1. The tuning scripts will run on a system separate from each of the instruments
2. There will either need to be a python script, or an IOC and associated PVs which will allow the start/stop buttons on the DAE on each instrument to be pressed simultaneously
3. This start will also need to allow for various wait conditions:
* wait for events
* wait for counts
* wait for good frames

**Comment by kjwoodsISIS** [comment]
Do we need something to display the state of each of the 3 muon instruments on the front-end?
@KathrynBaker  to ask the muon team.

Might be able to put DAE IOC on each muon control PC and display on muon FE.  This would be another ticket.

**Comment by KathrynBaker** [comment]
Just to ensure clarity, the front end is planned to work in a server only mode, and much of the interface work to be undertaken via an analysis PC. That PC would need to be able to start/stop the runs, and then pick up the data from those runs. As such there is no need for the front end to have any knowledge of the existing systems, except to generate/gather this data in order to allow the beamline to be tuned.

That remote start/stop is achievable via DCOM, and would need to be undertaken from genie_python, or possibly directly from Mantid.

**Comment by FreddieAkeroyd** [comment]
genie_seci_api.py in genie_python is a good place to start for ideas. It uses the "instapi.api" COM component, but may be easier to talk to "isisicp.dae" directly in this case.  One you have created a reference to this component, try calling the beginRun() method on it and that should start a run.

**Comment by AdrianPotter** [comment]
Thanks, I got that far. My main question is, where is "instapi.api" defined? From the code, it is used to initialise a DCOM session which makes various end-points available. Where is "instapi.api", or similarly "isiscp.dae" called from? Or rather, how do I know what's contained in the API?

**Comment by AdrianPotter** [comment]
All of the code is available in the repo:

https://github.com/ISISComputingGroup/mfe_control_scripts

You can either write your own Python that uses the multipleDaeController class or go straight for run_interactively to play with the functionality.

The functionality has been tested locally as well as with the three MFE machines. Keep in mind that if you connect to the MFE instruments, you'll need to switch them into simulation mode before running. To switch to simulation mode:

1. Change the "simulate" record value in `C:\Instrument\LabView Modules\dae\icp_config.xml` to 1
1. Restart SECI

Don't forget to switch it back when you're done! Note that the "end" command is currently aliased to "abort" because it avoids putting the run RB numbers out of sync.

The script should allow you to begin, end, abort, pause and resume runs. You can also get the number of events, frames and counts, as well as issue waitfor commands. The waitfors can also be initiated as part of the begin command.
