### ISSUE TITLE
MUON FRONT END: Documentation to aid scripting

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1212]
NEEDED SEPTEMBER 2016 CYCLE

As a scientist on the muon instruments I want to write tuning scripts in Mantid to correlate the data captured on HIFI, MUSR and EMU with tuning settings on MUONFE.

**Acceptance Criteria**
1. There is documentation explaining how to start/stop runs on each instrument remotely
2. There is documentation explaining how to access the blocks on IN:MUONFE to write the tuning control scripts via Mantid/Genie Python
3. There is documentation detailing the methods to switch between access gateway setups
4. There is a documentation covering the easy re-apply settings procedure

**Comment by kjwoodsISIS** [comment]
There is a [User Manual page](http://shadow.nd.rl.ac.uk/ibex_user_manual/MuonFEScriptGuidance) to provide guidance for writing scripts for MUONFE.  At present, the page is just a skeleton - individuals need to add content.

**Comment by IsabellaRey** [comment]
I've added documentation for point (4) above

**Comment by AdrianPotter** [comment]
I've added documentation for point (1)

**Comment by KathrynBaker** [comment]
I've put in some notes for (2) and (3), so am moving for review. The notes for (2) may not quite be complete, but assuming that #1660 does get done, it should be all that is needed.

**Comment by John-Holt-Tessella** [comment]
Please make the page navigatable from the home page.
1.1. Has extra line "Insert documentation explaining how to start/stop runs on each instrument remotely." In it. Split this section into two. Setting up additional machines (although maybe this goes in the support manual) and starting/stopping.
1.2. Link genie python commands to genie python documentation
2.1. Reference to configurations
2.2. Give command to set instrument
3.1. "In order to limit the systems listed in globals.txt to read only then sending the following command should be entered into an EPICS prompt:" -> "Machines listed in the globals.txt can be restricted to read only access by sending the following command:"
3.2. Would it be better to move all setup stuff to the dev wiki? Then just leave the commands to set the gateway links. 
4.1. Can we add a bit what values are being set and why you might want to do this?

I feel like the above is negative but I really like the documentation.

**Comment by AdrianPotter** [comment]
No worries @John-Holt-Tessella, thanks for the review. I've edited your comments above into a checklist. As this is a multi-assignee ticket, I'll do all the points I can I might have to leave some based on work I'm not familiar with

**Comment by AdrianPotter** [comment]
```
Please make the page navigable from the home page.
```

I've added an instrument page to the home page and linked it from the side bar. This subsequently links to the MFE page. The MFE page is already linked to on the scripting page.

**Comment by KathrynBaker** [comment]
Regarding 3.2 - The setup stuff is minimal in this section, the setup stuff I put in there was what I could see the instrument scientist wanting easily - so it is more of a subsection with specific details for this system.

Regarding 4.1 - The values being set are listed, the why feels self explanatory, as it is as simple as "these values need to be reset"

**Comment by IsabellaRey** [comment]
4.1 - I've added an example of when it's useful to have the option to  re-apply settings.
