### ISSUE TITLE
Synoptic save as not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1240]
Rob has reported that "save as" does not work properly with synoptics. You can save an existing synoptic under a new name, but you are then unable to edit the newly created synoptic. He is trying to create some new synoptics using existing ones as bases.

**Comment by kjwoodsISIS** [comment]
Further information from Rob:
_Entered on 01/06/2016 at 13:14:45 BST (GMT+0100) by ISIS Computing Support:_
If I try to save an existing synoptic using saveas the result is an empty synoptic.

_Entered on 01/06/2016 at 13:18:01 BST (GMT+0100) by ISIS Computing Support:_
Actually, the previous statement was not quite correct.
The synoptic is not empty is not actually empty having used saveas.
It just doesn't display when you select it. if you scroll through and then up 
the view appears.
Still... It's a bug

_Entered on 01/06/2016 at 13:21:29 BST (GMT+0100) by ISIS Computing Support:_
Further to the previous 2 bugs.  the synoptic shows but is not editable after using saveas

**Comment by kjwoodsISIS** [comment]
Rob confirms that he is using the following versions:
Client: 1.0.0.415
Server: 47afcda

**Comment by John-Holt-Tessella** [comment]
Appears that this is fixed in the latest version of the client that was placed on the Larmor as part of anther change. It can not currently be reproduced. 
If we have this problem again it appears that it is just certain synoptics that are broken. This one had `<pvtype>REMOTE_PV</pvtype>` on the synoptic copied but not in the broken one (i.e. the one that didn't display), that was the only difference. However simply placing the broken synoptic in an old block server didn't appear to fix the problem.
