### ISSUE TITLE
Some system tests failing on Jenkins

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1241]
As a developer, I want the system tests on Jenkins to pass. Currently 3 are failing:

DAEExperimentTabsAreDisabledIfRunning
DAEExperimentTabsAreEnabledIfNotRunning
AddFirstBlock

The AddFirstBlock is failing because blocks cannot now be added without a description. The test needs updating.

The failure of the new DAE tests has yet to be determined. Preliminary tests suggested that there are experiment setup parameters that may raise an exception on "Send changes", but the exact trigger and solution hasn't been determined.

Acceptance criteria: All 6 of the tests currently in place in the current set pass:

http://epics-jenkins.isis.rl.ac.uk/job/System_Tests/109/

**Comment by AdrianPotter** [comment]
This ticket would benefit from fixing ticket #1168. I believe the problem is that the initial instrument setup leaves it in an "unknown" state because there is no last known config. The assertion that the instrument is in a setup state will always fail.

We can modify the tests to enter a standard state but it shouldn't be an necessary work around.

**Comment by AdrianPotter** [comment]
I've created a pull request for the new test to get the instrument into its correct initial state:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/6

**Comment by IsabellaRey** [comment]
Merged with one small refactor so that the code uses the existing procedure to verify instrument is in SETUP mode

**Comment by AdrianPotter** [comment]
The add first block test has been fixed as expected. However, the test for getting the instrument in the initial "setup" state is still failing, and the DAE tests with it.

**Comment by AdrianPotter** [comment]
Part of the issue is that not only are our tests stateful, but the state of the system is persisted between runs on the system tests. This means there's no way to satisfactorily reproduce issues locally. We need the Jenkins startup script to essentially create a new instrument, run tests on it and then tear it down at the end.

**Comment by ChrisM-S** [comment]
Hi Adrian,

yes, this is the wider problem we have with all our control machines.  They “rust” as software is installed/removed/changed and so instead of essentially one system replicated 40 times predictably (with custom settings) we end up with 40 separate maintenance “stories” which represent maintenance issues.  The problem you are seeing with repeatable testing state between tests manifests itself in the uncertainty of tested software which works on one system but is not certain to work on another.

What I’m currently doing is building a “boilerplate” control system for IRIS/OSIRIS (OS+patches+required modules+base apps) from a script (MDT based).  By capturing uncertainties and building the system from not from live updates and kits, but from saved binaries, including saved web updates (which are fashionable currently but a great potential source of uncertainty as you were finding with eclipse!).

The gap to be closed is finding a way of getting IBEX-Client and/or IBEX-Server onto the boilerplate system in a predictable automated way for testing (with an appropriate post install update to install settings files).  Which is where something like an MSI installer would help.

I need to put together a new build system for the current version of MDT very soon and as Jenkins seems to be functioning well on the Windows 2012 R2 server it currently resides on, I would propose moving Jenkins to share the new MDT server  (a faster server with an SSD system disk) – i.e. the whole system can then be built as one from scratch, then tested and deployed mainly by replication.

Chris

**Comment by AdrianPotter** [comment]
Thanks for the advice Chris. It would be much easier to have an MSI, or even a container to load the initial configuration. I leave that for ticket #1165.

The simulated instrument data is contained in C:\data. Having spoke to @FreddieAkeroyd, clearing that should let us return the instrument to a clean state so I'll give that a try...

**Comment by AdrianPotter** [comment]
I've made the following changes:

- Replaced "wait"s with "try"s to improve run time
- Fixed "add first block" test now that a PV is required
- Cleared out the simulated instrument at startup

The system tests are now all green! The PR is:

https://github.com/ISISComputingGroup/ibex_system_tests/pull/9
