### ISSUE TITLE
GUI: The nebula P2 site has disappeared!

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1242]
There is now a version 1.0.0 repo, so we should move to that.
We should check it does not break anything (the DAE graphs!) first.

http://download.eclipse.org/nebula/releases/1.0.0

**Comment by AdrianPotter** [comment]
The link has been fixed in the GUI, thanks.

However, the new link just points to the new location of the old version of the plugin, not the 1.0.0 version as Matt suggests above.

We could put it in now but as LAMOR is down, we have no way to test the fix on updating DAE spectra (since simulated instruments don't currently cause updates).

I'm therefore setting the ticket to impeded until LAMOR is back running.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/316
