### ISSUE TITLE
Standardise IOC macro names

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1246]
It would be helpful if there were conventions for macro names, as there are for PV names. So, for example, we always call the communication port the same name, any calibration file and path etc. This ticket is just about choosing the names, editing later...

**Comment by KathrynBaker** [comment]
As this was coming up in conversation, I have actually started a page on the wiki of the developers manual https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Macro-Naming

Which lists much of what is already set via globals.txt on LARMOR, and a few others that I know about, or have been discussing already. This gives us a starting point for the conversation, and a reference at the end. I may add in some of the other IOC specific macros that I can see, as that would help us refine what needs to be corrected and which we are aware of.

We might also want to highlight values that MUST use a macro (such as COM port/IP address), and those which can (such as BAUD rates where a device will have a default that can be used if the value isn't set). There are probably a few other categories, such as calibration information, which may be required for one IOC, optional in another, and really not needed in others, although those could always be treated as could sets rather than must sets.

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/tree/master/COMMON
