### ISSUE TITLE
DAE/genie: begin() command should not affect running instrument

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#1332]
1. Start the instrument running
2. Open a scripting window
3. Run the begin() command

Command returns "ERROR: BEGIN" but you'll notice the instrument changes state from RUNNING to BEGINNING before returning to RUNNING.

I don't think the begin command should be able to affect the state of a running instrument at all.

**Comment by AdrianPotter** [comment]
Same with Paused run

**Comment by AdrianPotter** [comment]
It doesn't seem that the run is affected by the command. It's just disconcerting to see the state change at all

**Comment by FreddieAkeroyd** [comment]
OK, the problem here is that "transition states" such as "beginning" are IBEX only and not known by the underlying ISISICP. The IOC puts the system into transition state, calls the isisicp, and then takes it out. So the solution would be to check if a transition is valid before starting, however have to be careful about introducing possible race conditions based on state. Ideally "checkTransitionValid" would be a call to the ISISICP, but that would then necessitate a new isisicp on all instruments. The alternative is to reproduce the allowed state change logic in the IOC itself which is not a huge amount of duplication.

- [ ] create checkStateChangeValid() DAE function
- [ ] call the function if DAE is not in a transition state
- [ ] only proceed if this allowed

Because the ISISICP queues requests and the   checkStateChangeValid() and actual state change command are executed separately there may be the possibility of getting an incorrect response if commands were executed too close together, I think so long as all the commands are from EPICS the asyn locks will prevent this but if e.g. an external source was also writing directly to the ISISICP it may not always work.
