### ISSUE TITLE
IRIS: Create Prototype Configuration & Synoptic

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1393]
As developer, I would like to create a prototype configuration and synoptic for IRIS, so that I can demonstrate IBEX to the IRIS instrument scientists.

##### Acceptance Criteria
1. I can demonstrate how to create and edit configurations on IBEX to IRIS instrument scientists.
1. I can demonstrate how to create and edit synoptics on IBEX to IRIS instrument scientists.

##### Notes
1. None.

**Comment by kjwoodsISIS** [comment]
Configuration & Synoptic should contain the following devices:
1. Mk3 Chopper
1. 2 x monitors
1. 2 x TPG300 vacuum devices
1. 1 x TPG26x device
1. 1 x Lakeshore 218
1. 1 x Lakeshore 336
1. Sample changer, configured for IRIS sample can
1. McLennan Motors
   1. to rotate the centre-stick
   1. to rotate the centre stick
1. 6 x Eurotherms

**Comment by AdrianPotter** [comment]
A few issues from this morning:

- CRYVALVE does not start correctly in RECSIM mode. Floods the log with scan messages
- I thought there was an issue with the PDR 2000 in RECSIM mode as well, but it turned out  I hadn't correctly turned on RECSIM mode so that was a null action
- I widened the Lakeshore 218 title bar slightly to avoid overflow
- The TPG26X IOC would not start. It appears it hadn't been correctly added to the IOC DB table. I stopped the server and ran `make iocstartups` then restarted. After that it worked fine.

The configuration and synoptic are now set up apart from the motor records for the Galils and McLennans. Notably, the McLennans can't be configured properly until #1099 is completed and the changes pushed onto NDXIRISTEST.

We had several other issues whilst setting up the prototype. The main ones being:

1. On a simulated instrument, the ICP_binaries may be wiped, and the isisdae deregistered each time a new version of the server is deployed. In case of problems, run the steps
    1. Run `create_icp_binaries.bat` from `C:\Instrument\Apps\EPICS`
    1. Navigate in an administrator-enabled command prompt to `c:\Instrument\Apps\EPICS\ICP_Binaries\isisdae\x64\Release` and run 
        - `isisicp.exe /RegServer`
        - ` isisdatasvr.exe /RegServer`
1. When we were running many IOCs, the system became very unresponsive. This may be to do with the large number of messages going to the log server, partially owing to the IOCs that weren't started in RECSIM mode. I will create a ticket for this issue

**Comment by AdrianPotter** [comment]
The issue mentioned in point 2 is covered in #1521

**Comment by AdrianPotter** [comment]
The issues reported after the initial session have been fixed or assigned tickets for the upcoming sprint. @kjwoodsISIS, what more is needed on this ticket? As I recall we hadn't finished setting up the motors.

**Comment by John-Holt-Tessella** [comment]
On IRIS and Ian is happy.
