### ISSUE TITLE
Lakeshore 336: support for setting curve parameters

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1422]
In the Lakeshore336 IOC, it may be beneficial to be able to set a calibration curve's header parameters (protocol CRVHDR) and specify which curve an input should use (protocol INCRV). Currently the IOC only supports reading of these parameters, but the device allows setting them too.

These commands didn't seem necessary at the time of writing the Lakeshore 336 IOC (see ISISComputingGroup/IBEX#1404 ), but the time might come when they are.

This ticket is being added as a reminder, in case we decide we need this functionality

**Comment by IsabellaRey** [comment]
NOTE: these commands would be quite simple to implement, just need to follow the same format as the corresponding readbacks.

**Comment by kjwoodsISIS** [comment]
There is, as yet, no demand for this feature.  If we need to implement it, raise a new ticket.

**Comment by KathrynBaker** [comment]
I’m not certain that this is true. This was functionality that was specifically added for the support teams in the LabVIEW drivers. They will ask for it after they need it, not in advance, and we don’t ask them what they might need. As such this is a requirement that will not otherwise be captured, and we will probably do the same with the next ticket as it will be asked for then not needed for a few years.
