### ISSUE TITLE
Muon Front End: Calibration files need to be placed in git

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1425]
There is a SVN repository that contains instrument specific settings like the calibration files. This should be moved to git.

The plan is to move the common calibration files into a new repository. Then calibration files can be added, changed deleted from here. This repo can be shared between all machines and deployed via the script onto SECI machines.  The reasoning for a new repo can be found here (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files).

Tasks:

1. Create repo
1. Add calibration files to it
1. Change IOCs so that they point at the new location
    1. Danfysik
    1. Barndoors
    1. Eurotherm
    1. Search for others mentioning calib
1. Update release procedure  
1. Create documentation for the setting directory

**Comment by KathrynBaker** [comment]
Apologies for the confusion I'm about to cause, there was a time when the calibrations were in a repo, but this was stopped as it menat duplicating repo info between labview and EPICS - there is actually an area on kits that has the instructions for calibrations for temperature sensors, and there is a deployment script from there. There is no specific repo for the temp sensors as these are all available on all instruments, and don't change frequently. The magnet calibrations don't change much either, but at the moment only ever exist on the instrument they relate to.

So there is some code with puts all the temperature sensor calibrations just in \Instrument\Settings\config\calib. We can alter this and run the deployment script again, of course. Then can decide whether to keep the other calibrations in the same way or not.

**Comment by John-Holt-Tessella** [comment]
Calibration files are not current committed if you review this before they are talk with me.

**Comment by AdrianPotter** [comment]
As part of ticket #1403, please make sure that when running a Eurotherm:

- The ramp directory label is not empty
- The ramp file and sensor file behave the same on receiving bad input
    - When testing #1403, the sensor file started with a invalid value warning. The warning and the label text remained unchanged until a valid file was set. When an invalid file was subsequently added, a major alarm was triggered on the label and the label was not updated.
    - In the same case, the ramp file had no invalid value alarm, and when a bad value was set, the label was still updated and resulted in no alarm.

The decision was taken on consultation with @John-Holt-Tessella  not to fix this as part of #1403 because it would conflict with this change. Please make sure it's fixed before closing this ticket

**Comment by AdrianPotter** [comment]
Note that the ticket doesn't describe which repos have been updated. So far I have found:

- EPICS-csm
- EPICS-IOC
- EPICS-Eurotherm2k
- any more?

A few notes after testing:

1) The Ibex developer's manual ["Getting Started" page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)) doesn't include details about the calib directory
1) In the Eurotherm temperature controller, the address is represented as a double, rather than an integer
1) The issue from the 17th August comment above has not been fixed
1) The font of the sensor calibration dir in the Eurotherm OPI doesn't fit with the surrounding labels
1)  The documentation for [barn doors](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Barndoors-and-Momentum-Slits-on-MUON-Front-End) needs updating to reflect the new calib location

**Comment by AdrianPotter** [comment]
Picking up the rework since John is on holiday. Someone else will have to do the final review. Please just confirm that all the above have been fixed

**Comment by AdrianPotter** [comment]
Helpful for development to have an EPICS branch to set up the relevant submodules: https://github.com/ISISComputingGroup/EPICS/tree/Ticket1425_MFE_calibration_files_need_to_be_placed_in_git

**Comment by AdrianPotter** [comment]
Note that as well as the wiki change in the first point, I also updated:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC

**Comment by AdrianPotter** [comment]
This PR also didn't get merged as part of ticket 1403 which is causing some of the problems described above:

https://github.com/ISISComputingGroup/EPICS-ReadASCII/pull/1

**Comment by AdrianPotter** [comment]
The 17th August issues are fixed once the PR from ReadAscii is included

**Comment by AdrianPotter** [comment]
The directory fonts are fine to be smaller since they are generally long and otherwise overflow the space.

The same argument could be made for the file labels but the full value van be seen from hover and in general would benefit from an overhaul of the OPI styling. This is something @IsabellaRey is looking at.

**Comment by AdrianPotter** [comment]
All of the outstanding issues have been resolved. It did not need any further updates to the code so I'm going to merge and mark as review_complete rather than passing to a 2nd reviewer
