### ISSUE TITLE
ConfigVersionControl: Don't automatically push if you are looking at another branch

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1446]
One of the reasons for having configurations in branches on version control is that, as a developer, I can switch to another instrument branch and look at it's configs. However, if I do this the Blockserver will automatically push any changes I make to the instrument's configurations, this is undesired behaviour.

This could potentially be fixed by making sure the branch is only pushed if it has the same name as your machine.

**Comment by DominicOram** [comment]
Waiting on #1379 to be able to test

**Comment by AdrianPotter** [comment]
#1379 complete. Moving back to ready

**Comment by FreddieAkeroyd** [comment]
Pushing only if machine name == branch names works for instruments, but i know of developers who have used their federal ID as the branch rather than the computer name so they can share between multiple computers. Maybe rules are:
Pushing to master is always wrong
If branch name starts with ND assume it is a computer name and only push if it machine name == this
Otherwise OK to push as probably a fed ID named branch

**Comment by DominicOram** [comment]
Adding comment here that should definitely not push when on master branch. This will cover https://github.com/ISISComputingGroup/IBEX/issues/1736

**Comment by AdrianPotter** [comment]
Can't currently test as config git server seems to be down. Will try again later
