### ISSUE TITLE
GUI: IOC Status bug

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1458]
If an IOC started from the dialog in the GUI crashes, the IOC status shows correctly as Stopped in the table, but Running in the group box below. To get the correct status one has to close and re-open the dialog (though I haven't tried simply selecting another IOC).

Steps to reproduce:
- setup an IOC so it will crash at startup (e.g. in LINKAM IOC simply leave the PORT macro unset)
- from the GUI start the IOC

**Comment by AdrianPotter** [comment]
Check against #1614

**Comment by AdrianPotter** [comment]
Not fixed. Notably if you click on LINKAM95_01 (or whatever IOC) in the table, the state gets reset correctly. IOC panel might need to observe the state of the currently selected IOC to register any changes. It must to this to an extent already because the "running" state gets added. Similarly for the stopped state. Maybe it needs to keep listening past the first event.

The same behaviour can be observed by starting/stopping an IOC from the GUI but then stopping/starting it from the console. The table will update but the panel won't
