### ISSUE TITLE
Create a script generator perspective

### ISSUE THREAD

**Issue by simonfernandes** [ISISComputingGroup/IBEX#1459]
Create a new, invisible-by-default, script generator perspective in the GUI.

**Comment by DominicOram** [comment]
Functionality is there, can you do the following:
- [ ] Remove the browser control
- [ ] Add a pom so that it is built through tycho (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Adding-a-Plugin-or-Feature-to-Maven-Build). To confirm that this has worked build the GUI using build/build.bat and confirm the new perspective is in this build

**Comment by DominicOram** [comment]
Still needs a bit more work, see PR from ticket #1492

**Comment by DominicOram** [comment]
Remember that the plugin needs to be added to the parent pom as described at the bottom of that page. I've done this for you... this time...
