### ISSUE TITLE
URGENT: NDXIRISTEST - blank spectra table name

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1464]
When running IBEX on NDXIRISTEST, it appears that although the spectra table name appears in the drop-down list of files, the spectra table name string sent to the server is blank.

The following is the initial report of the problem:
```
freddieakeroyd [3:42 PM]  
Hi, just trying out something on iristest - wiring, detector and spectra tables all appear on dropdown in GUI but spectra table fails to load

[3:42]  
as in "file not found"

[3:44]  
looking at the XML string it would appear to be sending a blank filename for spectra, ok for wiring and detector

kevinwoods [3:45 PM]  
Does the spectra table load successfully on LARMOR & IMAT?  I am guessing that it does.

freddieakeroyd [3:47 PM]  
it did, so either something is funny about IRISTEST or a recent change has caused an issue
```

**Comment by kjwoodsISIS** [comment]
Consider fixing #1463 at the same time.

**Comment by John-Holt-Tessella** [comment]
There are two issues to fix:

1. Race condition, on switching instruments the setting can be set before the path list and when this happens the setting are not displayed, i.e. the relevant item in the drop down is not selected. (if this  is easy to fix fix it here otherwise create a new ticket)
1. Blank wiring table/spectra/detector (possibly period) is set in settings although it appears it is (this is the above bug)
    1. Remove c:\data and var/ioc/daesettings
    1. remove files from tables
    1. start instrument
    1. open client
    1. Apply changes on, PV for settings (see below) shows blank files
    1. Put a single wiring table/spectra and detector file in.
    1. Error message in drop down is replaced with file
    1. Apply changes does not send new values

NB Values are found in %MYPVPREFIX%DAE:DAESETTINGS 

I think the cause is that the value is only updated on selecting a value from the drop down and because the value is automatically selected as the highest priority then this is never selectable. If the value is blank the drop down needs to include this value to reflect this on change of files in the directory. If the file become invalid (i.e. the file is moved) message needs to reflect this; probably show original file in drop down with file not present after it.
