### ISSUE TITLE
IRIS: Migrate Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1535]
As a support person, I want to migrate some of the existing Open-Genie scripts for IRIS to genie_python, so that I can confirm that the genie_python scripts preserve the functions of the existing Open-Genie scripts .

### Acceptance Criteria
1. The new genie_python scripts should be tested on NDXIRISTEST.
1. The tested genie_python scripts should be copied to NDXIRIS

### Notes
1.  Not all existing Open Genie scripts on IRIS need to be migrated.  Ask the IRIS instrument scientists to nominate their "top five" scripts to be migrated.

**Comment by AdrianPotter** [comment]
The scripts have all now been translated (jointly between @IsabellaRey, @John-Holt-Tessella and me) into genie_python with the exception of iris_quiet_count_int  which is not a control script. @IsabellaRey is testing.

**Comment by IsabellaRey** [comment]
The scripts are now on IRIS, but I am moving this to impeded as there are some things to check with Ian:

* Probably bug in original code: quickstart.gcl line 129: high and low limits are not updated to be temp+2 and temp-2, but they probably should. The new code (quickstart.py, line 56) fixes this bug, but we need to confirm with Ian.
* Probably bug in original code:  SampleChanger.gcl line 86: Bot_Can_Top is set to 2 with runcontrol, but the runcontrol limits are still those from line 44. This means that the run following this code will not work, because Bot_Can_Top is outside of the runcontrol limits. I think Bot_Can_Top is not supposed to have runcontrol here (for consistency with other setups), but we need to confirm with Ian.  The new code (sample_changer.py line 64) behaves the same as the old code, SO NEEDS FIXING.
* iris_routines.py: pg002_megaoffset_50Hz() points at a table in Labview modules that doesn't exist. This should probably be spectra.dat in the usual tables directory, like for all the other functions, but we need to double-check

**Comment by John-Holt-Tessella** [comment]
Changes done on NDXIRIS by Adrian
