### ISSUE TITLE
User Manual: How to write genie_python Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1538]
As a support person, I would like the User Manual to include a section on how to write genie_python scripts, so that users amount of support required to help users write genie_python scripts is minimised.
### Acceptance Criteria
1. A section entitled "How to Write genie_python Scripts" is added to the User Manual (added as a sub-section from the existing "How To Do Things In IBEX" page).
2. The section entitled "Differences between Open Genie and genie_python" on the "WhatISIBEX" page is updated.
### Notes
1. The User Manual can be edited from:
   1. https://github.com/ISISComputingGroup/ibex_user_manual/wiki or
   2. http://shadow.nd.rl.ac.uk/ibex_user_manual/Home
2. **Please Note:** the User manual is written in reStructuredText (not Markdown).

**Comment by IsabellaRey** [comment]
Comments from review:

Thanks @AdrianPotter for the new page; it makes a lot of good points, and we can always add to it if we find users get confused about other things.

A few things to consider before marking the ticket as done:

In the side-by-side comparison table:
- [ ] should we add an example for (what I think are) optional arguments in open genie (i.e. where they have a "/")? Example from IRIS scripts: 
'''
cset/control Sample=temp highlimit=high lowlimit=low
cset/nocontrol TLCCR=temp-10
'''
- [ ] in the waitfor row, when talking about named and unnamed arguments it would be useful to link to the section "argument ordering", so it's clear they will get more info there

- [ ] should we have a string composition example (or is this taking it too far)? E.g. in IRIS there were lines like 
'''
PRINTIN "Setting TCB range " TLOW " to " THIGH " step " TSTEP
'''
but in python you have "Setting TCB range " + str(TLOW) etc, which may not be obvious

- [ ] Would it be good to make it more explicit that the indentation in python takes care of PROCEDURE/ENDPROCEDURE and IF/ELSE/ENDIF in open genie, either in the side-by-side comparison table or the indentation section? I know we're basically saying this already, but maybe it's best to have it spelled out (currently we're not mentioning ENDPROCEDURE or so)

Also:

- [ ] there was already a "Create and Manage Scripts" page  under "How to do things in IBEX". It seems to me that most of it is superseeded by the page created in this ticket, but it also links to other things such as the Muon FE scripting page. Could you please rework/move/remove this page so that everything is accessible from the sample place (this could be the Scripting link in the home page, and then "How to do things in IBEX" could link to that or not at all)

- [ ] Could you please update the section "Differences between Open Genie and genie_python" in the "What is IBEX" page, so it links to the scripting documentation

**Comment by AdrianPotter** [comment]
I've changed the document format from markdown to restructured text so it appears ok on the shadow copy. Please check you're still happy.

**Comment by AdrianPotter** [comment]
Opted not to do a string composition example.  I think it falls under the category of basic Python rather than genie_python specific knowledge. The line is definitely fuzzy, but I don't want the page to be a beginners' guide to Python

**Comment by AdrianPotter** [comment]
Personally I think the indentation is explicit enough. I gave it its own section. I didn't want to put it in the table because depending on the exact formatting it might be very hard to illustrate it effectively.
