### ISSUE TITLE
User Manual: Enhance the "Manage the DAE" section

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1540]
As a support person, I would like to enhance the Manage the DAE section of the User Manual, so that visiting scientists can use it to guide their use of the DAE.
### Acceptance Criteria
1. Expand the Manage the DAE section, notably the following sub-sections:
   1. Experiment Setup and descriptions of the Time Channels, Data Acquisition & Periods tabs
   2. Spectra Plots (e.g. a description of what exactly the spectra plots show).
### Notes
1. The User Manual can be edited from:
   1. https://github.com/ISISComputingGroup/ibex_user_manual/wiki or
   2. http://shadow.nd.rl.ac.uk/ibex_user_manual/Home
2. Adapt material from Freddie's DAE presentation.

**Comment by John-Holt-Tessella** [comment]
Maybe do this as part of the support workshop with Freddie leading this section. Then we can write it up later.

**Comment by John-Holt-Tessella** [comment]
Added mentioned documentation to sharepoint. They are `ISISICP and DAE.pptx` and `SECI User Manual.doc`

**Comment by John-Holt-Tessella** [comment]
Add something on monitors. Create an example by chatting with someone, probably @FreddieAkeroyd.

**Comment by John-Holt-Tessella** [comment]
Chatted with Matt to finish

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_user_manual/wiki/ManagetheDAE

**Comment by AdrianPotter** [comment]
- [ ] Please link back to the managing the DAE section from: https://github.com/ISISComputingGroup/ibex_user_manual/wiki/KeyConceptsinIBEX#dae-data-acquisition-electronics
- [ ] Replace `The view is split into a number of tabs and sub tabs.` with `The DAE can be managed from the DAE view in the client. It is split into a number of tabs and sub tabs. I know that sounds picky, but the page only implicitly relates to the DAE perspective. The manual should make that relation explicit.
- [ ] Under `Run summary fields`, have either the colon or `records`, not both. Otherwise it doesn't make grammatical sense. Further, the `records` just add repetitive bulk. I'd drop them.
- [ ] The run control buttons seem to have the wrong heading. They currently appear under `Message Log`. I'd suggest creating a sub-heading for `Run control buttons`.
- [ ] The comments on the IBEX dashboard apply to all run control buttons. Move them out of the `Begin run` button section and into the newly created parent section `Run control buttons`.
- [ ] The `Save Run` sub header is the only one in the format `Click on this to...`, rather than `This will...` or equivalent. It would be better to keep a consistent style.
- [ ] Under `Experiment setup`, consistently use `three` and `3`. In fact, the `3`s can be dropped entirely without any loss of meaning.
- [ ] Same with `tabs` and `sub-tabs`: be consistent. Use one or the other, but don't change, or it may be confusing.
- [ ] Clicking the `run summary` link under the `Experiment setup` header doesn't do anything
- [ ] The `Time Channels` section seems a little incomplete. It doesn't give much description of the various headers and options available within the time regime tables. Are we assuming instrument scientists just know all of that?
- [ ] Can you add a hyperlink on `settings` in the `Time Channels` section on how to set up instrument settings for the instrument (notably where the files are).
- [ ] Under `Data Acquisition` I don't think the colons are necessary at the end of the sub-headers
- [ ] As previously, link back to information about instrument settings in the `Data Acquisition/Tables` subsection
- [ ] In `Periods`, the first `setup` should be `set up`. The former is a noun, the latter is a verb
- [ ] In `Periods`, hardware should not have a capital letter.
- [ ] Under `Spectra Plots`, the first `Tab` should not be capitalised.
- [ ] As previously, the first `setup` should be `set up`.
- [ ] I don't think the fields should have colons, either in the manual or the GUI
- [ ] Diagnostics: You've left the manual blank, or the GUI is blank? Be clear. Is extra effort needed on this ticket before completion?

**Comment by kjwoodsISIS** [comment]
Some comments on the above suggestions:
>The `Time Channels` section seems a little incomplete. It doesn't give much description of the various 
> headers and options available within the time regime tables. Are we assuming instrument scientists just 
> know all of that?
There is very little "official" documentation on how the DAE works - the documentation of the corresponding features of SECI is equally meagre.  So, yes, we are in fact assuming that scientists just know all of that stuff.

> Diagnostics: You've left the manual blank, or the GUI is blank? Be clear. Is extra effort needed on 
> this ticket before completion?
The GUI is intentionally left blank.

**Comment by AdrianPotter** [comment]
Super. Thanks for addressing all points, especially given some were very picky :)
