### ISSUE TITLE
Version numbers: master should be X.x.x

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1549]
Update the version number of the master branches relevant to release to be X.x.x (currently they are 2.0.0).

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release  (standard release, point 3) for the places where the version number should be changed

**Comment by IsabellaRey** [comment]
NOTE: eclipse doesn't like X.x.x, it complains about invalid characters.
Best also checking with Matt if fiddling with the version number in the GUI would affect the Tycho build

**Comment by IsabellaRey** [comment]
P.S. Note that there is already a branch for this, but no work has been done on it

**Comment by AdrianPotter** [comment]
I've created PRs for the client, server and genie_python so that the version numbers are 0.0.0 on all 3. This will hopefully distinguish them as not being releases. As above, I haven't used X.x.m because it wouldn't be allowed by the client build and I wanted to maintain consistency. 0.0.0 is allowed by the Tycho build.

Notably the release process is documented here:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release

And includes instructions for updating the release numbers for a release
