### ISSUE TITLE
genie_python: option to allow exceptions to propagate

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#1557]
genie_python currently handles exceptions by catching them and printing an error message.

James Lord has requested that it be possible to set genie_python not to handle exceptions rather he wants it to let the exception through.

In most situations you probably don't want the script to exit on an exception; however, in other cases you may want this or you may want to handle the exception yourself.

By default it should use the current functionality of printing an error message and carrying on.

**Comment by John-Holt-Tessella** [comment]
There is already a flag in genie to do this, I think, called `_exceptions_raised` we just need a procedure to switch this on.

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/310

**Comment by rerpha** [comment]
Have left a comment on the PR: https://github.com/ISISComputingGroup/genie_python/pull/310#pullrequestreview-575282798

I think I'm probably being stupid, but I'm not sure this is an issue anymore as we seem to raise the exceptions anyway rather than printing them? Maybe its just for certain exceptions that we print, but I couldn't find anything on this anywhere?
