### ISSUE TITLE
GUI: Eurotherm OPI should only display tabs for active addresses

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1590]
As a user I want my Eurotherm OPI to only show tabs for active Eurotherms.

**Comment by DominicOram** [comment]
This is already done by macros in the IOC. Is there additional work required for this?

**Comment by John-Holt-Tessella** [comment]
Do we think/does it make sense to hide tabs which are not active instead of just making then active/inactive?

**Comment by DominicOram** [comment]
Ok, if that's what we're saying this ticket is, that's fine.

**Comment by ChrisM-S** [comment]
May be a silly question, but...

Do I read this as "configured" rather than "Active".  i.e., a Eurotherm might not be fully configured (port macro being changed) or communicating but I imagine you would still want to be able to see the tab?  Obviously if the tab did not show, it might not be possible to tell what was going on...  Would greying inactive tabs be a better option but not showing "unconfigured" tabs?

**Comment by John-Holt-Tessella** [comment]
Not sure Chris. So a Eurotherm crate can have from 1 to 7 eurotherms in it. In the configuration you declare the address of each eurotherm. If the eurotherm has an address the tab is active and shown. If it is not at the moment the tab is inactive (grey) and shown.
This ticket suggests that we should not show eurotherms without a configured address. Is this a sensible choice or will it confuse people looking at the OPI potentially seeing eurotherms 2, 4 and 7?
There is a further wrinkle that I know some people would like to see each eurotherm named (not just a sensor number) in which case seeing unnamed sensors is no longer confusing.

**Comment by KathrynBaker** [comment]
This was put to the SAG, and it was actually viewed that the inactive tabs is useful, so this ticket is not needed.
