### ISSUE TITLE
GUI: Scientific notation on small block values

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#1592]
When setting up IRIS we found that very small block values (< 0.01) were not being displayed in scientific notation and so were hard to read.

For the moment just set the the blocks view up to display scientific notation if the number is low. This should be user defined later.

To fix this you will need to look at the NumberFormat used in the VTypeFormat class

**Comment by IsabellaRey** [comment]
Following discussion with Dominic and John, I have set up the GUI so that blocks <0.001 or >=1000000 are displayed in scientific notation. The PREC field of the PV is taken into account to determine the number of fractional digits.

So for example:
| Value (double) | PREC 3  | PREC 5 |
| ------ | ----  | ------------- |
|  0.1 | 0.100 | 0.10000 |

**Comment by IsabellaRey** [comment]
I have created a separate ticket ISISComputingGroup/IBEX#1716 to have a discussion about the precision and document the outcome
