### ISSUE TITLE
GUI: IOC log rework

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1600]
During manual system tests, the IOC log perspective was found to be inconsistent and confusing, and could do with a global rework.

These are the things that were picked up:
- The "show info messages" checkbox has immediate effect, but the all others search filters require pressing the little "search" button. (note the filtering on severity may have changed from the time of writing with ISISComputingGroup/IBEX#1550)
- The From and To checkboxes require clicking the "search" button to take effect, but clicking the X button does not clear them
- The ioc log supports multiple types of search. When you switch search item in the dropdown menu, the previous search term is preserved. This makes it difficult to keep track of which filters are active and which are not. Each filter should get its own field. Less compact, but much clearer
- The "type" search filter doesn't work: Open the IOC log, set search filter to "ioclog". All messages disappear
- Radio buttons would make a better way of selecting severity rather than free form text (note again this may have been solved by ISISComputingGroup/IBEX#1550 in which case the Severity should probably not need to appear in the drop-down at all)

**Comment by John-Holt-Tessella** [comment]
Add to this: 

1. Searching returns a number of results but it is not clear that this is limited. So set the dates for a couple of days ago and do the search only old messages are returned.
1. From and To are not forgiving if you get then in the wrong order, i.e. To before From
1. Filters for application id, severity and type work in the GUI not in the database so that changing the filter can return misleading results. E.g. severity set to major report all messages for the last couple of days because of the limited number of results this could miss the major exceptions because all the returned messages are info and so the list is blank not full of latest MAJOR errors.
1. Application ID and send host are not shown in the table so it is impossible to guess what values you might what to use for these to find related messages.

**Comment by John-Holt-Tessella** [comment]
Decide what to do in this ticket then split off the appropriate bits. (It is getting very large I think)

**Comment by KathrynBaker** [comment]
The IOC log has limited useage, as such this work has limited usefulness, closing
