### ISSUE TITLE
Unable to add new group on LARMOR

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1629]
On LARMOR Rob is unable to add a new group for dashboard blocks, he just goes to edit current config -> groups -> add and when he clicks on the name to change it he gets a regular expression violation with the name and so cannot go further. Works fine for me on IRISTEST.

**Comment by kjwoodsISIS** [comment]
It would be worth checking which version of the client Rob is using to add a new group - it could be that he is using an old client and a new server.

**Comment by John-Holt-Tessella** [comment]
This is because he has a group called "JAW GAPS" which has a space in. This is not allowed; I think because the group is in a PV.  Usually this dialogue would work fine because you can not create a group with an invalid name but because the config already has an invalid name in the error message is not helpful. I suggest no action but let Rob know,

**Comment by John-Holt-Tessella** [comment]
@FreddieAkeroyd  is checking whether it is acceptable to restrict group names to not have spaces

**Comment by FreddieAkeroyd** [comment]
Rob seems happy with an _ in group names, have told him which XML files to change
