### ISSUE TITLE
Client Doesn't install correctly given user manual instructions

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1636]
There are a few issues with the client install for the most recent release 2.1.0:

1. The instructions in the Manual don't take account of the  release number i.e. 2.1.0 (there is one more directory level and more than one number)
2. The domain for the distribution **\\\\isis\inst$...** should really read **\\\\isis.cclrc.ac.uk\inst$...** for non-domain machines (e.g. a visitors laptop or any other machine not in the ISIS domain).  Maybe a URL link to the release distribution on the FTP server would be easier?
3. The build number example is shown with a "-" included and a much higher number than BUILD562 which has no "-" and is lower than might be expected.
4. The script appears to work but does not install GENIE-Python because the path is relative and ignores the extra directory level.
5. Instructions about using a Fed-ID for access to the distribution.
6. On start-up of the client, there is no clear user indication that it is missing GENIE-Python as the error (or that the client cannot function). A sanity check and message might be useful?

**Comment by kjwoodsISIS** [comment]
This bug report has crossed with changes made to the Manual.  Some clarifications in the original report are also needed.

1. Already fixed 

2. What is the URL of the FTP server?

3. Already fixed.

4. By script, do you mean `install_client.bat`?  It would appear the the script is designed to work from `\\isis\inst$\Kits$\CompGroup\ICP\Client\BUILDnnn`, rather than from `\\isis\inst$\Kits$\CompGroup\ICP\Releases\N.M.O\Client\BUILDnnn`.

5. What are the instructions about using a Fed-ID for access to the distribution?  What does the user need to know?

**Comment by AdrianPotter** [comment]
Note that this issue is partially fixed by ticket #1586

**Comment by AdrianPotter** [comment]
2. Note added to installation instructions
4. Done with #1586 
5. Added a note to documentation
6. Covered by #1259

**Comment by mattclarke** [comment]
Closed as part of reviewing #1586
