### ISSUE TITLE
IBEX Client network load possibly needs control for remote and or WIFI clients

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1652]
As a systems administrator, I notice that the network load of traffic from the server (NDXIMAT) _to_ the client running on a test machine in the R3 network (MININT-ISISTEST) is approximately 1MB/s (.08-0.09 of a 10Gb/s link).  The traffic _from_ the client to the server is negligible (~100 times less).  If we assume 20 scientists might be running IBEX remotely from home or a laptop a 20MB/s network load across the VPN is worth avoiding when it is not specifically required.

When the IBEX server ENDs/PAUSEs a run, the load drops to a very low level which suggests it is related to neutron data transfer from the instrument to the client.  The most likely candidate is the live DAE plot screens.  These screens are valuable and very well liked by the scientists (and me) and are IMHO a valid use of the network for the information provided even over wireless.

What might be wise is to allow these to be defaulted to not pass data to the client unless the plots are specifically enabled AND the GUI pane with the plots are activated and showing data to the user.  It may be that data rate can also be matched to the displayable resolution at the client end in the future.

Versions running on IMAT at time of test:
IBEX client (2.1.0.562)
IBEX server (2.1.0.d2ec)

**Comment by kjwoodsISIS** [comment]
While I can see that in general terms it is a "good thing" to be a good "corporate citizen" and use the VPN efficiently, I wonder how much value we will get out of such an investment of time and effort.
I assume that the VPN is a RAL-wide or even STFC-wide resource (as opposed to a pure ISIS resource).  Who else is contending for bandwidth on the VPN?  Presumably anyone at RAL (or STFC).  Are any of these people hogging bandwidth?  Could it be that IBEX's estimated use of bandwidth is modest (or even negligible) by the standards of other users?  How would we know?  Are there limits on the amount of VPN bandwidth anyone (or any group of users) can use?  If so, what are those limits?

If we did optimise IBEX as suggested, would there be side effects for the users?  For example, if the data was only pulled across the network when viewing the DAE data, would there be a delay each time the user switches to the DAE view?  (I suspect there would be a delay).  Would users find such a delay acceptable?  (I suspect not.)

What happens when the data streaming & data reduction work (being done by Matt & Owen) goes live?  Will this place additional load on the VPN?  I guess the answer is "quite probably" (notwithstanding the "data reduction" element of the work).

**Comment by John-Holt-Tessella** [comment]
Think about not updating spectra PVs when user is not looking at graph. Reduce update rate of spectra PV.

**Comment by KathrynBaker** [comment]
The remote client to server option is not widely used, and is currently impractical. Closing for now, appropriate tickets can be added once we return to making the client/server split more complete.
