### ISSUE TITLE
MySQL hogs memory unnecessarily on production machines

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#1685]
NDXIMAT seems to have almost 5GB of memory allocated to the mysqld.exe process compared with ndxiris and ndxlarmor. Unlike NDXIRIS and NDXLARMOR it appears to have # server_type=2 commented out where NDXIRIS and NDXLARMOR have # server_type=3 commented out.

measurements are:
**workingsetsize GB**
ndximat
4.67646408081055
ndxiris
0.097686767578125
ndxlarmor
0.63336181640625

NDXIMAT also has the mysql database located in a non standard place this should be moved.

**Comment by ChrisM-S** [comment]
Adding
[mysqld]
performance_schema = off

may well improve things on all systems, this is memory purely allocated for performance counters which as far as I know we don't use anywhere in production.  (it can be commented out and db restarted to re-enable).

**Comment by John-Holt-Tessella** [comment]
Document in instrument machine. Check on NDXDemo and add to release notes.

**Comment by John-Holt-Tessella** [comment]
OK The memory is set in the ini file it appears that depending on a option somewhere you can have different server profiles (as indicated by the comment server_type). The different server types set different memory allocations. Probably the most important parameter is `innodb_buffer_pool_size` which is 4Gb in the config file on IMAT and only 0.5Gb on Larmor. 
The plan is to set this file up to be the same on IMAT as it is on LARMOR although the location is different. I will recorded this in the release notes and add a comment to the wiki.

**Comment by John-Holt-Tessella** [comment]
Added to release notes https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_v3.0.0

**Comment by AdrianPotter** [comment]
There are probably answers to these but @John-Holt-Tessella you're currently not in the office to ask:

- The release notes describe the changes to make on the instrument. It would be useful to give some basic acceptance criteria (e.g. ioc log and alarm perspectives keep working)
- It isn't clear to me under what conditions the changes to the my.ini file will take effect. Does it require the service to be restarted?
- The ticket comments aren't clear about the current state of DEMO, IRISTEST, IMAT, ZOOM and MUONFE. Do they all have the correct version of MySQL and just need `performance_schema=OFF`. I assume that to be true since IMAT is the only one with special update instructions but it'd be good to know explicitly
- What side-effects demonstrate that `performance_schema=OFF` has been applied successfully to an instrument?

**Comment by John-Holt-Tessella** [comment]
1. Should be done whenever updating the machine
2. Yes mysql needs restartin ghave added that to release notes
3. Yes - added to ticket above
4. Less memory is being used but this will not clear just from restarting, I don't think we will be able to tell.

**Comment by ChrisM-S** [comment]
I did check this, stop the service,  put the line back and restart the service, memory should be a bit higher, stop service, take out, should drop by a noticeable amount.  I believe the amount may be larger or smaller depending on how many “instrument-able” tables are being stored in memory for the application.  Could include a load application (e.g. Start IBEX between these steps).

Chris
