### ISSUE TITLE
Planning: Device on instruments with dates

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1700]
To help us and the instrument scientists plan there should be a page which shows the devices that are written for an instrument, those that are planned (with the date they need to be ready for) and those we are not going to do. The scientists for each instrument should be made aware of the page.
A task should be added that every week someone checks the scheduled page to add any extra devices needed

**Comment by KathrynBaker** [comment]
We already have this on a per instrument basis (e.g. https://github.com/ISISComputingGroup/IBEX/wiki/IMAT-Instrument-Details), although dates aren’t included.

I don’t think we should consider duplicating the information, which is potentially the case if we start adding in an extra page with the schedule of when items are due across all instruments. A column in the existing tables which can specify “done”, “due by”, “planned for”, “not doing” or “unknown” might be a better option. New instruments are getting assigned to stewards, and we could assign the existing instruments to a nominated individual as well. Someone specifically takes on LARMOR and IMAT as a steward to keep track of new items for them, and ensuring that the tickets are prioritised appropriately, and they can then make sure that the pages are up to date, and that the tickets which are due can be highlighted in the planning sessions. The instrument pages should have the information on, so that if the appropriate steward is unable to attend a meeting, especially unexpectedly, someone else can just go to the page and see what should be prioritised.

**Comment by KathrynBaker** [comment]
This has certainly not happened, and given our currently available resources I shall close this ticket, as the interactions have changed in the time since this was last considered.
