### ISSUE TITLE
Push Pt100.txt from IRIS

### ISSUE THREAD

**Issue by IsabellaRey** [ISISComputingGroup/IBEX#1732]
The file C:\Instrument\Settings\config\common\temp_sensors\Pt100.txt was updated on IRIS to have an extra entry at the top of the file and remove a duplicate entry.

This file is currently only in NDXIRIS. It should be pushed to common and updated in all the other instruments too

**Comment by KathrynBaker** [comment]
Also need to check that we are using the right pt100 - there is a version which at one point at least was called correct (on EMU I think), and we should verify that the solution is correct with the Sample Environment Team

**Comment by kjwoodsISIS** [comment]
This discussion highlights the need to have a way of easily determining the version of a calibration file.  I think we ought to have some kind of comment line in the file that states the version number, as well as keeping the files themselves under version control.  For example:
```
# My_Calibration_File
# Version: 1.2
# Date: dd/mm/yyyy
# 
n.nn   mm.mmm
n.nn   mm.mmm
...
```
I appreciate that adding a comment line to the file might upset some modules that read the calibration files, but over time we ought to think about extending these modules so that they don't choke on calibration files.  As an alternative to adding comment lines, we could add a version number to the filename - e.g. Pt100_V1R2.txt

**Comment by KathrynBaker** [comment]
Adding those comments will break the LabVIEW code, which is why we haven’t added anything like that – so unless we are willing to change EVERY instrument for this, we can’t add comments yet. The comment lines shouldn’t be a problem in EPICS as I think we can easily skip the lines. Renaming the files isn’t usually necessary. In the last 10 years we have had 6 files that have altered, it just happens that the pt100 is one of them, the others were similar extensions to improve the readback. Naming the files would only add to the confusion. I’m actually reasonably certain that the pt100 in the files is the correct one renamed – but it should be double checked, as should the solution we have put in place, as there is concern that this is not actually an appropriate solution.

**Comment by kjwoodsISIS** [comment]
>> In the last 10 years we have had 6 files that have altered, it just happens that the pt100 is one of 
>> them ... reasonably certain that the pt100 in the files is the correct one renamed.

For exactly this reason (i.e. the relative infrequency of updates), we really need to have some kind of audit trail.  It is simply not sustainable to rely on people's memories.  If we can't have the audit trail in the file itself, then it needs to be recorded as comments in the repository.

Long term we really should add comments to calibration files, so that the audit trail can't be separated from the file.

**Comment by FreddieAkeroyd** [comment]
Aren't these files already versioned in git on IBEX instruments?

**Comment by FreddieAkeroyd** [comment]
Using $Id:$ and the "ident" gitattributes keyword might help too https://git-scm.com/docs/gitattributes

**Comment by John-Holt-Tessella** [comment]
These files are indeed in git although only added recently. If the commit comment is good enough then that should be enough to tell.

**Comment by kjwoodsISIS** [comment]
Kathryn will check with Jon Bones to make sure we have the right Pt100.txt.

**Comment by KathrynBaker** [comment]
Going forward the git comment should be enough I would have thought.

**Comment by KathrynBaker** [comment]
Having checked with Jon the extra point is quite acceptable to add to the file, so I shall proceed to make the change and push, then as part of the release we can update the calibrations and it should trickle through to the instruments.

**Comment by KathrynBaker** [comment]
File pushed - being a local repo there is no pull request. If you want to make sure it is there and correct, using the instructions on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Calibration-Files, make sure that you have an up to date copy of the repo, look at Pt100.txt, and there should be a value at the top of 0.0001,0.0001.

**Comment by ChrisM-S** [comment]
Kathryn,

Is this common repository pulled to each instrument automatically at some set point in time? (so can one assume that modifying a common file will propagate the correction to all instruments).

Chris

**Comment by KathrynBaker** [comment]
As part of the update/release process we should be pulling these files, or it can be done as required. If we don’t do this as part of the release/update process already – we need to make sure it is added, as that was the intention.

**Comment by John-Holt-Tessella** [comment]
This is part of the release process now see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC  upgrade Update the Common Calibration directory.

**Comment by John-Holt-Tessella** [comment]
Waiting on question answer from IRIS to finish review
