### ISSUE TITLE
Muon Front End: Momentum Slits - Not updating with current position

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#1798]
James reported that when changing the block pointing to the PV $(P)MSLITS it jumps to the setpoint, rather than showing the current position, which would make scripting hard for large moves, and does mean that the current position is not reported accurately. waitfor_move() has been suggested for the scripting side of things but we need to see if we can get this to report back an accurate position and whilst moving.

**Comment by FreddieAkeroyd** [comment]
Hi Kathryn, MSLITS is a motor alias rather than an axis object I guess? With motors if you directly point at the RBV field with a block i.e. MTR0601.RBV there are various aliases already created that I think will make a cset on the block do the right thing. This should work with MSLITS.RBV too if there is a MSLITS:SP alias

Regards,

Freddie

**Comment by KathrynBaker** [comment]
Thank you Freddie, that works nicely ☺

Regards,
Kathryn

**Comment by KathrynBaker** [comment]
As this was a pure config change, and as such there is very little to review I shall skip this straight through to Done, as whilst there was a fix it was pretty trivial (although one to remember for those of us setting up blocks in the future - I'd not set up a motion block before), and as such not worth recalling this as a ticket.
