### ISSUE TITLE
Vesuvio: IOC & OPI for Chell CCD100 Pressure Transducer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1827]
As a scientist, I want support for a Chell CCD100 Pressure Transducer in IBEX, so that I can measure and control the pressure in the gas handling system in my experiments.

#### Acceptance Criteria
1. I can use the IBEX GUI to control the Chell CCD100 Pressure Transducer.
1. I can use genie_python to control the Chell CCD100 Pressure Transducer.

#### Notes
1. For more details see (see [Vesuvio](https://github.com/ISISComputingGroup/IBEX/wiki/VESUVIO-Instrument-Details#noteChell) )

**Comment by DominicOram** [comment]
Work is spread over a number of repos:
* Top: https://github.com/ISISComputingGroup/EPICS/issues/62
* Support: master of https://github.com/ISISComputingGroup/EPICS-CCD100 (PR not required)
* IOC: https://github.com/ISISComputingGroup/EPICS-ioc/issues/115
* Emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/issues/7
* OPI: https://github.com/ISISComputingGroup/ibex_gui/issues/425

**Comment by ThomasLohnert** [comment]
Changing the units on the device panel leads to the IOC log being flooded with:
> TE:NDLT882:CCD100_01:UNITS: 4 bytes surplus input "    "
> TE:NDLT882:CCD100_01:UNITS: after 18 bytes: "INPUT UNITS STR: x"

The reason is that the reply the device is sending contains not only the character(s) you entered but also the empty spaces behind it (e.g. for unit "x" the reply is "x _ _ _ _"). You can get rid of this message by adding "ExtraInput = ignore" to the getUnits entry in the .proto file (unless you care about being able to set a unit with a space in the middle, as e.g. "x y" would just be read as "x")

**Comment by DominicOram** [comment]
This is no longer failing the builds and should be ok to merge.
