### ISSUE TITLE
IOC Inhibitor: IOC with SNL to disable record based on state

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#1865]
Create a LIMIT IOC which supports SNL. This will support 4 states as per docs(https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inhibitor). The PVs will be hard coded within the IOC and should be a motor IOC and a CAEN IOC.

Acceptance Criteria:

1. When the motor is not moving and the CAEN is not moving then the motor can be moved.
1. When the motor is moving the CAEN can not be switched on
1. When the motor is not moving and the CAEN is not moving then the CAEN can be switched on.
1. When the CAEN is on the motor can not be moved.
1. If switched on with the Motor moving and the CAEN moving

**Comment by AdrianPotter** [comment]
Since @Tom-Willemsen is about to start this and I'm out tomorrow, here's a brain dump of useful things to know when doing SNL. Found this source useful when I did the McLennan homing routine:

http://www.aps.anl.gov/epics/EpicsDocumentation/AppDevManuals/Sequencer/snl_1.9_man.html

Didn't use this previously but looks handy:

http://www.aps.anl.gov/epics/docs/USPAS2014/2-Tuesday/SNL_2_Sequencer.pdf

For reference, the McLennan homing routine is here:

C:\Instrument\Apps\EPICS\support\motor\master\motorApp\MclennanSrc\homing.st

The sequencer gets started in the startup cmd files:

C:\Instrument\Apps\EPICS\ioc\master\MCLEN\iocBoot\iocMCLEN-IOC-01\st-motor.cmd
