### ISSUE TITLE
Rethink of what we mean by release notes

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1874]
Our release notes page is more “how to upgrade an ibex release” than what I would think of as user release notes, which would highlight significant changes of interest to the scientist. It does contain a list of tickets forming part of the release, but I’m not sure how much of it would be directly read by a user especially as it can be quite long. Do we instead need to separate this out into:

Installation/upgrade notes
User release notes      

And could the list of tickets forming part of a release be auto-generated from ticket labels, I think it would be quite useful in the GitHub view to know what release a ticket appeared in without having to cross reference back to a wiki table – it would also make it less likely to forget listing a ticket in a release as the release label would show up (or not) in the waffle view of the completed tickets.

**Comment by AdrianPotter** [comment]
Awaiting feedback on preliminary plan as detailed below.

My goals based on the ticket for the revised release notes are:

•	To preserve information about which tickets were included in which release in a state accessible to developers
•	To provide instructions about how to upgrade an instrument from a previous release to developers
•	To provide information about critical and user-centric updates in a place and format accessible to users
•	To do all of this in as few steps as possible

The proposal is to have the following:

•	Developer notes
o	Per release
o	Stored in the developer’s manual
o	Contain same information as in the current release notes
	Tickets
	Upgrade instructions
	Dependency versions
o	Auto-generated by a script that looks at closed ticket dates and previous release notes
	Not 100% accurate given some tickets are released early as hotfixes. These can be adjusted manually. John and I discussed other ways of connecting tickets to releases but they all made life more rather than less complicated
•	Release notes
o	Per release
o	Stored in the IBEX manual (as current release notes)
o	Contains a list of changes that directly impact users
	Split by component (e.g. synoptics, hardware support, configurations)?
o	Generated manually from developer notes at release time

The workflow for generating the notes would be as follows:

1.	As tickets are completed that require changes to the instruments, the relevant instructions are added to an upgrade_notes page on the wiki
2.	When we reach a release, the release notes script is run. It generates a developer notes wiki page in the developer’s manual with the following:
a.	The release date
b.	Dependency versions from previous release
c.	Upgrade notes from the upgrade_notes page
d.	A list of tickets and their descriptions based on closure date and appearance in any previous release
3.	Any necessary manual modifications are made to the auto-compiled information
4.	Based on the tickets included in the developer notes, a list of user-related changes are manually created in the IBEX manual. These are what we would call release notes.

Please let me know if this sounds sensible, any clarifications you’d like me to make, and any adjustments you’d like to suggest.

Regards,
Adrian

**Comment by AdrianPotter** [comment]
As per @FreddieAkeroyd's feedback. List changes in the release by merged branches across ISIS_Computing_Group repositories rather than by date. Ticket numbers can be extracted from the branch names.

**Comment by AdrianPotter** [comment]
I'm going to make new tickets for the implementation of this. The scripting element will take a bit more time than was initially scoped for. For review please:

- [ ] Confirm that the new tickets cover the necessary work
- [ ] Confirm that the above plan is understandable by whoever comes to implement it

**Comment by AdrianPotter** [comment]
I've created new tickets to implement the process (#2185, #2186, #2187).
