### ISSUE TITLE
VESUVIO: Configure McLennan Motors

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1875]
As a support person, I want to configure the McLennan motors prior to finalising the configuration of foil positions.

See also #1825.

**Comment by AdrianPotter** [comment]
Who is the contact point for Vesuvio? Configuring the McLennans is reasonably straightforward, but we will need details about the setup: baud rate, encoders etc.

**Comment by kjwoodsISIS** [comment]
Vesuvio contacts are: Matthew Krzystyniak & Giovanni Romanelli.
If you need details of device configuration ask @davidkeymer - he might be able to extract the details from SECI.

**Comment by AdrianPotter** [comment]
Here are the Vesuvio configuration details we need:

[Mclennan PM600.txt](https://github.com/ISISComputingGroup/IBEX/files/713570/Mclennan.PM600.txt)

**Comment by AdrianPotter** [comment]
Basic configuration done. We need to go down to the cabin to test

**Comment by Tom-Willemsen** [comment]
Rename `FOIL_ROT` to `FOIL_BKSCAT` (or something else that conveys the idea that it's a backscattering foil).

**Comment by AdrianPotter** [comment]
I've created a PR for the fix to the McLennan IOC to talk to multiple axes on the same crate

https://github.com/ISISComputingGroup/EPICS-ioc/pull/111

I've ported the code over to Vesuvio so that it's running the 3.1.0 version but with a converter so it can still use the 3.0.0 IOC macros.

**Comment by AdrianPotter** [comment]
- [ ] Don't forget to check that the homing mode is as expected
- [ ] Check that MRES are specified to a sufficient level of accuracy
- [ ] Check whether MRES rounding has a cumulative effect on movement (I suspect the difference will be absolute rather than cumulative)

**Comment by AdrianPotter** [comment]
Need to go back down to the instrument to confirm setup

**Comment by AdrianPotter** [comment]
There appears to be a hardware fault in the back scattering foil which is preventing it from moving. The device reports that is hitting its upper and lower limit switches. This is confirmed in SECI, IBEX and direct communication with the device. We've reset the controller and investigated the instrument itself and there's no indication why this is the case so we suspect there is something wrong with the electronics. @davidkeymer is going to ask someone to have a look.

**Comment by mattclarke** [comment]
I think I have seen this happen before. If I recall correctly it was an issue with the wiring.

**Comment by davidkeymer** [comment]
New information has just come to light:  The backscattering foil motor* is part of the interlock system!  Which means that the motor can only be energised when the beamline is in a "run" condition and able to take beam.  During a shutdown, this isn't possible due to one of the interlock keys being held by the MCR until the beamline has been cleared, usually a few days before the cycle starts.

Someone is looking into the possibility of acquiring the missing interlock key so that the beamline can be locked up and said motor can be tested.  The main shutter still remains isolated in this case (separate interlock system), so there is no possibility of unauthorised exposure to beam, if any.

I shall report back when I've heard whether or not this is possible.

* To be specific, the limit switches are part of the interlock system and are disconnected when the blockhouse is unlocked, thereby preventing any motion (and the controller sees them as engaged simultaneously).

**Comment by davidkeymer** [comment]
I've just heard that the plan is to clear the beamline (very) early to enable all the interlock keys to be released.  Therefore the blockhouse can be locked and the backscattering motor can be run.

This will hopefully happen early next week (beginning 30th January).  I shall report back when I have confirmation.

**Comment by davidkeymer** [comment]
The VESUVIO beamline has now been cleared to take beam.  This should enable us to lock up the blockhouse and run the backscattering foil motor.

**Comment by AdrianPotter** [comment]
Needs ticket #2000
