### ISSUE TITLE
Multiple IBEX clients

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1893]
The users were running 6 instances of ibex on NDXLARMOR as they kept accidentally clicking on the icon pinned to the taskbar. Moving this to the start menu would be a simple short term solution, but could IBEX check if an instance is already running locally and then put up a dialog and exit?

**Comment by ChrisM-S** [comment]
I just tried this on my test machine, if you run the IBEX client and right-click “pin to toolbar” on the toolbar as it starts, all appears fine – but then IBEX renames its window and the Icon doubles up, if you click the inactive icon, it starts another version as many times as you want, if you click the active icon it iconizes or restores the session as normal.

If you wait until IBEX client is fully running (before doing the pin to toolbar), everything behaves fine after that and you can’t run multiple IBEcies without holding down shift.

**Comment by ChrisM-S** [comment]
Well, having spent a little while playing with multiple IBEX clients switched to different machines while seeing how the toolbar link was going wrong - I'm now a fan of being able to run at least two or three clients to monitor more than one instrument.  In a slight inversion of Freddie's suggestion, given a correctly working toolbar link multiple clients should only start if you deliberately go to start a new one from the start menu (or you use <SHIFT-Click> on the active toolbar icon to force a new window).

The behaviour of multiple clients seems good and I can see a scientist local contacting for another instrument keeping at least their normal instrument and contacting instrument open on their desktop.  I can also see a case for something like the Muon Front End being viewed in one IBEX on an EPICS MUSR along with the instrument control IBEX.

The only negative is you cannot easily stack/size them tidily without a very large screen as the size is fixed.

**Comment by ChrisM-S** [comment]
Not sure why but IBEX translates the junction points instead of reporting itself as running from the link, the second one will works fine and should remain OK on an instrument.
![untitled](https://cloud.githubusercontent.com/assets/3035405/21056683/9c62fc34-be2e-11e6-9587-5f8a0059efdc.png)

**Comment by kjwoodsISIS** [comment]
Are you sure that it is IBEX that is doing this translation?
I wonder if some of this behaviour is related to the JVM and/or Eclipse, rather than to anything we do (or don't do) in IBEX.

**Comment by ChrisM-S** [comment]
I agree, it’s probably not IBEX itself, unless the banner is coded differently?  Whatever, it doesn’t really matter, what is important is that on instrument installations in particular, we are careful to create the link by waiting until the banner has gone and the  GUI has started before pinning to the toolbar.  If IBEX is on the toolbar people will generally just click on the icon and get the correct behaviour each time as long as the icon is added correctly.  This probably means the ticket consists of changing the IBEX client install instructions in the developer manual so instead of:

                •Create a desktop shortcut to use to launch the IBEX client

It should be something  like

                •Create a toolbar shortcut to launch the IBEX client

-          Stop IBEX client (if it’s running), right click on any IBEX toolbar ICON and select un-pin

-          Start IBEX client, wait patiently until the full Client interface appears then “right click” on the toolbar icon and select “Pin”

-          Click the pinned icon again twice and check no more versions of the client are started and that there is only one toolbar icon still.

Note that the instructions in the user manual are probably correct.  This fix could/should probably be done as instruments are upgraded to 2.3?

**Comment by Tom-Willemsen** [comment]
Deployment instructions updated with the above points from @ChrisM-S

**Comment by AdrianPotter** [comment]
Generally good. Just a few comments on the new documentation.

> right click -> Pin to taskbar

It isn't clear that this refers to the start menu icon. It's minor, but could you make that clear to make it easier. The less implicit information in these algorithmic processes, the better.

> Check that you cannot open multiple clients by clicking on the taskbar icon again once IBEX is open

This is true. The original ticket was that multiple clients stack in the task bar. I would suggest a better fit would be that you should right-click the new icon, click ibex-client, and repeat. That will open multiple clients and they should stack. @ChrisM-S suggests that multiple open clients is a valid workflow so we should check that behaviour is as expected in that case. The more important reason to change it is that over time, the knowledge about why that step exists will be lost. It could create confusion in the future if the requirement is interpreted that only one client can be running at a time, which isn't the case.
