### ISSUE TITLE
VESUVIO: Install IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#1964]
As a scientist, I want IBEX to be installed on VESUVIO, so that I can use to control VESUVIO.

#### Acceptance Criteria
1. IBEX supports the VESUVIO sample environment equipment. 
1. IBEX installed and tested on VESUVIO in good time for the new cycle.

#### Notes
1. Next cycle starts on 14th Feb 2017
1. VESUVIO scientists will need time to test IBEX on VESUVIO before the new cycle starts.

**Comment by AdrianPotter** [comment]
Make the following changes to the installation instructions:

- [ ] The note about reinstalling MySQL if the correct version exists needs justifying. "Might ... consider" is too vague. Under what conditions is it ok to leave and reinstall.
- [ ] The note to check that EPICS blocks are logged is premature since it precedes installing EPICS
- [ ] The instructions currently say to run `config_mysql` on **upgrade**, but it should be on **install**
- [ ] The bullet point `install client` in install EPICS is confusing since there is a separate section on installing the client. The instructions should flow
    - The install client should be in line with the EPICS work flow
    - If someone wishes to install IBEX client standalone on their machine, it should be on a different page (since this is explicitly for instrument control PCs)

**Comment by AdrianPotter** [comment]
The instrument has been updated to accomodate the name change from NDXEVS to NDXVESUVIO. The web dashboard still needs updating though; we need someone with access to do it.

**Comment by AdrianPotter** [comment]
The web dashboard redirect has been done.

**Comment by Tom-Willemsen** [comment]
Ibex has been installed on Vesuvio successfully, the web dashboard works, and the installation instructions have been updated appropriately, so I am marking this as complete.
