### ISSUE TITLE
GALIL: allow alternative motor move commands

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1990]
The muon barn doors are not driven like regular motors, they are currently moved by a program within the galil using a bias voltage. The easiest way to move them with IBEX is to allow setting a galil controller variable as an alternative to a normal motor position command, so the existing program within the galil can be used.
So we would specify a string like "OFA=%f; XQ" and %f would get replaced with the requested position

**Comment by AdrianPotter** [comment]
With the new code, I lose the ability to move the motor normally. With the master version of the support module I can move the motor in Freddie's office. With the version on the PR, the motor doesn't move. Have I missed a step?

**Comment by FreddieAkeroyd** [comment]
Can you add a print in GalilAxis.cpp to check the move_command it reads from your environment. This is supposed to be initialised to a default of NULL/spaces by the EPICS db record, but maybe isn't somehow on your machine?

**Comment by FreddieAkeroyd** [comment]
What does your MTR0101_MOVE_CMD etc pv contain?

**Comment by AdrianPotter** [comment]
These errors are appearing after I restart the IOC:

![image](https://cloud.githubusercontent.com/assets/10273443/22458782/e30165f0-e795-11e6-8834-e01cc558daba.png)

**Comment by AdrianPotter** [comment]
The move command PV is empty but then naturally the motor is cooperating today when I try and reproduce the issue.

**Comment by AdrianPotter** [comment]
I restarted the IOC using the master branch and it gave the same errors as above. As I can't reproduce the error from last week, I can't see any reason not to merge it, but I'm a little cautious. Please could you make sure the MOVE_COMMAND is documented in the Galil documentation so that there's some information available in the case it does reappear:

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motor-SetPoints

**Comment by FreddieAkeroyd** [comment]
I always get some errors about jumpers from the motor in the office

**Comment by FreddieAkeroyd** [comment]
Document updated - i'll merge PR so Kathryn can test tomorrow

**Comment by KathrynBaker** [comment]
Just for reference regarding the jumper settings - this is down to the defaults used and set or not set within the Galil. Typically I've seen this on either test systems, or on systems with axes missing (it occurs with the Muon Galil), mainly because we don't always do the setup for the missing axes. I also think that these settings are checked under EPICS whether the motor is enabled or not, unlike under LabVIEW where (I think) it was only checked for the axis which are in use.
