### ISSUE TITLE
Make DAE support easier - Allow restart DAE IOC

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#2055]
As a member of support staff I would like to make it easier for fix common DAE problems which usually include restarting the DAE.  On Vesuvio yesterday there was a known DAE problem which requires intervention with the DAE outside IBEX. Whilst pair solving the issues with someone from Electronics, these issues came up.
1. The DAE IOC cannot be restarted easily from the IOC - this should be available to a suitably identified/privileged user as it is much quicker than restarting IBEX server.
2. When the DAE IOC cannot be restarted, it is necessary to restart IBEX server and there is nowhere on the client interface to allow this (again for a suitably privileged user).
3. When it is necessary to restart IBEX server not from the client interface, there are a confusing number of potential scripts which might do the job.  It would be easier if there was a simple link e.g. "Kill IBEX" as with the corresponding "Kill SECI" to ensure nothing is running and correspondingly, a suitable "Start IBEX" link (which might also start IBEX) on the client.
4. With Starting and Stopping IBEX in a support situation, potentially over the phone with no vision of what is happening it would be useful to know when the process has fully completed from the local screen at least.

*note*
A suitably privileged user may be an inexperienced scientist being instructed by a supporter from home so if something like a password is used it should be easy and generic

**Comment by KathrynBaker** [comment]
The DAE IOC can be restarted from the console, without restarting the IBEX server. Making this available to a client is possibly not a good idea, as this has, like the blockserver or database server been designated a “don’t touch” IOC – if there’s a problem we probably want to be looking at it. The consoles can be accessed by certain systems separate to the standard log ins (e.g. I could restart the Vesuvio DAE IOC from my desktop).

Similarly restarting the IBEX Server from the client is something that sounds wrong to me. You don’t restart a webserver from your standard browser (the server might give you a web page that would allow this, but that that is a function of the server not the browser), the browser is simply a client.

Some friendly shortcuts on the server might be nice, but at the moment the only specialist knowledge needed is that you have to go to c:\INSTRUMENT\APPS\EPICS and then run stop_ibex_server.bat and start_ibex_server.bat (in fact, just run the latter, at the moment it calls the stop automatically).

Whilst I am keen to see the separation of client and server, so that the client does not run on the NDX, I feel that we need to continue allow scientists access to this, so would imply that this password might fall into the category of machine passwords, as the console mentioned above is available on the server, and the friendly shortcuts would be too.

With what I’ve written above does this ticket boil down to “add a shortcut to start and stop _ibex_server.bat somewhere more obvious than in C:/INSTRUMENTS/APPS/EPICS”? If the console documentation (IBEX Developers Manual, not user manual) isn’t up to speed, make sure it is? Or even, provide something that can take an IOC name (it would need to be the IOC name) and will do the console restart without reference to the user, so that we can continue to keep those items that you don’t want to stop accidentally hidden from the client?

**Comment by ChrisM-S** [comment]
As a supporter, I would appreciate something as simple as CTRL-"." followed by a click on a run arrow --> to start up again when the DAE card has been changed.
;-)

**Comment by KathrynBaker** [comment]
Ticket came to a halt a number of years ago, closing, but can reopen or create a new one to cover what needs to be done if appropriate
