### ISSUE TITLE
Vesuvio: Fix instrument script

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2067]
Giovanni came and said that his instrument script is not working. A fix is required by this afternoon.

Issue is in `vesuvio_routines.py`. On line 62 there is `assert len(run)==2` but the `run` variable is not defined.

**Comment by Tom-Willemsen** [comment]
Now fixed. Marking as review for now. Close this if there are no related problems within the next few days.

**Comment by Tom-Willemsen** [comment]
Secondary issue reported by Giovanni:

"I started now the run but apparently there is a problem with the set-up of six periods. I can see an error in the "run summary" tab, in the IOCs Log and the top-left part of the screed shows "Period 1/1" instead of "Period 1/6"."

**Comment by kjwoodsISIS** [comment]
When we have fixed these problems, it would be good to understand why they occurred, so that we can try to avoid making them in the future.

**Comment by AdrianPotter** [comment]
They're fixed now. The issue here was a misunderstanding on my part about the translation between Open Genie and genie_python commands. I translated a:

```CHANGE NPERIODS=n```

to:

```g.change_period(n)```

rather than:

```g.change_number_of_soft_periods(n)```

The difficulty is that translating scripts between Open Genie and genie_python requires some understanding of what side-effects we might see on an instrument. I ran the script locally in simulation mode and the script did all the things I expected. I didn't notice the period not properly updating on the dashboard, nor did the reviewer. Perhaps it would be useful for common commands like these to have a page explaining what side-effects they should cause at the GUI level. This mistake is obvious now with the benefit of hindsight. 

We should also encourage instrument scientists to test converted scripts at the earliest convenience. Unfortunately I suspect it'd be hard to test these much earlier because of the beam state. The issue stopped Vesuvio from proceeding but the fix in each case was a couple of minutes' work from diagnosis to fix and test. Perhaps if a script can be run quickly in the production environment (which is true in this case) we should have one of the dev team sitting in when they run their first converted script just to fix any problems in place.

**Comment by Tom-Willemsen** [comment]
It may be worth discussing all the behaviours that are expected with the instrument scientists. If we have a checklist of things that the script it expected to do, then it should be relatively easy to test the translation and tick off the items on that list...

I also think Adrian's idea of a developer sitting in when they first run the script is a good one, but I'm not sure how scaleable it is when we start bringing several instruments online at once and they'll all want to test their scripts just before cycle starts...

The Vesuvio script wasn't overly complex, but other instruments will have more complicated script(s), so it may be worth having a think about how to reduce the chance of these sorts of translation errors occurring again, or at least catching them well before cycle starts.

**Comment by Tom-Willemsen** [comment]
No issues within the last couple of days, so I think this is complete now.
