### ISSUE TITLE
POLARIS: Jaws Manager

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2083]
As a scientist, I would like the IBEX Client to provide a GUI to help me manage the settings of all 5 jaw sets.  
To do this an IOC with the logic in needs to be created.

#### Acceptance Criteria
1. I can adjust the settings of all 5 jaw sets.
1. I can view a schematic representation of the blades (N, S, E, W) for each jaw set
1. I can adjust the settings of each jaw set by setting the N, S, E, W positions or by setting 
   values for the horizontal & vertical gap and horizontal & vertical centre positions.

#### Notes
1. The 5 set of jaws will be restricted via a password - see #2082
1. POLARIS jaws are JJ X-Ray jaws, driven by Galils.  The Galils IOC has logic for managing jaws.
1. There is an existing jaws OPI.  Perhaps we can adapt it for use in this OPI.
1. See the VI for forumlae
1. This has been updated from manage Jaws OPI which was going to be separate. If you determine that this really does need to be a different opi then rethink then.

**Comment by kjwoodsISIS** [comment]
I have a printed screenshot of the current LabVIEW UI of the POLARIS jaws manager.  Come and ask for it.

**Comment by Tom-Willemsen** [comment]
Put password into `inst etc` IOC. Passwords should be central and not linked to a particular IOC (at least according to @DominicOram...)

**Comment by Tom-Willemsen** [comment]
Review at the same time as 2082
https://github.com/ISISComputingGroup/ibex_gui/pull/475

**Comment by KathrynBaker** [comment]
Keeping with #2082

**Comment by KathrynBaker** [comment]
these cover both #2082 and #2083

**GUI**

Have added some checkstyle warnings when I look at Eclipse (total before 2171, total after 2178) - whilst the package.info is standard, the others should be resolved:

File | Line | Issue | Removes this many new checkstyles
---|---|---|---
EnterManagerModeDialog.java | 90 | try{ - needs a space before the { and after the try | 2
EnterManagerModeDialog.java | 119 | { followed by a space | 1
ManagerModeBannerModel.java | 41 | Missing javadoc | 1
ManagerModeBannerModel.java | 83 | { followed by a space | 1

The jaws_manager needs the same links as the jaws OPIs, or is there a reason that they are missing the link down to the lower levels, including the motor records)?

Are they meant to wait for the set button before moving when entering the size of beam at sample, as they don't

Should manager work on a local system? I would expect it to, but at the moment it doesn't seem to matter what state the manager PV is in (at least when set directly from a caput).

I thought the manager password was meant to be set to the same as we use in SECI - it isn't taking that for me


**Motor Extensions**

Some indicator that this is the polaris jaws in the motor extensions would be useful, as Nimrod is likely to need something similar, so just using JAWS:HGAP and JAWS:VGAP isn't overly helpful

The use of motorExtensions moves the barndoors code for hte Muon Front End - this isn't mentioned in the Release Notes - if I wasn't reviewing this I might not notice this, and suddenly have a problem with the code that would take forever to diagnose without that knowledge


**Jaws**

The DEFAULT for the jaws should be specified in the DB file with the macro ($(ASG=DEFAULT)) - that way only the variations need to be specified for the MANAGER group

**Comment by KathrynBaker** [comment]
After checking with Tom, I was using the default password I think of rather than the one detailed in the pull request, that password worked, so all we need to do is change it to use the standard password

**Comment by Tom-Willemsen** [comment]
Answers to a few of the above points:

- Checkstyle - yep ok, fixed.

- Link to motor records - the motors themselves are **not** currently protected by the access security as that would involve modifying the motor record which we think might be complicated. So that's the reason I didn't put in the option to "drill down" to the motors from the jaws manager OPI. I'm open to suggestions if that isn't an appropriate solution.

- Set button: good catch, that was just a leftover from a mockup that wasn't doing anything. I removed it.

- "Should manager work on a local system": yes. It looks like I forgot to create a pull request for the crucial bit of magic, which might explain why it didn't work. It's added to the main PR as well but here's the link: https://github.com/ISISComputingGroup/EPICS-AccessSecurity/pull/1

-  I imagine that the nimrod jaws would use a seperate DB file, and not load the `polarisjawset.db` ever, so there wouldn't be any conflicts with those two seperate db files using the same PV names. Correct me if I'm wrong on that assumption...

- Release notes: fair point, I will add that detail.

- Default macro - yep ok, will sort this

**Comment by KathrynBaker** [comment]
My point for the jaws names is more to do with loading it not being in the db file itself (as we might have something that uses the same logic anyway), and therefore effects the OPI. If it is just pointing at JAWS:HGAP then if you do load the wrong file, or the wrong OPI (more likely), then you could do something that would damage a system, or at least give crazy readings. If the Polaris jaws OPI is looking for POL:JAWS:HGAP then that is a touch safer. Especially if you type it out manually for some reason. It is unlikely to happen, but the impact is high, so it is a risk worth mitigating – not in the db file, you can add the POL in the dbload, but in the OPI.

**Comment by Tom-Willemsen** [comment]
Summary of changes since the last PR:
- Access security PR has been added now, so it should all "just work".
- Checkstyle fixed.
- ASG defaults to `DEFAULT`, only have to tell it explicitly if you want a different access security setting.
- Removed "Set" and "Stop motion" buttons from the OPI as they weren't doing anything.
- Barndoors - I've removed the code from this pull request and generated a new ticket #2218 to move the code over.
- Password has been updated to the one you'd expect.
- PV names now use something like `TE:NDWxxxx:POLJAWSET:VGAP:SP` to minim of confusion / wrong OPIs being opened.

Configuration file (configurations/galil/jaws.cmd) now looks like this (I've also updated it in the GUI pull request):

```
############ Polaris jaws ##############
# Create a soft motor record on top of a normal motor record which allow the gap to be set for the motor
# Copy this file to C:\Instrument\Settings\config\<machine>\configurations\galil

# Define a set of jaws from first 4 motors on second controller (if present)
$(IFDMC02) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS1:,mXN=MTR0201,mXS=MTR0202,mXW=MTR0203,mXE=MTR0204")
$(IFDMC02) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS2:,mXN=MTR0205,mXS=MTR0206,mXW=MTR0207,mXE=MTR0208")
$(IFDMC03) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS3:,mXN=MTR0301,mXS=MTR0302,mXW=MTR0303,mXE=MTR0304")
$(IFDMC03) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS4:,mXN=MTR0305,mXS=MTR0306,mXW=MTR0307,mXE=MTR0308")
$(IFDMC04) dbLoadRecords("$(JAWS)/db/jaws.db","P=$(MYPVPREFIX)MOT:,JAWS=JAWS5:,mXN=MTR0401,mXS=MTR0402,mXW=MTR0403,mXE=MTR0404,ASG=MANAGER")

# Define jaws as soft motor records using the second galil controller, if present

$(IFDMC02) dbLoadRecords("C:/Instrument/Apps/EPICS/support/motorExtensions/master/db/polarisjawset.db", "P=$(MYPVPREFIX), COLHEIGHT=40, COLWIDTH=82, MOD_TO_SAMPLE=14000, MOD_TO_COL=1610, MOD_TO_JAWS1=6502, MOD_TO_JAWS2=9440, MOD_TO_JAWS3=11085, MOD_TO_JAWS4=11735, MOD_TO_JAWS5=13175")

```
