### ISSUE TITLE
LARMOR : PLC Connection Problem

### ISSUE THREAD

**Issue by GDH-ISIS** [ISISComputingGroup/IBEX#2101]
Problem with LARMOR PLC Connection.
Origin of problem : The bench on LARMOR has now been loaded with far more weight as a result of the spin echo equipment from DELFT. As a result, the bench feet need more flow to lift the bench when it is needed to be moved. Peter Barnes and Jonny Ranner were involved in reconfiguring the PLC with new flows to lift the bench. After this, the remote operation of the bench was not possible from ndxlarmor. PLC was on the network. According the Peter and Jonny, the PLC looked fine.

**Comment by GDH-ISIS** [comment]
Matt Clarke noticed that the ioc was generating errors : \\ndxlarmor\c$\Instrument\Var\logs\ioc\FINS_01-20170221.log. The errors appeared to be of the form :


[2017-02-21 04:57:46] 2017/02/21 04:57:46.089 IN:LARMOR:BENCH:FLOW4:RAW devAsynInt32 process read error 

[2017-02-21 04:57:46] 2017/02/21 04:57:46.089 send_fins_header: port PLC, send() failed with An existing connection was forcibly closed by the remote host. .

[2017-02-21 04:57:46] 2017/02/21 04:57:46.089 IN:LARMOR:BENCH:VALVE1:RAW devAsynInt32 process read error 

[2017-02-21 04:57:46] 2017/02/21 04:57:46.089 send_fins_header: port PLC, send() failed with An existing connection was forcibly closed by the remote host. .

**Comment by GDH-ISIS** [comment]
The FINS IOC did not look as though it was restarting. After manually restarting the FINS IOC all was ok again.

**Comment by GDH-ISIS** [comment]
Did a quick test :
Turned PLC off.
Turned PLC back on.
Remote operation no longer worked.
Restarted FINS IOC. 
Remote operation now worked.

At present, I think if the PLC is power cycled, the IOC generates an error and the FINS IOC needs to be restarted.

**Comment by KathrynBaker** [comment]
This would follow, and I think the same is true for those being used under LabVIEW as well. Without having sent the handshaking at the start of the FINS then it will be in the wrong state to interact with the remote system.

This means that the error is valid, the PLC isn’t responding to commands or queries, and the easiest way to resend those initial commands is to restart the IOC.

I’m not sure there is anything better as a solution than ensuring that people know to restart the IOC if the PLC is power cycled.

**Comment by kjwoodsISIS** [comment]
Perhaps, as a first step, we could add a note in the Release Notes.  At least that way the scientists would know that they need to re-start the relevant IOCs.
We could also add something to a troubleshooting page in the User Manual.

**Comment by ChrisM-S** [comment]
##Robustness

We have sometimes had this problem with VIs in the existing control system.  If there is something that can be done from the computer side to make things work, it’s usually imperative that we do it – because the alternative may be beam time loss – and we will be asked for it after this happens.

With VIs and I’m guessing also with the IOC, it may not be necessary to restart the IOC, but it might be necessary for the IOC to realize that the comms. are giving an issue and do a full initialization of the connection (serial or Ethernet) – and maybe try this on a reduced frequency for when the kit is switched on/reconnected etc.  If the only way it can fix itself is to fall on its own sword for a restart it probably should.

Another similar example from the Oxford Instruments ITC (and comms to most the Oxford kit in fact) is if the user has the ITC under computer control but pushes the local/remote button on the physical device so they can look see a sensor temperature, it is possible to send the command to put the ITC back into remote mode and keep control going (otherwise the user will break the experiment from then on).  This sounds counter intuitive initially, but if the script is controlling something and the user wants to fiddle and take control, they have to stop the script first! – the users often don’t really understand the implications of what they are doing.

I don’t know if this is possible, but if an IOC does fault and crash, it is probably important to restart it (unless it is marked to not allow restarting).  Like a windows service, it might be worth having a limit for restarts – but once again, it could avoid loss of an experiment.

##Caveat

This doesn’t mean we have to start certain things (like Fermi choppers) where we are requested not to bring them back under computer control after an issue.  Neither does it mean we have to try and fix or mask faulty hardware (which is inherently faulty) through software means – but we still have a habit of doing this for the same reason.

**Comment by FreddieAkeroyd** [comment]
I think the FINS IOC should auto-reconnect on error and it shouldn't be too hard to add - I've created a ticket #2103   Given it is in procServ simply doing exit() on an error would cause a restart and reconnect, but that is not a nice solution :-D

**Comment by GDH-ISIS** [comment]
I think this ticket is just a place holder for information. It is currently operational generally as long as the PLC is not power cycled. This ticked is now superseded by #2103.
