### ISSUE TITLE
GUI: Can't edit IOC macros

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2150]
To reproduce:
* Create a config with an IOC
* Save the config
* Edit the IOC
* Notice that you cannot see any of the IOC macros

**Comment by AdrianPotter** [comment]
Not sure how much you've done yet, but this might be the culprit

https://github.com/ISISComputingGroup/IBEX/issues/2048

I removed the EditableIoc class because the functionality appeared redundant once the description is not editable. It may be that I didn't hook up the macros (or more) correctly.

**Comment by DominicOram** [comment]
It looks like you removed the EditableIocState rather than EditableIoc? Am I looking at the right PR?

**Comment by AdrianPotter** [comment]
Awaiting #2156
