### ISSUE TITLE
Deploy New IBEX Release to Instruments

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2171]
As a developer I want to deploy the new release of IBEX to instruments prior to the 2017/01 cycle. 

#### Acceptance Criteria
1. Deploy MySQL 5.6.latest to instruments (same list as below)
1. New release of IBEX deployed to
   1. LARMOR
   1. IMAT
   1. IRIS
   1. ALF
   1. VESUVIO
   1. POLARIS
   1. HRPD
   1. MUONFE
   1. ZOOM

#### Notes
1. Cycle 2016/05 is the current active cycle. It finishes on 31st March 2017.
1. Cycle 2017/01 starts on 2nd May 2017.  It finishes on 2nd June 2017.

**Comment by AdrianPotter** [comment]
I've asked the inst scientists about installation. Rob (Larmor) and Genoveva (IMAT) have asked for deployment this afternoon.

@Tom-Willemsen is going to do IMAT, but without the stress rig because it needs expert set up. He's then going to demo with @ThomasLohnert.

@ThomasLohnert is going to deploy to Larmor.

Russell (ALF) has replied "as soon as you like" so we'll get round to it asap. If anyone else wants to pick it up before I do, please go ahead and reply here that you're doing it.

**Comment by ChrisM-S** [comment]
just for @Tom-Willemsen, the NDHIMAT machine is not in the rack with the DAE so all should be for installing except for the Stress Rig and DAE - I will check out the DAE when it is back in the rack.

**Comment by Tom-Willemsen** [comment]
IMAT upgrade complete and demoed to instrument scientists.

**Comment by ThomasLohnert** [comment]
There's seemingly a problem with the DAE on LARMOR at the moment. I upgraded IBEX and got up to the server tests part before running into that.

**Comment by ThomasLohnert** [comment]
LARMOR upgrade is complete

**Comment by AdrianPotter** [comment]
All instruments except MFE are now on 3.2.0. MFE will be migrated by Kathryn at a later date once it's available.

**Comment by KathrynBaker** [comment]
All instruments except MUONFE are updated, need to add the MySQL update to MUONFE deployment for next time.
