### ISSUE TITLE
GUI: Synoptic DAE no longer switches perspective

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2182]
Clicking on the DAE within a synoptic used to switch the perspective to the DAE perspective, this no longer works.

**Comment by Tom-Willemsen** [comment]
This occurs because the list of perspectives looks like this internally:

```
&Beam Status : uk.ac.stfc.isis.ibex.ui.beamstatus.perspective
&Experiment Details : uk.ac.stfc.isis.ibex.ui.experimentdetails.perspective
Log &Plotter : uk.ac.stfc.isis.ibex.ui.logplotter.perspective
&Web Links : uk.ac.stfc.isis.ibex.ui.weblinks.perspective
&Alarms : uk.ac.stfc.isis.ibex.ui.alarm.perspective
De&vice Screens : uk.ac.stfc.isis.ibex.ui.devicescreens.perspective
IOC &Log : uk.ac.stfc.isis.ibex.ui.log.perspective
&Motors : uk.ac.stfc.isis.ibex.ui.motor.perspective
&NICOS Scripting : uk.ac.stfc.isis.ibex.ui.nicos.perspective
Script &Generator : uk.ac.stfc.isis.ibex.ui.scriptgenerator.perspective
&Scripting : uk.ac.stfc.isis.ibex.ui.scripting.perspective
S&ynoptic : uk.ac.stfc.isis.ibex.ui.synoptic.perspective
&DAE : uk.ac.stfc.isis.ibex.ui.dae.perspective
```

Notice the random ampersands everywhere.

When you then try to switch to the DAE perspective it complains that it doesn't exist.

In `/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/Perspectives.java` modify the getID method to look like this:

```
public String getID(String perspectiveName) {

        if (perspectiveName == "DAE") {
            perspectiveName = "&DAE";
        }

        return ids.get(perspectiveName);
}
```

This fixes the issue (but is definitely not a "good" fix)!

I suspect this bug was caused by #1934

**Comment by DominicOram** [comment]
The solution to this should be that instead of looking up the ID based on the perspectiveName a PerspectiveTarget should hold the ID it wants to switch to.

**Comment by DominicOram** [comment]
GUI code at: https://github.com/ISISComputingGroup/ibex_gui/issues/489
System tests at: https://github.com/ISISComputingGroup/ibex_system_tests/issues/45
