### ISSUE TITLE
Scripting: Script checker gives errors for comments

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2205]
If I have a script with triple-quote documentation, then the script checker gives errors if it contains certain keywords (e.g. pause, end, update) associated with genie_python routines. I should be allowed to use these words in the comments.

```
def my_function()
    """
    This function does a pause, an update, and ends the run
    """
```

**Comment by Tom-Willemsen** [comment]
This is unfortunately not a trivial change. At the moment the script checker only checks one line at a time (using regexes) and has no awareness of whether it's within a comment block or not.

You *might* be able to hack together a solution based on how many `"""` lines you have passed, but the real solution is to use an actual python parser instead. 

That will make a lot of things much easier (and less error prone) than the current system of using regexes, and the functionality mentioned in this ticket will come "for free".

**Comment by FreddieAkeroyd** [comment]
Can you pre-filter using a multi-line regex match on """" to strip out all comments?

**Comment by Tom-Willemsen** [comment]
Yes, that's along similar lines to what I suggested above, but it feels like a hack to get around the fact that we're not using the right tool for the job.

**Comment by FreddieAkeroyd** [comment]
indeed - I guess we are not aware of any scientist being caught by this issue?

**Comment by kjwoodsISIS** [comment]
Could we use Python's own checking capabilities?  Might not be easy.

**Comment by Tom-Willemsen** [comment]
Can the python linting ticket do this for us instead?

**Comment by JamesKingWork** [comment]
> Can the python linting ticket do this for us instead?

#4630 Has partially solved this ticket because we are now using pylint for a lot of script checking. For example writing pause, update or begin in a comment is checked by pylint which recognises comments and as such no error is given. However, defining additional builtins in pylint does not work correctly and as such we have had to leave checking if g or inst is redefined to the old script checker. Because of this being left in the script checker, after #4630, writing `g=3` in a comment still shows an error to the user when checking a script.
