### ISSUE TITLE
Install: Client install script does not work

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2249]
The client install script no longer works. It errors with:

```
Z:\3.2.0\Client>if exist "Z:\3.2.0\Client\..\genie_python" (
set GENIE_PYTHON_TOP=Z:\3.2.0\Client\..\genie_python
 call \genie_python_install.bat
)  else (
set GENIE_PYTHON_TOP=Z:\3.2.0\Client\..\..\genie_python
 for /F %I in (\LATEST_BUILD.txt) DO SET LATEST_BUILD=%I
 call \BUILD-\genie_python_install.bat
)
'\genie_python_install.bat' is not recognized as an internal or external command
```

The reason is that the varibales in the if are replaced early not during the if evaluation so this does not work.

**Comment by John-Holt-Tessella** [comment]
Workaround use MSIs

**Comment by FreddieAkeroyd** [comment]
Which bit do you use the MSI for - the client or genie_python or both?

**Comment by FreddieAkeroyd** [comment]
The client install script will install the client but not genie python due to the error, so you could just then call genie_python_install separately

the client MSI just installs the client and not genie python

the genie_python MSI doesn't currently create an ipython profile, so if you are installing on a brand new machine running genie_python_install would be best for now

**Comment by John-Holt-Tessella** [comment]
Ahh, ok we used msi for all build we will correct this when we update.

**Comment by FreddieAkeroyd** [comment]
I'm note sure how important the profile is, I just noticed it got created in the install script. I was updating the msi to do this, but hadn't completed that yet.
