### ISSUE TITLE
MUONFE: GUI: Something which looks good and is useful

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2275]
As an instrument scientist I want a GUI for the Muon Front End which is pictorially correct, and allows for setting of values

#### Acceptance Criteria
There is a GUI, with the single beamline split into three, with beam paths for all of them

#### Ideal situation
The beam path would be highlighted as in an error condition after any item that has errored.

#### Notes
1. This might sound like #1195, and whilst it would be nice to enact on the synoptic, it may be better, as anything like this will be quite bespoke to generate the solution as an OPI, or a specific perspective.
1. In discussion, we agreed that it would be better to do it as a real synoptic (if we can) - i.e. follow the #1195 route if technically possible.

The team would like this, to make IBEX even more useful for them, for cycle 17/2

**Comment by kjwoodsISIS** [comment]
We think it would be better to do #1195, rather than this ticket.

**Comment by Tom-Willemsen** [comment]
@KathrynBaker is already down to demo to the muon scientists on 19/6. This would probably be a good time to talk to the instrument scientists to see exactly what they would like, as it's not entirely clear how this OPI should look. Possibly take a (very quick) mockup and see what suggestions the scientists have?

I can do this unless someone else wants to.

**Comment by Tom-Willemsen** [comment]
Mockup OPI is on a branch for this ticket.

**Comment by kjwoodsISIS** [comment]
Can you add a link to the mockup to this ticket, so that it is visible from the originating ticket.

**Comment by Tom-Willemsen** [comment]
![image](https://user-images.githubusercontent.com/24375813/27278019-1ea3b50e-54d8-11e7-8612-47ce36650ff5.png)

That is an initial mockup which displays the same data as their existing synoptic but makes it clearer where the beamlines split. I am conscious that it is quite crowded but I think that's potentially inevitable given how much data they want to display.

**Comment by Tom-Willemsen** [comment]
Feedback from muon scientists:
- Just want a compact "overview"
- Benefit if it can fit on one screen full
- "LED" status indicators are ok - two for each power supply: on/off and out of range alarm
    * Alarm could be raised on any of current, voltage, power and needs to propagate properly.
- Buttons to open a more detailed view of any one particular power supply would be good
- Fine to split the beamline if it makes the layout easier

If possible:
- One global "everything OK" LED, dependent on the status of many other indicators.

**Comment by AdrianPotter** [comment]
Look great, thanks. As discussed, just a couple of points:

- [ ] I don't like the aesthetic of colons on the column headers. Feel free to either disagree or remove
- [ ] The repetition of `Details...` boxes looks cluttered. Better if we can have the device labels as buttons. The best way I can think of to do this is to have 2 buttons, one hidden and one visible, depending on the value of PV_ROOT. A little messy perhaps but worth it I think.

**Comment by KathrynBaker** [comment]
Having had a quick look, I'm not sure this is what the instrument scientists want, it might be worth double checking with them before completing this ticket, it is quite a bit different from the 'tube map' version of the initial mockup in an earlier comment.

**Comment by AdrianPotter** [comment]
I don't think having the entire linking container clickable is especially user-friendly. 

- There is no obvious sign until you hover over the OPI that the control is clickable
- It's not intuitive what clicking in that area will do
- It is not obvious whether clicking on the LEDs, or the device name, have different behaviour. It should be obvious and intuitive to the user what the result of their action should be before they perform it

I would much rather the device name just be clickable as a button. That way it's obvious what is actionable, and intuitive what it's likely to do. It's not as neat from a coding perspective but I think offers significant usability benefits.

**Before moving back to review**, please also present the new OPI to the instrument scientists to confirm this is genuinely what they want, rather than the "tube map". From Tom's comment, I believe this has already been run by the instrument scientists once, but it would be good to get the thumbs up on the final design lest it come back to us in a couple of sprints.

**Comment by DominicOram** [comment]
Waiting on feedback from scientist

**Comment by DominicOram** [comment]
Current version on branch has been approved by scientist
