### ISSUE TITLE
GUI: Allow multiple perspectives open simultaneously

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2278]
When we demoed to Rob on LARMOR, he said that it would be useful for him to see multiple perspectives at once. In his case he wanted to see his synoptic, a scripting window and a graphing window all in one "view".

i.e. something that looks vaguely like this:

![a](https://cloud.githubusercontent.com/assets/24375813/25525470/f7178a28-2c06-11e7-804b-31f9bc89d6f1.png)

**Comment by ChrisM-S** [comment]
Compliments on the MSpaint skills!

When this ticket comes up, it would be a good idea to also talk to the muon scientists as they pushed the design of SECI in a very specific direction with their requirements for the equivalent of multiple perspectives – similar to above, but including device log plots with actual values, and set points drawn on the same graph.  Possibly also other things I've forgotten.

(I take no credit, The data artist in this case is SECI :-)

![muonseciscreen](https://cloud.githubusercontent.com/assets/3035405/25525908/1dd887a0-2c09-11e7-851f-128105504a72.png)

**Comment by KathrynBaker** [comment]
Please also consider ticket #852 when thinking about this, as we already have something which is almost exactly this ticket. We have been asked for this for a long time. It has been looked into in the past (possibly not since the SVN days), and there was a reason we didn’t do it then. I have something in my mind about this kind of perspective being horridly difficult and a lot of work, and at the time we were looking at Eclipse 4. There may be other similar tickets as well.

**Comment by DominicOram** [comment]
This actually shouldn't be too bad from a code POV, these windows are designed to be very movable (so much so that if you switch between some perspectives too quickly you can replicate the above picture). However, we have gone to great lengths in the past to ensure that they're quite locked down. I believe a decision was made before I started that having too much customisation could confuse users and get the GUI into very bizarre states. It's also worth keeping Eclipse 4 in mind with this ticket. Any solution we come up with will almost certainly have to be entirely rewritten in e4.

**Comment by kjwoodsISIS** [comment]
Postpone until we do Eclipse V4

**Comment by KathrynBaker** [comment]
We have been on eclipse V4 for a number of years of this point, and whilst not the best workaround it is possible to open multiple clients looking at the same server, which allows this style of functionality, closing.
