### ISSUE TITLE
LARMOR: Stop MySQL Catalogue update

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2346]
Rob reported tasking.exe window associated with MySql that keeps flashing up. Googling suggests this is related to update of the catalogue. Put instruction on how to turn this off in.

**Comment by John-Holt-Tessella** [comment]
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/server-release-tests

**Comment by ChrisM-S** [comment]
I've had a look to see if not adding this auto-update check is an option in the command line MySQL installer, unfortunately, it doesn't appear to be possible - so the programmatic way of doing it has to be

`schtasks /delete /tn \mysql\installer\manifestupdate`  (which removes the task after installation).

If you manually run the GUI installer the presence of this task is checked and if it is not there it will at any opportunity ask you to enable it again! There is also the possibility that an update for security or otherwise to the installer will do this - I did try an upgrade of the database (5.7.17->5.7.18) and it did leave the task alone. A manual update of the catalogue also seems fine.

Also, slightly worrying, this task on the instruments is set to run as `NDX<inst>\spudulike` which is the non-privileged account.  Had it run as `NDX<inst>\gamekeeper` the task window would have been supressed (although the update would have run) and not risked popping up in a user session.

Does this ticket include deleting it off all the instruments it is still on so it doesn't flash every day? not a big deal. I can create a controls ticket if necessary.
`PS C:\> 'NDXIRIS', 'NDXLARMOR', 'NDXVESUVIO', 'NDXALF', 'NDXZOOM', 'NDXPOLARIS', 'NDXIMAT', 'NDXHRPD' | %{ schtasks /delete /s $_ /tn \mysql\installer\manifestupdate }
`

**Comment by Tom-Willemsen** [comment]
Instructions on the wiki to disable the update seem fine. 

Just an idea - could that command that @ChrisM-S mentioned be run as part of one of the installation scripts (e.g. `install_to_inst.bat` or similar? Or would bad things happen if we run the command and the scheduled task doesn't exist?

**Comment by kjwoodsISIS** [comment]
We seem to put a large proportion of our tickets into "rework".  If a ticket genuinely need rework, that's fine.  But if the solution meets the needs of the ticket, why put it through rework?

In this case, the task was to create instructions on how to prevent MySQL update from running on an instrument.  The instructions have been created; they meet the requirement (i.e. they don't need to be reworked); job done.  
If we want to come up with a more general, automated solution, it should be the subject of another ticket.

**Comment by ChrisM-S** [comment]
Yes, I agree Kevin, but I guess we can get a real pattern out of this example.  There are three almost automatic tickets for an operational issue (during cycle).

1)	**BUG**/Defect etc There is the immediate need for a fix/workaround (so I did this in the controls ticket which was for all machines).
2)	**Change to deployment process** There is the need for testing and finding something to go into IBEX deployment instructions (otherwise the problem might appear again)
3)	**Clear up/Fix forever** Then there is a sort of research ticket or a “Fix this problem for good - ticket” which makes sure there is one less issue.  In this case, I’ve done the research and appended the information to the controls ticket to keep a consistent history.

If the problem is not “critical” some things could be spun off to be done later.

As we are still on the original IBEX ticket, I will point out that from what I’ve discovered it is documented and probably wise to simply uninstall the MySQL installer from the Windows Control Panel.  This leaves MySQL untouched and takes away the “extra bells and whistles code” which really (as with the Java updater) has no place on managed production system.  This might be another ticket to do to document this.
