### ISSUE TITLE
EMMA: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2364]
As an instrument scientist, I would like to migrate EMMA to use the IBEX instrument control system.

#### Acceptance Criteria
1. IBEX is installed on EMMA
1. Configuration files are created (see #2387)
1. IBEX is configured for the devices on EMMA.
1. EMMA scripts are converted to genie_python
1. EMMA scientists are trained in how to use IBEX
1. IBEX is tested on EMMA

#### Notes
1. The devices on EMMA are listed on the [EMMA Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/EMMA-Instrument-Details) list
1. The following tickets should be implemented prior to deploying IBEX on EMMA
   - [x] #2365
      - In progress
   - [x] #2366
      - #1197 ~~awaiting review~~ complete
   - [x] #2387 
   - [x] #2388
   - [x] #2397
       - ~~Impeded awaiting #2768~~
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
   - [x] Ask Facilities IT (Anthony Shuttle) to create a private network for EMMA.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
      - Emailed Anthony 15/11/17
   - [x] Check that NDXEMMA has sufficient disk space to install IBEX
   - [x] Check whether EMMA uses 5- or 8- digit run-numbers
      - [ ] ~~If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)~~
   - [x] Create a virtual instrument for testing purposes
      - [x] Set up a test system, say, NDXEMM-ATEST.
      - [x] create IBEX configurations to correspond to their SECI equivalents
      - [x] create genie-python scripts to correspond to their Open-Genie equivalents
      - [x] test these configurations & scripts
      - [x] check that all the devices previously supported by SECI (on EMMA) are supported by IBEX
   - [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
      - [ ] demonstrate the configurations & scripts (created above) to the instrument scientists and check that they are happy with the migrated configurations & scripts

**Comment by ChrisM-S** [comment]
Sent a note to EMMA instrument scientists to say that EMMA will not be migrated for next cycle.

**Comment by Tom-Willemsen** [comment]
Note the machine is actually called `NDXEMMA-A` not `NDXEMMA`.

**Comment by AdrianPotter** [comment]
I've done the majority of the setup. I'm setting impeded until the Fermi chopper and lift are in so I can add them.

I've migrated some scripts I found on EMMA. They seem to have been stolen from GEM but customised for EMMA. I've migrated them to genie_python. Tom is going to ask whether that's sufficient or whether they want more as part of #2388.

The configurations have been migrated but currently don't contain the chopper or lift.

Training has been organised for 23rd/24th January. We'll make sure Jeff is encouraged to attend

**Comment by AdrianPotter** [comment]
Jeff is signed up on the training. Waiting for outstanding tickets to be reviewed. I've asked Jeff for a time we can do a preliminary migration to confirm everything is set up to his liking

**Comment by AdrianPotter** [comment]
The migration is mostly complete. There are a few outstanding tasks:

- [ ] The shutter status is currently listed as "UNKNOWN". I'm told that's because the shutter status is contained in a PV with instrument name "HET" rather than "EMMA-A". We need to see if we can create a new PV.
- [ ] I can't talk to the Eurotherm at the moment. Neither can LabView. I suspect it's unplugged. It has the same COM port listed as the Galil though which is weird. I need to ask Jeff
- [ ] I've burnt the standard IP address to the Galil. It just needs plugging in to the network now, which needs to be done by one of the controls team
- [ ] I want to double check what Jeff expects with regard to the CAENs.

**Comment by kjwoodsISIS** [comment]
@FreddieAkeroyd - do we need to retain the legacy name, "HET"?  Is it likely that there is some other process (perhaps something owned by the Accelerator Controls team) that still uses "HET"?  Can it be eliminated?

**Comment by FreddieAkeroyd** [comment]
There was already a PV for the EMMA shutter, but it was called "EMMA" rather than "EMMA-A" - I've added an "EMMA-A" alias which should now be active. I haven't removed the HET alias yet, but it is not causing any problems. All instrument shutter PVs are actually aliases for an underlying port PV which is named something like  N9 for "north 9"

**Comment by AdrianPotter** [comment]
Super, thanks. Moving to impeded awaiting connection of the Galil via ethernet

**Comment by AdrianPotter** [comment]
I've done the final setup on Emma. Waiting for Jeff to get back to me so we can organise a time to look at it together

**Comment by AdrianPotter** [comment]
Meeting on EMMA today 1:30 with Mark Brind from the chopper group to finish and test the setup

**Comment by AdrianPotter** [comment]
Jeff's happy with the current setup. We haven't been able to test the chopper lift or chopper because the chopper is broken. Mike Brind has scheduled maintenance

**Comment by kjwoodsISIS** [comment]
If we are waiting for the chopper to be fixed, we should not leave this ticket in an impeded state (because it might take some time to fix the chopper).  It would be better to create a new ticket to address the outstanding chopper tasks, rather than hold up the review & completion of this ticket.

**Comment by Tom-Willemsen** [comment]
IBEX is deployed on EMMA.

Reviewed:
• I've had a look at their configs, synoptics, DAE tables. They seem plausible.
• I had a look at the scripts - they seem ok, a bit more advanced than most instrument scripts in terms of python knowledge but they seem ok.
• I had a look at the logs that have been generated so far, nothing jumps out as being wrong since they were last updated on 2/2/2018. Before that date the ARACCESS IOC was spewing some logs but it looks like that has been fixed since the new deployment.

There is some outstanding work for this e.g. test the Fermi Chopper but this is captured in separate tickets so I will mark this as complete.
