### ISSUE TITLE
ENGIN-X: Superlogics - IOC & OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2378]
As an ENGIN-X scientist, I need IOC & OPI for the SuperLogics POE-8019 Thermocouple Box, so that I can acquire & log data from thermocouples attached to the ENGIN-X stress rig.  

#### Acceptance Criteria
1. The IOC must support communications with up to 8 thermocouples.
1. The IOC must log data from up to 8 thermocouples.
1. The OPI must display the status and readings from up to 8 thermocouples.
1. Create an emulator.
1. Integrate into IOC testing.

#### Notes
1. See [ENGIN-X Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/ENGIN-X-Instrument-Details) for additional information.
1. There is an existing LabVIEW VI for the Superlogics box (ask Gareth for details).  The IOC & OPI could be based on the logic in the VI.
1. How are these thermocouples calibrated?  Do they use the same calibration files as thermocouples attached to Eurotherms?
1. Logging needs to be done across runs - so needs a special logging solution (but not part of this ticket).

**Comment by KathrynBaker** [comment]
Few issues to be addressed (hence the rework):

For https://github.com/ISISComputingGroup/EPICS-superlogics/issues/1
1. The db file has a mix of spaces and tabs, which I just find annoying

For https://github.com/ISISComputingGroup/EPICS/issues/88
1. There are merge conflicts again already - probably best to leave until reviewer is merging

For https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/issues/7
1. Both the Dev Sim and Rec Sim tests run as expected, although both gave a missing PV error
1. Do these need adding to the run_all_test.bat?

For https://github.com/ISISComputingGroup/ibex_gui/issues/521
1. The temperature graph is a little 'glitchy', different traces have different setups and it doesn't do what I would expect on most of the channels, which would be an update after any change to the values (based on scan rates etc.) and a point per trigger value, which is not what we get

For https://github.com/ISISComputingGroup/EPICS-ioc/issues/153
1. I had to add SPRLG to the makefile specifically to get build.bat to run, this should probably be in the PR
1. SPRLG_02 isn't able to start, it can't find a file (basically there is an iocBoot missing in the st-common.cmd path)

Otherwise this all looks good to me.

**Comment by samueljackson92** [comment]
@KathrynBaker Thanks for your comments. These should all now be dealt with. Only two things remain:
 - The issue with the IOCTestFramework seems to be that it failed to find the PV it was waiting for during startup, but when I re-ran it several times the issue disappeared. I'm not sure what caused this.
 - Merge conflicts need sorting. I will wait for you to approve the new changes.

**Comment by KathrynBaker** [comment]
One final comment, again for the OPI - could they all have the same buffer length please, otherwise the later traces are truncated a little.

Otherwise, everything is good and ready to merge.

**Comment by samueljackson92** [comment]
@KathrynBaker new PR for /EPICS is: ISISComputingGroup/EPICS/pull/89

**Comment by kjwoodsISIS** [comment]
re-opened in error
