### ISSUE TITLE
Proposal: Limit PVs displayed in get PV

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2451]
As a scientists adding a block I want fewer PVs to select from so it is easier for me to create my configuration.

There are various ways this might be achieved this ticket is to think about them and then let Rob select the one he likes best. Ideas mentioned:

 - Create a white list/black list of PVs for the instrument which the instrument scientist can edit
 - Make the by config selection work better by using the current IOCs in the configuration (and its components).
 - Allow PVs to be selected based on IOC

**Comment by KathrynBaker** [comment]
Options to filter by IOCs in cofig, and those which are active are already in place for selecting PVs. The interest level should also be contributing here, and if not then we are getting the interest levels wrong. This has also not been requested or mentioned since this, and is not likely to be as beneficial as some of the other tickets around. Closing
