### ISSUE TITLE
ENGIN-X: Migrate Scripts

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2462]
Migrate their scripts

**Comment by samueljackson92** [comment]
This is now done and ready for review. There's no pull request because all of the work is on the `NDXENGINX` branch in the `Settings` folder. 

## Preparing to test
Due to the fact lots of work is being done on ENGIN-X at the moment you'll also need to do the following things to prepare for testing:

 - Checkout the branch `Ticket2400_create_third_linmot` in `EPICS/ioc` and build the LINMOT.
 - Build yourself a recent version of Genie python so you get the changes from [this](https://github.com/ISISComputingGroup/IBEX/issues/2488) PR.
 - Add a `__init_ndwXXXX.py` file to your Python directory in the settings folder

You'll also need to make sure the following IOCs are running:
 - Eurotherm_01
 - Galil_01
 - Simple IOC
 - Linmot_03

Additionally download the test files attached to this script and put them in a new folder called `C:\scripts\file_scan`.

### Test files
 - [pos.txt](https://github.com/ISISComputingGroup/IBEX/files/1212296/pos.txt) - Example positioner file
 - [pos_rocking.txt](https://github.com/ISISComputingGroup/IBEX/files/1212292/pos_rocking.txt) - Example positioner file with rocking curves
 - [stress.txt](https://github.com/ISISComputingGroup/IBEX/files/1212294/stress.txt) - Example stressrig file
 - [stress2.txt](https://github.com/ISISComputingGroup/IBEX/files/1212295/stress2.txt) - Example stressrig file
 - [temp.txt](https://github.com/ISISComputingGroup/IBEX/files/1212293/temp.txt) - Example furnace file


Now you should be ready to test the script.

## Testing
The scripts control several pieces of equipment:
 - The furnace (Eurotherm)
 - The stressrig (Currently pointing at Simple IOC)
 - The positioner (Galil)

Each of these components can be controlled by calling a command and passing a file name which must be relative to `C:\scripts\file_scan`. The commands you need to test (probably after code review) are:
 - `inst.positioner_file_scan` - (with and without rocking curves)
 - `inst.furnace_file_scan`
 - `inst.stressrig_scan`

Information about each method and the file formats is in the code comments and printed by passing the `help` flag.

**Comment by Tom-Willemsen** [comment]
Well written, well documented, functionality seems to be there for the most part. A few things need amending before this can be considered complete.

- [ ] Needs the `ARBITRARY:SP` PV to be moved to a constant at the top of the file and be qualified by `INSTRON_01`. 

- [ ] Please investigate the following error log:
```
inst.stressrig_file_scan("stress2.txt", False, False)
Run            Channel        Setpt          Rampt          uamps          
1              stress         5.00           20.00          5.50           
2              setstress      0.0            0.0            0.0            
3              rstress        50.0           20.00          5.50           
4              strain         100.00         20.00          5.50           
5              rstrain        10.0           20.00          5.50           
6              setstrain      0.0            0.0            0.0            
7              rnowstress     3.0            20.00          5.50           
8              rnowstrain     3.0            20.00          5.50           
9              position       10.0           20.00          2.50           
10             setpos         0.0            0.0            0.0            
11             rposition      0.00           20.00          2.50           
12             unload         0.0            0.0            0.0            
13             havertriangle  0.0            0.0            0.0            
14             stresswave     -50.0          1.0            10.0           
15             haversine      0.0            0.0            0.0            
16             strainwave     -50.0          1.0            10.0           
17             triangle       0.0            0.0            0.0            
18             poswave        -50.0          1.0            10.0           
Are you happy with this schedule? (y/n)y
Reading savepos = 0.00mm
Reading savestress = 50.00MPa
Reading savestrain = 1.00%
Controlling channel is: stress
Waiting for 20.0 seconds
** Beginning Run 00000028 at 16:55:59 11/08/17 
*  Proposal Number: 0
*  Experiment Team: 
ERROR: 'float' object has no attribute 'lower'
```
- [ ] I don't think the title should have a newline in it. Please strip newline before setting as title (running furnace using temp.txt file):
![image](https://user-images.githubusercontent.com/24375813/29221670-89826786-7eb7-11e7-8d5c-9a35e7b0af3e.png)

- [ ] If I run `inst.positioner_file_scan(title="THIS IS MY TITLE")` my title is never set to the thing I passed in. I'm not sure that's the right behaviour...?

**Comment by samueljackson92** [comment]
@Tom-Willemsen Ok, all should be fixed now. Please re-check when you can.

**Comment by Tom-Willemsen** [comment]
Getting a stack trace when doing the `inst.position_loop()` method.

Other than that the latest changes seem fine.

```
>>> inst.position_loop()
Enter title root: HERE IS A TITLE
Enter position increment: 1
Enter ramp time: 1
Enter count time: 1
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\ipython-2.2.0-py2.7.egg\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-f7e2c3e68d76>", line 1, in <module>
    inst.position_loop()
  File "C:\Instrument\Settings\config\NDW1799\Python\inst\stress_rig.py", line 97, in position_loop
    delta_pos, ramp_time, title)
TypeError: _print_position_loop_parameters() takes exactly 6 arguments (5 given)
```

**Comment by samueljackson92** [comment]
@Tom-Willemsen One more time?

**Comment by Tom-Willemsen** [comment]
I've tested the functions described above. All seems to work as expected (at least, to me). Appears to do the same things as the current genie scripts. Well written and documented. This can be considered complete now I think.
