### ISSUE TITLE
IOC: Eurotherm change ramp rate to be K/min

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2465]
As a user I expect the ramp rate on the Eurotherm to be in K/min not K/s.

 - [ ] Tell Vicky it is done

**Comment by DominicOram** [comment]
The ramp PVs also do not have any interest level. Set them to medium interest.

**Comment by samueljackson92** [comment]
Main PR is: https://github.com/ISISComputingGroup/EPICS-ioc/pull/175

**Comment by samueljackson92** [comment]
Whoever tests this, could they also try and test it with [this PR](https://github.com/DMSC-Instrument-Data/lewis/pull/262) in lewis. The PR fixes the problem with the eurotherm requiring time out support in Lewis rather than the hacky work around we've done here by adding fake terminators when in dev mode.

**Comment by DominicOram** [comment]
Tested with PR, which works correctly. This code can be cleaned up after https://github.com/ISISComputingGroup/IBEX/issues/2386
