### ISSUE TITLE
Web Dashboard: Modify the ArchiveEngine to serve JSON

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2477]
Following on from #2463 the solution for #2316 etc. has been proposed as:
* Get the most up to date code for the ArchiveEngine, which still uses the same database schema as we do and so is backwards compatible (this could well be the latest v4 version). This code is a headless eclipse app within CSS.
* Modify the code so that, as well as the current webpage, the ArchiveEngine also serves values (that are not truncated) as JSON.

As part of this ticket you should discuss what you are doing with the CS-Studio collab and suggest our additions be merged.

**Comment by DominicOram** [comment]
Sent an email to csstudio asking which version we should fork

**Comment by DominicOram** [comment]
We should wait 2/3 days for a response then re-examine this.

**Comment by DominicOram** [comment]
That was quick: https://sourceforge.net/p/cs-studio/mailman/message/35989134/

**Comment by DominicOram** [comment]
To test this:
* Copy the new version of the archiver from \\isis\inst$\Kits$\CompGroup\ICP\new_archive_engine
* Run an instrument
* Stop your ARINST
* Run ArchiveEngine
* Confirm you can see all the webpages at http://localhost:4812/ as normal
* Confirm that you can get valid json for the following pages:
    - [ ] http://localhost:4812/main?format=json
    - [ ] http://localhost:4812/group?name=INST&format=json
    - [ ] http://localhost:4812/groups?format=json
    - [ ] http://localhost:4812/disconnected?format=json
* Confirm that this json contains non-truncated strings rather than arrays for waveform pvs. e.g. TITLE, SURNAME
* Review the code at https://github.com/ISISComputingGroup/cs-studio/tree/archive_engine_return_json_2265 using the guidelines at https://github.com/ControlSystemStudio/cs-studio/wiki/CodingGuidelines

Note that once this has been reviewed we should:
- [ ] Change the version that we have in C:\Instrument\Apps\EPICS\ICP_Binaries\CSS
- [ ] Put in a PR for the changes to be merged into csstudio

**Comment by John-Holt-Tessella** [comment]
- [ ] I got `"Last Archived Value": "2017-09-19 13:55:24.737000000	Engine start time",` the tab character is not valid json it should be `\t` also did you mean to include "Engine start time". This is also in  `"Current Value":"2017-09-19 14:19:11.664128596	20.123 K	","Last Archived Value":"2017-09-19 14:19:11.664128596	20.123 K	"`
 - [ ] Quotes are not escaped in values try title `(DAE SIMULATION MODE) (DAE SIMULATION MODE) long titlevery long title with quotes in "`
 - [ ] slashes are also not escaped
 - [ ] can you separate out the timestamp, value and alarm? and maybe units

 - [ ] Think about using an existing json library
 - [ ] This might have problems if writing objects containing objects
 - [ ] Some counting on open and close brackets would probably be a good idea, so that it wouldn't be possible to open an object in an object. And all open objects have a close etc.
 - [ ] There is a lot of logic which does not have any tests (everything apart from json writter)

**Comment by DominicOram** [comment]
- All escaped character should now be fixed.
- The values are now separated out as suggested
- I have made some more improvements on opening objects within objects etc. it should be much harder to create malformed JSON
- I couldn't find an easy way to write more tests as it's hard to mock the VType objects, which are cast to lots of different types

**Comment by DominicOram** [comment]
Pull request created at https://github.com/ControlSystemStudio/cs-studio/pull/2306
