### ISSUE TITLE
Deploy: Tidy release files

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2494]
As a system maintainer it would be good if there were fewer files in the system to look after and version. There are many temporary files which are not needed in the final release:

.git*
Makefile

In iocs and support potentially (check) all configure, XXXApp directories

Possibly some documentation sources and any other files we use only for building.

**Comment by FreddieAkeroyd** [comment]
Is this from a deployment performance point of view?

**Comment by AdrianPotter** [comment]
Would potentially benefit the performance. **However**:

- Cannot blanket remove IOC directories. Causes some things, including autosave, to stop working
- Removing the "src" directories would prevent on-instrument debugging because the pdb files would not be pointing at anything valid
- Git files already removed
- PR below for removing makefiles
