### ISSUE TITLE
Graph of PV as a function of time embedded in OPI

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2517]
As a scientist, I want to view plots of PVs as functions of time in device OPIs, so that I can easily understand how device-related PVs vary in time.

#### Acceptance Criteria
1. I can view the PV as a function of time in an OPI.
1. On first use, the origin of the time axis should be the time at which the OPI was opened.
1. I can change the origin of the time axis to any point in the past (up to the earliest value stored in the archiver).
1. My choice of time origin should be persisted (so that I can close the OPI (or re-start IBEX) and re-open it without having to reset the time origin).
1. I can see persisted data when on a remote instrument. I.e. if I switch to Engin-X I can see previous stress rig data.

#### Notes
1. The intention behind this ticket is to create a CSS component (with the behaviour described above) that can be embedded in an OPI.  The PV will be determined when the component is bound to the OPI.
1.  Essentially, this is similar behaviour to that provided by the Data Browser, but embedded in an OPI.

**Comment by John-Holt-Tessella** [comment]
This has been partially achieved by #2439 but not all these points are hit. For this the databrowser widget was made accessible in the OPI. It also does not work from remote only on the local machine because of the archive address which is embedded in the plot. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation#data-browser-graph-creation for instructions on how to embed the widget.

**Comment by KathrynBaker** [comment]
Those OPIs where this is needed has had something implemented, issue should be re-raised if/when a specific requirement is identified.
