### ISSUE TITLE
Eclipse 4: Continuation [TIMEBOX: 8d]

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2547]
Continue the E4 migration, following on from #2491. A more detailed plan will be put in place at the conclusion of that ticket. Likely candidates are:

1. Instrument switching
1. DAE perspective
1. Experiment details perspective
1. Finish perspective switching

**Comment by Tom-Willemsen** [comment]
#2491 should be completed first.

**Comment by kjwoodsISIS** [comment]
No, it is not strictly correct that this ticket is impeded by #2491.
#2491 is a timeboxed ticket - we do as much as we can in the time available and then stop.  If we didn't manage to complete everything we hoped to complete in #2491, then it can be carried over into this ticket.  The only outstanding activity left on #2491 is a review (which should not lead to re-work, because any "re-work" would be done as part of this ticket).

**Comment by AdrianPotter** [comment]
#2491 is nearly done, I don't expect any further functionality to be added. On reflection, I think we should either:

1. Do a stand down day where we partition migrating the remaining perspectives
1. Keep doing this with 1 or 2 people and do some more of the non-perspective functionality

The perspectives are a good way to introduce people to E4 and are relatively straightforward. It's a knowledge sharing opportunity we shouldn't miss.

If we go with the 2nd option then I'd suggest focusing on:

- Instrument switching
- Blocks panel
- Bump strip

**Comment by kjwoodsISIS** [comment]
My preference would be to do 1., because it shares the knowledge to the widest group of people.  However, given the imminence of Cycle 2017/02, we should hold off on doing this until after the cycle starts (in practice, this means waiting until SPRINT_2017_09_21).  Until then, we should carry on as we have been doing up until now.

**Comment by AdrianPotter** [comment]
So it sounds like, assuming there's time, we'll do 2 this sprint and 1 next sprint. #2491 is now done, pending a bit of wiki from John and review so this can start any time.

**Comment by AdrianPotter** [comment]
On completion, make sure to update the description of #2587

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/560

**Comment by AdrianPotter** [comment]
Alarms do not work on switching instruments. That may be entirely my fault owing to work I was doing early on in the prototype process. Would be good to fix now rather than later

**Comment by John-Holt-Tessella** [comment]
- [ ] Scroll bars on all DAE perspectives
- [ ] Check all injects are postconstructs
- [ ] Fix detector diagnostic enable

**Comment by John-Holt-Tessella** [comment]
Branches that should be reviewed:

**Comment by Tom-Willemsen** [comment]
After discussion, I've added scroll bars on DAE perspectives and fix detector diagnostics enable to E4 TODOs wiki page.

**Comment by DominicOram** [comment]
Please may someone review:
* https://github.com/ISISComputingGroup/ibex_gui/pull/576
* https://github.com/ISISComputingGroup/ibex_gui/pull/575
* https://github.com/ISISComputingGroup/ibex_gui/pull/574
* https://github.com/ISISComputingGroup/ibex_gui/pull/573
