### ISSUE TITLE
Improve performance on changing configurations

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2577]
As a user, I would like to be able to change my configuration without having to wait for a long time for my instrument to update so that I can update my current config without excessive interruption to my workflow.

Using the current block server, release 4.0.0, loading a couple of simple configurations took between 40s and 1 minute. The first 20s of the update was spent "Stopping" IOCs, most of which were not running. Potential speed improvements are:

1. Don't stop a stopped IOC
1. Find a way of stopping IOCs asynchronously, or improve the threading so this loop can be completed more quickly.

If we map out exaclty what the blocksever restart is doing, we might find additional opportunities for multi-threading and refactoring.

This change has been requested both by the development team and by users as part of the IBEX introductory training.

## Acceptance criteria

The updates after the following operations are completed in 15s or less. Be sure to try them on non-trivial configurations and ensure the test can be passed repeatedly.
- [ ] Editing the current configuration
- [ ] Loading a new configuration

**Comment by John-Holt-Tessella** [comment]
This should be a meeting before starting work to decide what to do

**Comment by John-Holt-Tessella** [comment]
Could we write a performance test for this.

**Comment by Tom-Willemsen** [comment]
The following charts show the amount of time needed, on my system, to load some configs. I've profiled it into major time sinks.

![image](https://user-images.githubusercontent.com/24375813/31830226-79a6d676-b5b7-11e7-8a5e-749f85a743b2.png)

![image](https://user-images.githubusercontent.com/24375813/31830636-bdaf3498-b5b8-11e7-913f-ad5fb73be2f2.png)

Things that would save significant amounts of time if we fixed:
- Writing to PVs appears to take exactly 100ms from the blockserver. This makes me suspicious that there is an implicit 100ms timeout somewhere. Since the blockserver writes to a lot of PVs this causes us to waste a lot of time.
- There are two major arbitrary waits, one for 1 second (after the archive settings file is uploaded) and one for 6 seconds (after the runcontrol IOC is started).
- There are a couple of places where we're waiting for external processes to be in a certain state (e.g. runcontrol, archive settings uploader). Do we actually need to block the main blockserver thread to wait for them?

I will organise a meeting to discuss the above findings and figure out a plan of action.

**Comment by AdrianPotter** [comment]
[BLOCKSVR-20171023.log](https://github.com/ISISComputingGroup/IBEX/files/1407861/BLOCKSVR-20171023.log)

As per the attached Blockserver logs, I tried switching config with two configs of ~15 IOCs. Change time was in the region of 20-30s. Performance has improved significantly but has not yet met the specified acceptance criteria on a less performant machine

**Comment by AdrianPotter** [comment]
@Tom-Willemsen analysed the logs and the alarm server is giving weird characters. Trying with a fresh build of EPICS to try and eliminate any funky behaviour

**Comment by AdrianPotter** [comment]
Tested on DEMO with a range of configurations and performance is within acceptance

**Comment by kjwoodsISIS** [comment]
@AdrianPotter do you have a note of the performance times achieved?  It would be useful to record them (e.g. against this ticket) for future comparisons.

**Comment by AdrianPotter** [comment]
On demo, switching between configs with ~15 IOCs on NDXDEMO with v4.1 took between 7 and 12 seconds. The attached logs give precise timings:

[BLOCKSVR-20171024.log](https://github.com/ISISComputingGroup/IBEX/files/1410335/BLOCKSVR-20171024.log)
