### ISSUE TITLE
MUONFE overview: LEDs aren't correct

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2592]
On the MuonFE overview OPI some of the LEDs aren't in the correct state. This seems to be because sometimes 0=OFF, 1=ON but other times 0=ON, 1=OFF.

This can probably be fixed by setting a rule on the appropriate LEDs to look for ON/OFF as opposed to 0/1

Let James Lord know when this ticket is complete.

Edit: Some weirdness going on with the Danfysik IOC, dynamically changing On/Off?

```
C:\Instrument\Apps\EPICS>caget IN:MUONFE:DFKPS_04:POWER.ZNAM IN:MUONFE:DFKPS_04:POWER.ONAM IN:MUONFE:DFKPS_09:POWER.ZNAM IN:MUONFE:DFKPS_09:POWER.ONAM
IN:MUONFE:DFKPS_04:POWER.ZNAM  On
IN:MUONFE:DFKPS_04:POWER.ONAM  Off
IN:MUONFE:DFKPS_09:POWER.ZNAM  Off
IN:MUONFE:DFKPS_09:POWER.ONAM  On
```

**Comment by DominicOram** [comment]
After talking with Kathryn the issue is that different models swap the names around as the underlying device comms have swapped around chars for off and on. The above solution will work but we could also do it in the IOC layer, i'm checking if the archive stores the number or the string, if it does we definitely need to swap the IOC.

**Comment by DominicOram** [comment]
Archiver appears to store just the enum val, not string. To make that data more clear I'm going to change the IOC.

**Comment by Tom-Willemsen** [comment]
- Confirmed that this has fixed the issue on MuonFE. 
- Hotfix is appropriately noted at https://github.com/ISISComputingGroup/IBEX/wiki. 
- Dom already sent an email to James to let him know this is fixed.
