### ISSUE TITLE
ZOOM: Oxford 7.5T Cryomagnet into IBEX

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2593]
As a scientist on ZOOM I want to use the [7.5T magnet](https://www.isis.stfc.ac.uk/Pages/75T-Magnet.aspx) during the cycle starting on the 14th of November

**Acceptance Criteria**
1. I am able to create blocks and interact with the 7.5T magnet in IBEX as I can in SECI - setting/reading the same values

**Comment by kjwoodsISIS** [comment]
> From: Alba Venero, Diego (STFC,RAL,ISIS) 
> Sent: 15 September 2017 11:24
> To: Woods, Kevin (Tessella,RAL,ISIS)
> Cc: Baker, Kathryn (STFC,RAL,ISIS)
> Subject: RE: 7.5T magnet on ZOOM in Cylce 2017/03
> 
> Hi Kevin,
> 
> Yes, you are right it is the 7.5T magnet.
> 
> Cheers,
> 
> Diego
> 
>> From: Woods, Kevin (Tessella,RAL,ISIS) 
>> Sent: 15 September 2017 11:05
>> To: Alba Venero, Diego (STFC,RAL,ISIS)
>> Cc: Baker, Kathryn (STFC,RAL,ISIS)
>> Subject: 7.5T magnet on ZOOM in Cylce 2017/03
>> 
>> Hi Diego,
>> 
>> Kathryn tells me you plan to use the “7T magnet” with IBEX in Cycle 2017/03.
>> 
>> On checking the sample environment pages, I see that there is no 7T magnet.  
>> There is a 7.5T magnet - https://www.isis.stfc.ac.uk/Pages/75T-Magnet.aspx.
>> I assume that’s the one you mean.  Is that correct?  (I want to be sure that we provide support 
>> for the right magnet).
>> 
>> Thanks,
>> 
>> Kevin

**Comment by AdrianPotter** [comment]
- [ ] The VI needed for this ticket can be determined by looking at the SANS2D SECI configurations. The magnet will probably be listed as 7T rather than 7.5T
- [ ] Once you've found the VI, talk to @GDH-ISIS about integrating it into IBEX. It'll probably be an LvDCOM. 
- [ ] It would also be advisable to talk to Diego (in email above) about what controls they want in the IOC/OPI. Depending on the complexity of the VI front panel, we may or may not make them all available.
- [ ] I would recommend we move the VI into the IBEX repository rather than calling into LabView Modules to prevent further coupling.
- [ ] Once you've got the necessary requirements. Write the IOC as normal. A sensible approach would be to write the emulator to talk to the VI front panel, then and the IOC and OPI on top. This will provide some useful verification.

**Comment by Tom-Willemsen** [comment]
Impeded awaiting confirmation from Diego about exactly what he needs from this ticket. Kathryn is meeting with him tomorrow to discuss this.

**Comment by KathrynBaker** [comment]
I have checked with Deigo, and it is unlikely to be needed for next cycle now (this is in light of commissioning this cycle), and if it is available then it can be run without scripting options.

I will move this back into the backlog for the time being. If the work to integrate this is significant I will let someone who has a better idea of how significant decide if it needs to be re-proposed for the next sprint, otherwise I will re-propose it for the Christmas sprint if it will be needed in the February cycle.

**Comment by Tom-Willemsen** [comment]
Quick overview of what was discussed for this ticket (so that we don't have to rediscuss all of this next time):

The 7.5T magnet is made up of 3 devices in a rack:
- IPS (Intelligent power supply)
- ILM (Intelligent level meter)
- ITC (Intelligent temperature controller)

There is also some ancillary equipment in the same rack, e.g. a Neocera, that we don't need to worry about as part of this ticket. 

The three units in the rack are daisy chained together and fed into an ISIS "box" which presents a single serial interface to all three units (the units are then addressed).

The scientists sometimes want a very basic level of control (i.e. Input field strength, let the driver figure out all the other parameters), and sometimes they want very fine control (e.g. setting the PID parameters of the temperature controller.

From a discussion between @GDH-ISIS @FreddieAkeroyd @John-Holt-Tessella and myself we think the EPICS solution is:
- Three IOCs, one for each of the devices mentioned above
- An overarching IOC / set of DB records that can monitor and set values on all three of the devices mentioned.

The LvDCOM solution would involve LvDCOMing the following VIs:
- `C:\LabVIEW Modules\Oxford Software\SOLOITCFRONTPANEL\SoloITC503 - 1.vi`
- `C:\LabVIEW Modules\Oxford Software\ilmapps.llb\ILMFrontPanel2.vi` (*)
- `C:\LabVIEW Modules\Oxford Software\Teslatron\Teslatron System Manager2.vi` (*)
- `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetField2.vi`
- `C:\LabVIEW Modules\Oxford Software\Teslatron\TeslSetTemp2.vi`

If we only wanted the "basic" level of control we might be able to get away with only LvDCOMing the VIs marked with (*). However there are some issues to consider with LvDCOM as this might tightly couple the LvDCOM to the configuration of one particular beamline.

The final issue to consider is that this equipment is being phased out over the timescale of ~1 year, so if we do put the effort in to write a full EPICS solution, it may not necessarily see much use before the equipment is retired.

---

(Note: If anything in this comment is wrong/missing, please do edit it and/or make corrections below.)

**Comment by ChrisM-S** [comment]
I cannot believe that all those individual pieces of Oxford Kit are being replaced everywhere within one year? But even so I expect we will find some of these components on other IBEX conversions (or arriving on some current ones).  If I'm way out of date and we will never see and ITC or ILM in use after Sept 29 2018 I'm happy to be corrected not sure whether to :joy: or :cry: !

**Comment by kjwoodsISIS** [comment]
> From: Howells, Gareth (STFC,RAL,ISIS) 
> Sent: 27 September 2017 14:24
> To: Akeroyd, Freddie (STFC,RAL,ISIS); Willemsen, Thomas (Tessella,RAL,ISIS); Holt, John (Tessella,RAL,ISIS); Woods, Kevin (Tessella,RAL,ISIS)
> Subject: FW: 7T magnet on Zoom
> 
> Dear All,
> 
> After talking with Diego, the 7T cryomagnet for Zoom will not be installed this cycle. When I 
> pushed further, he did not sound convinced it would be next cycle either – they have other 
> problems.  I mentioned to him that if he decides to put the 7T magnet on to contact ASAP so 
> that we are aware.  Please see Diego’s email below.
> 
> Regards,
> 
> Gareth
> 
>> From: Alba Venero, Diego (STFC,RAL,ISIS) 
>> Sent: 27 September 2017 14:15
>> To: Woods, Kevin (Tessella,RAL,ISIS)
>> Cc: Howells, Gareth (STFC,RAL,ISIS)
>> Subject: 7T magnet on Zoom
>> 
>> Hi Kevin,
>> 
>> We are not going to install the 7T cryomagnet in Zoom during this cycle. I scheduled it but after 
>> some discussion with Richard Down and Kathryn Baker we decide to postpone it. I then removed 
>> it from the scheduler, but it seems that the second part didn’t arrive to you. 
>>
>> Apologies and thank you very much,
>>
>>Diego

**Comment by KathrynBaker** [comment]
Not certain this should be awaiting, we haven't done anything with it yet so am going to move this back to the backlog for suggesting when the time is right.

**Comment by KathrynBaker** [comment]
Re-proposing in March 2018, Asked for the April cycle, but accepting that it may not be available in IBEX (and therefore scriptable) until the 5th of June cycle.

**Comment by FreddieAkeroyd** [comment]
Emulator #3075

**Comment by Tom-Willemsen** [comment]
I haven't tested against the hardware but I think the review can be started against the following (some changes may be required when I get access to the hardware).

- https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OxfordInstrumentsIPS
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/277
- https://github.com/ISISComputingGroup/EPICS-IPS/pull/2
- https://github.com/ISISComputingGroup/ibex_gui/pull/692

emulator and tests in #3075 should probably be reviewed at the same time

**Comment by GDH-ISIS** [comment]
Hardware has now been arranged so that the ioc can be tested. Located on top of LET. Tom informed. LET MOXA has had the accessible IP addresses disabled so that TOM can gain access to the hardware. I will re-instate the accessibility settings for LET again when it is closer to cycle.
