### ISSUE TITLE
Eurotherm OPI: Tab ordering 

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2646]
Ron Smith on Polaris just reported an issue where, after setting a set point on the eurotherm OPI, focus was given to the ramping on/off button which he accidentally pressed, causing some confusion. Ensure that focus instead goes somewhere where pressing enter again will not cause issue.

**Comment by DominicOram** [comment]
+1 from Ron again

**Comment by John-Holt-Tessella** [comment]
Can we do tab ordering in an OPI?

**Comment by DominicOram** [comment]
Sort of, after some experimentation it seems that after you press enter on any text box focus goes to the button that is specified first in the xml. This means we could fix this by changing the order in the xml to put a more benign button first or add a dummy button that goes in first. (This may be fixed /something we can fix in CSS4)

**Comment by ChrisM-S** [comment]
Does the default tab ordering follow the same pattern as the order of XML too?

**Comment by DominicOram** [comment]
As far as I can tell there is no tab ordering in OPIs

**Comment by AdrianPotter** [comment]
In our meeting with the Polaris instrument scientists, this was again raised as an issue. I don't think it should be technically challenging to put in at least a partial fix. The consequence of the issue is potentially lost beam time if a user accidentally triggers a ramp so I think we should treat this sooner rather than later. If nothing else, it is very important to the Polaris scientists.

**Comment by AdrianPotter** [comment]
I just had a quick play and it's not obvious how CSS does things. 

By reordering the XML widgets, I got the OPI to switch to the auto tune toggle rather than the ramp on toggle, but that's only a minor improvement.

I tried using the same trick to get it to switch to a hidden toggle button instead, but that didn't work. I didn't explore it fully though.

**Comment by John-Holt-Tessella** [comment]
Add hidden in run but shown in design label saying remember tab order.
