### ISSUE TITLE
ZOOM PLC db oddities

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#2666]
As a developer, I want to get to the bottom of what is actually going on with the records on the ZOOM PLC

**Acceptance Criteria**
1. The effect of asyn on record init functions has been investigated
1. The effect of the fins driver on record init functions has been investigated
1. The behaviour of VAL fields set in db files, but without PINIs has been investigated
1. There is an addition to the IOC pages giving guidance on the setting of VAL fields without PINIs, and on how to initialise a record with a value

**Comment by KathrynBaker** [comment]
Do not forget to review the records and rename as appropriate from #2665

**Comment by KathrynBaker** [comment]
It was found that the original setup for the ZOOM vacuum PLC was not actually writing to the items that needed writing to.

Originally there was a soft bo (e.g. MONITOR:2:INSERT) with a FLNK to an asyn longout (e.g. MONITOR:2:INSERT:RAW:SP), the longout had a VAL of 1 in the db, which it never seemed to actually use, the VAL in the IOC was always 0.

According to the manual setting a DOL to a constant value then the init functions should write that value to VAL, and remove the UDF flag. This didn't happen.

A semi-hacky fix was applied in #2665, which put an interim soft record between the bo and the longout, which writes a 1 to the longout via a PP in the OUT field.

**Comment by FreddieAkeroyd** [comment]
OK, the root of the problem is that asyn will try to initialise a record to be the readback from the device. The FINS driver has separate asyn parameters for read and write, the write ones thus don't really have a value. It doesn't re-assign if there is an error reading the parameter, but we are not getting such an error. So we have a combination of  asyn behaviour and FINS oddities. If FINS marked it parameters as uninitialized it might help. 

P.S. in process of following this up I modified the FINS ioc to have a crude device simulation mode

**Comment by KathrynBaker** [comment]
Thank you Freddie,

We’ll have to think about what the resolution should be.

Simulation modes are usually helpful ☺

**Comment by kjwoodsISIS** [comment]
Now resolved.

**Comment by KathrynBaker** [comment]
As this has been resolved I'm closing the issue
