### ISSUE TITLE
RB number service: centralise and simplify

### ISSUE THREAD

**Issue by mattclarke** [ISISComputingGroup/IBEX#2669]
Currently, there is a C# Windows service on each instrument that fetches the RB number info.

As a developer, I would like to simplify this and move it to a technology we support.

* Make it a central service that supplies the data to all the instruments.
* Rewrite it in Python or Java
* Check with BusApps to see if there is an easier way to interface with their system. There may be a REST interface.

**Comment by mattclarke** [comment]
There is currently not a REST interface that is suitable for us to use

**Comment by mattclarke** [comment]
For a code chat I put together a proof of concept implementation of the connecting to the BusApps webservices using python:

**Comment by mattclarke** [comment]
```python
from suds.client import Client
import ssl

# This is a workaround because the web service does not have a valid certificate
if hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context

# Get a session id
auth_client = Client('https://fitbaweb1.isis.cclrc.ac.uk:8443/UserOfficeWebService/UserOfficeWebService?wsdl')
session_id = auth_client.service.login("SEE SHAREPOINT FOR USER AND PASSWORD", "PASSWORD")

# Connect to the scheduler
scheduler_client = Client('https://fitbaweb1.isis.cclrc.ac.uk:8443/ScheduleSessionBeanService/ScheduleSessionBean?wsdl')

# Create a dateRange object suitable for SOAP
date_range = scheduler_client.factory.create('dateRange')
date_range.startDate = "2017-09-05T15:31:34.1022366Z"
date_range.endDate = "2018-03-24T15:31:34.1022366Z"

teams = scheduler_client.service.getExperimentTeamsForInstrument(session_id, "POLARIS", date_range)
dates = scheduler_client.service.getExperimentDatesForInstrument(session_id, "POLARIS", date_range)
contact = scheduler_client.service.getExperimentLocalContactsForInstrument(session_id, "POLARIS", date_range)

for t, d, c in zip(teams, dates, contact):
    print("----------------------")
    print(t.rbNumber)
    print(d.scheduledDate)
    print("Contact: {}".format(c.name))
    for experimenter in t.experimenters:
        print(experimenter.name, experimenter.organisation, experimenter.role)
```

**Comment by mattclarke** [comment]
The login details for the webservice are in SharePoint

**Comment by ThomasLohnert** [comment]
Moving to impeded until we have had a discussion with BusApps about webservices access security

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert : when is the meeting with Business Apps scheduled?

**Comment by ThomasLohnert** [comment]
The meeting is scheduled for tomorrow afternoon

**Comment by ThomasLohnert** [comment]
The meeting with BusApps has generated some ideas on how to solve the authentication bit:
- Centralise the service as per the original ticket, so that the credentials are not stored on the instrument machines. This will require a user with external write access to be created on all instruments so the data can be pushed into their databases.
- Store the credentials in the windows credentials manager and access those in python (e.g. using [Keyring](https://pypi.org/project/keyring/))
- Pull out the authentication bit into a compiled piece of code e.g. in C
- BusApps said there is an option to implement authentication via domain credentials using [NTLM](https://docs.microsoft.com/en-us/windows/desktop/secauthn/microsoft-ntlm), however this is a lot of work for them and we should not expect it anytime soon.

We should have a discussion what the best way forward is. I will move this back to the backlog for now.

**Comment by DominicOram** [comment]
Main work at https://github.com/ISISComputingGroup/ExperimentDatabasePopulator. DB users added in https://github.com/ISISComputingGroup/EPICS/pull/140 and https://github.com/ISISComputingGroup/EPICS-upgrade/pull/18

To test:
* Add an exp_data_writer@localhost account to your db (see one of the two PRs above on how to do this)
* With a new Python 3 virtual environment pip install the requirements.txt file
* Confirm all unit tests run
* Confirm that tests are running in Jenkins
* Modify main.py to DEBUG=True
* Run main and confirm that your exp_data db is replaced with data for LARMOR

Optionally:
* Run the system test, this will go through every instrument and dump a csv file of what it would have written to the db and what is currently written
* Confirm that this test is able to access all the data
* Confirm the comparison is correct for most instruments, there will probably be some exceptions as discussed in the comments for the system test

**Comment by DominicOram** [comment]
Once this is reviewed discuss with @FreddieAkeroyd how to deploy

**Comment by ChrisM-S** [comment]
A couple of things that would be useful to consider at this point, I suspect mainly related to when the service runs and the cursor (if there is one) on the database query.  Both are useful to know in case the instrument (for whatever reason) is left without access to anything more than the local network during a cycle.

1) How often will the data be updated (i.e. how long before a change - say to an RB number or addition to the to users in the Business apps front end would be replicated in the local database).
2) Will all the future experiment./scheduling data available for the instrument picked up by the query or just a window/cursor (like experiments this cycle, in the next 7 days etc.?).

**Comment by DominicOram** [comment]
1. The current default is updating every hour
2. The data picked up is a window of 200 days centred on today. I.e. from 100 days ago to 100 days in the future

These were both defaults left in from previously but are easily changed. If the update fails for whatever reason it will just try again in the next hour. It's also possible to manually force a new update.

**Comment by ChrisM-S** [comment]
Thanks @DominicOram, they look like pretty good defaults to me, hopefully there is no conceivable way we would be out of network contact for 100 days ☺

**Comment by Tom-Willemsen** [comment]
Since there is no PR for the main code I will leave review comments here:

Code:
- There is a `start_expdata.sh` script that doesn't do the equivalent of it's `.bat` counterpart. Remove or update it.
- [`main.py:8`] I'm not sure the `IGNORE_LIST` is very extensible. In fact it is already out of date as NDXIRISTEST has been added. I think instead we should add a field to the instrument list (or some other central service) to denote whether it is a scheduled instrument.
- [`main.py:44`] Prefer to use `threading.RLock` objects over `threading.Lock` objects wherever possible (Lock objects are easy to get into deadlocks with as they are not reentrant).
- [`main.py:67`] This might not be a problem but it will be faster if the code does the stop and then the join in two separate for loops.
- [`main.py:87`] I think we should also log the root exception - especially as this is a top-level handler.
- [`main.py:102`] Nit: Usually in python use `item instanceof str` as opposed to `type(item) == str` 
- [`main.py:105`] I think this functionality has been forgotten. Either remove it or implement it.
- [`exp_db_populator/webservices_reader.py:66`] Usually it is better to use the [traceback](https://docs.python.org/2/library/traceback.html) module to print errors as it gives more context than just the error text. Also, it's better to just use the bare `raise` keyword rather than `raise e` if you're in a catch block as this preserves the original exception stack trace. Comment repeats for other similar blocks.
- [`exp_db_populator/webservices_reader.py:115`] Nit: use `{}` as opposed to `dict()`
- [`tests/system_test.py:115`] Can you remove the commented out code in this file?

Functional:
- Pressing "M" in the menu does nothing.
- Pressing "U" in the menu while in "debug" mode crashes the script with 
```
Enter: M to display menu, U to force update from instrument list or Q to Quit
 u
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    main.inst_list_changes(main.prev_inst_list)
  File "main.py", line 79, in inst_list_changes
    for inst in inst_list:
TypeError: 'NoneType' object is not iterable
```
- Running the system test crashes with
```
C:\Instrument\Dev\ExperimentDatabasePopulator\tests>C:\Instrument\Apps\Python3\python.exe system_test.py
Traceback (most recent call last):
  File "system_test.py", line 3, in <module>
    from main import convert_inst_list, INST_LIST_PV, correct_name, IGNORE_LIST
ModuleNotFoundError: No module named 'main'
```
- In non-debug mode, typing `U` at the prompt causes a crash:
```
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    main.inst_list_changes(main.prev_inst_list)
  File "main.py", line 80, in inst_list_changes
    name, host = correct_name(inst["name"]), inst["hostName"]
TypeError: string indices must be integers
```
- It occasionally prints out things like `<suds.sax.document.Document object at 0x0B3E0DB0>`. This isn't really helpful to an end-user and should be removed (I'm not sure where it is printing from)

Documentation:
- I found some [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Experimental-Database) but this will be out of date once this is merged and I couldn't find anything else. Have I missed it?

**Comment by DominicOram** [comment]
I've added it to the instlist at https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/172

I could only reproduce the `<suds.sax.document.Document object at 0x0B3E0DB0>` error when it couldn't connect to the instrument, with IRIS_TEST removed I haven't seen this issue.

Documentation has been updated at the provided link.

Once this is merged we should:
* Update the inst list
* Remove the old way of populating the table

**Comment by Tom-Willemsen** [comment]
Code looks better now, thanks for making the changes. However the system test still doesn't run correctly for me. I get:

```
Traceback (most recent call last):
  File "tests\system_test.py", line 90, in <module>
    populator.get_from_web_and_populate()
  File "tests\..\exp_db_populator\populator.py", line 85, in get_from_web_and_populate
    with self.db_lock:
AttributeError: __enter__
```

After I fix the above error, I get:

```
Traceback (most recent call last):
  File "tests\system_test.py", line 93, in <module>
    web_data = get_data()
  File "tests\system_test.py", line 18, in get_data
    exps = model.Experiment.select().order_by(model.Experiment.experimentid, model.Experiment.startdate).dicts().execute()
  File "C:\Instrument\Apps\Python3\lib\site-packages\peewee.py", line 1604, in inner
    return method(self, database, *args, **kwargs)
  File "C:\Instrument\Apps\Python3\lib\site-packages\peewee.py", line 1675, in execute
    return self._execute(database)
  File "C:\Instrument\Apps\Python3\lib\site-packages\peewee.py", line 1826, in _execute
    cursor = database.execute(self)
  File "C:\Instrument\Apps\Python3\lib\site-packages\peewee.py", line 418, in __getattr__
    raise AttributeError('Cannot use uninitialized Proxy.')
AttributeError: Cannot use uninitialized Proxy.
```

After fixing a few more errors, I get the following (Not just on HRPD, this is an example):

```
Getting web data for HRPD
2018-10-23 13:59:21,489 [INFO] Creating connection to :memory:
Getting real data for HRPD
ERROR: Comparison failed for EXPERIMENT on HRPD. Error was: list index out of range
ERROR: Comparison failed for USERS on HRPD. Error was: list index out of range
ERROR: Comparison failed for EXP_TEAMS on HRPD. Error was: list index out of range
```

---

I'm also slightly confused about exactly which SQL accounts are writing to the instruments as the code looks to be using a different account than the one added in the PRs - perhaps it is best if we talk about this in person?

**Comment by Tom-Willemsen** [comment]
I've merged the PRs which needed to be in the release. The actual ExpDbPopulator code still needs some rework, but since it runs centrally it's not required for the release.

**Comment by DominicOram** [comment]
I've removed the system test as it wasn't a stable test and I trust we're getting the correct data. I've also added an upgrade step to remove the old populator.

**Comment by Rory-Potter-Tessella** [comment]
All looks good. 

Flash review of PEP8 changes and fixing an incorrect merge conflict resolution by @Tom-Willemsen.
