### ISSUE TITLE
Vnc: Unable to type brackets

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2737]
Reported by Helen Walker and Adroja Devashibhai (Merlin)

If I VNC in the following pattern I am unable to type brackets.
Office machine (Windows) -> Cabin machine (Linux) -> NDX machine (Windows)

The link between office machine and cabin machine is VNC, the link between cabin and NDX is made over remote desktop.

If I VNC from
Office machine (Windows) -> Cabin machine (Linux) 
I can type brackets successfully.

If I remote desktop from 
Cabin machine (Linux) -> NDX machine (Windows)
I can type brackets successfully.

There might be some interaction between the VNC and remote desktop sessions that is causing this issue.

**Comment by kjwoodsISIS** [comment]
This does not sound like an IBEX issue to me.  As @Tom-Willemsen says, it sounds more like a VNC/Remote Desktop problem.  It would probably be more appropriate to report this via FIT.

**Comment by ChrisM-S** [comment]
I have had a chat about this and the scientists will discuss between themselves what they would like to do.  The most likely resolution will be to move screens/machines around in the cabin so that an ordinary windows viewing machine can be used (there are potentially two machines available already).  The Linux machine or it's successor can still be remote accessed from VNC to see analysis screen and NDX screen but will get its NDX display from VNC->NDX (directly which is a supported setup).

**Comment by kjwoodsISIS** [comment]
Well, this still doesn't sound like an IBEX issue, so I am closing it.  If it needs to be followed up, it can be done in a more appropriate forum.
