### ISSUE TITLE
Mclennan: Allow remote reset of controller

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#2760]
The IOC does not provide the ability to reset the controller remotely should an error occur (e.g. tracking abort, timeout during move, etc.).  The only method of doing this currently is to power-cycle the controller, which is obviously inconvenient for the users.

A method to allow the "RS" command to be sent should be added.

**Comment by AdrianPotter** [comment]
Frequently needed owing to hardware issues (e.g. misalignment, dirt)

**Comment by kjwoodsISIS** [comment]
@davidkeymer to check if there is a simple way to do this.

**Comment by AdrianPotter** [comment]
At the backlog prep meeting we discussed sending a reset command with each move request. I think that should be quite easy in the current setup. I'll take a quick look at the driver and propose a solution if it's quick. We can discuss and test it when David gets back after Christmas

**Comment by AdrianPotter** [comment]
Ignore the last 2 links there. Invalid cross-reference

**Comment by Tom-Willemsen** [comment]
Tested using office mclennan. I added release notes for you.

**Comment by GDH-ISIS** [comment]
Please ensure the error is recorded in the IOC log file. Also the error should be reported in the alarm gui and logs otherwise the axis will be deemed operational when in fact it is not and there is a hardware fault. The reset will potentially hide an axis issue - users will simply try again and because the axis may get there a second time, will assume it is operational.

**Comment by AdrianPotter** [comment]
I think this is done, but the office McLennan broke. I'm setting to impeded until it returns and I can verify.

**Comment by John-Holt-Tessella** [comment]
- [ ] Call reset on stop so that the axis can be halted
