### ISSUE TITLE
IOC creation script

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2764]
As a developer, I would like to be able to create the common parts of an IOC quickly using a script, so that I can immediately start working on the IOC-specific functionality rather than boilerplate code.

This script could create:
- IOC ([see wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-an-ISIS-StreamDevice-IOC)) with simulate/disable records
- Support module
- Appropriate macros in top level EPICS
- Appropriate additions to makefiles in the support directory
- Boilerplate for the lewis emulator
- Boilerplate for the IOC test framework

Even if some of these steps were left as manual steps (e.g. if they are difficult to script), it would significantly speed up the IOC creation process. At the moment it can easily take a few hours to get to the stage where you have an IOC, protocol file, emulator and tests all talking to each other, before even adding any functionality.

**Comment by davidkeymer** [comment]
Having just gone through the current process, I noticed that a default `st-common.cmd` file isn't created, whereas an 'st.cmd' file is.  However, this could be because I only generated one IOC and therefore didn't strictly need one.
This is something to at least look at during the work for this ticket.

**Comment by AdrianPotter** [comment]
https://github.com/ISISComputingGroup/IBEX_device_generator/pull/1
