### ISSUE TITLE
MERLIN: JAWs sometimes overshoot

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2786]
Investigate Merlin Jaws overshoot. Merlin scientist set the vgap and it went to a larger VGap.

**Comment by John-Holt-Tessella** [comment]
Requested gap: 45.0
Actual Gap: 47.617

The retry count is set to 10  (IN:MERLIN:MOT:MTR0101.RTRY)
I have exported the gap value and it looks like:
![gap.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5714ad1111fbb71300db4967/125516c66e82c728ace21e0d46ef958a61cec1b99de6b546a749b2ce6b1371702f56a62822d6b27aec1029505c5f4eab455d0946aaeb9539e4e76224d50152a7842f4d7ed43c19a6b9871ebf06bf27884681b0ba8c5e8d.png)

**Comment by John-Holt-Tessella** [comment]
F: Setpoint appears to follow value:
![setpoint.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5714ad1111fbb71300db4967/125516c66e82c728ace21e0d46fb918e338d8aa79babf301b44fff9e2c4533317346f67d7383b12dbc1028505d5c4cae405b5f44fbfd8c7da4e02e6c981e5ab38532022d8c6853beb2901eb80bbb258a4f82b3bb8e4fc7e93424f5c6.png)

**Comment by John-Holt-Tessella** [comment]
Asked H:

1.	Do you script this and if so is it hampering your experiment?
2.	How often do you set it?
3.	How often does it fail?
4.	Does it only fail when going to extreme positions or opening or closing?
5.	Is it always vertical gap or does the horizontal gap fail too?
6.	Could we use your jaws next shutdown to do some testing?

**Comment by GDH-ISIS** [comment]
Looking at the 4 jaws, it looks to as though one of the jaws is a bit behind (lazy). The time stamp in the caput log (on the archive) has a slightly different time to what appears in the graphs (~5 sec difference). Although this is interesting, I do not think it solves the problem. MTR0101.DMOV shows that a move is being retried in a manner that does not look normal.

![merlin jaw](https://user-images.githubusercontent.com/13995522/32899519-1e10c358-cae3-11e7-9df1-d3cacbc46768.jpg)

**Comment by John-Holt-Tessella** [comment]
Impeded until Helen returns.

**Comment by GDH-ISIS** [comment]
Hi Gareth,

We have occasionally had problems with our jaw set where they’ve announced that we can’t close them down as far as we want to go, or alternatively that we cannot open them as far as we want. The range of sizes we use is 5x8 (VxH) to 48x48 mm. The source of the trouble has, as far as I remember, been traced back to a spurious offset appearing on the individual blades, which has been linked to power offs. I cannot see where this offset would be entered in IBEX, but I believe it was accessed via the galil individual motor screens in SECI. The problem was that we weren’t sure what the offset should be, and we don’t have an encoder on the jaws. The other problem we’ve seen is that on occasion we haven’t been entirely convinced that the jaws were moving as they should be. This is a rather tricky thing to investigate. In the past it has involved us turning off the tank vacuum and removing the sample environment, so that Jon Bones can be dangled upside down inside the sample space to actually watch the jaws while we send movement commands. Alternatively when we haven’t had a spare 8 hours to mess around with the tank, we’ve tried slowly closing down the jaws to try and identify when they are actually closed, but this is a rather nerve wracking experience since people don’t seem to know whether the blades overlap or close to touch each other, and I don’t want to drive the blades into each other damaging them.

Please let me know if that was all too garbled and requires clarification, but hopefully that covers all our jaw niggles.

Thanks
Helen

**Comment by AdrianPotter** [comment]
@John-Holt-Tessella. Helen is presumably back by now?

**Comment by kjwoodsISIS** [comment]
Flag this to the Motion Control team.

**Comment by John-Holt-Tessella** [comment]
Done as part of #4953 I believe these now work. Wait for scientists to notify us if not.
