### ISSUE TITLE
POLARIS: support for Keithley 2420 (specifically for thermoelectric cell)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#2801]
As a visiting scientist, I would like to use a Keithley 2182 voltmeter to make measurements on POLARIS.

#### Acceptance Criteria
1. I can control a Keithley 2182 voltmeter from IBEX
1. I can log data collected by the Keithley 2182 voltmeter.

#### Notes:
1. [Keithley 2182A](https://www.tek.com/keithley-low-level-sensitive-and-specialty-instruments/keithley-nanovoltmeter-model-2182a)
1. We may have existing LabVIEW VIs for the Keithley 2182A.  We could wrap these up in lvDCOM.
1. Jamie Nutter (Electronics) may have an alternative device (for which we do have drivers) and we could use that instead.
1. Scientists would like to test this on Wednesday/Thursday (6th/7th December 2017), if possible.

**Comment by Tom-Willemsen** [comment]
How many distinct things do they need to measure? If it's just a few, maybe it would be sufficient to set up the [SDTest](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SDTest) ioc?

**Comment by kjwoodsISIS** [comment]
> From: Seb Long (external)
> Sent: 29 November 2017 12:41
> To: Woods, Kevin (Tessella,RAL,ISIS); Smith, Ron (STFC,RAL,ISIS); Howells, Gareth (STFC,RAL,ISIS)
> Cc: Nutter, Jamie (STFC,RAL,ISIS); Hull, Stephen (STFC,RAL,ISIS)
> Subject: Re: Polaris - Ibex - Keithley interface
> 
> Hi Gareth,
> 
> Ive just had a look at the source meter and it looks like it is possible to invert the current between constant current voltage measurements.
> 
> And just to confirm, the 3 measurements from the source meter would be:
> 1) voltage 
> 2) resistance with a constant current of say 30 mA
> 3) resistance with a constant current of -30mA
> 
> Seb 
>

**Comment by GDH-ISIS** [comment]
Currently, I believe the measurement is going to be done with a Keithley 2420. Electronics has given me  a unit that is now in our office (in the corner where the devices are kept).

**Comment by John-Holt-Tessella** [comment]
I suggest then that we test the device using the following.

1. Add the Keithly 2400 to a config
1. Add some user blocks for the three items needing measurement
1. Write a python script function which:
    1. Sets the IOC to use passive measurements
    1. Loops around:
        1. Set into voltage mode
        1. Measure the voltage (process the record) puts it in the user pv
        1. Goes into current mode
        1. Sets current to 30 mA and measures the resistance puts it in the user pv
        1. Set the current to -30mA and measures the resistance puts it in the user pv
1. Wrap the function in a thread which can be started/stopped so other python scripts can be run alongside

Measurements need to go into a user block because the different values are taken for different reasons.

**Comment by GDH-ISIS** [comment]
Path to existing LabVIEW vi is :
C:\LabVIEW Modules\Drivers\Keithley 2410\Keithley 2410 - Thermoelectric Cell.llb\Keithley 2410 - Thermoelectric Cell - Front Panel.vi
Note : This vi does not cover the complete procedure Seb now requires.

**Comment by GDH-ISIS** [comment]
I have asked for a test resistor and cabling from electronics.

**Comment by GDH-ISIS** [comment]
Test resistor and cabling not connected to Keithley 2420 in R3 office. Device is set to 9600 baud rate.
It is necessary to put device into auto ohms source manual mode. This is done by :
1. Press the CONFIG key.
2. Press the MEAS Ω key.
3. Select the SOURCE menu item.
4. Select the MANUAL ohms source mode.
The resistance measurement can then be made with a user defined current - for this ticket 0, +30mA and -30mA

**Comment by GDH-ISIS** [comment]
User is currently not here at RAL. Maybe consider contacting him via email when this has been implemented.

**Comment by Tom-Willemsen** [comment]
I believe the following script has the right behaviour (tested on Keithley 2420 in the office).

[khly2420.zip](https://github.com/ISISComputingGroup/IBEX/files/1518371/khly2420.zip)

Setup:

Keithley 2400 IOC settings:
Baud = 9600
Bits = 8
Port = COM13 (COM 9 in office moxa)
Stop = 1
Everything else default.

To set up blocks:
`keithley2420_resistance_2` -> `TE:NDW1799:PARS:USER:R2`
`keithley2420_resistance_1` -> `TE:NDW1799:PARS:USER:R1`
`keithley2420_voltage` -> `TE:NDW1799:PARS:USER:R0`

Set up precisions and units:
```
caput TE:NDW1799:PARS:USER:R2.PREC 5
caput TE:NDW1799:PARS:USER:R1.PREC 5
caput TE:NDW1799:PARS:USER:R0.PREC 5

caput TE:NDW1799:PARS:USER:R2.EGU ohm
caput TE:NDW1799:PARS:USER:R1.EGU ohm
caput TE:NDW1799:PARS:USER:R0.EGU volt
```

Script is intended to be used as a context manager so that they can easily wrap their existing scripts

i.e.

```
with ThermoElectricCell(current1=0.01, current2=-0.01):
    do_existing_script
```

If they want to run it standalone, just give it an infinite function in the body of the `with` statement, e.g.

```
with ThermoElectricCell(current1=0.01, current2=-0.01):
    raw_input("Press return to stop thermo electric cell")
```

It does all it's commands in a different thread so should not interfere with any existing scripts they have.

Check behaviour against LabVIEW driver in `C:\LabVIEW Modules\Drivers\Keithley 2410\Keithley 2410 - Thermoelectric Cell.llb` - should be the same.

Note: In the office the keithley is set up with a resistor, it's best to use a smaller current (say, +10mA and -10mA) currents.

If the keithley box complains "can't set source in auto resistance mode" then follow the process that Gareth detailed two comments above to put it into manual mode

I also found and fixed a (tiny) bug in the keithley driver as part of this ticket, so when reviewing please check you have the change introduced in https://github.com/ISISComputingGroup/EPICS-ioc/commit/536e0b9e9eb2b96ae9f99ec404a55acc13f0bf28

**Comment by Tom-Willemsen** [comment]
Version that fixes the resistance mode setting:
[khly2420.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584824c871a2f60e0061286a/125516c66e82c728ace21e0d46e39c963ad0d7fbdfabf301b44fff9e2c4533317346f67d7383b12dbc1028505d5c4cae405b5f44fbfd8c7da4e02e6c981e5ab38532022d8c6853beb2901eb60bbb258a4d81bfb98e49c0ed3820f5c6.zip)

**Comment by Tom-Willemsen** [comment]
Also turned off all scans/PINIs for Polaris' Keithley 2400 IOC. That will also need undoing when the experiment is over.

**Comment by GDH-ISIS** [comment]
Current source range needs to be set on the device before hand.

**Comment by Tom-Willemsen** [comment]
Now documented on wiki at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2420-(POLARIS-Thermoelectric-cell)
