### ISSUE TITLE
GEM - Oxford ILM

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2893]
GEM has blocks pointing at a VI in `c:\labview modules\oxford software\ilmapps.llb\ilmfrontpanel2.vi`. This was missed during the first pass of the migration but needs to be done to convert GEM.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen  - I believe the ILM is one of the old Cryogenic devices, being replaced by Tritons.  Please double check with Gareth.

**Comment by Tom-Willemsen** [comment]
I think this is related to their Mercury cryostat, I will follow up on whether this is still going to be in use.

**Comment by GDH-ISIS** [comment]
ILM devices from Oxford Instruments are legacy devices. Having asked Cryogenics, their removal from circulation at ISIS is likely to take a reasonable length of time - 1 to 2 years, maybe longer. As a result, the ability to monitor would be beneficial.

**Comment by AdrianPotter** [comment]
- What model ILM is it specifically? There is an EPICS driver available for the 201: https://www.imca.aps.anl.gov/~jlmuir/sw/oxford-ilm201.html. The EPICS page links to a 201S as well but it is broken
- What is the communication method to the ILM? The VI appears to support RS232, ISOBUS and GPIB

The device itself looks quite simple. We could do this very simply as an LVDcom, point at the blocks and done. For GEM it doesn't strictly even need an OPI since they only need blocks. Or we could do a full IBEX conversion and speak to it directly with EPICS with an OPI and emulator. How many of these are there around? Who else uses them apart from GEM?

**Comment by AdrianPotter** [comment]
Discussed with @John-Holt-Tessella and @Tom-Willemsen. Decided this should be done as an LvDCOM for the impending release. It should be done as a proper EPICS driver though because it's so simple. I will create a new ticket for that.

**Comment by AdrianPotter** [comment]
Given GEM is no longer running this cycle, perhaps this should be done as an EPICS driver first time around now.

**Comment by AdrianPotter** [comment]
Putting as priority for review since GEM needs it soon.

**Comment by ChrisM-S** [comment]
Just a note on this [](https://github.com/ISISComputingGroup/EPICS-ILM200/commit/e2ed9be) I can't see the context from this change, but is this carried out on every attempt to write/query a value to the ILM (on an a retry after a write failure) and is it _persistent in trying_?  It's not uncommon for the older Oxford kit to be taken out of remote mode during a cycle by someone using the front panel.  The normal behaviour would be to ensure that it is put back into remote mode by the OI comms in the VI on the next poll to ensure that control of the box doesn't then cease for the rest of the evening.  This is also true of ITC and probably others.  @GDH-ISIS will have most details.
