### ISSUE TITLE
SANDALS: Scripts not working correctly

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#2945]
The sandals scripts are not working correctly.

1. Create a test instrument
1. Debug the scripts.
1. Let them know

I intended to take lots of quick scans (20 uamps for empty cans and VNb, 10 uamps for empty instrument).
The first sample is processed fine, but the next one goes back to the default 250 uamps.
On the first test run, it did not even move on to the next sample, but repeated the VNb instead.
I’ve then changed the order of samples in the script, reloaded and restarted. Now it went on to the next sample, but still went back to the default uamps.

**Comment by John-Holt-Tessella** [comment]
reviewed by @Adrian and will be reviewed by instrument scientists

**Comment by AdrianPotter** [comment]
Reviving ticket as a result of meeting on 19th February. A couple of fixes and refactors have been requested by the scientists

**Comment by AdrianPotter** [comment]
Updated scripts tested and pushed to NDXSANDALS branch. Awaiting review and confirmation from instrument scientists before pulling onto instrument.

**Comment by AdrianPotter** [comment]
Meeting request sent. Decision on topic pending

**Comment by AdrianPotter** [comment]
Instrument scientists haven't been able to check the code yet and can't give a date when they will. I suggest checking the code looks sensible and opening a fresh ticket rather than bouncing this one along indefinitely. As part of the latest stage I:

- Appended the position and temperature automatically to titles rather than using embedded format statements
- Added run control to temperature runs
- Changed the interface to do a single temperature to give clarity to the run order.

The changes are on the NDXSANDALS settings branch but have not been pulled to the instrument yet because they haven't been approved by the scientists. The latest version of the user scripts are in C:\scripts on NDXDEMO. If the scientists want to test the scripts on DEMO, you can use settings branch NDXSANDALSTEST which is currently up to date with SANDALS but notably has its Python init file set for DEMO.
