### ISSUE TITLE
Eurotherm: max retries alarm

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3019]
MERLIN reported that the `RETRYCNT` PV on their Eurotherm frequently gets into a minor alarm state. They have not noticed this causing any actual issues, but it has caused concern and confusion for their users (they usually tell them to just ignore it). 

As a MERLIN scientist, I would like the Eurotherm to only set alarms for real issues so users can trust them. Investigate if this alarm is being set for a good reason, or prevent it from happening otherwise.

**Comment by KathrynBaker** [comment]
Similar issue seen on SANDALS

**Comment by FreddieAkeroyd** [comment]
Do other instruments see this, or is the eurotherm on merlin having to retry more than others?

**Comment by Tom-Willemsen** [comment]
Just having a quick scan through, the retry count alarm is also seen on IRIS currently

**Comment by KathrynBaker** [comment]
So that is three instruments, MERLIN (original ticket), SANDALS (my re-request) and IRIS (Tom looking specifically).

The fact that IRIS hasn’t been on touch to my knowledge to ask about this alarm means we should either stop bothering to report alarms, or make sure that they are all correct and that we know what to do about them. If this is something that doesn’t matter, we need to suppress the alarm on the retries.

**Comment by Tom-Willemsen** [comment]
+1 EMU who reported that this alarm is present "1/3 of the time" despite not causing any real problems.

**Comment by ConorMFinn** [comment]
For Review:
- [ ] https://github.com/ISISComputingGroup/EPICS-ioc/pull/703
