### ISSUE TITLE
GUI/BLOCKSERVER: Deleting an in use synoptic

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3211]
If a synoptic which is used by a configuration is deleted there is no warning and that configuration then default to the 1st synoptic on the list. It should be set to None.

Acceptance criteria

- On edit or load of configuration whose synoptic does not exist the NONE is selected
- On deletion of a synoptic used in a configuration the user should be warned.

**Comment by RichardTysonIsis** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/715

**Comment by jeremyspencer39171** [comment]
The user should be warned if they are deleting a synoptic which is in use by any configuration, not just the current one.

For example:
At the moment, if a user deletes a synoptic which is used by an inactive configuration then that configuration will pick a random synoptic to use.

When a synoptic is deleted, we need to look through all the configurations to see if any use that synoptic, if so, show a warning.
Then if it is deleted, either immediately set the synoptic in that configuration to "-- NONE --", and/or add a check when a configuration is edited or loaded to make sure the synoptic exists, otherwise set to "-- NONE --".

Let me know if that doesn't make sense.

**Comment by RichardTysonIsis** [comment]
After chatting with Dom about this, it was decided that this ticket will not change the synoptic of configurations using the synoptic to be deleted to "-- NONE --". This is because Dom thinks it makes more sense to do it on the blockserver, but it's fairly complicated to do as the part of the blockserver that deals with the configurations knows little about the synoptics and vice versa. A solution implementing the desired change in the GUI wouldn't be great.

I'm creating a ticket to solve this issue but for further reference, here a set of observed behaviours relating to the issue:
-If the current configuration's synoptic is deleted then it will display "-- NONE --" as it's new default synoptic. However, if an EPICS command is used to ask what synoptic is being used in the configuration, it will return the synoptic that has just been deleted, and the configuration.xml file will display the same information.
-If a non-current configuration's synoptic is deleted then it will display the current configuration's synoptic as its new default synoptic, although, once again, the changes are just on the gui and neither displayed by the EPICS command window or the xml file.
