### ISSUE TITLE
Documentation: Online genie_python course documentation fails to render

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3216]
There are a number of pages on the user wiki for the `genie_python` course that fails to render:

- http://shadow.nd.rl.ac.uk/ibex_user_manual/genie_python-and-IBEX-%28Exercise-solutions%29
- http://shadow.nd.rl.ac.uk/ibex_user_manual/genie_python-and-IBEX-%28Common-commands%29
- http://shadow.nd.rl.ac.uk/ibex_user_manual/genie_python-and-IBEX-%28Getting-started%29

The possible solutions are:

1. Fix the rendering (and then put a nagios job to check for rendering errors)
2. Don't replicate to shadow and use Github directly.
3. As 2. but also create off-line documentation which is part of the GUI.

Historically, the availability of Shadow is significantly below Github and we expend significant effort maintaining it. The latter is made difficult because only Freddie has access to the machine containing the wiki.

**Comment by FreddieAkeroyd** [comment]
The  Gollum wiki is written in Ruby, but is calling rest2html (which is python) to render the pages and this is crashing. It doesn't like the page content.   

I pasted the page into an RST checker and it objected to the use of :: at the end of some lines

System Message: WARNING/2 (<string>, line 69)
Literal block expected; none found.

Having fixed the incorrect lines in the wiki, it is still not rendering OK; however if I open up the page in the editor and say it is "markdown" rather than "restructured text" then it renders OK in the preview.

**Comment by John-Holt-Tessella** [comment]
All pages appear to have images on them. I cannot preview a file with

```
.. image:: genie_python_and_ibex/StandardStartupOutputOnDemo.png`
```

**Comment by Tom-Willemsen** [comment]
The gollum wiki works ok on a server other than shadow. I have put one up temporarily at http://ndxdemo:4567/IBEX-GUI-Features as a demo and the instructions to set it up are at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Gollum-wikis

I think as part of this ticket we should:
- Agree on a new server to run the wiki from (or we could run it entirely locally on each instrument)
- Move the script which updates the wiki from shadow to the new server
- Set up redirection from shadow to the new server so that old links that we can't update (e.g. people's bookmarks) keep working
- Update links in GUI to point at the new server

Impeded until we can agree where to run this.

**Comment by FreddieAkeroyd** [comment]
There were some package conflicts in shadow between local and global gems, think it is working now
