### ISSUE TITLE
genie_python: Unable to import one inst function from another

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#3217]
In `C:\Instrument\Settings\config\[name]\Python\inst` do the following:

- Create `a.py`
- Create `b.py`
- Create a function `a` in `a.py`
- Create a function `b` in `b.py`
- Use function `b` in function `a` (i.e. `from b import b`...)

Then do the following

- Start IBEX
- Open a scripting terminal
- I get the following error:

```
There was a problem with loading init_ndw1836 so will use default.
Error was No module named b
```

This is contrary to the `genie_python` documentation and training material.

Notably the same thing isn't true if you import `a` into `b`. If the imports are in alphabetical order then there is no error, and possibly why we haven't seen it on instruments.

Scripts will still work if you use `inst.b()` instead of importing the function explicitly.

## Acceptance criteria

- The workflow described in the documentation is correct (i.e. fix the current workflow or update the docs)
- The workflow used on instruments is consistent with the workflow described in the documentation
    - This is so that if scientists copy the pattern used in their existing scripts, they don't hit a confusing behaviour where one import works but another doesn't

**Comment by jeremyspencer39171** [comment]
The repository for the configurations and scripting directory isn't on GitHub, so this will have to be a manual pull request and merge into master.

### Work
The work here fixes the bug where files cannot import each other out of alphabetical order, gives warnings when importing multiple different functions/variables/classes/modules of the same name, and tells the user if there is an error when importing a file.

### Repository
The instructions for cloning the repository are here:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/First-time-installing-and-building-(Windows)#setting-up-the-configurations--scripting-directory

The branch is called "Ticket3217_importing_between_inst_modules"

### Testing
The you should be able to test it by running python in the command line from "C:\Instrument\Settings\config\MACHINENAME\Python", putting some python files in the inst directory here and doing "import inst".

### Acceptance
Make sure you can import files which import other files in the inst directory both before and after itself in the alphabet.
Check that warnings appear when you import something with the same name as you have previously, for example, two functions called print_a() from different files.
Check that there is an error message when a file cannot be imported (for example due to invalid syntax), but that the script continues importing the rest of the scripts anyway.

**Comment by Alistair-McGann-Tessella** [comment]
The new inst script checks for already loaded variables and issues a warning if there is already an object of the same name loaded.

```==========================================================================
WARNING:
{} has already been imported into inst.
That will be overwritten and any calls to 
inst.{} will refer to the one from {} instead.
You can still call things explicitly with inst.filename.thing.
==========================================================================
```
This warning seems to be issued when a module and a function share the same name, such as in the example quoted above when `a.a` and `b.b` are the example functions, which could cause confusion. Could a check be performed so that modules and functions can share a name?

Could this warning be made more clear to aid script debugging by replacing `filename.thing` with the previously loaded module and object names?

**Comment by Rory-Potter-Tessella** [comment]
There is an error message given when you try to overwrite a module, nothing is imported and the warning makes sense. 

However, when I try to call `inst.b.b` I get an attribute error because inst.b refers to the function `b` in `a`, which is not what the current error states. The error message should state that inst.b.b cannot be called.
Also, the warning message could be clearer.

E.g.
```
WARNING importing function: b
Something else called "b" has already been imported into inst.

The previous instance of "b" will be overwritten and any calls to inst.b 
will refer to the function b in a instead. Because of this, you cannot access inst.b.b.
```

**Comment by Rory-Potter-Tessella** [comment]
Updated error messages to make them clearer. Flash review by Tom Willemsen.

**Comment by John-Holt-Tessella** [comment]
This needed to be reverted see #3496
