### ISSUE TITLE
Muon Front End: The OPI for the overview uses the wrong motor for the momentum slits

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#3236]
The OPI currently points to the underlying motor, not the MSLITS motor, which means the values are half of those of the block, and only half the gap - this needs updating to be the correct value

**Comment by kjwoodsISIS** [comment]
To me, this sounds like an avoidable error.  Why didn't we point the OPI at the right motor?

**Comment by KathrynBaker** [comment]
It is pointing to the correct motor, there is a soft motor on top of it, that if you weren’t aware of it you would go with the one in the motor table, rather than the calculated one. This is going to be those who know were aware of it, so if it was programmed and reviewed by someone unaware of the situation it can be missed.

The only way to limit this kind of error is to ensure that those “in the know” do some analysis up front or undertake the review. It might also mean we should be putting more technical detail in the tickets, which are meant to be user stories.

**Comment by kjwoodsISIS** [comment]
The user story is the bit at the top of the ticket that starts "As a <X> ...".  It describes the desired functionality & acceptance criteria from <X>'s point-of-view.  There is absolutely nothing to stop anyone adding extra information in the form of notes and comments to help developers & reviewers.  Indeed, that is precisely what we should be doing -  it is all about sharing information.  After reading the ticket, everyone should be "in the know".

**Comment by Tom-Willemsen** [comment]
This is already configurable in the muon overview OPI (as a macro, `MM_MOMENTUM`). I don't think any changes to the OPI are required - just a configuration change.

**Comment by RichardTysonIsis** [comment]
As pointed out by Tom, the PVs for the slits in both the Slits (single motor) OPI and in the Muon overview OPI are made from macros ($(P)$(MOT) and $(P)$(MM_MOMENTUM) respectively). If the value in the block is different from the value in the synoptic it's probably due to the fact that the macros haven't been given the correct PV name; the PV in the block is IN:MUONFE:MOT:MSLITS.RBV whilst the one in the synoptic is IN:MUONFE:MOT:MTR0104.RBV (for the gap on the momentum slits). My guess is that changing the PV in the synoptic to IN:MUONFE:MOT:MSLITS.RBV would solve the issue.
Kathryn said she would get in contact with the instrument scientist to see if we can get onto the system and make the necessary changes.

**Comment by RichardTysonIsis** [comment]
After getting the instrument scientists' approval, Kathryn and I changed the Macros to point to the right PVs in the synoptic display; on the GUI the correct values are displayed.
