### ISSUE TITLE
GUI: Keyboard Shortcut to stop execution of a Script

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3241]
As a scientist, I want to use a keyboard shortcut to stop execution of a script, so that I can quickly and easily stop a script that contains an error or has been started in error.

#### Acceptance Criteria
1. If a script is executing in the Script Console, on pressing a defined key (or key combination), IBEX immediately stops the execution of the script.
1. If a script is not executing in the Script Console, on pressing a defined key (or key combination), IBEX does nothing.

#### Notes
1. In many scripting environments "Ctrl+C" is used to halt a script.  However, "Ctrl+C" is used by Windows GUIs to mean "copy" and will be intercepted by the GUI framework (preventing the signal from getting to the scripting console).  So, we need to choose an alternative keyboard shortcut.
   1. We have explained to the scientists that "Ctrl+C" gets intercepted, so we can't use that to halt a script.  They are fine with that.  Any other suitable combination will do.
1. Some Ctrl+key combinations may not be ideal. For example, if the user is in a text window, Ctrl+H or Ctrl+D might delete a character; Ctrl+C, Ctrl+X, Ctrl+V, Ctrl+N, Ctrl+O, Ctrl+S all have conventional interpretations and are all used frequently in other applications.
1. Some suggested keyboard shortcuts:
   1. Ctrl+I  (I for interrupt)
   1. Ctrl+K  (K for kill)
   1. an F-key?  (althought these may be less obvious).

**Comment by ChrisM-S** [comment]
**"As a scientist, Ctrl-C is what I use on Windows and Linux consoles and probably always will do - and _speed_ and _instinct_ is often important to stop the wrong control getting set if my script goes wrong, and Ctrl-C is what I already use in Open GENIE - please don't invent a solution I don't want, this is my requirement"**

We spent a while trying to convince people that Ctrl-C was not exactly what they wanted in Open GENIE because it was hard to implement - and then had to implement it anyway. So a bit of a counter example to this mornings one, but the requirement here and ticket should really be _"GUI: Ctrl-C to stop execution of a script"_, the implementation is unimportant :smile: 

Ctrl-C/Ctrl-V does not to my knowledge work on normal consoles;  in editors and IDEs however it's great (after all who want's Ctrl-C in an editor - sorry Emacs fans if it's in there?)

**Comment by kjwoodsISIS** [comment]
To be clear: We have been down this road before.  We **CANNOT** use "Ctrl+C" in IBEX because this particular keystroke is intercepted by the underlying framework (either CS-Studio or Eclipse).  The "Ctrl+C" keystroke never reaches IBEX, therefore, we cannot take action if anyone presses it.

**Comment by ChrisM-S** [comment]
I would agree that it might be harder if Ctrl-C was not passed to the PyDev console, but given that the CopyAction clearly is executed as a result of this, why would it not be possible to override the "CopyAction" handler instead (i.e. to push the yellow button!)?  In fact, given that the Ctrl-C was pressed while the prompt is inactive, the "Copy" could still be done, so this functionality could be retained with no great loss while building a command line.  If there was no prompt, there is clearly a command running which should then be interrupted... 

There is an example piece of code at:
[https://www.javatips.net/api/Pydev-master/plugins/org.python.pydev.debug/src_console/org/python/pydev/debug/newconsole/HandleBackspaceAction.java]()

this appears to show overriding of the BackspaceAction handler whilst on the command line.  I think this could potentially be quite simple to do in a similar way.

**Comment by DominicOram** [comment]
Since we last looked at this we've learnt a lot more about keybindings in Eclipse. I have managed to implement it as Ctrl+C. However, the key binding mechanism is different in E4 so I have created #3286.
