### ISSUE TITLE
IOC: Beckhoff Z axis doesn't finish move

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3247]
The Z axis does not finish its move correctly.
This appears to be caused gravity sitting on the Beckhoff this means that it does not really stop moving because it is correcting for gravity. The Beckhoff controller does have a "doing move" flag that I saw within the controller. We should talk to Steve Cox and then use this as our done move.

**Comment by John-Holt-Tessella** [comment]
Discovered during #3245

**Comment by John-Holt-Tessella** [comment]
Another thing to try might be setting RDBD which might tell it the movement has finished when it is within this limit.

**Comment by FreddieAkeroyd** [comment]
Back in March the Z axis used to move like this

[2018-03-19 22:40:10] 2018/03/19 22:40:10.923 [MC_CPU1,-1,0] [../EssMCAGmotorAxis.cpp:615] [motorPoller,00000000026E1FA0,10] poll(2) nowMoving=1 bBusy=1 bExecute=1 fActPosition=7.999835

[2018-03-19 22:40:12] 2018/03/19 22:40:12.261 [MC_CPU1,-1,0] [../EssMCAGmotorAxis.cpp:615] [motorPoller,00000000026E1FA0,10] poll(2) nowMoving=0 bBusy=0 bExecute=1 fActPosition=5.995288

[2018-03-19 22:42:09] 2018/03/19 22:42:09.950 [MC_CPU1,-1,0] [../EssMCAGmotorAxis.cpp:159] [MCU1,0000000001FBFE40,50] out=Main.M2.bExecute=0 in=OK status=asynSuccess (0) oldPosition=5.999942

The rotation still moves in this way, but now for Z the bBusy indicator is not going to 0 any more. 

nowMoving=0 bBusy=1 bExecute=0 

Is the gravity correction new? It seems the beckhoff is behaving differently in Z. The nowMoving indicator is a derived quantity and still going to 0. We changed to the axis record, but the underlying Beckhoff control was unchanged. If the readback is nowlvarying due to more accuracy, it may be the motor record defines "end of move" as "readback stable" as well as controller finished, it might be RDBD helps here or something else is needed.

**Comment by FreddieAkeroyd** [comment]
It looks to have been working like this on 7th May too

**Comment by FreddieAkeroyd** [comment]
Plan to test week of 23rd July before SPS is locked off for other work

**Comment by FreddieAkeroyd** [comment]
Went down to IMAT this morning with @Rory-Potter-Tessella to meet with Steve Cox, it looks like the Beckhoff PLC program thought a "home" had been requested and was still in progress which was why the moves of Z never finished. Steve cleared the home variable and all now works as before. It looks like the "home" button on the motor screen was pressed accidentally at some point, we checked this reproduced the previous behaviour. I'll create a ticket to make sure pressing "stop" clears the home variable in the PLC.

**Comment by kjwoodsISIS** [comment]
Review:
   - [x] Problem diagnosed.
   - [x] Solution devised & implemented
   - [x] Solution checked
   - [x] New ticket created to implement a solution to minimise risk of future reoccurrence.

Review complete.
