### ISSUE TITLE
Muon Separator: Display Status of Separator PSU

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3408]
As a muon scientist, I need to see the current status of the Separator PSU, so that I can monitor its behaviour.

#### Acceptance Criteria
1. I can view whether the Separator PSU is currently switched ON or OFF
1. I can view the voltage readback of the Separator PSU (measured in kV)
1. I can view the voltage setpoint readback of the Separator PSU (measured in kV)
1. I can set the voltage setpoint of the Separator PSU (measured in kV)
1. I can view the current readback of the Separator PSU (measured in mA)

#### Notes
1. required by #3072
1. The Separator PSU is controlled by a National Instruments DAQ device (DAQ-Mx).
   1. See [Kicker_Separator_Schematics](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Muon%20FE/MuonFE_Kicker_Separator%20v4.pptx).
1. The ON/OFF status of the Separator PSU cannot currently be read from the Muon FE PLC.
   1. The ON/OFF status of the Separator PSU has to be inferred from the analog signal (see below).
1. The Separator PSU voltage can be both read and set (via the DAQ-Mx).
1. The Separator PSU current can also be both read and set (via the DAQ-Mx).
1. **Note:**  IBEX does not communicate directly with the Separator PSU.  It communicates with the NI DAQ-Mx.  In order to read or set the voltage and/or current on the PSU, there needs to be some sort of calibration or lookup between the NI DAQ-Mx and the PSU.
   * The calibration (scaling) relationship is: 
      * Separator Voltage: 0-10V (DAQ) = 0-200kV (PSU) 
      * Separator Current: 0-10V (DAQ) = 0-2.5mA (PSU)
   * The threshhold voltage for determining whether the Separator PSU is ON/OFF is 0.1V (i.e. if the DAQ voltage (corresponding to the Separator Voltage) is less than 0.1V, the Separator PSU is deemed to be switched OFF).  The threshhold voltage should be configurable at run-time.

**Comment by LiamPanchaud** [comment]
Branches: 

https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket3408_separator_psu_status

**Comment by Rory-Potter-Tessella** [comment]
After testing down on MuonFE, we got the following error:

```
2018/09/04 12:07:24.576 TE:NDW1973:SEPRTR_01:DAQ:CURR:ACQUIRE devAsynUInt32Digital process error
2018/09/04 12:07:29.074 dmbWrite: failed to send message 2
```

To fix this, I think we need to slow down the scan speed of `ACQUIRE` record.

**Comment by LiamPanchaud** [comment]
I've added averaging to the db files so that the reported value in the OPI is more representative of how the SPU is performing, rather than just using a single value from the dumped array of data. 

The scientists have added a filter to try to clean up the mains noise present in the signal, and want the averaging removed. However, I don't think this is a good idea. I think it's important the the RBV is representative of the whole frame. 

For the stability and spark count, the averaging will not be used since this would lose too much data about the stability (this is what Alistair is working on). 

If anyone is interested in this I can explain it better in person, feel free to stop by and discuss.

**Comment by LiamPanchaud** [comment]
I've removed the averaging and added macros for frequency and number of elements sampled before the DAQ returns the data to the IOC. It defaults to 100 samples @ 1kHz, so will update every 0.1 seconds. This should be "live" enough for the users, but they can change it if they need to
