### ISSUE TITLE
Deployment: Create Release

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3413]
As a developer I want an IBEX release so I can install it on the instrument machines for the start of machine physics on 27th August.

Acceptance Criteria:

- [x] [Pre Testing Steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#pre-testing)
- [x] [Testing steps](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#testing)
- [x] [Post Testing](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Creating-a-release#post-testing)
- [x] [Create a ticket to update dependencies to latest versions and test](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Dependency-updates)

**Comment by Rory-Potter-Tessella** [comment]
All looks good:

- System tests were performed by Liam, Rory and Patrik.
 - One bug was found during system testing and was fixed by [#3488](https://github.com/ISISComputingGroup/IBEX/issues/3488).
- Ticket to update dependencies is [#3506](https://github.com/ISISComputingGroup/IBEX/issues/3506).

Work to do:

- Needs the system test spreadsheet to be updated.
- Results of the system test to be placed on [System Test Results page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests-Results).

**Comment by LiamPanchaud** [comment]
I've uoloaded the latest test results to the wiki and updated the manual testing template. 

I also created 2 tickets for the bugs we found.

**Comment by Rory-Potter-Tessella** [comment]
Tickets created are:
- [#3548](https://github.com/ISISComputingGroup/IBEX/issues/3548)
- [#3549](https://github.com/ISISComputingGroup/IBEX/issues/3549)
