### ISSUE TITLE
OSIRIS: Prepare to Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3446]
As a developer, I want to complete the preparatory steps prior to migrating OSIRIS to use the IBEX instrument control system.

#### Acceptance Criteria
1.  [x] Facilities IT have confirmed they will create a private network on OSIRIS 
1.  [x] NDXOSIRIS has sufficient free disk space to install IBEX 
1.  [x] IBEX has support for the devices used on OSIRIS 
      - requires #3460 
      - requires #3463 
      - requires #3629
1.  [x] The version of the ICP program on OSIRIS has been checked 
1.  [x] Configuration files matching the current SECI config files used on OSIRIS are created 
1.  [x] OSIRIS scripts are converted to genie_python
1.  [x] OSIRIS configuration files and genie_python scripts are tested on a test instance of IBEX

#### Notes
1. The devices on OSIRIS are listed on the [OSIRIS Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/OSIRIS-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for OSIRIS.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   -  [OSIRIS VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/OSIRIS/OSIRIS_VLAN_Settings.txt)
- [x] Check that NDXOSIRIS has sufficient disk space to install IBEX
  * OSIRIS has NN-Gb of free space.
- [x] Check whether OSIRIS uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, plan to upgrade the ICP program (to permit 8-digit run-numbers)
- [x] Create a virtual instrument for testing purposes
   - [x] Set up a test system, NDXOSIRISTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
      * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [x] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on OSIRIS) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
   * Done!  Training arranged for 1st November 2018.

**Comment by John-Holt-Tessella** [comment]
Blocks used in Mantid:

>For TOSCA and OSIRIS there are a few names that are currently used but the scripts have also been recently updated so that the user can provide these names on the GUI if they need to so it won't be a drastic problem if they did change. The ones they currently use in scripts but I don't think are in every run are:
>
> - Sample
> - Position
> - Temperature
> - Bottom_can,
> - Middle_can
> - Top_can

**Comment by kjwoodsISIS** [comment]
The SECI configs to be migrated should be determined as follows:
   1. check the SECI logs to see which configs & sub-configs have been used over the last 4 cycles
   1. migrate these configs & sub-configs to IBEX

**Comment by kjwoodsISIS** [comment]
On OSIRIS, OpenGenie scripts are created by taking an old script and modifying it to suit the current experiment.  There is no library of scripts, other than the collection of old scripts.  In other words, old scripts are used as templates to create new scripts.  The OpenGenie scripts to be migrated should be determined as follows:
   1. check to see which scripts have been used recently (e.g. in last 12 months)
   1. it may be that the most recently used scripts are all very similar.  If possible, try to select  up to 4 recently used OpenGENIE scripts that illustrate a variety of uses; otherwise, just select the 4 most recent scripts.  Create genie_python equivalents of these scripts - please include clear comments to explain how each script works - they will become templates for future genie_python scripts.

**Comment by davidkeymer** [comment]
Recently used SECI configurations (in approximately inverse chronological order i.e. most recent first):
TLCCR_New_Standard
Triton+Magnet+Rotation
Ox50+Rot
Triton+Rotation
magnet+rot

**Comment by davidkeymer** [comment]
Renamed Blocks In Triton Component as blocks must start with a letter:

- `4K_HX_Temp` -> `Temp_4K_HX`
- `JT_HX_Temp` -> `Temp_JT_HX`

Also renamed `JT_HX_Temp` to be consistent.

**Comment by davidkeymer** [comment]
Further updates to Beryllium Filter OPI and third Lakeshore 218 IOC as detailed in the following ticket:
- requires #3629

**Comment by Rory-Potter-Tessella** [comment]
Just a few things that need to be fixed/are being fixed:
- [x] I found the multiple Mk3 choppers OPI used confusing as it shows disconnected choppers and the name of the chopper is not on the tab. A ticket to fix this has been created #3728. David has reverted to using two single chopper OPIs for OSIRIS's two choppers.
- [ ] The journal parser wasn't working as expected. This is because the install script was not run as part of upgrading the ISISICP as David didn't find the wiki page. I've now linked the "Upgrade ISISICP" wiki page to the install section of the deployment page, and the journal parser install script has been run.

A few comments on the scripts:
#### Instrument scripts
- There is only one file of instrument script. Could this file be the `inst.py` file? The file is quite long though so it may be better to split the file up into separate files in inst folder:
    - Basic Routines (basic_routines.py) (should include OpenGENIE aliases)
    - Instrument settings -- inelastic (inst_inelastic_settings.py)
    - Quiet count settings (quiet_counts_settings.py)
    - Spectroscopy settings (spectroscopy_settings.py)
    - Diffraction settings (diffraction_settings.py)
- The inst `__init__.py` needs updating to the latest version if the inst folder is to be kept.
- You could refactor the `_collect` function which collects data to be an `inst` function? This could potentially be a genie function as it is used a lot. See ticket #3729.

#### User scripts
- More consistency regarding documentation. Include parameter types.
- Check that only relevant modules are imported (e.g. no need to import inst in `muamps.py`)
- Use snake case (underscores between words) to improve readability of variables - see scan function parameters in `YPPbase0p6TendAnd0p4T.py`.

**Comment by davidkeymer** [comment]
Suggestions from review implemented.
