### ISSUE TITLE
INES: Keithley 2410 Source Meter

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3452]
As a scientist, I want IBEX to support the Keithley 2410 Source Meter, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. I can control a Keithley 2410 Source Meter via the IBEX GUI
1. I can control a Keithley 2410 Source Meter via genie_python

#### Notes
1. We already have support for Keithley 2400 and 2420 models (see #1826 and #2801).  Check if 2410 can be supported by existing IOC, or if existing IOC can be extended to support 2410.
1. Check existing VI to ensure functionality available in SECI is implemented in IBEX

**Comment by LiamPanchaud** [comment]
The only difference between a 2400 and a 2410 is in the voltage range they can measure. The 2410 is a high voltage SMU and can measure up to (±)1100V at (±)20mA. 
The documentation indicates that the 2400 series SMUs all use the same command set, so the same db and proto files can be used. 
There are VIs for 2400 and 2410 models, which I will compare once LabVIEW has finished installing.

**Comment by kjwoodsISIS** [comment]
I presume this means we can support both devices by way of configuration.

**Comment by LiamPanchaud** [comment]
It looks likely. The VIs have some slightly different modules/files but I suspect this is because the users wanted slightly different things. They seem to share the same way of communication/follow the same instruction set.
In fact, the common VI files shared between the 2400 and 2410 are identical (even down to the titles of the intruments in the user interface. They are all labelled as Keithley 2400)
