### ISSUE TITLE
IMAT: Galil axes not working

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3458]
Was reported to Motion control, but we should check all OK from our end

IMAT SPS Galil axes don't work following the PAT testing of last week.

AT first only the X-axis caused problems, but now that the other axes (y,rot, 
arc-low-arc high) moved once, none of them moves.

Reported by: Winfried Kockelmann (mailto:winfried.kockelmann@stfc.ac.uk)
ISIS Instrument: IMAT
Name of computer problem was submitted from: ndximat.isis.cclrc.ac.uk
Current ISIS Cycle: 18/1
Product: Instrument Problem/Bug Report
Category: Electronics: Motion Control Operation/Mechanical/Electrical
Severity: major
Priority: P1
Scientist Contact Information: http://www.isis.stfc.ac.uk/people/instrument-scientists-4398.html
Instrument Contact List (i.e. who gets these sorts of emails): http://sparrowhawk.nd.rl.ac.uk/footprints/contacts.html
Email sent by:ISISinstrument@sparrowhawk.nd.rl.ac.uk

**Comment by John-Holt-Tessella** [comment]
Email sent to lots of people finding out the status and whether we need to get involved.

**Comment by John-Holt-Tessella** [comment]
Feedback is that this is an IBEX issue; someone will go down today.

**Comment by John-Holt-Tessella** [comment]
I went down the y axis moves. The x axis moves but does not appear to be within its physical limits. I didnt move anything else, the IMAT instrument scientist reports:

> I couldn’t move the jaws yesterday afternoon, and I couldn’t move the GALIL SPS axes. I did not check the Messina camera axes and I did not check the sample slits.
> X and y axes have absolute encoders. I thought that the x-axis came back with a nonsensical position after a restart of the IOC, outside the physical limits of the axis (I think it was ~555 mm).

We should check the jaws tomorrow.

**Comment by FreddieAkeroyd** [comment]
Axes now seem to be working, the X axis was outside soft limits as per motor record but is now back to normal. I have put in an new ethernet cable around the outside of the crate as the connector is broken on the existing one to GALIL05 and this caused communication errors if it got knocked. There were some error lights on galil crates 1 and 2, these went after a power cycle and the jaws could then be homed

**Comment by kjwoodsISIS** [comment]
It might be useful to create a simple troubleshooting guide for the IMAT scientists, to help them diagnose _some_ of these problems.  If they could diagnose the problems themselves, the problem could be resolved much faster (i.e. they wouldn't have to wait for someone from Computing Controls to come down and fix it).
Naturally, no-one should expect the scientists to resolve all problems (e.g. they should not have to fix a faulty ethernet cable).  On the other hand, if, for example,they need to power cycle a Galil and then discover they can't re-home the motor (because it is outside soft limits), some simple instructions could save a lot of time.

**Comment by John-Holt-Tessella** [comment]
Works now see https://github.com/ISISComputingGroup/ibex_user_manual/wiki/IMAT-motors for what we did.
