### ISSUE TITLE
LOQ: Add live view for LOQ detectors

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3479]
As a LOQ scientist I need to be able to view the main (ORDELA 2661N) detector live while the instrument is running.

It should also be investigated if the secondary 'high-angle' detector can be viewed live in a similar way.

More information: https://github.com/ISISComputingGroup/IBEX/wiki/LOQ-Instrument-Details#noteLiveView

**Comment by FreddieAkeroyd** [comment]
LOQ uses separate "count integrating" hardware rather than running in event mode, the existing liveview framework will be usable but needs a modification to read the data from a different source. Currently you give it a range of spectra and it reads a special "event mode integrated list", for LOQ you would give it a range of spectra served by the separate DAE hardware and want it to use them directly for liveview.

**Comment by FreddieAkeroyd** [comment]
Requires #3630 to be merged first

To test: set up liveview as per wiki entry. There is a section there how to enable histogram liveview, you should then be able to run in histogram mode with something displayed that loks the same as when you run in event mode, but just takes longer to update

**Comment by Tom-Willemsen** [comment]
Hi, this looks fine, just one query: in the comment above you say "you should then be able to run in histogram mode with something displayed that loks the same as when you run in event mode". I get two very different pictures in event and histogram mode. Is this expected?

Event mode:
![image](https://user-images.githubusercontent.com/24375813/47370852-80fdca80-d6de-11e8-8953-dd85011b8cfd.png)

Histogram mode:
![image](https://user-images.githubusercontent.com/24375813/47370880-9246d700-d6de-11e8-9c68-62ca975c1a34.png)

**Comment by FreddieAkeroyd** [comment]
They should be the same, it looks like the counts have maybe got spread. At the bottom of
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Live-View it talks about the DATAMODE PV for doing a TOF view, i think you reviewed that ticket so that setting may have been autosaved, that would cause a spread. If you set DATAMODE:SP to 0 for AD1 does that make then both look the same? There is a ticket #3575 to add such setup options to the OPI
