### ISSUE TITLE
E4: load and save instrument-specific layout positions

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3503]
As a scientist, I would like to make the most of the fact that windows in E4 can be moved and resized. I would like to be able to define my instrument's default layout and save it. When I press the reset layout button it should bring back my instrument's default layout rather than the generic layout.

This has been asked for by several scientists (independently) at the E4/nicos demo sessions

**Comment by DominicOram** [comment]
At first glance there are a few things that think this needs:
* The perspective should be able to be reloaded without restarting the GUI
* It would be good if the user could be told when the layout no longer matches the saved layout
* Rather than try and upgrade layouts ourselves can we just tell the user that something is out of date and they will need to reload their perspective?

**Comment by Tom-Willemsen** [comment]
As part of the review it's been decided to add the acceptance criteria:
- I must be able to reload the saved layout *without restarting the user interface*

Unfortunately this means that this ticket is no longer technically feasible. I will document what's been done and close this ticket as a wontfix

**Comment by DominicOram** [comment]
After discussion the 1st criteria above would increase the time required for this ticket to make it unrealistic. Instead:
* Make perspective layouts persist between restarts as part of this ticket
*Document why this is so hard and everything that we have learnt in doing this ticket
