### ISSUE TITLE
GUI: Stack small groups on top of each other

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3512]
As an instrument scientist on HRPD, I would like small groups to stack on top of each other vertically (if there is enough space). This would let me see more of my blocks simultaneously

Asked for by Dom Fortes (HRPD)

**Comment by kjwoodsISIS** [comment]
How about providing another option, namely to display blocks "ungrouped" (i.e. simply display them in alphabetical order (probably best), or in order of creation (I think this is less good))?

**Comment by ThomasLohnert** [comment]
Heard someone else +1 this recently (I cannot remember who it was, sorry. probably SURF or POLREF)

**Comment by kjwoodsISIS** [comment]
Actually, SANDALS have asked for this too.

**Comment by davidkeymer** [comment]
Possibly have "collapsible" groups using the same mechanism as the main toolbar on the left of the GUI?  Still showing the group name, then these "tiles"(?) could be rearranged to save dashboard space.  When expanded, the groups would pop back to their original positions.

**Comment by Adam-Szw** [comment]
PRs:
Ibex GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1396
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7028

Features added:
- Groups stack vertically
- Groups can be collapsed using a button
- Groups can be sorted by size-based algorithm or left in user-defined order (default)

I didn't add option [suggested here](https://github.com/ISISComputingGroup/IBEX/issues/3512#issuecomment-458941573) because this is the same as just leaving all blocks without group which would place them in 'other' group.

**Comment by rerpha** [comment]
Just going to take myself off review as I didn't get round to finishing it yesterday, in case someone else picks it up

**Comment by rerpha** [comment]
Can we squish test this? if so, can one of you create a ticket for it pls?
