### ISSUE TITLE
Generalise buttons in banner

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3562]
As a user, I would like the contents of the banner (at the bottom of the screen) to be relevant to my instrument.

Therefore, I want to be able to configure the banner to have different buttons. For example:
- Reflectometers want stop all motion
- Muon front ends might want "all magnets off"
- Other use cases can be envisaged.

There is an existing file in `C:\instrument\settings\config\NDblah\configurations\banner.xml` that configures the read-only parts of the banner, but this can't currently configure the writable parts. This ticket is to make the writable buttons in the banner configurable.

**Note:**
The buttons do not need complex behaviour. Writing an arbitrary (constant) value to an arbitrary PV should be sufficient for this ticket. The logic can (and probably should) be implemented in the server.

Do with #3508.

**Comment by KathrynBaker** [comment]
Completing this might also cover the requirements of #2442

**Comment by John-Holt-Tessella** [comment]
Look at configuring size of button.

**Comment by Tom-Willemsen** [comment]
Re-requested by Aidy and James.

**Comment by adamb56789** [comment]
#### Pull requests
- [GUI](https://github.com/ISISComputingGroup/ibex_gui/pull/927)
- [Inst server](https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/215)
- [IOC](https://github.com/ISISComputingGroup/EPICS-ioc/pull/401)
- [Upgrade script](https://github.com/ISISComputingGroup/EPICS-upgrade/pull/30)

#### General acceptance criteria
- After running the upgrade script, `banner.xml` is updated correctly and the banner looks and functions the same as it did before (motor motion display and button moved to xml and work properly)
- Already existing custom items which already exist on some instruments are not changed
- Custom items which display a PV are unchanged
- Custom buttons can be added that write a given value to a given PV
- Size and colour of the buttons can be customised appropriately
- The order that items are placed into the xml correspond to their order in the GUI

#### Documentation
- Updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Spangle-banner
- https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Banner should be updated but I am not sure how to as the changes will not apply until a new release

#### Notes
- Since stuff that was previously hard-coded into the GUI has been moved to `banner.xml` (the motor status and stop all), should a `banner.xml` be added automatically when building a new instrument/dev machine for the first time?

**Comment by adamb56789** [comment]
Since #2442 is being done as a part of this ticket, here is its PR: https://github.com/ISISComputingGroup/EPICS-ioc/pull/403
