### ISSUE TITLE
Log plotter: autoscaling and linked y-axes

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3585]
From James Lord: 

> If I select Log Plotter from a block in the dashboard, the Y axis is by default scaled from 0 to 10 and it’s quite likely that no curve is visible. I have to right click, find “Properties” among a number of largely irrelevant menu items, navigate through tabs to the Y axis, and tick Auto Scale. By default it should either use Auto Scale or choose a starting scale according to the current / recent values of the block.
Also in Log Plotter we sometimes need to plot two or more logs on the same Y axis. For example, when we have instrument control in IBEX, we will want to plot Temperature_Cryostat and Temperature_Sample, where the offsets between them are of interest. At the moment we get separate axes: it’s possible with some fiddling to set them up to be the same but that won’t work when we need to use Auto Scale. But the option of independent Y axes and linked X is still useful, for example Temperature_Cryostat, Temperature_Power and Temperature_GasValve.
In the Log Plotter dialog there’s a very confusing option “when archive data arrives, Perform Stagger”. That really does need a better explanation!

Autoscale should work once when graph is opened.

**Comment by John-Holt-Tessella** [comment]
+1 review

**Comment by kjwoodsISIS** [comment]
consider making the configuration option more obvious

**Comment by KathrynBaker** [comment]
+1 assuming RIKENFE given the scientist in question, but could have been MUONFE

**Comment by adamb56789** [comment]
We considered various possibilities for autoscale. The issue was needing to wait for data before being able to scale the graph sensibly.

1. Start the plotter with autoscale on, then turn it off after a certain amount of time.
2. Use the listener on the model `selectedSamplesChanged` which seemed to trigger once every time a data point was added (from both archived data and current data, I think?), start with autoscale on and turn it off after some number of listener events.
3. Start with autoscale on, and create a new button in the plot's toolbar which could be used to toggle it.

3 was difficult as it would require modifying CSS code. 2 was preferred over 1 as the amount of time that it would be appropriate to wait for would vary significantly. I've initially set the number of data points to wait for to 10.
