### ISSUE TITLE
DAE: wiring table change performance / feedback

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3610]
As an instrument scientist, I do not want to have to wait for a long time for my wiring table to be accepted.

We should investigate the performance of loading wiring tables into the isisicp.
- If we can improve the performance significantly, great.
- If not, we should provide more feedback (e.g. a progress bar) to give feedback to the user about the load process

Reported by Helen Walker (Merlin). Was also reported by Adroja earlier in the cycle.

**Comment by kjwoodsISIS** [comment]
How long does it currently take?

**Comment by FreddieAkeroyd** [comment]
The wiring tables are not loaded into the DAE ioc, they are loaded into the ISISICP. There are 3 files concerned, each 143000 lines long, and the time is probably due to having to cross check all the individual entries against each other to make sure a valid combination of files has been selected. It takes about 30 seconds to load and check the wiring tables, but the whole operation now takes about 45 seconds as I realised that I was doing some things at the start/end of each run that I can do at this point and cache. So changing tables does now take a little longer, but runs will start and finish quicker.

**Comment by FreddieAkeroyd** [comment]
I could add a "CHANGING" state to the DAE so that it would be clear on the dashboard that something was in progress?

**Comment by FreddieAkeroyd** [comment]
Adding C HANGING would also automatically enable the  STATETRANS   PV that indicates if the DAE is in transition, which could be used for a "please wait" diaglog

**Comment by FreddieAkeroyd** [comment]
After talking to Helen this looks like it is a race condition between genie_python set_ei and changing tables in the DAE. So needs some thought onto best solution.

**Comment by FreddieAkeroyd** [comment]
Work for this is now contained in #36326, #3627 and #3628
