### ISSUE TITLE
Check that Instruments run IBEX server boot script on reboot

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#3661]
It was noticed recently that some IBEX instruments don't have a shortcut to `ibex_system_boot.bat` in the startup groups of their start menus.  This means that the IBEX server would never start on a reboot of the machine, potentially causing loss of beamtime and/or support issues.

The instruments in question are:
- MAPS
- MERLIN

Although there could be others.

This ticket is to check that all IBEX instruments have the shortcut to the aforementioned file in their startup groups.  The instructions are [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup)

If a script is to be written, then the knowledge that the shortcut lives in:
`\\ndxINSTRUMENT\c$\users\spudulike\appdata\roaming\microsoft\windows\start menu\programs\startup` may be of use.

**Comment by ChrisM-S** [comment]
It would be good to have a tool as part of the installation process (Possibly just a heuristic - e.g. total number of folders under each root install path) to provide a means of checking that an IBEX installation is complete.  There are several ways in which an installation might not be finished at one time by one person or have not worked fully due to a disk space or network issue.

We have also on SECI also had the experience of losing some critical folders in the installation between one run and the next! - the reason these vanished was never discovered but a "check_IBEX_install script" which could run remotely and ensure all parts of the installation were at least there on disk might be worth considering?

**Comment by John-Holt-Tessella** [comment]
It is part of the standard install but the instructions are currently wrong. We should fix this see #3492

**Comment by FreddieAkeroyd** [comment]
I've ran a checker on the instruments. 
 
IBEX instruments - these should have ibex_system_boot.bat as a shortcut present in the spudulike start menu area

ALF - OK
ENGINX - had ibex_system_boot in all users rather than spudulike and also a copy not a link, now fixed
GEM - OK
HRPD - OK
IMAT - OK
IRIS - OK
LARMOR - OK
MAPS - was missing, now fixed
MERLIN - was missing, now fixed
POLARIS - OK
SANDALS - OK
VESUVIO - was missing, now fixed
ZOOM - OK

MUONFE - I believe this is done as a boot time task as windows server has no auto logon?
RIKENFE - is anything in place?
EMMA-A - machine is down so cannot tell at the moment

The following instruments run mini inst and have has start_ibex_server in spudulike rather than ibex_system_boot. SECI always started on boot, so we may not want to change this

MUSR
CRISP
HIFI 
INTER 
LET 
OFFSPEC 
POLREF 
SANS2D
SURF

**Comment by FreddieAkeroyd** [comment]
We may need to manually fix TOSCA, INES and OSIRIS during deployment if the issue mentioned in #3492 is still present

**Comment by ChrisM-S** [comment]
As far as I'm aware the folders still there and function through to Windows 10 and Server 2016.  The script should just put the link in there.

`C:\Users\spudulike\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

and

`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`

for user specific startups and all user startups respectively.  A "one-liner" which will create the link programatically is 

```powershell
set PWS=powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile
%PWS% -Command "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('C:\Temp\test.lnk'); $S.TargetPath = 'C:\Temp'; $S.Save()"

```

**Comment by Rory-Potter-Tessella** [comment]
ALF, ENGINX, EMMA-A, GEM, HRPD, IMAT, IRIS, LARMOR, MAPS, MERLIN, OSIRIS, POLARIS, SANDALS, TOSCA, VESUVIO, ZOOM are all okay.

- Riken FE: Doesn't have the boot script. Should it?
- Muon Fe: Doesn't have the boot script. Should it?
- INES: Doesn't have a boot script.

**Comment by KathrynBaker** [comment]
RIKENFE should have one
MUONFE being a server OS doesn’t have that option at the moment – we need to watch this if we do switch it a standard instrument setup in the future

**Comment by ThomasLohnert** [comment]
Added the boot script shortcut on INES.

**Comment by kjwoodsISIS** [comment]
Judging from the above discussion, all instruments have been done, with the exception of RIKENFE.  Is there any reason for delaying the fix on RIKENFE?  Can we do it now?  If we have to wait before applying the fix to RIKENFE, can we do that under a new ticket, rather than keep with open while we wait?

**Comment by kjwoodsISIS** [comment]
@davidkeymer , @FreddieAkeroyd  - can we make progress on this ticket?

**Comment by John-Holt-Tessella** [comment]
INES - Checked
RIKENFE - Checked

**Comment by ChrisM-S** [comment]
I just rebooted ENGINX for updates and although I'm sure I didn't shut down the server before forcing a the reboot it doesn't look like the IBEX server has started?

**Comment by FreddieAkeroyd** [comment]
If the server was running there should be a file c:\instrument\var\tmp\ibex_running.txt - this file doesn't look to be present, which would suggest the server had been shutdown prior to reboot?

**Comment by FreddieAkeroyd** [comment]
nagios suggests IBEX was likely shutdown about a week ago

**Comment by ChrisM-S** [comment]
Bizarre!, but I can see the log file dates are old.  I held off updates at their request because they were running an experiment which finished this afternoon - must have just been on the setup machine. Sorry for the confusion.
