### ISSUE TITLE
Induction furnace IOC: implement maximum temperature based on sample holder

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3798]
As a user of the induction furnace IOC, I would like the software to dynamically change the upper temperature limit based on what type of sample holder I have mounted.

> We are gonna use several different sample holders and they operate with different maximum temperatures due to melting points. So can we make a box in the advanced settings with multiple options for the sample holder That will define the maximum possible temperature of an experiment? I would like the list to contain the following options:
> -Chose sample holder
> -Aluminium (max 500 C)
> -Steel (max 1000 C)
> -Graphite (max 1600 C)
> -Quartz (max 1500 C)
> -Single crystal sapphire (max 1600C)
> I would like it to be such that the standard setting is the "Chose sample holder" which will disable the start button. This way people will only be able to run the device with the right settings for the particular sampleholder.

It has been confirmed that there are no potential safety implications about doing this check in software - this is just to save equipment damage

Do as part of #4042

**Comment by ChrisM-S** [comment]
Some consideration should be given to the state of the OPI and the "Choose sample holder" control as a result of an IBEX server restart, IOC restart or system crash.
1) Would the control setting be maintained to reflect the sample holder currently "at temperature" (i.e. if the sample was already at 1500 degrees C, would Quartz or Saphire be the only options available?).  To avoid sudden unexpected cooling unexpected heating (for example if the system crash was caused by a power off which also took the furnace offline?
2) Would the experiment not continue (to be defined) if a sample can type was not selected on the OPI after a restart?
3) Which options would balance sample compromise and potential beam time loss?

### note:
A table of outcomes/options might be useful for us to adopt more generally to ensure options are considered, particularly against Beam time loss and mitigation of sample loss/damage  For example, choppers, persistent cryomagnets etc. where management of state could affect both sample and experiment.

|Restart type|recovery action|how implemented?|
|---|---|---|
| Restart of control computer alone|
| Restart of IOC (intentional or not?)|
| Crash/restart of IBEX server only (intentional or not?)|
| Power failure affecting control computer AND apparatus under control|

**Comment by Tom-Willemsen** [comment]
Further emails from Jakob have confirmed that we do *not* need to implement the maximum temperature in the IOC any more - instead, they have implemented this in the arduino code on the far end. The new approach is simply for us to send the type of sample holder using the `>sHold` command (It can be read back via `?sHold`). The valid options for this command are:
- `aluminium`
- `glassy_carbon`
- `graphite`
- `quartz`
- `single_crystal_sapphire`
- `steel`
- `vanadium`
