### ISSUE TITLE
Build system: Incremental build not creating dbd file

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#3806]

**Comment by Alistair-McGann-Tessella** [comment]
The incremental x64 build stopped did not build the separator's dbd file correctly, leading to the system IOC tests failing. Because this is an incremental build this error was propagated forwards and not being changed. The workspace of this build was cleaned to force a new build.

**Comment by Tom-Willemsen** [comment]
Is there also a more general ticket to fix the incremental build in future? We don't want to be caught by this type of error again as it is tricky to diagnose.

This error is caused because the incremental build doesn't necessarily realise it needs to rebuild an IOC after it's dependencies change. As Alistair notes, the fix is relatively simple: delete the jenkins workspace (effectively making it a clean build) but the diagnosis can be tricky.

**Comment by Rory-Potter-Tessella** [comment]
The more general solution is to use the latest clean build for running the IOC tests and this is implemented as part of #3836.
