### ISSUE TITLE
Polaris: CCD100 support

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3818]
Scientist is using a CCD100 pressure gauge. Talk to it. 
- When trying to connect via the IOC or putty/hyperterm from the cabin machine we get junk back on the serial line. 
- Have tried with and without null modem
- We have tried communicating with the device directly using serial-USB adapter and a laptop but it didn't respond

Diagnose, fix, and document resolution for next time.

**Comment by Tom-Willemsen** [comment]
Appears to be a "MK1" unit where we have only ever talked to "MK2" units before. The communications may be different (and may not even necessarily be possible with a MK1 unit). I will create a separate ticket to implement support for a MK1 CCD 100.

**Comment by davidkeymer** [comment]
Reviewed:

- Ticket #3819 for MK1 marked as `won't fix` because unit incapable of communication.
- Ticket #3821 for MK3 created to check that current IOC can communicate with MK3.
- Wiki page with details of all CCD100 models located at:
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/CCD100
