### ISSUE TITLE
IOC for MK1 CCD100 pressure readout

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3819]
As an instrument scientist on Polaris and potentially other beamlines, I would like to be able to read the pressure from a MK1 CCD100 device. Note that this is **different** from the MK2 CCD100 device which we already have support for. 

There is a unit in the office currently on @GDH-ISIS desk.

**Comment by kjwoodsISIS** [comment]
@Tom-Willemsen - do the Pressure & Furnace section have a manual for the Mk1 model?

**Comment by Tom-Willemsen** [comment]
There is one, and it has been put on the usual manuals shared drive. I'm not sure how useful it is for us.

**Comment by GDH-ISIS** [comment]
Contact at Chell is Jamie Shanahan

**Comment by GDH-ISIS** [comment]
Reply from manufacturer :

Thanks for your email.
Unfortunately the Mk1 CCD100 was a 'badged' display which never offered user facing digital communications, and was obsoleted many years ago. The CCD100 Mk2 was the first of the CCD units we designed and built at Chell and has RS232/485 comms. The current Mk3 has comms over Ethernet, RS232 over USB and an internal webserver.
I'm afraid it sounds as though the Mk1 is not suitable for your application.

Mark Kibble has ordered several Mk2 so you could ask him if he has a spare you could use, or we can quote to supply a new Mk3 unit from stock if not. Datasheet attached for information.

**Comment by GDH-ISIS** [comment]
After asking for clarification, this is the reply from the manufacturer :

It is confusing because, as you say, details of these pins have been shown and they shouldn't have been. You have a standard Mk1 CCD.
From what I understand there is some level of remote comms included by the OEM, but it is not customer facing. We were never given any information on protocol, command set etc to enable use of it.
When I say 'badged', this was a display type which was bought in in quantity from a display manufacturer and labelled as Chell. Back then we didn't have the facilities to design and manufacture fully ourselves. The following two versions of CCD have been designed and manufactured by Chell.

**Comment by GDH-ISIS** [comment]
This looks to have run it's course. With the information we currently have, we can not communicate with this CCD100 MK1 device. I will inform the pressure and furnace support team so that they are aware.

**Comment by GDH-ISIS** [comment]
Pressure and furnace support team have now been informed.

**Comment by GDH-ISIS** [comment]
CCD100 MK1 unit used to investigate the communication issue has now been returned to the pressure and furnace group.
