### ISSUE TITLE
IMAT: Setup 3 axis rotational stage Galil_08

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3828]
IMAT need the rotation stage setting up. 

There are new parameters that need setting:

Motor resolution = 0.0036
Encoder resolution = 0.01

Acceptance criteria:

1. Plug in 
1. home 
1. check movement

**Comment by John-Holt-Tessella** [comment]
Converted to use serial, on port com 13 using 11520 baud rate. 
Label added to the crate recording baud rate.

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by ThomasLohnert** [comment]
Since the scientists have been using it and are happy I think it's reasonable to assume this is working fine - have checked the setup of the records for `GALIL_08`, which is as described in the issue. I'm not sure what else to do for review, please let me know if you can think of anything.

My only comment is that the `GALIL_08` axes in use should have descriptive aliases like the rest of the motors on IMAT.
