### ISSUE TITLE
Memory usage: java: add appropriate memory limits to all java processes

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#3859]
As a system developer and maintainer, I want to make sure that the java processes in the system are not using unnecessary memory.

As discussed in a meeting, this ticket is to go through our java processes and add appropriate startup flags to limit memory usage to an appropriate level:
- `ibex_gui`, currently set to 512MB, leave as 512
- `ActiveMQ`, currently set to 1G. Try to set to 512 or 256 and test.
- `IOCLogServer`, curently no limits defined, try setting to 256 or 128 and test
- `ARINST` - currently no limits defined. Measure and set appropriately
- `ARBLOCK` - currently no limits defined. Measure and set appropriately

**Comment by kjwoodsISIS** [comment]
put nagios checks on java cpu aswell

**Comment by DominicOram** [comment]
* Both archive engines already have a limit of 256MB. They also report memory usage via their web interface.
* Setting `ARINST` to < 256MB caused serious issues, even without much running on a dev machine. Instruments tend to be using ~70% of this when viewed through the web interface. Leaving at 256MB.
* `ARBLOCK` looks like it may be able to cope with less. It's happy with 128MB up to 100 blocks. However, setting each archive engine to different amounts is hard due to the way we build the archive engine. So I'll leave it at 256.
* The alarm server was originally set at 256MB, setting to 128MB caused no issues.
*  Sending 10,000 messages with the test logging script caused the IocLogServer to peak to ~30MB so I'm setting this to 64MB.
* With the above test on activeMQ at 128MB I saw no issues so will set to that.
