### ISSUE TITLE
Reflectometry: A user can zero the motors from the OPI

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3895]
As an instrument scientist I want to be able to "zero" a motor when it is on the straight through beamline this is so I can lock in the alignment I have performed.

Ideally this would work in the same way as SECI; if this is hard check with the reflectometry scientists if we can just change offset in IBEX motors.

**Comment by ThomasLohnert** [comment]
Being able to set 0 on the motor itself is a hard requirement at least for the beginning so that users can switch seamlessly between SECI and IBEX (e.g align beamline in IBEX, then switch to SECI later and have the positions preserved - this would not work with offsets as they are in the motor controller and not available in SECI)

The procedure for redefining zero on a motor in IBEX is setting the motor `.SET` field to "Set", setting 0 as the motor position, then setting the `.SET` field back to "Use". The scientists want this operation to be encapsulated in some way, such that they can zero the motors with just one click / command line instrunction.

**Comment by ThomasLohnert** [comment]
Implemented as a function in the scans library ([Code](https://github.com/ISISNeutronMuon/InstrumentScripts/compare/refl_zero_motors)). This simply encapsulates a sequence of channel access commands required to redefine zero on a motor. It also uses a lookup dictionary hardcoded to CRISP to lookup the correct motor based on the axis name. 

This is a temporary solution for CRISP testing, hence I have just left it on the branch. Eventually the goal is to zero motors via high level reflectometry parameters. Ticket for this is here: https://github.com/ISISComputingGroup/IBEX/issues/4131

**Comment by Tom-Willemsen** [comment]
@DominicOram are you still reviewing this or should someone else pick up the review?

**Comment by DominicOram** [comment]
Sorry, I must have missed that my name was on this. I'll drop it for someone else to pick up.

**Comment by John-Holt-Tessella** [comment]
This needs a test.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/system_tests/pull/15
