### ISSUE TITLE
JASCO: create caLab interface

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#3934]
A caLab GUI is required for the JASCO #3923 for use on SECI instruments

**Comment by KathrynBaker** [comment]
LabVIEW code is in source safe, @davidkeymer can probably review that - if someone wants to check it alongside #3923 then that is possible as well

**Comment by davidkeymer** [comment]
### Review of ticket

#### `Jasco HPLC Pump - Front Panel.vi`:
- No units shown on setpoints or readback values
- `Start`, `Stop`, `Timed` buttons don't seem to work (unless have to select one and then press `Set`?)
- `Pump For Time Setpoint` and `Pump Set Volume Setpoint` controls can be set simultaneously, which confuses the IOC and user.  One or the other should only be allowed at one time.  c.f. OPI
- ***Diagram:*** Write PVs subVI doesn't have setup cluster wired in "Set All" event frame

#### `Jasco HPLC Pump - Write PVs.vi`:
- ***Diagram:*** Typo in 'PRESSURE:MAX:MP' PV in string array

**Comment by KathrynBaker** [comment]
* Units added to match the db file
* Standard behaviour, even on a button under LabVIEW was to use the set button, so that is a press set scenario
* The two controls is a race condition, and would exist in scripting as well as here - I have created a new ticket (#4029) to limit that ability, to mitigate at least some of the problem I have added "not equal to the previous value" checks to those two values
* Setup cluster now connected
* Typo corrected

**Comment by davidkeymer** [comment]
Additional rework completed by @davidkeymer and subsequently reviewed by @KathrynBaker.
