### ISSUE TITLE
IOC: NetShrVar segmentation fault when reading double arrays

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#3955]
As an external user I am getting a bug when using double arrays in shared variables. See https://github.com/ISISComputingGroup/EPICS-NetShrVar/issues/4

**Comment by FreddieAkeroyd** [comment]
Patched merged, will be tested by external user

**Comment by Tom-Willemsen** [comment]
Could we write a test for this?

**Comment by FreddieAkeroyd** [comment]
Now we have googletest in the framework we probably could add a test where we threw an exception on read,  I don't see the error myself but i am running on Windows rather than Linux and it may depend on how the shared variables are initially created e.g. I used labview and they may be on a PXI crate

**Comment by kjwoodsISIS** [comment]
How many points?

**Comment by FreddieAkeroyd** [comment]
Fix confirmed by user
