### ISSUE TITLE
MARI: Frames/Current jump

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#3979]
As a MARI instrument scientists, I have observed odd behaviour for frames / current values on the dashboard: the counters freeze every few seconds, then jump to the current value, keep ticking, freeze again etc.

Monitoring the values on the DAE IOC shows the same behaviour so the source of the bug seems to be further down than the display level.

**Comment by DominicOram** [comment]
Also seen on LOQ

**Comment by FreddieAkeroyd** [comment]
I've seen this before on DAE3 machines but not with DAE2. Dom did an quick analysis and:

* POLARIS (OK)
* GEM (OK)
* IMAT (OK
* LARMOR (OK)
* LET (OK)
* MAPS (OK)
* MERLIN (OK)
* TOSCA (BAD)
* MARI (BAD)
* LOQ (BAD)
* OSIRIS (BAD)

There seems to be no correlation of ibex or ICP versions. May be able to analyse more on LOQ, but LOQ issue may be due to live view from the second detector card.

**Comment by FreddieAkeroyd** [comment]
Have some time to test on LOQ

**Comment by FreddieAkeroyd** [comment]
Looks to be due to LOQ using an older environment card, I had fixed an issue with reading vetos for the period card but not applied that change to the older environment card software. The issue would not have been noticable under SECI. Fix applied to LOQ and brief testing looked OK.

**Comment by FreddieAkeroyd** [comment]
Updaeted and looks OK
