### ISSUE TITLE
IBEX Drop In Session 13/Feb/19

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#4009]
This is just a catchall to keep together the things we need to look at/answer for this session.  I've put down a tick list with the issues which were brought up by the Muon group (the only attendees) during the hour.

I've circulated the minutes and just put a checklist here to group the issues we need to address. The order is roughly the order in which things came, not necessarily priority.

IBEX Drop in Session (MUON group, no other attendees)
=====================================================

  - [x] 1.  **MUSR Memory**  (see [#592](https://github.com/ISISComputingGroup/ControlsWork/issues/592) & [#595](https://github.com/ISISComputingGroup/ControlsWork/issues/595))
  - [x] 2.  **The late release of IBEX** (see comment about e-mail below)
  - [x] 3.  **IBEX release notes** (see comment about e-mail below)
  - [x] 4.  **Footprints *response time*** (see comment about e-mail below)
  - [x] 5.  **PSU Interlock statuses** (see comment about e-mail below)
  - [x] 6.  **NaNs for Lost/failed comms** (see comment about e-mail below)
  - [x] 7.  **Python Power supply control issue** (see comment about e-mail below)
  - [x] 8.  **Cursor keys in the IBEX console** (see comment about e-mail below)
  - [x] 9.  **Machine Naming** (see comment about e-mail below)
  - [x] 10. **MUSR Detector PSU control is very flaky** (see #4073)
  - [x] 11. **Rename session “Instrument Control Drop in session” (Instead of
    IBEX Drop in session)** (see comment about e-mail below)
  - [x] 12. **Invite to drop in session to be by sending a meeting request** (see comment about e-mail below)

**Comment by John-Holt-Tessella** [comment]
We think most of this is dealt with by emails and thought. Kevin to collate and close.

**Comment by kjwoodsISIS** [comment]
The following is the content of an e-mail sent by @FreddieAkeroyd to Aidy addressing each of the points above:

Thank you for attending the IBEX drop in session and feeding back to us on various issues. Chris provided us with some detailed notes from the meeting and after discussing with the IBEX team we would like to give you an update on how we hope to address the issues raised 

#### 1. MUSR Memory Issue (also EMU & HIFI) ####
We do not yet understand the root cause of this problem.  There are two things we will do:
a) Reassess the evidence and see if we can spot a pattern
b) Switch on memory allocation flags in the Windows Kernel to see if that can tell us where the leaking packets are coming from.  There is a risk that doing this could impact the performance of the server (but we won’t know this until we try it).
 
#### 2. The late release of IBEX ####
IBEX was released late because we were unable to test some device until late in the shutdown.  We are happy to change our policy.  In future, we will release new versions of IBEX near the start of the shutdown.  Please be aware that if a device is not available for testing prior to the release, support for that device may not be included.  We will, of course, try to add support for such devices via a patch release, but this will be on a best endeavours basis.  In some cases, this may mean that support for a device will have to wait until a future release (which could be at the end of the next cycle). 
 
#### 3. IBEX release notes  ####
It was highlighted that working out the potential impact/changes of a release was not clear. The release notes at https://github.com/ISISComputingGroup/IBEX/wiki/Release-Notes-v5.2.0 split into instrument specific and device sections, but the device section can apply to multiple instruments. Was it this split that made things unclear, or was it the one line summary of the changes themselves?
 
#### 4. Footprints response time  ####
We believe this relates to an issue that was reported at the weekend i.e. out of hours. Our on-call out of hours support for urgent issues is telephone initiated as mentioned on our contact sheet and the web submission page, emails may get answered but that should not be relied upon for urgent matters. If we need to make this clearer or look at our wider out of hours procedures we would be happy to discuss with you, but procedure changes may require discussion with ISIS management.  
 
#### 5. PSU Interlock statuses ####
These are available – see the Danfysik OPI.  Perhaps the quickest thing to do is for somebody to pop down to show you.  Let us know a convenient time to do so.
 
#### 6. NaNs for Lost/failed comms ####
We think this is a good suggestion and agree with the general approach.  We have also mentioned it to other scientists and, so far, all agree it is a good suggestion.  We are discussing it within the group, to make sure we identify all the consequences of making such a change.  We are also discussing it with the Mantid team to make sure the change doesn’t introduce any unwanted side effects.  Once we have agreement with the Mantid team, we will circulate a note via the SAG to inform everyone of the planned change.  Then we will proceed to implement the change.
 
#### 7. Python Power supply control issue ####
The python language is case sensitive and we are constrained by how much we can change/hide. True and False are Python keywords  so allowing    cset a=false   as well as   cset a=False   would not be possible. Where we have options to catch things is if strings are used  i.e.   cset a=”false” or cset a=”on”  and  cset a=”ON”.  Another option is having separate commands rather than using cset. We will need to discuss this issue and what we could do to help more with you. 
 
#### 8. Cursor keys in the IBEX console ####
This is an artefact of the 3rd-party component that we use to provide a console, we could investigate alternative components at some point in the future.
 
#### 9. Machine Naming ####
Thanks for letting us know.  We’ve made a note to do this.  Please let us know when you are ready to proceed with the new names.
 
#### 10. MUSR Detector PSU control ####
Thanks for letting us know.  We will take a look at this and attempt to diagnose the problem.
 
#### 11. Drop in session ####
Happy to give it a new name.  Also happy to send outlook invitations instead of an e-mail.

**Comment by kjwoodsISIS** [comment]
Accidentally closed.

**Comment by kjwoodsISIS** [comment]
All issues have now been addressed - either by an e-mail to the muons group or by tickets (referenced in the original issue description).  Issues which have a ticket will be followed up via the ticket.  Issues which don't have a ticket will be followed up as and when the muons group responds (and, if necessary, new tickets will be raised to deal with any further issues).  No further work is required for this ticket.
