### ISSUE TITLE
LET: MySQL database not in usual place

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4015]
The MySQL database files on LET are in c:/ProgramData rather than  c:/Instrument/var/mysql. These should be moved at a convenient point, or maybe just MySQL reinstalled?

**Comment by kjwoodsISIS** [comment]
We should try to understand why MySQL was installed in `C:/ProgramData`.  Was it simply an oversight?  Is there a problem with the installation script?

**Comment by Tom-Willemsen** [comment]
The MySQL installer makes it very difficult *not* to install in `C:/ProgramData`. We have instructions for it on the wiki, but the MySQL installer is confusing and if a step is missed will just install it in the wrong place.

Probably the best we could do is to add an automated step to the deployment script just after installing MySQL to verify that it has been put in the correct place.

**Comment by ChrisM-S** [comment]
I have a one liner that does a fully unattended install of mysql with the correct location of of the database in “var”, it works up to 5.7.19 – but then they broke it and I didn’t have a chance to find the fix (or whether the bit the broke it mattered and could be left out).

It would be very easy to install this version and then simply update immediately (very quick to do manually and everything will stay in place then).  In fact, I might use this trick myself because I realise I can also automate the update…

You need the full  `mysql-installer-community-5.7.19.0.msi` (which has the full install in the MSI - I have it).  Then the command is as below.  Might as well not waste the effort!

```
msiexec.exe /qb- /l*vx %LogPath%\MySQL.log REBOOT=ReallySuppress UILevel=67 ALLUSERS=2 CONSOLEARGS="install server;5.7.19;x64:*:type=config;openfirewall=true;generallog=true;binlog=true;datadir=""C:\Instrument\var\mysql"";serverid=1;enable_tcpip=true;port=3306;rootpasswd=ROOTPASSWORDHERE:type=user;username=root;password=ROOTPASSWORDHERE;role=DBManager -silent" /I mysql-installer-community-5.7.19.0.msi
```

**Comment by John-Holt-Tessella** [comment]
We are installing 5.7.22 and will soon bundle it with the ibex install (hopefully). However until then there are instructions for moving it on the wiki.

**Comment by DominicOram** [comment]
Closing as this will occur naturally when we release to LET
