### ISSUE TITLE
GUI: unable to type in python window after Crtl-C

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4070]
Reported by Adrian Hillier - a python script was running in the client script window on RIKENFE, pressing Ctrl-C correctly terminated the script but after that they were unable to type anything in the python window. After a client restart the window again worked.

**Comment by DominicOram** [comment]
I can't reproduce this locally, we may need more information about what else was going on at the time.

**Comment by FreddieAkeroyd** [comment]
Update from Aidy. "It was Saturday morning 10:45 ish. We could type in the terminal but no script or command was actioned."

**Comment by DominicOram** [comment]
Do we know what script they were running?

I think this might be due to the fact that you can't inject a keyboard interrupt into a sleep in python. The signal will not occur until you come out of the sleep. If you sleep for a long time in the GUI and do a keyboard interrupt you will get weird behaviour until the sleep is finished. Ensuring we are always doing a loop of short sleeps in genie_python will help with this, this is also how NICOS does it.

**Comment by FreddieAkeroyd** [comment]
would the script name be in the genie python log file?

**Comment by FreddieAkeroyd** [comment]
@DominicOram I passed on your findings and have some more details from Aidy. He thought he did see
Keyboard Interrupt (in red), but possible he didn't. 

"The error occurred in the reset_psu_interlocks() in front_end.py. I changed lines 13 so comms was ilk (line 14 was ilk instead of comms – this was the error in the script. I had 50/50!). So could it get into a funny state within the getpv??"

He said we could run this with this bug on the maintenance day if that would help..

**Comment by DominicOram** [comment]
it looks like CaChannel uses a sleep when you do a getw() with a timeout. We currently have the timeout set to 15 seconds, which is plenty of time for a user to type something in the GUI. We should one of the following:
* Use CaChannel better so that it's not waiting on these (reading the docs looks like you might be able to do this)
* Do the waiting in a loop in our wrapper (we already do this for searching for the PV)

This will probably keep hitting us for when users do sleeps in their own scripts, we should do some of the following:
* Modify pydev to make it more obvious what is happening (feeding back to the developer)
* Get user scripts to use our own sleep (or NICOS's one?)

**Comment by Tom-Willemsen** [comment]
IRIS reported that this happened when they interrupted a wait. Stack trace:

```
Waiting for 600 uamps 
** Ending Run 00088786 at 10:27:46 12/03/19 
** Beginning Run 00088787 at 10:27:55 12/03/19 
*  Proposal Number: 1910021
*  Experiment Team: Raja, Silverwood and Parsons
Waiting for 30 uamps 
** Ending Run 00088787 at 10:39:00 12/03/19 
** Beginning Run 00088788 at 10:39:13 12/03/19 
*  Proposal Number: 1910021
*  Experiment Team: Raja, Silverwood and Parsons
Waiting for 600 uamps 
Traceback (most recent call last):
  File "C:\Instrument\Apps\Python\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-ccbb95d71b37>", line 1, in <module>
    all()
  File "U:\Ian\Jack-5.py", line 129, in all
    qens(373)  # (temperature, uA - optional - defaults to qens_uamps value at script start)
  File "U:\Ian\Jack-5.py", line 56, in qens
    g.waitfor(uamps=ua)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie.py", line 416, in waitfor
    frames, raw_frames, uamps, early_exit)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_waitfor.py", line 127, in start_waiting
    res.append(self.api.dae.get_uamps() < uamps)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 571, in get_uamps
    return self._get_pv_value(self._get_dae_pv_name("uamps"))
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_dae.py", line 185, in _get_pv_value
    return self.api.get_pv_value(name, to_string)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 260, in get_pv_value
    if not self.pv_exists(name):
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_epics_api.py", line 275, in pv_exists
    return Wrapper.pv_exists(name)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 245, in pv_exists
    chan = CaChannelWrapper.get_chan(name, timeout)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 180, in get_chan
    with CACHE_LOCK:
  File "C:\Instrument\Apps\Python\lib\threading.py", line 174, in acquire
    rc = self.__block.acquire(blocking)
KeyboardInterrupt
end()

```

**Comment by DominicOram** [comment]
So the KeyboardInterupt was shown to the user but they still didn't get a prompt?

**Comment by Tom-Willemsen** [comment]
Correct
