### ISSUE TITLE
ENGINX: Eulerian Cradle

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4074]
As a scientist on ENGINX I would like to be able to control the Eulerian Cradle in order to manipulate my samples orientation

**Acceptance Criteria**
1. The Eulerian Cradle is set up in IBEX on ENGINX

**Notes**
1. This has been requested for use on the 8th of March
1. This is controlled via a portable Galil
1. There are two axes, and the rotations in question are readable from the scales on the device
1. It has been set up and used in SECI in the past
1. There is no known use of it under IBEX
1. This is a mainly a commissioning task, the two axes could be aliased via motion setpoints and the generic sample stack OPI be used for an interface
1. This should only take a couple of hours at most
1. The instrument scientist will endeavour to get the system set up so that we can interact with it on the 6th of March

**Comment by davidkeymer** [comment]
A few hours were spent in preparation for the installation of the cradle by creating and testing an IBEX component using simulated motors.  The hardware was delivered late to the beamline (end of day on Thursday 7th) and because of unavailability of staff and beamline, the system wasn't able to be tested in-situ until late on Friday (8th) afternoon.
A few more hours were then spent setting up and testing the system, but to no avail: the axes could not be moved, nor the encoders and limit switches read despite establishing communications to the Galil controller (via serial).  As this was a new installation of a Galil IOC using untested hardware (in IBEX), it was assumed that the problem lay somewhere in the software configuration.  It was decided not to use the cradle over the weekend and resort to a manual goniometer.
On the morning of Monday 11th, the control crate was inspected by SE Electronics group and an internal cable found to be disconnected.  This was the 100-way high-density cable that links the Galil controller to the breakout card which interprets the motor, encoder and switch signals, thereby explaining why these couldn't be read remotely.
A couple more hours were then spent testing and calibrating the two axes of the cradle and the device was used successfully for the rest of the week.
