### ISSUE TITLE
4090-1: BLOCKSERVER: Do not restart the gateway or archiver on config set if blocks have not changed

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4110]
As part of #4090 the code which stoppped the archiver and blocks gateway restarting if no change was made was removed. Reinstate the code and review the testing to make sure it works. Code is `BlockServer/core/active_config_holder.py` line 170-171. Remoce this:

```
# As a hotfix #4090 this will get round inconsitencies with cache config
return True
```

Particularly add a system test for the workflow in #4090.

**Comment by Tom-Willemsen** [comment]
There are several unit tests annotated with `@unittest.expectedFailure("To be fixed in ticket 4110")
` which should be looked at in this ticket

**Comment by Tom-Willemsen** [comment]
I have been having a look at this issue. It turns out that the `_cached_config` in the `ActiveConfigHolder` class is not always correct.

This is quite a tricky problem - I discussed with @John-Holt-Tessella and @kjwoodsISIS and we decided that this is important enough to fix now. I have updated the ticket estimate correspondingly.
