### ISSUE TITLE
NIMROD: Sample Changer

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4113]
As a scientist, I want to control the NIMROD sample changer, so that I can select and position the sample during my experiments.

#### Acceptance Criteria
1. I can use the IBEX GUI to control which sample is placed in the neutron beam.
1. I can use a genie_python script to control which sample is placed in the neutron beam.

#### Notes
1. The NIMROD sample changer is very similar to the SANDALS sample changer, except that is controlled by a Galil.
1. See also the [NIMROD wiki](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) page.

**Comment by Tom-Willemsen** [comment]
Motion tested using both GUI and scripting (copied from Sandals per request from instrument scientists). I believe the only thing now remaining on this ticket is to sort out the homing, which can't be done until the galils are on ethernet, which in turn can't be done until FIT tell us which private network ports to use.

**Comment by Tom-Willemsen** [comment]
Private network installed, galils talking happily on ethernet.

Tested homing both sample changer axes and all works as expected. It is controllable both via the GUI (added to NIMROD's synoptic) and scripts (copied from SANDALS). I don't think there is any further work to do on this ticket.

**Comment by DominicOram** [comment]
Generally looks like it's working, checked the config, synoptic and the current state of NIMROD. Some questions:
* There are no limits on either of the axes, it's generally a good idea to put some limits in if we can
* Is rotation meant to be in mm? I would naively assume it would be degrees but I don't know the device

**Comment by Tom-Willemsen** [comment]
- Limits: thanks for spotting this - the script hadn't migrated these and I forgot to do it manually. I have now applied the limits that SECI used to have onto both axes.
- Units: The units of the underlying motor axis are correct but the motionsetpoints db hard-codes the units to `mm`. We should probably make the motionsetpoints db copy the units of the underlying axis, but I feel this is out of scope for this ticket so I've created https://github.com/ISISComputingGroup/IBEX/issues/4689 . For now I've pointed NIMROD's blocks at the underlying motor rather than the motionsetpoints axis so that the units display correctly.
