### ISSUE TITLE
NIMROD: Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4129]
As a developer, I want to migrate NIMROD to use the IBEX instrument control system.  As a scientist, I want NIMROD to be migrated to IBEX in time for the start of Cycle 2019/02.

#### Acceptance Criteria
1. IBEX is installed on NIMROD
   1. The IBEX server boot script is installed (see [IBEX auto-startup](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Deployment-on-an-Instrument-Control-PC#creating-ibex-auto-startup))
1. NIMROD is added to the list of available instruments
1. Configuration files matching the current SECI config files are created 
1. IBEX is configured for the devices on NIMROD.
1. NIMROD scripts are converted to genie_python
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   * On NIMROD, normal practice is to simply use an old script as a template.  However, there is one script which would be worth converting (see [NIMROD Wiki](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) page)
1. IBEX is tested on NIMROD

#### Notes
1. The devices on NIMROD are listed on the [NIMROD Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/NIMROD-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for NIMROD.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   - Done (14-03-2019)
   - [NIMROD VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/NIMROD/NIMROD_VLAN_Settings.txt)
- [x] Check that NDXNIMROD has sufficient disk space to install IBEX
  * NIMROD has 30Gb of free space.
- [x] Check whether NIMROD uses 5- or 8- digit run-numbers
   - [x] If it uses 5-digit run-numbers, upgrade the ICP program (to permit 8-digit run-numbers)
- [x] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXNIMRODTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [x] create genie-python scripts to correspond to their Open-Genie equivalents
      * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [x] test these configurations & scripts
   - [ ] check that all the devices previously supported by SECI (on NIMROD) are supported by IBEX.

**Comment by Tom-Willemsen** [comment]
Initial testing:
- Jaws **appear** to talk correctly
  * I'm not sure the collimation logic currently does what the scientists want - https://github.com/ISISComputingGroup/IBEX/issues/4672
  * Need to set soft limits on all the jaw axes - these are not set by the migration script
  * EDEL of `0.25` seems "about right" when I asked the scientists.
- Sample changer now appears to move correctly. 
  * Needs de-energise switched off on the vertical axis (otherwise it falls under it's own weight). 
  * Homing from IBEX currently doesn't seem to work - I may have selected an incorrect homing routine during the migration.
- CCR (eurotherm) appears to communicate as expected.
- Julabo appears to be talking correctly. 
  * External temperature is not reading, but the scientists tell me that this sensor is not plugged in so it makes sense. 

Still to test:
- TPG for beamline vacuum
- Oerlikon centre-one
- MKS PR4000 gas panel
- Edwards turbo pump
- Motor axis 0403 (not quite sure what this is connected to!)
- Other eurotherm channels (8 channels in total - only the 3 CCR ones were tested above)
- Sample changer homing (both axes)
- Jaws collimation logic once https://github.com/ISISComputingGroup/IBEX/issues/4672 is done

Scripting:
- Copy over sample changer scripts from sandals, and test on NIMROD (given that the sample changers are of similar design, SANDALS' scripts should in theory work for NIMROD - but this needs testing.

**Comment by FreddieAkeroyd** [comment]
I noticed NIMROD was on serial - is that to allow an easier SECI revert? I think downloading the homing program may be timing out - enabling software flow control on the galil via the dip switch has fixed this in the past.

**Comment by Tom-Willemsen** [comment]
The galils are on serial because we don't yet know which ports have been assigned to the private network. I think the intention is to switch them to ethernet as standard as soon as we know the relevant ports. Thanks for the hint about homing timeouts.

**Comment by Tom-Willemsen** [comment]
Although we had been told that the MKS gas panel is now on NIMROD, the scientist is unable to find it down on the beamline. May need to consult pressure and furnace section to find out where it's been put...

**Comment by Tom-Willemsen** [comment]
The gas panel has now been located and placed on top of NIMROD.

**Comment by Tom-Willemsen** [comment]
Both MKS units are now tested and working (the two units use different serial parity settings - I've documented this on the wiki).

The Edwards turbo communications works correctly, but would be better if it could read in `mbar` rather than `Pa`. This is a simple change to the IOC, @Alistair-McGann-Tessella is taking a quick look.

**Comment by Tom-Willemsen** [comment]
Created https://github.com/ISISComputingGroup/IBEX/issues/4714 and https://github.com/ISISComputingGroup/IBEX/issues/4715 for the remaining SE tests, as we are now in cycle.
