### ISSUE TITLE
MERLIN: VNC issue

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4139]
As a Merlin instrument scientist I have the following issue:

> If the NDX Remote desktop window is minimised on the cabin PC, I'm unable to VNC into that device. I want to look and maybe change scripts. Remote desktop is annoying because it steals focus from the user.

Suggest ways to the user to fix this, potentially by installing a client on their office machine.

**Comment by ChrisM-S** [comment]
It might be worth investigating this a bit more.  Part of the standard configuration for cabin machines is to have a "viewing machine", e.g. NDCMERLIN.  The purpose of this is that it is a screen which always shows the state of the NDX and is also available for anyone who needs to configure the instrument while users are working on the analysis systems (ideally it is not configured so that it can be used for analysis - lower memory and CPU).  If the users are minimising the instrument screen they will not see alarms changes to the run state etc.  It is also not normal for remote desktop to steal focus from the user.  I suspect this may be the Linux RDP client running on an analysis machine.  MERLIN did have a windows machine for this purpose (although I don't think it was NDC).  We should check what happened to this and possibly provide them with one (or at least discuss this with them).

**Comment by kjwoodsISIS** [comment]
Speak to the user
Work out a solution
Explain it to the user

**Comment by KathrynBaker** [comment]
We've altered some of our VNC interactions since this ticket, re open if we know there are still issues
