### ISSUE TITLE
RIKENFE: New Server

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4156]
As a support person, I want to set up a new server to host the IBEX system used to control the RIKEN Front End.

#### Acceptance Criteria
1. New server provisioned with Windows Server and the NDXRIKENFE VM.
1. New server physically installed in a cabinet (north side of R55) and connected to the network.
1. Task to be completed by 1st April 2019.

#### Notes
1. See ticket #4502 for outcome of discussion about new RIKENFE server.
1. See also ControlsWork tickets [#557](https://github.com/ISISComputingGroup/ControlsWork/issues/557) and [#601](https://github.com/ISISComputingGroup/ControlsWork/issues/601)
1. **Note:** Check for network routing problems or firewalls that might prevent communication to instances of SECI on muon instruments.

**Comment by Tom-Willemsen** [comment]
Verified that:
- The NDXRIKENFE machine is available
- It has come up with 14G of memory as per https://github.com/ISISComputingGroup/IBEX/issues/3860
- It is talking to some of it's power supplies correctly (most are not talking, but I am assuming this is because they are interlocked off out of cycle).
- It is available via EPICS over the network.

As far as I can tell, this task looks complete.
