### ISSUE TITLE
Script generator: preview script before sending to nicos

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4170]
As a user, I would like to be able to preview my script before it gets sent to nicos

Acceptance criteria:
- I can preview the generated script(s) before sending them to NICOS

**Comment by JamesKingWork** [comment]
Has this ticket been satisfied by #4167? Of which the behaviour is that the user can open the file from a dialog message box or have a link to the file on the system.

**Comment by kjwoodsISIS** [comment]
In my opinion, no, #4167 does not satisfy this ticket.  The user should not have to go and find the relevant file.  The system knows where the generated file is located, so why make the user locate it (even if you do provide a link).  I think the expectation is something like this:
   1. the UI provides a Preview button
   1. on pressing Preview, the system generates the python script (if it has not been generated already) and displays it to the user in a read-only window.
   1. on closing the Preview window, the window is merely closed.  The generated file can hang around until it is superseded (e.g. when the user makes a change to his script).
The Preview window should provide a read-only view, because an edited python script cannot be read back into the Script Generator.

**Comment by kjwoodsISIS** [comment]
OK.  Some things to think about:
   * Does "Open File" have to be called "Open File"?  Does it have some function other than for viewing generated python files?  Could it be called "Preview".  
   * How difficult is it to create a window that displays the contents of a text file?  It may be a python file, but we don't have to display it like an editor would display it (with syntax-checking & colours, etc.).  We can display it as plain text with no editing functionality.
   * If the permissions on the generated file were set to read-only when it was created, it would be a read-only file.  Although this might be a nuisance when you want to delete the files.
   * if generated python scripts are not deleted by the Script Generator, when are they deleted?  Are we going to allow them to build up indefinitely?  I imagine they don't take up a lot of space, but I can imagine there being a lot of them after just a few weeks (and it will be impossible to associate them with any given experiment - essentially, once they have been run they become useless).  Perhaps we could delete them at the start of each cycle or each time we update IBEX

**Comment by JamesKingWork** [comment]
Should include squish tests

**Comment by mihai-stfc** [comment]
https://github.com/ISISComputingGroup/ibex_gui/pull/1325

**Comment by rerpha** [comment]
RN: https://github.com/ISISComputingGroup/IBEX/pull/6644
