### ISSUE TITLE
Wiki: Email offensive spellers

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#4211]
As a developer, I want developers to know when they have caused a failure in the wiki checker via bad spelling/unknown word/parsing problems (i.e. unknown unicode character).

**Comment by GRyall** [comment]
1) Some people spell poorly as a result of disability and suggesting them doing so is "offensive" is problematic
2) the wikicheck is run regularly and reviewed at every stand-up.  Either that has been implemented since this ticket, or this ticket is asking for work that is not required. There have been no further requests in the last 5 years so I am closing it.
