### ISSUE TITLE
MIGRATE: 2985-1 SECI->IBEX Galil Backlash

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4232]
As a migrator I want the backlash settings to be correctly converted from SECI. This is s small part of #2985. This is done but needs checking and correcting if needed.

Acceptance Criteria

1. Positive backlash distance is correctly transferred
1. Negative backlash distance is correctly transferred
1. Backlash speeds and accelerations are set as 1/10 of motor speed and accelerations

NB This ticket needs a labview programmer

**Comment by KathrynBaker** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI has information on how SECI deals with this and suggestions on values to use

**Comment by KathrynBaker** [comment]
There is now some new code in LabVIEW Modules/Drivers/GalilDMC2280/Galil - Epics.llb which undertakes this work as well as some of the changes needed for #4231. As such this should be reviewed against the logic listed on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI

When starting on the changes it was realised that in order to make these effectively, and more importantly when needing to make the changes for the remaining corrections that the existing lv code needed some significant refactoring. As such this has increased from 2 points to 5 points this sprint (I have already spent just over 3 on the rough time estimate values).

Note that the existing conversion script is still in place so that the refactor can be verified against what presently occurs, as well as the changes described being in place for BDST, BVEL, BACC for this ticket and OFF for #4231, the different encoder types are still outstanding.

A set of error checking and warning has been introduced for items that are not currently handled well - specifically initialisation code and pre and post move, as well as the situation where both kinds of backlash are specified.

A few repeated values were also limited to only the second value used (_ON_CMD, LIMITTYPE_CMD and HOMETYPE_CMD).

The line preceded by REM has also been removed.

It should be noted if reviewing the refactor with a comparison that the order of set values has changed significantly.

**Comment by KathrynBaker** [comment]
It's probably also worth noting that this can be reviewed by comparing the information in each set of `caputs` output by the original VI and the new one and that the LabVIEW could possibly be treated as a black box, the LabVIEW code has already been pushed to source safe for others to access it.
