### ISSUE TITLE
MIGRATE: 2985-1 SECI->IBEX Galil Deadband and retry

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4234]
As a migrator I want the deadband and retry setting to be correctly converted from SECI. This is s small part of #2985. This is done but needs checking and correcting if needed.

Acceptance Criteria

1. Deadband values should mirror those is SECI
1. If no deadband is set a reasonable deadband shouldbe set in IBEX
1. Rety setting should be set correctly.

**Comment by KathrynBaker** [comment]
There is a level of difference in behaviour here which needs to be verified, and the tool corrected. Estimate a 1 point complexity

**Comment by ThomasLohnert** [comment]
Current behaviour:
- The script will use the `Positional Accuracy` value under SECI as the retry deadband (`.RDBD`) under IBEX. `Positional Accuracy` is described as "The difference in the motor position from the setpoint before it is regarded as an error".
- The script will set the number of retries to 10 in IBEX (via the `.RTRY` field) if `Correct Motion` is ticked in SECI, or to 0 if it is not ticked.

This solution seems a bit rough but not unreasonable to me.

**Comment by KathrynBaker** [comment]
There was a check that there was an encoder present as well before setting the `RTRY` value, but after a brief discussion it seemed that this was valid so has been left in place.

As @ThomasLohnert said, the `positional accuracy` is probably appropriate for `RDBD` as both are in `EGU` and there is probably not enough information to make this any better.

The `SPDB` (Setpoint Deadband) isn't currently set at all, so that has been added.
That change has been made to the LabVIEW and it has been checked into source safe.

The following was added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galils-Under-SECI

```
Deadbands
- `RDBD` is the retry deadband and equates to the `positional accuracy` - both are in the engineering units
- `SPDB` is the setpoint deadband, and equates to the parameter of that name - both are in the engineering units
```

**Comment by KathrynBaker** [comment]
The best way to test is just get the latest version from Source Safe and run it against a galil setup and see that it comes up with the expected outputs.

**Comment by KathrynBaker** [comment]
Consider testing #4233, #4234, #4509, #4510 and #4512 together
