### ISSUE TITLE
Datastreaming: Run forward_epics_to_kafka on all instruments

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4237]
As a developer I would like the forward_epics_to_kafka module to be run on every instrument to be able to better test the datastreaming software. The module requires a >VS2010 build and so is partially blocked by #2830. However, the following can still be done as part of this ticket:
* Ensure that the module will be built and run automatically when we move to >VS2010
* For the time being run the forwarder centrally for all instruments

**Comment by DominicOram** [comment]
Moving this into this sprint as it is a datastreaming milestone to try and get it done for this cycle and I will do it using my datastreaming time. What needs to be done is:
* Confirm the forwarder and the BlockserverToKafka tools both still work
* Get the static 2017 build of the forwarder to deploy as part of IBEX deployment (like the journal parser)
* Get start_ibex_server to also start the forwarder and BlockserverToKafka (likely under procserv)
* Get a kafka topic set up for all instruments

**Comment by ChrisM-S** [comment]
This seems like quite a major addition to all instruments (as I assume once it is in the mid-May release and not on a development branch it will go everywhere)!  Is there a bit more detail available on exactly what function it is performing and why it is necessary to deploy to all rather than a single test instrument?  Does it have measurable Disk, CPU, Memory or network impact?  Can it break? if so could it break a scheduled instrument. What is the back-out plan if there are problems and how will they be detected.

Sorry this sounds a bit negative, I've clearly sat on too many CABs (change advisory boards :smile:) - but it would be worth knowing more about  how this affects the movement of data and control information on the instrument and whether any of this is relevant to the data movement discussion ticket #4258 which doesn't seem to have made it to "Ready" and as a design ticket should probably be a prerequisite of any related deployment.

**Comment by DominicOram** [comment]
This is two processes:
* A process that takes EPICS PVs and forwards them to a Kafka server
* A process to configure this service

I've run them both locally, admittedly a while ago, and they produced no significant load. Importantly this system is not science critical in the slightest, if they appear to produce more load than expected we can kill them remotely with no impact to IBEX at all. I don't see how this is related to #4258 as this produces no data of it's own, merely forwards data from one service to another.

I would like to roll this into being a 'standard' IBEX component and deploy everywhere so that we can start to properly test the datastreaming work. I think the risk is mitigated well enough by a Nagios check and the ability to kill it remotely. Would you rather a different deployment strategy?

**Comment by ChrisM-S** [comment]
So, what I guess I am saying is that for something to go on a critical instrument system next cycle there has to be a good case showing the balance between the **benefit** (to the science being carried out on the instrument) and the **risk** of anything we do (to the science being carried out on the instrument).  In my current self adopted one man CAB role, there are a lot of things I would want to know or see.

-  [ ]   1.  If you were able to start a ticket with:

"As a scientist using instrument <_x_> I would like the `forward_epics_to_kafka` module to be run on my instrument because <_benefit to me/my experiment_>..." we would have a starting point to sell a test of the system to a particular instrument scientist and something to balance any risks against.

-  [ ]   2. Before we roll out, even to one critical instrument however, I would also want to know whether it had been tested on one or more non-critical test instrument systems for a period (for some of the things mentioned above).

-  [ ]   3. What are the _acceptance criteria_ for the data streaming testing you are proposing to do (or group of tests)? - wherever they are carried out.  Can they be satisfied without the need to involve a critical system?

-  [ ]   4. Finally (after understanding more than I do now) I would ask have you considered reading PVs from the instrument to get the information to pass into Kafka from **off** the instrument, this is how we would normally expect control information (block values etc.) to be accessed remotely and what PVs are for.  Doing this, the instrument is protected by the gateway when used in this way and if it is good enough for a remote IBEX client with all functionality and no impact, does Kafka have any need to work in a different way?

As for putting the test on _all_ instruments, because of our regular pre-cycle release method, it is easy to deploy something which is needed, tested and proved onto all instruments very quickly - so why hurry? it's much easier to develop and test a system without a potential down-side of 30-40 instruments with some unanticipated problem.

**Comment by DominicOram** [comment]
After discussion the plan is now to run the BlockserverToKafka python process on all instruments and the forwarder on a central instrument. BlockserverToKafka is a much more lightweight process and so holds much less risk.

**Comment by DominicOram** [comment]
Main PR is at https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/199
