### ISSUE TITLE
Reflectometry: Stop All Motion causes slit vertical/horizontal RBV to change to current values.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4252]
When setting a set point for the vertical  or horizontal gaps and performing a move, using the `Stop All Motion` button results in the RBV changing to the current value.

Example:
![relf_rbv_change.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9a5e1072fac50011b3cedb/125516c66e82c728ace21e0d46fa919625bd91ab99d6bc4ba553f7916b0a65633b0ba92e7391a172fd172d02095d1bff435b5e46fffb8b2aa5b63c778e595def877f4366846c4ff8e7df46f554f832815d84beb68b49c5ec342ce7838e493b18000ac4.gif)

**Comment by ThomasLohnert** [comment]
This is because the SP on the underlying motor actually changes to the readback value when a motor is stopped (I believe there is such a concept as a separate "setpoint" and "final setpoint" in the motor but I'm not sure). The slit gap parameter is designed to be just a wrapper around the motor so it's `RBV`s and `SP:RBV`s mirror those of the underlying PVs. 
So in summary this behaviour is expected (not sure wether it is _desired_ however!)

PS: the demo gif is a nice touch!

**Comment by John-Holt-Tessella** [comment]
See #4307 for setpoint pull up question

**Comment by John-Holt-Tessella** [comment]
Fxied as part of #4307
