### ISSUE TITLE
Upgrade Cluster Machines to Windows 10

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4274]
Look at upgrading 

NDXSELAB
NDADETMON
NDWRENO
NDWVEGAS
NDXDEMO
NDXSCIDEMO

to windows 10. This could be done as an inplace upgrade (offered by cluster management).

**Comment by ChrisM-S** [comment]
I would agree with @FreddieAkeroyd  in being cautious not to upgrade ourselves out of support/test platforms for W7 until all critical systems are off it, I guess one build/test path for W7 and W10 would be ideal so there are no surprises because of changes/patches on one or other system.  Only SELAB has an "instrument machine" and this is probably a good candidate for early adoption of the full W10 new system in a non-critical environment (but not too early!).  The others are all FIT supported so could be upgraded to the Semi-annual W10 almost at any time of choosing (with the option of a backout back to W7 within the 10 day downgrade window if things really didn't work).

**Comment by KathrynBaker** [comment]
Superseded by other work
