### ISSUE TITLE
Sort out CALab niggles for Jasco

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4280]
As a SECI instrument scientist using the CALab wrapper for the JASCO I have difficulties that need fixing. 

1. To start a timed run the timed run button needs pressing and then set all needs to be pressed. Probably also true of the start and stop button.
1. Values seem to be set only after the set is pressed, i.e. you have to press set after every change of a parameter. But there is only a single set button which should do them all. This may be because of the auto-calculated time/volume.
1. Use it with the emulator and make sure it works as expected.

Once done let the CRISP instrument scientist know so the open genie he wrote can be updated.

Acceptance Criteria

1. Runs can be started, stopped and timed without the need to press set
1. More than one parameter can be changed and set at once
1. *Update if you can think of a better way* The volume/time is set separately and will update the time/volume using the calculation in the IOC. (This is two similar requirements)

**Comment by Tom-Willemsen** [comment]
Once this ticket is done, remember to patch the updated VI onto [Offspec](https://github.com/ISISComputingGroup/IBEX/issues/4242), [Polref](https://github.com/ISISComputingGroup/IBEX/issues/4243 ) and [Softmat](https://github.com/ISISComputingGroup/IBEX/issues/4244)

**Comment by KathrynBaker** [comment]
Thanks for the acceptance criteria, except, the set sends everything at once (that has been that cause of multiple reworks on the original ticket), and the use of the set button is a standard for SECI - so are you actually saying "make this run differently to every other SECI driver"? So for criteria 1, we have to go against our standard, 2 is how it should be working on the front panel (it will always work as a set each one for blocks that is how SECI is designed). Or do you just envisage a proliferation of sets?

**Comment by John-Holt-Tessella** [comment]
final chat:

1. Control button not need set good
2. Is as expected (check)
3. Specific 2 set buttons for volumne and time

**Comment by KathrynBaker** [comment]
I've made the changes to the VI and have checked it back into Source Safe - whilst I've found the time to make the changes as follows:
* Start/Stop/Timed no longer need the set button to be pressed
* There is a specific set for volume and time, but they are still included in the set all functionality
Setting multiple parameters from the one set button is typical in this situation, so that has not been changed

I don't have the time to spare to get the Emulator etc. set up and running, so it may fail at that point (not sure how, unless it is unexpected behaviours based on the PVs not actually doing what they imply)

Note that these changes to behaviour will need to be communicated to the users of each system as the item is deployed - with the exception of the start/stop/timed buttons, it isn't actually a change to worry about.

**Comment by ThomasLohnert** [comment]
Checked functionality against device emulator, all looks good. I have deployed the changes to OFFSPEC, POLREF, INTER and SURF so as far as I am aware they should all now be ready to use the Jasco.
