### ISSUE TITLE
IOC: Convert an IOC to Lua

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4288]
As a developer I want an IOC converted to use LUA because it is a nicer language to use to start an IOC.

Acceptance criteria

1. IOC st.cmd uses LUA instead
1. Database is still updated
1. Devsim and rec sim tests still run in the IOC test framework
1. Log is still captured as log file and in the database
1. Errors in missing macros, db files are still reported

**Comment by Alistair-McGann-Tessella** [comment]
I started writing a lua boot script as part of another ticket; I had to stop because it was getting too much work. The issue I came across was that `asynSetOption` was not available to be called from lua.

The remedy to this is by adding this function to the lasynlib.cpp file in core lua. There are other asyn functions already called from this file.

What also needs to be adressed is where our utilities functions for lua scripts will go. I wrote a few functions which are generally useful to all IOC boot files. We decided these would go in the utilities repository so they can be accessed everywhere. I didn't get as far as moving them out of a single lua script though.

The lua script I wrote is on this branch:
https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket4288_sample_lua_code

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/EPICS-lua/pull/2
https://github.com/ISISComputingGroup/EPICS-ioc/pull/433
https://github.com/ISISComputingGroup/EPICS-utilities/pull/12

**Comment by JamesKingWork** [comment]
A lua script is now called from st-common.cmd to run the regular functionality of st-common.cmd

Lua utility scripts now placed in utilities module and used in the st-common.lua 

IocTestFramework tests for oercone pass. However, the code can definitely be cleaned up and not all acceptance criteria are met.

Still to do:
- Launch lua version of st.cmd from cpp main function and do functionality of st.cmd in lua
- Clean up dead code 
- Test against hardware

**Comment by JamesKingWork** [comment]
See new ticket for future work on this issue https://github.com/ISISComputingGroup/IBEX/issues/4811
