### ISSUE TITLE
Find solution for setting macros where both a Mini-Instrument and Instrument are present.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4294]
As a user I would like to be able to set configuration fields on devices when using IBEX vs wrapped CALab for SECI. Both of these point to the same place when looking for this configuration information.

**Comment by Tom-Willemsen** [comment]
The root problem is that some machines, such an NDXSOFTMAT, are being run as both mini-instruments and as full instruments.

Since it is being run as a full instrument, it doesn't have the mini-instrument start up files as usual.

Currently mini-instruments look in globals.txt for their com ports, however we don't typically want to use globals.txt on a full instrument as it overrides the configuration in a hard-to-diagnose way.

This ticket is to come up with a better solution for how to manage settings (e.g. com ports) for CALab wrappers running under SECI, but on a system that can run a full IBEX instrument.

**Comment by KathrynBaker** [comment]
This has just come up as an issue from SOFTMAT - they wanted to talk to the Jasco in SECI.

This isn't just a setting macros issues - it is running the IOC at all as much as anything else.

For something like the Jasco which will only exist in IBEX this isn't actually an issue - run the full instrument and SECI alongside each other - the problem comes if there needs to be interaction with devices that exist in BOTH SECI and IBEX. This should only be an issue where min-insts exist, or on developer machines of systems like SELAB/SOFTMAT - education might be a better solution than trying to manage settings

**Comment by KathrynBaker** [comment]
With all but three instruments now running IBEX this work is no longer required as the migrations will complete before this would be returned to.
