### ISSUE TITLE
Reflectometry: Definition of theta

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4306]
Currently, Theta is calculated as the angle between the sample point and the component it is angled to (e.g. the detector). The position for the latter takes the positional offset parameter into account. This interdependency causes problems, e.g. it means you cannot scan over the detector height.

Change it so that theta is calculated as the angle between the sample point and the beam intercept of the component it is angled to (not taking offsets into account) thus making the values of theta and the offset independent from each other.

In addition, make the readback on the component use the theta setpoint to calculate offset.

Acceptance Criteria

1. Set a positive offset on the detector. Click move:
    1. readback of offset should tick up from zero to offset
    1. theta read back should tick up from negative to setpoint
    1. other components should tick down from positive to their offsets
1. Still with an offset, set a new positive theta. Click move
    1. readback of offset should tick up from new position to setpoint
    1. theta should tick up to set point
    1. other components offsets should remain around 0

**Comment by John-Holt-Tessella** [comment]
Quick example: Staright through beam hits the detector at 0 with an angle of theta. If I set the beam offset for the detector to 1 (and it is 1 away from the sample), Theta should still read 0 not 45 degrees. If I set Theta to 45 deg then detector is now at 2 (theta readback is 45).
If I restart the reflectometer it must "autosave" the offset because it is not recorded in any motor positions. The position of the detector is the beam offset + theta.
