### ISSUE TITLE
Reflectometry: Expose Z Coords of Components as a Parameter

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4331]
As a script writer I want to access the positions of components from a PV so I can use them in my script instead of hard wiring them.  E.g. sample position

### Acceptance Criteria

1. There is a way that I can expose a read-only PV from my configuration file.
1. I can read that read-only parameter from outside.

**Comment by John-Holt-Tessella** [comment]
- https://github.com/ISISComputingGroup/ibex_gui/pull/1008
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/277
- https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/261
- https://github.com/ISISNeutronMuon/InstrumentScripts/pull/46

**Comment by ThomasLohnert** [comment]
It's working well, however I dislike the naming of `ValueParameter` - firstly because it's not very descriptive (every parameter has a value), secondly because it is misleading (these are not instances of `BeamlineParameter`, which is what we usually mean by "Parameter" in the context of the refl IOC)

My suggestion would be to rename as follows:
-  `BeamlineConstant` class instead of `ValueParameter`
-  `Beamline Constants` tab title on OPI instead of `Instrument Values`
- `REFL:CONSTANT:X` PVs instead of `REFL:VALUE:X` 

(something along those lines, maybe you have a better idea)

Plus some minor rework on https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/261 (fix max length of description field)

**Comment by John-Holt-Tessella** [comment]
Add:

```
    beamline_constants = [
        BeamlineConstant("S1_Z", z_s1, "Slit 1 z position"),
        BeamlineConstant("S2_Z", z_s2, "Slit 2 z position"),
        BeamlineConstant("SM_Z", z_sm, "Super mirror z position"),
        BeamlineConstant("S3_Z", z_s3, "Slit 3 z position"),
        BeamlineConstant("S4_Z", z_s4, "Slit 4 z position"),
        BeamlineConstant("PD_Z", z_point_detector, "Point detector z position"),
        BeamlineConstant("MD_Z", z_multi_detector, "Multi-detector z position"),
        BeamlineConstant("S3_MAX", 30, "Maximum S3 opening size"),
        BeamlineConstant("S4_MAX", 30, "Maximum S4 opening size"),
        BeamlineConstant("MAX_THETA", 4, "Maximum Theta value"),
        BeamlineConstant("NATURAL_ANGLE", 1.3, "Natural angle of the beam"),
        BeamlineConstant("HAS_HEIGHT2", "NO", "YES if has second height stage, NO otherwise")]
```
