### ISSUE TITLE
GUI: Set OPI size on OPI open

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4332]
As a MUONFE instrument scientist, I would like an OPI when opened from the synoptic or device screens to open so I can see the whole of the OPI. This is particularly important on a small screen for MuonFE, but I think this will also be important for Reflectometry front panel.

**Comment by Tom-Willemsen** [comment]
It is easy to get CS-Studio to zoom the OPI so that it fits into the space it's been given (this is an option exposed in the CSS GUI when building an OPI). Of course, if the OPI is too big and the space given is too small, it will be shrunk to the point where it unreadable.

It will be tricky to open different sized eclipse views based on the contents of an OPI. We could just make the default size of the OPI view bigger.

**Comment by John-Holt-Tessella** [comment]
I meant instead of showing this:

![image](https://user-images.githubusercontent.com/7570055/57460510-289eac80-726d-11e9-9922-105b35b0f61f.png)

it shows:

![image](https://user-images.githubusercontent.com/7570055/57460535-33f1d800-726d-11e9-842c-98e877b3bc1d.png)

**Comment by davidkeymer** [comment]
Is there a method (or option) to _only_ zoom _in_ to fill the available space so that the OPI is never shrunk and made illegible?

**Comment by Tom-Willemsen** [comment]
- Reflectometry has an entire perspective devoted to it so that it can size appropriately
- MFE opi fits within bounds on a standard-size screen
- I think it's highly unlikely we'd do this before new gui anyway - so closing
