### ISSUE TITLE
Danfysik: Danfysik bug fixes

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4355]
There are several bugs in the Danfysik IOC which need to be addressed.

- [ ] Calibrated danfysiks send a field value of zero when restarting the IOC. This will cause confusion if the IOC is rebooted while the magnet is on.
- [x] The scaling for a calibrated danfysik is not applied correctly. In the `Field` records there are magic numbers (1000000) which have to be removed/replaced to get the values to scale properly.
- [x] The OPI for the calibrated danfysik displays the field as an integer, this should be a float (at least for Tesla units)
- [x] Calibrated danfysiks lose their field units when the IOC is rebooted
- [x] LOQ needs to have a DRVH field on the RAW:SP record. This needs to be set at 750000. It should be able to be set via macro
- [x] The 8500 series OPI needs to display its interlocks (should be the same as an 8000 series)

**Comment by kjwoodsISIS** [comment]
Are these bug fixes specific to the LOQ Danfysik? (well, the 5th item is obviously specific to LOQ.)  Or do they apply more generally?

**Comment by Tom-Willemsen** [comment]
They are specific to calibrated danfysiks. I'm not sure calibrated danfysiks are in use on IBEX instruments anywhere except LOQ at present.

**Comment by kjwoodsISIS** [comment]
Can we manage calibrated and non-calibrated Danfysiks in a single IOC?

**Comment by Tom-Willemsen** [comment]
Yes, we do.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/386/files
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/188
- https://github.com/ISISComputingGroup/ibex_gui/pull/890

Bugs at top of ticket:
1. I think this needs a separate ticket. I believe it is caused by one of the UNLOCK/REM commands which we currently send at startup. It is general to all danfysiks and would need some testing on real hardware and making sure it doesn't adversely affect other danfysik users. I think we decided on a solution in point 11 of our [decision log](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Decision-Log) i'll create a ticket to implement and test this specifically.
1. I've made changes to the calibrated danfysik db to make it consistent with what is tested & working on LOQ while still being generic. I don't believe any other beamline is using danfysiks in calibrated mode, so this change should not affect any other beamline.
1. Precision of PVs set in PRs above.
1. Units are autosaved in PRs above.
1. Added a macro for maximum raw setpoint in PRs above. Macro defaults to 1000000 (100% of full scale). I have set this macro in LOQ's `globals.txt`, so when they get the next IBEX version they will not need any upgrade.
1. Interlocks displayed in PRs above

**Comment by kjwoodsISIS** [comment]
How many points was this?
