### ISSUE TITLE
HIFI Cryomag: Test the Keithley 2700 IOC connected directly to the device

### ISSUE THREAD

**Issue by LiamPanchaud** [ISISComputingGroup/IBEX#4368]
Testing the K2700 IOC on Sci Demo failed after communications repeatedly desynced. 

A similar problem was observed when testing with the K2700 device in the office via MOXA, but the issue ceased when connected directly to a developer machine via USB to serial. 

This requires an IBEX installation on NDXHIFI_CRYOMAG.

Acceptance criteria:
* [ ] Tested the IOC on a machine connected directly to the device

**Comment by kjwoodsISIS** [comment]
Direct connection is fine for testing purposes, but what happens when the system goes into production?  Are we still expecting the Keithley 2700 to be connected via a MOXA?  We should try to understand why we have these problems connecting the Keithley 2700 via a MOXA.  Perhaps this investigation should be the subject of a separate ticket.

**Comment by KathrynBaker** [comment]
The HIFI_CRYOMAG system does NOT use a MOXA, for just this kind of reason – we do not want the network involved in the control of a cryomagnet. A separate ticket to get the K2700 working via a MOXA will be of interest to IBEX, but not to the HIFI Cryomag work.

**Comment by kjwoodsISIS** [comment]
Ah!  OK.  So all devices are directly connected to the HIFI Cryomag control PC?

**Comment by KathrynBaker** [comment]
Yes, USB or USB to serial at most

**Comment by John-Holt-Tessella** [comment]
impeded until computer purchased

**Comment by ChrisM-S** [comment]
The computer is purchased and has been for some time.  I missed this dependency during our planning meeting or I would have mentioned it!  This ticket does however depend on controls ticket [#415](https://github.com/ISISComputingGroup/ControlsWork/issues/415) which itself is dependent on the requirement to use the new Windows 10 clone on the system rather than the existing tested W7 clone.  The only significant pre-requirement is that it is possible to get into a regular cycle of IBEX and system VHD updates (facilitated by #4415) _before_ the delivery date of the system to users/cryogenic testing.

It looks like this ticket has not been "pointed" but if it is likely to be holding up a task which should be done this sprint I will simply push [#415](https://github.com/ISISComputingGroup/ControlsWork/issues/415) before other systems work.

**Comment by John-Holt-Tessella** [comment]
Since you only need the release version of the IBEX vhd as a stop gap I can create you a set for release 5.4.1.
If I can I will do this as a script but don't let this stop you generating the machine. If you would do it now I will generate it today.

**Comment by ChrisColeExpControl** [comment]
Initial testing returned with an error where the IOC would no longer complete the processing of readings after roughly 1 day of operation. After a fix is implemented further testing would be desired.

**Comment by FreddieAkeroyd** [comment]
Just to confirm, talking via usb to serial never shows an issue, this is only shown via moxa?

**Comment by ChrisColeExpControl** [comment]
this was an inherent issue with the IOC, typing up in another ticket now

**Comment by John-Holt-Tessella** [comment]
Still impeded?

**Comment by ChrisColeExpControl** [comment]
Upon testing, no issues were found with this IOC, however the CP2800 was found not to be communicating correctly with its IOC. a separate ticket to fix this is found here: #5823
