### ISSUE TITLE
SUPPORT: Comms error

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4376]
Power supplies on RIKENFE stopped communicating on com6. We tried:

- rebooting IOC (no effect)
- restarting the moxa (no effect)
- restarting the PC (this worked)

The outcome is that scientists would like a way of doing this as a last resort (esp during unsupported hours)

Acceptance Criteria

1. Communication is reestablished
1. Reboot script has been given with instructions to the muon group
1. The question has been asked if everyone else wants this.

**Comment by ChrisM-S** [comment]
With regard to (3) we should be careful to ask/supply what people need (not necessarily what they want!).  There are plenty of situations where a reboot will be tried in extremis for the wrong problem and guarantee no more data taking until support becomes available.

Also, there is a document here, issued in response to a similar general request. The process and reboot script are on all instruments and although hardware details need updating, is still probably a good place to start.

http://www.facilities.rl.ac.uk/isis/computing/instruments/Instrument%20Documents/Instrument%20Control%20Computers%20First%20Aid.doc

The main thing is it encourages some thought and an element of triage before carrying out a reboot in response to anything that doesn't seem to work.

**Comment by John-Holt-Tessella** [comment]
I will just forward this link on. How do you find this link?

**Comment by ChrisM-S** [comment]
Sorry, I should have given you the link for the more friendly the top page for the instrument systems site rather than the long direct link.

http://www.facilities.rl.ac.uk/isis/computing/instruments

The documents are a bit down the page, there are not that many in there but it’s not a bad place for them.  It’s also the friendly page for current for instrument hardware details.

**Comment by John-Holt-Tessella** [comment]
This does not seem to be a user-facing page. Should we copy the info from the link to the user manual and them delete it from sharepoint?

**Comment by KathrynBaker** [comment]
This computing first aid document is meant to be one for us when receiving a support call, I’m not sure this should be on a user facing page, and as it goes out of date too quickly is not something I’d want to be maintaining in the public (not just non-computing, but all the world like this ticket) domain.

For the issue seen here, only part 1 is needed, and this should be provided as a script that can be accessed in the same way.

**Comment by ChrisM-S** [comment]
Yes, this was meant for (and sent to) **all** instrument scientists at the request of the instrument control advisory group at the time (or IDG, can't remember which now).  This was not meant for users.
The difference being that the instrument scientists have a reasonable right to (in extremis) to know how to restart the machines out of hours if necessary and they are (hopefully) responsible for what they do and for any beam time they might lose.

The original email was sent because people did not know how to safely re-start a rack mounted server with a cover which was tricky to remove and a less than obvious power button.  I wouldn't put this in a public manual  so I think the existing location should be kept unless we establish a private wiki where we would could be a bit more helpful in terms of local details, contacts phone numbers photos of instrument computer location etc.

**Comment by John-Holt-Tessella** [comment]
Does this mean that this document should be in the instrument scientist (https://github.com/ISISComputingGroup/IBEX/wiki) or developer wiki (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki) and then this link is sent to instrument scienitsts?

**Comment by John-Holt-Tessella** [comment]
Feels like this is another instance of stuck ports? Do we think this is fixed?

**Comment by Tom-Willemsen** [comment]
Yes.

**Comment by FreddieAkeroyd** [comment]
Hopefully fixed by #4435
