### ISSUE TITLE
Lost Central Services PVs

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4387]
At ~8:00 the various beam status PVs served centrally started reporting incorrect values (mostly zeroes) for some PVs. This caused various instruments that had run control enabled to go into waiting states. The PVs were restored at ~12:00 and the fault was discovered to be on the accelerator side. Given that this was a problem that effected all instruments in a potentially serious way we should discuss what we could learn from this incident. Specifically:
* Could the accelerator team have been automatically notified of this issue?
* Could we have better communicated the issue to scientists?
* Do we have gaps in our knowledge of how to support this part of the system?

**Comment by Kevin-Woods-Tessella** [comment]
Is this also related to #4383?

**Comment by John-Holt-Tessella** [comment]
I don't believe so.

**Comment by Tom-Willemsen** [comment]
This is in the ready column, but it's not immediately clear what work needs doing.

Is this ticket a meeting to discuss the points above?

**Comment by Tom-Willemsen** [comment]
After checking with @John-Holt-Tessella this is a meeting.

Email sent

**Comment by FreddieAkeroyd** [comment]
I've just had a meeting with Ivan Finch from the accelerator side:
- our process runs on their "hot spare" server as their others are quite loaded, however the problem is that if the accelerator databases we read that are replicated on the hot spare stop updating we may be the only people to notice
- they are setting up an MQTT bases system to provide information, I am getting details and this could provide an alternative/backup route for us.
- I've had clarification of login details for the computer running our current server that I will share separately, however the process is set to restart automatically when there are issues so there is often not much to gain from logging into this machine other than confirm there is a problem and notify controls computing

**Comment by Tom-Willemsen** [comment]
Meeting scheduled 11/7/2019 13:30

**Comment by FreddieAkeroyd** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beam-Status,-Shutter,-accelerator-information

**Comment by FreddieAkeroyd** [comment]
I will also see if there is a better reporting mechanism that a list of email addresses

**Comment by FreddieAkeroyd** [comment]
Currrently PVS are aliases via a gateway, an intermediate IOC would give us more control, work with run control and also let us determine failover better

**Comment by DominicOram** [comment]
Based on the conversation yesterday I have:
- Added some additional documentation to the link Freddie provided
- Added a brief note on the wiki to remind people to email all scientists if required (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/On-Call-Guidance)
- Created (https://github.com/ISISComputingGroup/IBEX/issues/4530)
