### ISSUE TITLE
GUI: Reduce CPU usage

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4398]
As a user i would like the client to be as responsive as possible and not too take up too much resource. Currently GUIs tend to split there time in thirds:

![image](https://user-images.githubusercontent.com/10086797/59025394-fa03f980-884b-11e9-8b70-12acd09545f2.png)

We should attempt to reduce some of this time. The poller may be the best place to start as this is somewhat more under our control.

**Comment by Tom-Willemsen** [comment]
These 3 are a bit misleading in VisualVM - they show up as "using a lot of CPU" but really they're blocked in native system calls doing I/O (in the case of ZMQ and CAJ) or sleeping / waiting for windows events (in the case of `WaitMessage`), and not really using any CPU cycles - but visualvm doesn't know that, because from visualvm's perspective it is just a call into C code that is taking a long time.

---

We have found and fixed a number of other CPU issues since this ticket was written.

---

Closing
