### ISSUE TITLE
JASCO: Feedback from User

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4425]
As a OFFSPEC instrument scientist I would like the following fixed/answered in the SECI Vi:

1. ABCD - Use D as a cal for the others should all add up to 100%. Instead of autocalc D.
1. If A, B or C > 100 then it locks out of boxes without an error (not quite clear what the error is reproduce (ask NS))
1. Readback, setpoint and value are confusing, ideally two values. Maybe an explanation needed on Vi.
1. On boot the inital min and max pressure are 0 which when pressing set get sent to JASCO these should be autoremember or set from read points. Make sure the values are populated in IOC
1. Timed and start  don't make sense. We want:
    - Pump for time (which uses the time value)
    - Pump for volume (which uses the volume value)
    - Pump for ever
1. Set set pump for volume you need to press the "set time" button
1. If it loses Comms background should go red. [#4403]
1. Layout to be similar to Jasco OPI (Involve CK from POLREF in this)

**Comment by KathrynBaker** [comment]
Just as an instinctive response,


1)      Should be possible

2)      Should be possible

3)      Should be possible

4)      Auto remember is NOT done in SECI/LabVIEW – we can read from the device for the LabVIEW side, but the decision for IOCs is that we don’t populate setpoints with readbacks at the moment as this is too hard – so this needs greater discussion

5)      This is a mimic of the IOC – so changes will need to occur in both places – please break this out into an appropriate ticket

6)      This is probably a minor wiring issue

7)      It will if it loses comms to the IOC – there is a separate ticket to cover this issue already

8)      Layout is a SECI layout rather than the OPI – OPI layouts have a different style and the need for the various set buttons means that we cannot match the layout that closely

**Comment by FreddieAkeroyd** [comment]
4) can we autosave but not set PINI? Or use @init in stream device? Or even asyn:READBACK if that is appropriate.

**Comment by kjwoodsISIS** [comment]
Regarding point 1.  above - see #4283

**Comment by John-Holt-Tessella** [comment]
Do the alarms: 1 point

**Comment by aaron-long** [comment]
+1 SURF/CRISP

**Comment by davidkeymer** [comment]
While working on #4403, I have addressed points 2, 3, 5, 6, and 7 from above.  Although I haven't replicated the style of the OPI (point 8), I have tidied up the layout.  I've also added a 'Restart IOC' button, which the other CALab VIs have.

**Comment by davidkeymer** [comment]
To address point 1, I have added a calculation and indicator for the D component.  The IOC and device will still not allow setting of this manually, but it gives the value that the device _will_ calculate itself and use (when asked to pump).

To address point 4, I have added an initial read of the setpoints from the IOC and populated the controls before the main loop is entered.

**Comment by davidkeymer** [comment]
As per the IOC/OPI, I've also added readbacks for `Last input error` and `Device error`, along with buttons for `Reset Error` and `Reset Pump`.

**Comment by kjwoodsISIS** [comment]
This ticket has been in "review" since 5th September.  What value is being served by having it remain in "review" for this period of time?  We should expedite its review.

**Comment by John-Holt-Tessella** [comment]
Review:

1. concentration for component D should not be absolutes, let it go negative if it is negative. Can you make the box red if it is negative?
![image](https://user-images.githubusercontent.com/7570055/71677967-ec7c0700-2d7b-11ea-994d-078e5d5fd53f.png)

2. If the concentrations add to >100 what is the pump meant to do? The emulator suggests it will pump -ve concentration D that can't be right. Ask @aaron-long 
3. "Current values" rather than "returned values" I think, unless this is a SECI thing. Should we add a tip strip to the boxes (or is this a 2016 thing). Also "setpoint readbacks" instead of "setpoints readback"
4. Once in error pressing the reset button shows:
![image](https://user-images.githubusercontent.com/7570055/71679341-429e7980-2d7f-11ea-9471-8919ef9439ee.png)
clicking ok does nothing. 
5. "Device error" is cleared on error so can't see its value message says something strange. Is this right?
![image](https://user-images.githubusercontent.com/7570055/71679411-711c5480-2d7f-11ea-82ce-a629eaf84083.png)
Error was created with: `C:\Instrument\Apps\Python\python.exe C:\Instrument\Apps\Python\scripts\lewis-control.exe -r 127.0.0.1:60813 device error 4`

and

`C:\Instrument\Apps\Python\python.exe C:\Instrument\Apps\Python\scripts\lewis-control.exe -r 127.0.0.1:60813 device input_correct False`

**Comment by John-Holt-Tessella** [comment]
Sorry this has taken so long to review

**Comment by davidkeymer** [comment]
1. Box has red background when concentration -ve.
1. [Ticket](https://github.com/ISISComputingGroup/IBEX/issues/5427) created to investigate behaviour of hardware.
1. Columns renamed.
1. Believed dialogue box only appears when VI is _not_ running within SECI.  Messages are queued and diverted to separate perspective when VI is run in a SECI configuration.
1. Error messages remain in boxes. Emulator backdoor variable `device error 4` cleared with `Reset Error` button on VI. `input_correct` error not possible to clear due to lack of logic in emulator.  **NB** VI will occasionally "go red" on initial detection of errors, but will display correctly after internal 30s timer rereads state and re-enables control.

**Comment by davidkeymer** [comment]
VI located in usual place: `C:\LabVIEW Modules\Drivers\Jasco PU-4180 HPLC Pump\Jasco HPLC Pump - System.llb\Jasco HPLC Pump - Front Panel.vi`
