### ISSUE TITLE
Project board: Automate labels and columns

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4438]
As a developer I would like the project board to be somewhat automated for menial tasks.

## Acceptance Criteria
* The appropriate label should be added when a ticket is either moved into the column or periodically
* The ticket should move into the appropriate column either when the appropriate label is added (bear in mind there may be multiple boards that this is required on) or periodically
* There is sufficient documentation on the wiki on how to maintain this
* Wiki is updated to reflect that manually adding labels is no longer part of the workflow

**Comment by FreddieAkeroyd** [comment]
I had been thinking about this in the wider context - only just noticed there was a ticket. Useful things I had found in the wider workflow context were:

* https://github.com/apps/project-bot
* https://help.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events
* https://github.com/actions/labeler
* Issue States app at https://probot.github.io/

**Comment by RaiBishal** [comment]
> * The ticket should move into the appropriate column either when the appropriate label is added (bear in mind there may be multiple boards that this is required on) or periodically

All the GitHub actions available in the marketplace for card automation features like this seem to offer something similar but not exactly what we want. 

The action will move the card into the appropriate column when the appropriate label is added however it will only move it to a specified project in the `workflow` file. 

If a card in the `Reflectometry` project is moved to `In progress` within the project, this action will move the card to whatever project is specified in the `workflow` file. This is an issue because we actually only want to move the card to the projects that it is already assigned to.

 This is the limitation for all the card automation actions currently. An issue is however open for this feature https://github.com/alex-page/github-project-automation-plus/issues/46.

**Comment by RaiBishal** [comment]
To review:
- Move cards between columns in IBEX project and see if labels are added/removed appropriately.
- Check https://github.com/ISISComputingGroup/IBEX/actions has not workflow errors

**Comment by rerpha** [comment]
Awesome, works brilliantly.
