### ISSUE TITLE
VESUVIO: configure furnace

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4483]
There is a furnace (RAL furnace 4) experiment on VESUVIO on Thursday, they would like to configure IBEX on beamoff day (Wednesday). It should just be a eurotherm to configure.

Contact: Matthew

**Comment by Tom-Willemsen** [comment]
Email sent to scientist

**Comment by Tom-Willemsen** [comment]
Configured on vesuvio:
- Standard beamline eurotherm with 2 sensors rather than their usual 3 - created a new config and synoptic on vesuvio for this setup
- Both sensors are using `K.txt` calibration file
- Both sensors are using a PID table, `ral4.txt`, copied over from some printed documentation on furnace parameters
