### ISSUE TITLE
Run control: Allow user to specify behaviour on connection lost

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4530]
As a user I would like to be able to choose whether I continue taking data if I lose connection to a PV that I have runcontrol on. This ticket originated from https://github.com/ISISComputingGroup/IBEX/issues/4387. The worry is that most instruments have runcontrol on the beam status such that they will stop taking data if there is no beam. If we are incorrectly reporting the beam status they could stop taking data despite having beam.

Acceptance Criteria
============
- There is a checkbox in the GUI that says `ignore runcontrol on connection error`
- If this is ticked the runcontrol IOC will ignore a PV if it goes into disconnection error.

**Comment by FreddieAkeroyd** [comment]
I just wanted to clarify the reference to #4387 - the description there suggested the PVs showed incorrect values, or was that as a result of the pv becoming disconnect over channel access? Or by "disconnected" did you mean the general case of a PV giving a communication alarm because it could not read the associated hardware? The beam PVs may be a slightly odd case - they are read in a loop and the server restarts if it gets too many read errors, there is a gateway in between so depending on the restart frequency I'm not sure what PVs state might show. If we use a proxy as per #4528 we can control the behaviour here a bit better, but that still leaves the general question of what to do if you have run control on a device and the IOC cannot read from the device.

**Comment by DominicOram** [comment]
I think, like you said there are two issues here:
* The beam current should show as disconnected if we don't trust what we're reading (If not already covered then hopefully covered in #4528)
* Run control should do something sensible on this state. Covered by this ticket.

**Comment by DominicOram** [comment]
Fixed by https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/254
