### ISSUE TITLE
Support: RIKENFE - GUI freezing periodically 

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#4538]
Support call on RIKENFE. Scientists noticed that since trying to use the IBEX GUI client in the morning that it would freeze after performing most actions (eg change perspective, run script). The pc’s performance was nominal and showed no signs of over utilisation. Elements in the GUI (real time values) would update during the unresponsive client freezes.

- The client was restarted but the freezes persisted. 
- Another Java application was tested and would not run.
- The IBEX server was restarted and the freezes seemed to stop. And the additional java application was tested and it ran correctly.
- Client logs seemed normal.
- Freddie, Dom checked the logs for the host pc and IBEX server and it seemed okay.

**Comment by Tom-Willemsen** [comment]
There doesn't seem to be anything much to review here.

We made our best effort at diagnosis, but because we were unable to load up java visual vm, this is limited. Something in the server side may have been hogging some resource - but this was neither CPU nor memory as these both looked ok from task manager.
