### ISSUE TITLE
SANS2D: Minimum Baffle/Detector Intervals

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4587]
As a SANS2D scientist, I want IBEX to respect the minimum permissable distances (intervals) between the detectors and baffles, so that the detectors and baffles do not collide.

#### Acceptance Criteria

1. Front Detector-Front Baffle Interval: minimum is 1050 mm.
1. Front Baffle-Rear Baffle Interval: minimum is 210 mm.
1. Rear Baffle-Rear Detector Interval: minimum is 350 mm.
1. The IBEX GUI should warn me if I set detector/baffle to positions which violate these limits.
   * the intervals should be calculated from the detector & baffle positions
1. I can use the IBEX GUI to set the detector & baffles positions in any order.
   * **Note:** in SECI the detector & baffles positions have to be entered in a specific order (which confuses users).
1. The interval limits should be configurable, but this is not an action often required. i.e. having a PV that we can put a new value into, which is autosaved is probably a good solution
1. There should be 6 rules which stop a detector moving if:
    - interval between the object and the next object is less than the minimum
    - AND the direction of travel will make the interval smaller (i.e. we allow movement from a distance which is too small to one which is too large) An important test is put 3 objects closer than the minimum distance I should only be able to move the end ones away from the others. I should not be able to move the middle one.
    - rules are stop 1 if 1<->2 is too small, stop 2 if 1<->2 is too small, stop 2 if 2<->3 is too small, stop 3 if <2-3> is too small etc.
   - See notes below for a _suggested_ algorithm.
1. Using manager mode I can turn off the automatic stopping in case I get into a position that I can't get out of for some reason.
1. CAM should not be used but there is documentation of why it couldn't be used.

#### Notes
1. For the avoidance of doubt, this ticket is all about preventing clashes between baffles and detector trolleys.
   * the solution described above has been used on SECI for some time and works well, we should reproduce it  in IBEX, because it is proven and the scientists are familiar with it.
   * yes, we do have the CAM system, but the solution described above is simpler; a solution based on the CAM system can be considered at a later date.
1. This ticket is a sub-ticket of #4576.
1. The distances defined above have been measured on SANS2D.  It has been confirmed that they prevent collisions.
   * While it will be useful to define the minimum distances as configurable items, the expectation is that they will not change frequently.
1. Scientists prefer to enter all the detector/baffle positions, check that the intervals are valid (i.e. do not violate the minimum values) and only then press the "Move All" button (see #4577).
1. Check the paragraph describing the Clash Prevention in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.
   * **Note:** take special note of the comments about speed, acceleration, deceleration & homing of the detector & baffle trolleys.
1. Here is a _suggested_ [algorithm for managing the movement of the baffles & detectors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Algorithm%20for%20Permitting%20Movements%20of%20Items%20in%20SANS2D%20Vacuum%20Tank.docx).

**Comment by DominicOram** [comment]
Given that we decided `Move All` was not a requirement (https://github.com/ISISComputingGroup/IBEX/issues/5499) this ticket will need some more thought about how we complete it. Specifically we need to think about the cases where one item is in motion and I try to move another. It may be that the simplest solution for this is still do the `Move All` functionality. In that case though we will still have to be careful to make sure that the speeds of the items are similar enough that one will not catch up to another and collide.

**Comment by DominicOram** [comment]
As @Kevin-Woods-Tessella wrote on https://github.com/ISISComputingGroup/IBEX/issues/5499 the solution may change to be:

> To mitigate the risk of clashes in the Vacuum Tank (without implementing a delayed Move command), I have specified that the new OPI displays and continuously updates the distance between the detectors and baffles (see #4580). The Instrument Scientist has provided me with the minimum allowable distances between the various detectors & baffles - the system should stop if any of the distances reaches the minimum value. The system can also warn the user if the detectors/baffles are getting too close. In case you are wondering, the minimum distances do allow for the distance required to decelerate and come to a stop. The distances are specified in #4587.

This is pretty much exactly how the CAM works so it may be that if we implement this solution we should do it using the CAM.

**Comment by kjwoodsISIS** [comment]
I would prefer that we implement the simple solution described above (at least initially).  IIRC, when  we used the CAM system on ZOOM, it took a lot of adjustment to get it right.  I don't want to lose time adjusting the CAM system on SANS2D when a simple solution is available.

**Comment by kjwoodsISIS** [comment]
@JamesKingWork - can you please check the speeds at which the detectors & baffles move and let us know the result.  Thanks.

**Comment by DominicOram** [comment]
> I would prefer that we implement the simple solution described above

Which solution are you referring to? The solution in the original ticket requires `Move All`. The solution that you proposed on #5499 is reproducing the functionality of the CAM.

**Comment by JamesKingWork** [comment]
According to SECI the speeds for both detectors in the Z-axis is 4096 and the acceleration/deceleration is 2048. Both baffle's z axes have a speed of 14305 and an acceleration/deceleration of 5120. The motors use mm, but I can not seem to find a unit for the speed, maybe mm/sec as IBEX suggests it uses. Does this sound reasonable?

**Comment by KathrynBaker** [comment]
For reference, speed, acceleration, and deceleration in SECI are not in any form of unit for the Galil, as the Galil itself doesn't consider them as a unit as such. There is maths undertaken on conversion to go from what is used in SECI to the unit/sec, or unit/sec-squared of the motor record. So to make sense of those numbers we need the resolution as well as the numbers in those fields.

**Comment by kjwoodsISIS** [comment]
We can go a long way on this ticket without implementing `Move All`.  If I set one of the detectors or baffles moving, the intervals will update.  If the requested setpoint will produce an invalid interval, then we can display a red box around the interval field.  Similarly, if I start one baffle/detector moving and then start another, the interval fields will again update.
Admittedly, this is not the same as having everything remaining stationary until the `Move All` button is pressed, but does provide clear feedback that the requested interval is invalid.
Once we have a basic mechanism in place to warn users of invalid intervals, we can go back at a later date to implement more desirable solutions (like `Move All`).

**Comment by KathrynBaker** [comment]
That update based on interval is what the CAM does, or at least it's what I thought it does, and seems to be what @DominicOram  thinks it does too. At the moment I think that simple solution described is all that the CAM does at the moment.

**Comment by kjwoodsISIS** [comment]
But the CAM solution requires a lot of adjustment to get the intervals right (that's what I recall from ZOOM - see comment above).  I don't want us losing time fiddling with the CAM system, especially when we have to work remotely.

**Comment by KathrynBaker** [comment]
But can you guarantee that implementing another solution won't require the same levels of adjustment? 

#5494 if it is generic enough would solve this problem too, and that discussion pointed out other things that might do the job or at least parts of it (some of the run control/alarm related items, the inhibitor), because at heart the issue is the same. if Parameter A (the distance between the items) is out of tolerance, then don't allow parameter B (in motion/start move) to be set, or put it to a safe value (stop). We can use the alarm mechanism for the tolerances, and stopping motion is exactly what the inhibitor is meant to do. The CAM is meant to consider the ranges of motion and collision opportunities, and include the limits of motion in the thinking as well/

**Comment by KathrynBaker** [comment]
It's also worth remembering on ZOOM, it was the first time the CAM had been used with actual hardware on a beamline, so depending on the adjustments made it might not be an issue for re-using it now that they have been done once - if it was changes to code, they have been completed, if it was changing to settings, are we sure that wasn't new system commissioning?

**Comment by kjwoodsISIS** [comment]
No, I can't guarantee that the interval solution proposed in #4580 won't require similar levels of adjustment, but it is a much simpler solution than the CAM solution, so I think there is far greater chance that it will require less adjustment.

**Comment by DominicOram** [comment]
Looking over the discussion of the CAM (https://github.com/ISISComputingGroup/IBEX/issues/2936) the major issue seemed to be what distance to set the parameters such that they have enough clearance to decelerate to a stop. We already have these numbers for SANS2D, as you said above:

> In case you are wondering, the minimum distances do allow for the distance required to decelerate and come to a stop.

I think at a worst case the two solutions will take the same amount of time to implement and given we would want to replace any bespoke solution with the CAM at a later date anyway then it seems sensible to put the time into the CAM rather than something new.

A good solution might be a very small (0.5 day) timebox to investigate whether the CAM works for this, if it doesn't appear to easily work then we can re-evaluate?

**Comment by kjwoodsISIS** [comment]
@KathrynBaker  - following [James's updates to his comment](https://github.com/ISISComputingGroup/IBEX/issues/4587#issuecomment-654181466), do we now have enough information to calculate the speed of the detectors & baffles?  Is the calculation documented anywhere?

**Comment by KathrynBaker** [comment]
The equations are done as part of the convert routine in the motor settings script generator, it isn't explicitly documented anywhere other than that code at present - I'm pulling it up to detail it in a comment here

**Comment by KathrynBaker** [comment]
I'll use the motor record fields for the EPICS side of things and the names for the SECI side of things:

`MTR.VELO = Speed ÷ Motor Steps per unit`
`MTR.ACCL = Speed ÷ Acceleration`

**Comment by DominicOram** [comment]
Just to elaborate a little those equations basically come from the different units used in each. In SECI (and internally in the galil):
```
[Velocity]=steps/s
[Acceleration]=steps/s^2
```
In the motor record (and therefore in IBEX):
```
[Velocity]=_units_/s
[Acceleration]=time_to_full_speed
```
Where `_units_` depend on the setup but are usually `mm` or `degrees`. These are documented on the [official motor record docs](https://epics.anl.gov/bcda/synApps/motor/motorRecord.html)

**Comment by FreddieAkeroyd** [comment]
Do we always set MTR.VBAS=0 as MTR.ACCL = time from MTR.VBAS to MTR.VELO

**Comment by KathrynBaker** [comment]
I don't think we explicitly set `.VBAS`, so that will be the default of 0 usually

**Comment by DominicOram** [comment]
Yes, it's set to 0 (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil-default-parameters)

**Comment by DominicOram** [comment]
Note that the CAM uses bits of genie_python but also runs in Python 2, we should confirm this works ok.

**Comment by DominicOram** [comment]
In a meeting with @Kevin-Woods-Tessella, @KathrynBaker, @John-Holt-Tessella, @Alistair-McGann-Tessella, @JamesKingWork and myself the following plan was decided for this ticket:
* Warn the user in an obvious way if the setpoints put you in a state where you will collide (This should be a warning so that I'm not forced to move things in a specific order)
* Timebox half a day to investigate the CAM, attempt to configure it for this problem and test if it works correctly
* If the CAM does not look like it will work easily implement the logic to stop the motors if the readbacks of positions are about to collide

**Comment by DominicOram** [comment]
I successfully configured the CAM for this problem in this branch https://github.com/ISISComputingGroup/EPICS-inst_servers/tree/Ticket4587_minimum_intervals. It will stop any collisions but has the following issues:
* By moving two objects towards each other you can get just within the above limits before it comes to a stop, this is likely fine as we have enough room for the deceleration. However, when inside these limits the CAM will halt all motion and not let you move the items apart again. This same issue will exist in any other solution we come up with, so we should be careful that you can get out once within the limits
* The CAM is a little conservative, e.g. it sets limits to only allow you to get to 1080 mm gap rather than 1050 mm, if this is a major issue we can tweak the limits to be a bit tighter
* The feedback isn't great, it's not obvious why you can't set the limits so we will require some additions to the OPI to make this clearer

**Comment by Tom-Willemsen** [comment]
See fast deceleration galil code in `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Galil`

**Comment by DominicOram** [comment]
After another discussion with @John-Holt-Tessella, @Kevin-Woods-Tessella, @davidkeymer and @JamesKingWork it was decided that we do the following:
* Implement a solution in the DB logic rather than the CAM
* The logic will need to have a rule of stop if the gap is too small and if the direction of motion will cause the gap to lessen. There will need to be 6 such rules, one each for the dectectors and two each for the baffles.
* There should be a way for an instrument scientist in manager mode to turn off these checks and force movements if they want to

Although I started this ticket by looking at the CAM I encourage others to pick it up instead.

**Comment by John-Holt-Tessella** [comment]
@DominicOram could we note down somewhere why the CAM was not acceptable as a solution because I think that would be good for developing the CAM. Also the configuration might be worth storing somewhere. Finally could we update the scceptance criteria etc of the ticket to be (if this is acceptable):


As a SANS2D scientist, I want IBEX to respect the minimum permissable distances (intervals) between the detectors and baffles, so that the detectors and baffles do not collide.

#### Acceptance Criteria

1. Front Detector-Front Baffle Interval: minimum is 1050 mm.
1. Front Baffle-Rear Baffle Interval: minimum is 210 mm.
1. Rear Baffle-Rear Detector Interval: minimum is 350 mm.
1. The IBEX GUI should warn me if I set detector/baffle to positions which violate these limits.
   * the intervals should be calculated from the detector & baffle positions
1. I can use the IBEX GUI to set the detector & baffles positions in any order.
   * **Note:** in SECI the detector & baffles positions have to be entered in a specific order (which confuses users).
1. The interval limits should be configurable by ***HOW? James might have done this already ***
1. There should be 6 rules which stop a detector moving if:
    - interval between the object and the next object is less than the minimum
    - the direction of travel will make the interval smaller (i.e. we allow movement from a distance which is too small to one which is too large) An important test is put 3 objects closer than the minimum distance I should only be able to move the end ones away from the others. I should not be able to move the middle one.
    - rules are stop 1 if 1<->2 is too small, stop 2 if 1<->2 is too small, stop 2 if 2<->3 is too small, stop 3 if <2-3> is too small etc.
1. CAM should not be used but there is documentation of why it couldn't be used.

#### Notes
1. For the avoidance of doubt, this ticket is all about preventing clashes between baffles and detector trolleys.
   * the solution described above has been used on SECI for some time and works well, we should reproduce it  in IBEX, because it is proven and the scientists are familiar with it.
   * yes, we do have the CAM system, but the solution described above is simpler; a solution based on the CAM system can be considered at a later date.
1. This ticket is a sub-ticket of #4576.
1. The distances defined above have been measured on SANS2D.  It has been confirmed that they prevent collisions.
   * While it will be useful to define the minimum distances as configurable items, the expectation is that they will not change frequently.
1. Scientists prefer to enter all the detector/baffle positions, check that the intervals are valid (i.e. do not violate the minimum values) and only then press the "Move All" button (see #4577).
1. Check the paragraph describing the Clash Prevention in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.
   * **Note:** take special note of the comments about speed, acceleration, deceleration & homing of the detector & baffle trolleys.

**Comment by DominicOram** [comment]
@John-Holt-Tessella, I'll write something up, yes. Thank you for the modified Acceptance Criteria, I agree with them and will copy them in with minor corrections.

**Comment by DominicOram** [comment]
Configuration I created is at https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/313, please review as part of this ticket. Main issues with the CAM were written up in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Collision-Detection-Project#sans2d-tank

**Comment by DominicOram** [comment]
At the SANS2D demo yesterday, it was highlighted that this collision avoidance is also required when homing the axes.

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/29
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/365
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/534
- https://github.com/ISISComputingGroup/ibex_gui/pull/1181

**Comment by John-Holt-Tessella** [comment]
review:

- It is a pain but can we have a message on the GUI when a stop has occurred which gets cleared on the next move? Otherwise it isn't clear that the motion has been stopped mid move
- Do we care about stopping the motion if one of the motors is in alarm? I think no because a controller is likely up or not and so since all the motors are on one controller they will share an alarm

**Comment by KathrynBaker** [comment]
If the code already is set to look at individual motors I'd leave it that way, as it is possible that motors could be split to other controllers (possibly even by different manufacturers), so stopping if one motor is in alarm is probably better defensive programming than relying on the setup we currently have

**Comment by Tom-Willemsen** [comment]
> 
> 
> review:
> 
>     * It is a pain but can we have a message on the GUI when a stop has occurred which gets cleared on the next move? Otherwise it isn't clear that the motion has been stopped mid move
> 
>     * Do we care about stopping the motion if one of the motors is in alarm? I think no because a controller is likely up or not and so since all the motors are on one controller they will share an alarm

This is a good question and I think it needs some thought. At the moment the galils are on serial and so flicker in and out of comms alarm as they can't quite keep up, I guess once we switch to ethernet this will go away.

I think I am slightly worried about a small comms blip causing motion to stop but I could probably be persuaded away from this position. 

Maybe some kind of check of how long it has been in alarm, e.g. if in alarm for more than 5s stop the axes?

**Comment by Tom-Willemsen** [comment]
>     * [ ]  It is a pain but can we have a message on the GUI when a stop has occurred which gets cleared on the next move? Otherwise it isn't clear that the motion has been stopped mid move
> 

Plan is to use an aSub to write a timestamped string to an "error" pv, and then have a button on the OPI to manually clear the error. In discussion automatically clearing the error on next move is a bit tricky in this case.

**Comment by Alexandru-Dascalu** [comment]
>     Alarm on intervals and stop on intervals are not connected. Probably want the lo/lolo alarm to be the same as stop distance? Maybe lo is minim interval + 10% and lolo is minimum interval?
> 

According to Acceptance criteria 6 from https://github.com/ISISComputingGroup/IBEX/issues/4580, which is the ticket that implemented the calculation of intervals and their state of alarm, it says the minor and major alarm intervals should have fixed default values that should be configurable. It does not say the alarm thresholds should be dependant on the stop thresholds.

Has that been discussed since and have we changed our minds?

**Comment by John-Holt-Tessella** [comment]
@Alexandru-Dascalu no but it would be strange to be in the situation where the motor won't move to a place because of the stop interval but there is no warning that this is a bad place to move the motors to.

**Comment by Alexandru-Dascalu** [comment]
@John-Holt-Tessella Yes, it makes sense since currently the stop thresholds are bigger than the alarm thresholds. Though perhaps this should be discussed with the instrument scientists outside of this ticket?
