### ISSUE TITLE
SANS2D: Fast Shutter Commands

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4590]
As a SANS2D scientist, I want IBEX to provide me with pre/post- commands for BEGIN and END, so that I can control the opening and closing of the fast shutter as required.
#### Acceptance Criteria
1. I can use pre- and post- commands, via genie_python, to control the fast shutter .
1. I can use pre- and post- commands, via genie_python,  that do not control the fast shutter.
1. I can use pre- and post- commands to control the fast shutter via the IBEX GUI (via the DAE screen).
1. I can use pre- and post- commands that do not control the fast shutter via the IBEX GUI (via the DAE screen).

#### Notes
1. This ticket is a sub-ticket of #4589.
1. OpenGENIE has pre- and post- commands for the SANS2D fast shutter.  These need to be reproduced in genie_python.
1. The SECI VI for the DAE does not support the SANS2D pre- and post- commands.  The instrument scientists would like IBEX to support the pre- and post- commands on its DAE screen.
1. Check the paragraph describing the Fast Shutter in the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document.

**Comment by Tom-Willemsen** [comment]
- Should the fast shutter be closed when a run is aborted?
- Should the fast shutter be closed/opened when a run is paused/resumed?

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/510
- https://github.com/ISISComputingGroup/EPICS-isisdae/pull/66
- https://github.com/ISISComputingGroup/ibex_gui/pull/1133

Docs for post begin/post end hooks added at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-and-the-ICP

**Comment by FreddieAkeroyd** [comment]
The SANS2D open genie file does the following:

* Open fast shutter as begin pre-command, unless /QUIET qualifier specified
* Open fast shutter as resume pre-command, unless /QUIET qualifier specified
* Close fast shutter as end post-command, unless /Immediate qualifier specified
* Close fast shutter as abort post-command, unless /Immediate qualifier specified
* Close fast shutter as pause post-command, unless /Quiet qualifier specified

The fast shutter is opened as a pre-begin command so that you are not recording data as the shutter is moving away (or still in place). Same reason for resume command. 

We also need to consider how we implement functionality equivalent to the /quiet and /immediate qualifier if the action is being done in db records, unless we know such functionality is no longer required?

**Comment by FreddieAkeroyd** [comment]
We also need to consider if an optional delay, or other synchronisation mechanism, is needed for pre-commands

**Comment by Tom-Willemsen** [comment]
- My understanding is that they put run control on the fast shutter state so that they don't record data while shutter is moving/closed.
- Thanks, I'll add the hooks for pause/resume/abort.
- I didn't think we could rely on the `/quiet` or `/immediate` options any more as they also want this functionality from the GUI DAE screen. So instead they have a "shutter automatic" option on the gas panel - if it's in manual mode, the begin and end pre-commands do nothing.

**Comment by kjwoodsISIS** [comment]
I think we should specify what the pre- and post- commands, along with the /QUIET and /IMMEDIATE qualifiers, should do.
@FreddieAkeroyd  - what do the OpenGENIE pre- and post- commands actually do?

**Comment by FreddieAkeroyd** [comment]
pre and post commands are hooks for the scientist to add anything they require doing as part of that sequence, either before or after the operation concerned, and synchronised to it if required. /QUIET and /IMMEDIATE are two standard qualifiers present on the commands, the values of which are also transmitted to the pre/post commands and so can be used in whatever way desired. /QUIET was originally for Muons and meant their begin-pre-cmd did not prompt for questions on a begin, however it looks like sans2d do not open the fast shutter when /QUIET is specified - maybe quiet here is interpreted as "quiet counts" ? /Immediate is mainly used on END and PAUSE, it indicates that a hardware period sequence (if being used) should not be allowed to complete but the data collection be stopped immediately. We should check with SANS2D how they use these qualifiers within their scripts.

**Comment by FreddieAkeroyd** [comment]
As discussed with @Tom-Willemsen 

- we will check with scientists as per use of /Immediate and /Quiet after ticket complete. These qualifiers may no longer be used, or may need to interact with the manual/auto mode or somehow shortcut the DB logic.
- run control is usually enabled on the fast shutter and will stop data collection when it is CLOSED. This means that opening the fast shutter can be done as a postcmd as the instrument will go into waiting on resume/begin and then start collecting data only when shutter is fully open. The Open GENIE script opened the shutter and then waited for it to fully open, before starting collection (i.e. precmd) - it thus did not reply on run control being enabled for synchronisation of begin/resume. So ibex is fine if run control is enabled. In SECI I believe run control was primarily used to cover the shutter being put in by e.g. the user independently or the detector overcount mechanism.
