### ISSUE TITLE
GUI: Switch to new config option does not work

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4605]
Steps to reproduce:
1. Create a new configuration
1. When saving, a dialog pops up asking whether you want to switch to this config now. Select "Yes"
1. The new configuration should now be set as the currently active configuration, but it is not.

**Comment by adamb56789** [comment]
This worked a few months ago but then was broken somehow. What broke it was probably this commit https://github.com/ISISComputingGroup/EPICS-inst_servers/commit/fad6941f4e289b10dd722b5bafaa5e0b2f03150e, which changed the behaviour of `set_curr_config` in the BlockServer. It was saving the details of the newly created configuration, but then reloading the current config instead of setting the current config to the new one like it did before it was broken.

**Comment by kjwoodsISIS** [comment]
How many points?
