### ISSUE TITLE
GUI: Clear Macro button greyed out

### ISSUE THREAD

**Issue by Alistair-McGann-Tessella** [ISISComputingGroup/IBEX#4614]
As a user I need to be able to set IOC macros through the GUI. It appears that the clear macro button has been disabled so once a macro is set its value needs to be erased manually. It is unclear if this workaround will have same behaviour as clearing the macro (as opposed to setting it to an empty string).

## Acceptance criteria
 - [ ] Clear macro button is not greyed out and appropriately clears the macro
 - [ ] The behaviour of the clear macro button is defined
 - [ ] Using this definition, a squish test is created to test this functionality going forward

**Comment by ThomasLohnert** [comment]
If we were to treat blank macro values the same as unset macros I think we would not need to worry about the clear button. Would that be a sensible thing to do? 

Then we could change the view so that you can directly edit the table cells (same as OPI macros in the synoptic/device screens configuration dialog) and do away with the entire panel below the table (except for the pattern matching error message)?

**Comment by Tom-Willemsen** [comment]
I am not sure about this that, I think it may need more thought. e.g. this situation:
```
$(MACRO=#) somethingCommentedOutByDefault
```
where specifying the empty string as the value "uncomments" the line but passing no macro "comments it out".

There are patterns similar to this used in a number of places

**Comment by ThomasLohnert** [comment]
In that case the GUI should make it  clearer whether a macro is set to a blank string or set to nothing at all. Currently there is no way to tell the two apart.

**Comment by adamb56789** [comment]
This ticket will be made redundant by #4624 as the button will be replaced.
