### ISSUE TITLE
NIMROD: Make it collect Data

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#4617]
A user wanted it collect data but run control meant no data was collected and so no datafile was created on end run. The solution is to turn off run control. Item has been noted in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Trouble-Shooting and not written in dev notes.

**Comment by FreddieAkeroyd** [comment]
After further clarification from the user all data was collected OK and creating runs with run control enabled works fine. The issue was that is the instrument is in a WAITING state for the entire run, then the end_time as written in the nexus file/journal will be the same as the start time. The ICP interprets end time as end of neutron data collection, so if this never starts it remains the same as the start time and run duration is 0. The user had looked at the journal file and seen a time gap between one run end and another start, which was interpreted as a missing run and missing data, but in fact nothing was missing.
