### ISSUE TITLE
GUI: Blocks in groups cannot be moved down in the order

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#4647]
The "Groups" tab in the edit config dialog provides controls for reordering blocks in the selected group by moving them up / down. The "move down" buttom is currently broken as it merely moves the selection down by 2 rows, but does not reorder the blocks. This should be fixed.

As a side note, the ordering of the available blocks seems to be completely arbitrary - perhaps we could sort these alphabetically as part of this ticket (if it is an easy fix).

Acceptance Criteria:
1. Can reorder blocks in a group using the "move down" button.

**Comment by kjwoodsISIS** [comment]
As part of this ticket, it would be good to understand why a piece of functionality that was previously working is no longer working.  This kind of understanding is important to help ensure similar issues don't occur in future.

**Comment by adamb56789** [comment]
It looks like #4076 is what broke this, specifically [this commit](https://github.com/ISISComputingGroup/ibex_gui/pull/862/commits/a34c07dbafe2a679fae44cc141bbf622a8f231b5). There was some refactoring done to reduce code duplication, but the refactoring made a change to which method was being used. Instead of `selectedList.setSelection(int n)`,  `selectedList.select(int n)` was used instead, the difference being that for `setSelection`, "The current selection is first cleared, then the new item is selected", whereas `select` does not clear the selection first, it adds to it so that multiple items were selected, which is what caused the bug.

In the future we need to be more careful about making sure that we use the same methods when refactoring, and we need to make sure that we test things that have been refactored to check that we haven't made a mistake.
