### ISSUE TITLE
VESUVIO: unable to read from DAE3 [Tasks: Shutdown]

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#4719]
The control program was unable to read from the DAE3 over the private network, Kelvin confirmed that he was able to write values from NDXVESUVIO but all reads resulted in a timeout. I suspected a firewall issue and on disabling the firewall on the private network adapter VESUVIO was again able to read from the DAE3.

I am unsure if the firewall was previously off and has somehow been enabled, or if the firewall is usually on but the relevant udp port and program exceptions have disappeared

As part of #4691 a change was made to the firewall settings on instruments, is it possible that running this command turned on a firewall that was previously off or disrupted existing firewall rules?

**Comment by ChrisM-S** [comment]
Yes the firewall rules were a bit screwed up - incoming traffic to the DAE3 software was blocked from the wrong network (public).  The rules should be set as below (because this currently works on MARI).  Needs a bit more thought though, denying debug builds is just documentary as this will happen unless they are explicitly allowed! I didn't add this but it may just be failure to click an interactive permission request - which will end up with a deny by default.

![image](https://user-images.githubusercontent.com/3035405/64698806-76395900-d49b-11e9-92f7-e91f16dfc9b0.png)

**Comment by kjwoodsISIS** [comment]
This urgent ticket has not progressed for 21 days (date of previous comment).  What is stopping it from making progress?  If it can sit idle for 21 days, can it really be urgent?

**Comment by ChrisM-S** [comment]
Agreed, Sort of important to follow on and check this though, it requires someone to confirm that the install script isn't the thing that broke the firewall - but this may have been done?  Also to turn it back on VESUVIO and test it is now fine (maintenance day job or shutdown?).

**Comment by aaron-long** [comment]
Tasks: Turn firewall back on and test DAEIII comms.

**Comment by ChrisM-S** [comment]
Turned firewall back on, checked DAE connection by beginning, pausing, resuming & aborting a run a couple of times.  Began a run and looked a run diagnostics (histogram & detector diagnostics) then ended the run.  Checked the ICP logfile for any comms. errors after this, all appeared fine.

**Comment by ChrisM-S** [comment]
Anything else you would want to check @FreddieAkeroyd?

**Comment by ChrisM-S** [comment]
Actually, they shut down all the machines to work on the UPS very soon afterwards and it was turned on and came back working the next morning from cold – so I think that step is covered now.
