### ISSUE TITLE
GUI: Ctrl + C doesn't work in scripting window [timebox: 4]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4736]
As a user of GEM I would like to be able to stop a script with `Ctrl+C` in the scripting window. As part of this ticket we should introduce regression tests to make sure this doesn't happen again.

**Comment by DominicOram** [comment]
Note that this isn't broken on my developer machine or for @Tom-Willemsen but I have confirmed that it is broken on GEM.

**Comment by DominicOram** [comment]
We should also try and find out if this is happening on other instrument machines

**Comment by Alistair-McGann-Tessella** [comment]
+1 GEM

**Comment by Alistair-McGann-Tessella** [comment]
I've tried copying the GEM client on to my machine, ctrl-c successfully stops a script. We need to have a closer look at the GEM instrument machine.

I've asked for permission from the the instrument scientists to have a look during the beam-off day next week, or whenever they have a free moment to get in touch

**Comment by Alistair-McGann-Tessella** [comment]
Steps to reproduce the bug:
1. Switch to scripting perspective
1. Open a second console window
1. Press reset layout button
1. Ctrl+c no longer works and buffer reads 'NaN% full'

**Comment by Alistair-McGann-Tessella** [comment]
We have spent a few days trying to find a solution to this bug, we need to repoint this and think about its priority.

This is a summary of the work done so far:
We think there is an issue in the IBEX codebase and not in PyDev itself, as the reset perspective button works in the latest version of eclipse and PyDev, but our reset layout button kills the scripting console view.

The IBEX reset layout button makes a direct call to `resetPerspective()` to reset the perspective/layout. We suspect that because this is gets the current workbench through an E3-style call (using `PlatformUI`), the pyDev console is not included in the page. This is then lost when `resetPerspective()` gets called. The relevant code is in `uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/PerspectiveResetAdapter.java`. 

The eclipse 4 IDE codebase uses a different call to get the active workbench/page to reset the perspective:
```public class ResetPerspectiveHandler extends AbstractHandler {

@Override
public Object execute(ExecutionEvent event) {
IWorkbenchWindow activeWorkbenchWindow = HandlerUtil.getActiveWorkbenchWindow(event);
if (activeWorkbenchWindow != null) {
    WorkbenchPage page = (WorkbenchPage) activeWorkbenchWindow.getActivePage();
}
[...]
page.resetPerspective();
```
This method requires passing an `ExecutionEvent` to the handler, which is the E4 way of doing things. We have an unused handler in `uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/ResetPerspective.java`, so a possible solution is to convert this to the e4-style handler. This might allow it to function like the eclipse reset perspective menu item.

**Comment by Alistair-McGann-Tessella** [comment]
![image](https://user-images.githubusercontent.com/39486445/65900483-04737180-e3ae-11e9-86d5-87f0f22e91ad.png)
This is a screenshot of the latest IBEX GUI with PyDev 7.3.0 after Reset Layout has been pressed. In the eclipse IDE, if you make a new perspective containing the same version of the PyDev console the console remains persistant over a 'Reset Perspective'. This is why I think that the issue is in how IBEX handles workspaces; the code to reset the perspective in the two cases is the same.

**Comment by Alistair-McGann-Tessella** [comment]
I think there are probably around 3 points left on this ticket. This is because I expect getting an e4-style handler working in IBEX to be very fiddly.
