### ISSUE TITLE
Galil: Alert when powered down

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#4745]
As a support person I want to know if a galil has lost power and therefore lost positions. This ticket is to provide a PV to tell me that the galil is in this state and put a nagios check on it. We may wish to do more like stop users from moving items when in this state but this is not part of the ticket. Some implementation options:
* Write to a variable on the controller and confirm periodically that it still holds data
* Confirm that the TIME variable on the controller has not lost any time or reset to zero

**Comment by IainJohnson** [comment]
It might be useful to highlight some occurrences in recent months:

• Polref - Bench unexpectedly drove to upper limits. We think the Galil 5v dipped and caused a Galil reboot, possibly due to addition of more encoders. The Galil was then swapped for another with a higher rated internal PSU.
• Offspec - After replacing UPS, axis would not move , possibly because the setpoints at zero violated the soft limits. Cycling SECI restored valid setpoints/positions.
• SANS2D - Spring Shutdown - Scientist found the Guides had unexpectedly all driven to/past the lower limits, causing amplifier faults on all axes.
• SANS2D - Summer Shutdown - after work on the NDX UPS, Guides had driven to lower limits, presumably because setpoints/positions did not tally.

Generally this is associated with problems on the UPS supplying the Galil motion controllers, or failures with the Galil's internal power supply. EEUSG endeavour to replace the UPS/batteries when practicable, however sometimes the UPS can fail silently. EEUSG now also fitting upgraded Galil internal PSUs where applicable, which have higher power rating/thermal performance.

**Comment by davidkeymer** [comment]
+1 for GEM.  Would have saved support query detailed in this [Footprints ticket](https://footprintssc.fed.cclrc.ac.uk/footprints/servicedesk/application.html#runtimecontainer/view/workspace/82232/28502)

**Comment by DominicOram** [comment]
The software in https://github.com/ISISComputingGroup/IBEX/issues/4175#issuecomment-735926862 may also be able to provide something here.

**Comment by FreddieAkeroyd** [comment]
We probably need to look for TIME going "backwards" as we probably wouldn't catch zero, do we know when it wraps? This however would miss a power cycle with the IOC not running - writing a volatile variable might work better, we can choose a new value on boot after confirming old autosaved value - that is to try and guard against it being automatically burnt into memory.

**Comment by John-Holt-Tessella** [comment]
So the order of play is:

- Every longish time span (5 minutes?):
    - the variable is read by the IOC calling `MG <variable name>` 
    - the check PV is set with a status reflecting whether it equals the autosaved value
    - If equal the variable and autosaved pv are updated by adding 1 mod 10
- When done @FreddieAkeroyd will put a nagios check on this PV

so we need:

- expected power off detection value pv which is autosaved, and when written to writes the variable to the galil
- pv to read the current power off detection value from the galil
- checking pv which checks the current value against the autosaved value

**Comment by FreddieAkeroyd** [comment]
@John-Holt-Tessella  why only mod 10 and not a larger value (10000)?

Also do we should display something on the OPI / GUI banner in event of power off

**Comment by FreddieAkeroyd** [comment]
I think this can be done entirely in DB by using galil userdef records via https://github.com/ISISComputingGroup/EPICS-ioc/blob/master/GALIL/GALIL-IOC-01App/Db/galil_userdef_records8.substitutions - this will create a per axis variable that is autosaved and then you just need some more db logic to change and monitor its value. Rather than the auto (monitor) part of autosave we may want to try manual/triggered save, the problem with the default system is that there is a window of time between writing the new value to the galil and the periodic autosave happening during which if the ioc restarted it would reload an old value and register a mismatch. Maybe the thing is to use the periodic timer to get it working, and then tweak the actual saving later

**Comment by FreddieAkeroyd** [comment]
This approach is used in https://github.com/ISISComputingGroup/EPICS-motorExtensions/blob/master/emmaChopperLifterApp/Db/emmaChopperLifter.db and 
https://github.com/ISISComputingGroup/EPICS-motorExtensions/blob/master/oscillatingCollimatorApp/Db/oscillatingCollimator.db
