### ISSUE TITLE
genie_python: g.begin() does not produce an error message if the ICP cannot begin a run

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4792]
As a user on LOQ I do not want a `g.begin()` command to appear to hang if the ICP cannot begin the run (for example, if inconsistent wiring/detector/spectra tables have been set).

### Acceptance criteria:

1. The user is given a sensible error explaining why the operation failed (if possible), or some indication of where to look for the errors (e.g. look in DAE perspective at error log). When the ICP has not been able to begin a run.

### Notes

We should probably keep the behaviour that `g.begin()` does not return after issuing the error message, this will stop users continuing with a run when the cannot collect data. If you disagree with this behaviour then please create a discussion ticket based on this.

**Comment by FreddieAkeroyd** [comment]
Yes, it should not return if it cannot begin - otherwise the next waitfor may work based on microamps left over in dae, then it will get to end, which will fail, but probably not hang as you are already in setup. So you could run through the script not doing much neutron wise, but potentially ramping your sample which may be a one way operation.

**Comment by mihai-stfc** [comment]
Pull requests: 
https://github.com/ISISComputingGroup/genie_python/pull/282
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/71 (test)
