### ISSUE TITLE
Python 3: convert IOCTestFramework

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#4890]
As a developer I would like the IOC testing framework and all of it's tests to run under python 3.

**Comment by rerpha** [comment]
PR: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/395

I have run the tests over the weekend and got them to log to a file by running `run_all_tests.bat > log.txt` - this showed some errors which were caused by byte-strings and processes not being flushed correctly so I have sorted those out. I did get some failures but i think its because I haven't got all my IOCs up to date and built rather than py2/3 differences. 

I alos created #5978 for sorting out the use of the `imp` module which is now deprecated.
