### ISSUE TITLE
18/11/19 - EMU need support on this morning with getting a Kelvinox set up

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#4937]
Email request came in for this support - has since been corrected to be a Kelvinox rather than Triton

**Comment by Tom-Willemsen** [comment]
Slightly off-topic but if they need help setting up a kelvinox now, will they need IBEX support for the kelvinox once they have migrated?

**Comment by KathrynBaker** [comment]
Good question, and I’m afraid the answer is “probably” – might be worth a check with the scientists.

**Comment by KathrynBaker** [comment]
I asked the instrument scientists, I was told yes they will be using the Kelvinox for many years to come.

**Comment by Tom-Willemsen** [comment]
For the avoidance of doubt: this is a kelvinox *insert* controlled by a triton *controller*. The bit we talk to is triton.

**Comment by Kevin-Woods-Tessella** [comment]
So, in reality, the task here is to help the scientists set up a Triton (which just happens, on this occasion, to have a Kelvinox insert). 
   1. We can certainly setup a Triton to communicate with SECI (because EMU still uses SECI).
   1. Configuring a Triton to control a Kelvinox insert is a job for the Cryogenics team.
Is this correct?

**Comment by KathrynBaker** [comment]
To my understanding yes that is correct.

**Comment by davidkeymer** [comment]
Equipment connected and configured, SECI sub-configurations and configuration created.  Instrument scientists will test control of the fridge over the next couple of days, but seemed happy that everything was ready.
