### ISSUE TITLE
Engin-X: portable galil for eulerian cradle won't talk [timebox: 5]

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5004]
As a user and instrument scientist on Engin-X, I would like to be able to use the eulerian cradle.

Problem 1: connection needed an additional null modem (there is one null modem with the galil that I couldn't remove, so it is now effectively running with two null modems (which cancel each other out)

Problem 2: the epics galil driver hangs on connecting. Sending raw commands via hyperterm works.

### Acceptance criteria:
- We can communicate with the GALIL from the ibex ioc

### Notes

Documented at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting#partial-communication-i-can-talk-to-it-using-hyper-term-on-the-instrument-but-driver-does-not-connect

**Comment by John-Holt-Tessella** [comment]
Tried  to connect from my desktop ❌ 
Tried to connect with hyperterm from my desktop 🆗 
Tried to connect with labview from my desktop 🆗 
Tried the version of epics from ENGINX backedup in 2019_06  ❌ 

When we went down: 

- controller looks fine, 
- couldn't added it to subnet (no private VPN)
- lab can talk with it

Plan:

- Create a calab wrapper which sets pvs for the set point they can run it on a hybrid system.
- After experiment we will diagnose the problem.

**Comment by FreddieAkeroyd** [comment]
Sorry, not able to see everything but a comment above talks about NULL modems and then private networks are also mentioned. The galil looks to be using ethernet (at least the last entry is if I have looked at the right log file), is labview using serial or ethernet? Has epics been tried with serial? If epics is tried with serial has xon/xoff has been enabled in the controller?

**Comment by Tom-Willemsen** [comment]
The galil is on serial. We tried ethernet (briefly) but realised this would not work as engin-x does not have a VLAN set up. The last entry in the log probably reflects this brief test.

Labview is talking on serial, we talked to it using hyperterm on serial, epics hung when attempting to talk to it using serial.

**Comment by FreddieAkeroyd** [comment]
```
[2019-12-04 14:21:21] GalilCreateAxis("Galil","A",1,"",1)
[2019-12-04 14:21:50] sevr=major connect: 1011 TIMEOUT ERROR.  Galil::command("") took longer than 500 ms to read : response.
```
All I can suggest is check the xon/off switch - i'm not sure why it lists the offending command as ""

**Comment by Tom-Willemsen** [comment]
@davidkeymer and I went down and with some help from electronics found some numbers that appear to work to drive both stages.

Instrument scientist seemed happy that they can use this setup to run an experiment (via the epics-labview compatibility vis that @KathrynBaker put together). After their experiment is over we need to diagnose why epics was completely unable to talk.

**Comment by KathrynBaker** [comment]
For reference, the VIs are now in source safe under Instruments > ENGINX > Temp Stage for IBEX

Here is a brief description of what is going on/how to recreate this on ENGINX just for future reference as the solution in use is very much an ugly hack to get it working

- Create blocks in IBEX which point to the USER PVs - these are PVs with little to no substance served by INSTETC I believe - @Tom-Willemsen please correct this assumption if it is wrong
- Make sure that you do not have the user PV aliased so that the PV and the setpoint are the same entry - this does require separate entries
- Within the lv setup dialog create a "mid level" with the same name (including formatting) as the block - don't forget to save, you can then assign the Galil axis that you wish to associate with these blocks. If you do not use the block name correctly this will not work, as the block name is part of what is used to generate the PV name
- Run the front panel VIs, there are only 2 at the moment

This setup allows you to read the position and write the setpoint from a block in IBEX and this is forwarded to/from the LabVIEW ToM in the same way as any other item of LabVIEW motion.

**Comment by John-Holt-Tessella** [comment]
Some docs for the cradle itself: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Portable-Eulerian-Cradle

**Comment by Tom-Willemsen** [comment]
Plan is to look at this in January shutdown to try and diagnose the issues.

**Comment by Tom-Willemsen** [comment]
Response from scientist:
> We may need it again at some point this cycle

**Comment by John-Holt-Tessella** [comment]
Partially fixed. I have replaced two cables between the galil crate-patch pannel and patch pannel - moxa and this seems to make it much happier. My guess is that the cables in question did not have a hardware control line in them so the IOC did not speak to the galil because it thought it was busy. 
I can see the controller is now connected:

```
# G21X3Config($(GCID),"$(GALILADDR)",8,2100,2000)
GalilCreateController("Galil", "COM28 38400", 100)
Galil1.dll
sevr=info Connected to COM28 38400, DMC2280 Rev 1.0o-CM, 21420
```

I have not got the cradle attached so have not actually moved the motors. I also seem to be getting an error in the galil code:
```
Transferring code to model DMC2280 Rev 1.0o-CM, address COM28 38400 -t 1000

Error downloading code model DMC2280 Rev 1.0o-CM, address COM28 38400 -t 1000 msg 1011 TIMEOUT ERROR.  Galil::command("DL400
") took longer than 1000 ms to read : response.

GalilStartController:GalilController::writeReadController:XQ 0,0:2010 COMMAND ERROR.  Galil::command("XQ 0,0") got ? instead of : response.  TC1 returned "10 Undefined label or empty sequence line"
sevr=major XQ 0,0: 10 Undefined label or empty sequence line
GalilStartController:GalilController::writeReadController:XQ 0,0:2010 COMMAND ERROR.  Galil::command("XQ 0,0") got ? instead of : response.  TC1 returned "10 Undefined label or empty sequence line"
sevr=major XQ 0,0: 10 Undefined label or empty sequence line
GalilStartController:GalilController::writeReadController:XQ 0,0:2010 COMMAND ERROR.  Galil::command("XQ 0,0") got ? instead of : response.  TC1 returned "10 Undefined label or empty sequence line"
sevr=major XQ 0,0: 10 Undefined label or empty sequence line
GalilStartController:GalilController::writeReadController:XQ 0,0:2010 COMMAND ERROR.  Galil::command("XQ 0,0") got ? instead of : response.  TC1 returned "10 Undefined label or empty sequence line"
sevr=major XQ 0,0: 10 Undefined label or empty sequence line
Thread 0 failed to start on model DMC2280 Rev 1.0o-CM address COM28 38400 -t 1000

Thread 0 not running on model DMC2280 Rev 1.0o-CM, address COM28 38400 -t 1000
Thread 0 not running on model DMC2280 Rev 1.0o-CM, address COM28 38400 -t 1000
Thread 1 not running on model DMC2280 Rev 1.0o-CM, address COM28 38400 -t 1000
```

These two issues need solving.

**Comment by FreddieAkeroyd** [comment]
Hi,

These were standard serial cables rather than RJ45 cables?

What are the dip switches on the Galil controller set to? Switch 2 is ON for Xon/Xoff flow control, which we normally enable as otherwise you get timeouts on the homing program download  (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting). I didn't think we set switch 3 ON (hardware handshake) but if that was enabled and it had a three wire serial cable connection that would certainly be a problem. 

Freddie

**Comment by John-Holt-Tessella** [comment]
Standard serial cables.

XON/XOFF switch 2 didn't wok with it on or off. I think it is currently on but I will check.

 Switch 3 is not on.

**Comment by kjwoodsISIS** [comment]
So, the emerging consensus seems to be that he problem is with the cables.  Correct?
Would it be sensible to have labelled cables, to minimise the chance of using the wrong type.  Perhaps also attach a label to the Galil making it clear to people to use the the correct type of cable?

**Comment by FreddieAkeroyd** [comment]
Are we aware of the cables being changed? If switch 3 is not ON then I think that eliminates hardware flow control issues. Then if there was an issue with the remaining 3 wire connection, why did it work with labview?

**Comment by ChrisM-S** [comment]
Probably worth asking the same question as usual, is the light pattern the same on the on the RS232 tester when LabVIEW is working the cradle and when IBEX is working the cradle?  If the connection really is 3-wire, it may be that a flow control input to the Moxa/Galil is floating or looped back incorrectly?

**Comment by FreddieAkeroyd** [comment]
talking more to John he saw that the pc end always requests hardware flow control whatever the galil is set to. So it could be floating lines with a 3 wire connector.

**Comment by John-Holt-Tessella** [comment]
Yes the cables were added this time.
Didn't use the tester in that way, but used a serial sniffer which did not receive anything from the pc.
I suspect that labview does not use hardware flow control.
