### ISSUE TITLE
Muons: Dashboard fields

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5014]
As a muon scientist I need the IBEX dashboard to show fields which are relevant to muon experiments (as opposed to neutron experiments).

#### Acceptance Criteria
1. For muon instruments, the IBEX dashboard shall display the following fields
   1. Run (for all states except SETUP)
      * Next Run (in SETUP state only)
   1. Kicker Status
   1. Good/Raw Frames
   1. Total MEv
   1. Inst. Time
   1. Run Time
   1. Period
   1. Count Rate
1. If I point my GUI at EMU I want the modified dashboard

#### Notes
1. An illustration of how the dashboard could appear for a muon instrument is attached.
![Dashboard](https://user-images.githubusercontent.com/7249337/70327401-a3916b00-182e-11ea-8bb6-9c07138b42e1.png)
1. Compare this with the SECI equivalent:
![EMU Dashboard](https://user-images.githubusercontent.com/7249337/70327246-439ac480-182e-11ea-99fd-3d8055315bd3.png)
1. **N.B.** For muon instruments only: In SETUP state, the Run field should be labelled "Next Run:".  In all other states, the Run field shall be labelled "Run:".  There is no need to change the value of the run number, just change the field label.
    * For the avoidance of doubt, for neutron instruments, the Run field is **_always_** labelled "Run:", regardless of the state.
   * In pseudo-code, the logic is this:
```
if (IsMuonInstrument(instrument) && (state == "SETUP"))
   label_text = "Next Run:"
else
   label_text = "Run:"
```

**Comment by kjwoodsISIS** [comment]
Responses (from Koji) to questions:
1. SECI shows the “Next Run”, IBEX shows the current “Run”.  Does it matter to you which run number is shown by the dashboard?
   * _Yes, we would like to see the run number assigned to the next run (not the one already finished). This may be more like a preference, but because we have conventionally seen the next run number in this pane, we would like to keep it in the same way._
1. IBEX shows the shutter status.  Presumably this is not relevant to muon instruments.  Would you prefer to see Kicker Status instead?
   * _We would like to have the Kicker Status in the window. On the other hand, I think James Lord is working on a status readback from the shutter of each arm of the muon beamlines. However I don’t think it’s in place yet. For now we just need the Kicker Status._
1. Both IBEX and SECI show “Good/Raw Frames”.  We can continue to display “Good/Raw Frames”, or we can replace them with something else.  Do you have a preference?
   * _“Good/Raw Frames” should be fine._
1. IBEX shows “Current/Total”, which is not useful to you.  I propose we show “Total MEv” (millions of events) instead.  OK?
   * _Yes, we would like to have the “Total MEv”. We record the proton current in the data file, but don’t need to show “Current/Total” in the pane._
1. IBEX shows “Monitor Counts”.  I propose we show “Count Rate” instead.  OK?
   * _Yes, we need the “Count Rate” on the window._

**Comment by davidkeymer** [comment]
During a recent meeting, @FreddieAkeroyd mentioned the idea of using configurable PVs (via aliases) in the dashboard to enable customisation for the Muon group (but would also allow each instrument to have their own configuration).  This would mean the dashboard values would be set at source rather than having to configure each client separately (as has been proposed as a solution via the `preferences` file).  This may need further discussion amongst ourselves.

@FreddieAkeroyd also suggested that we ask the neutron instruments whether or not we could change the wording on the dashboard to `Next Run` as per the muon group requirement explained above.  This would mean a common display across all instruments and no special customisation.

**Comment by kjwoodsISIS** [comment]
@davidkeymer  - are you going to ask the neutron scientists?

**Comment by davidkeymer** [comment]
@Kevin-Woods-Tessella - I thought it could be raised at the next SAG.  In the meantime, we can create a bespoke version of the client for EMU using the original "preferences" file.

**Comment by kjwoodsISIS** [comment]
@davidkeymer - how does that work?

**Comment by davidkeymer** [comment]
@Tom-Willemsen thought it would be straightforward enough to put an option in the preferences file`*` to customise the dashboard accordingly.

`*` the file that determines which perspectives to display

**Comment by Tom-Willemsen** [comment]
After discussing the implementation with @John-Holt-Tessella we have decided the following:
- The IBEX dashboard will look at consistently named PVs, but these are not (directly) the DAE PVs.
  * e.g. something like `%MYPVPREFIX%CS:DASHBOARD:1:1:LABEL` for the label of the item on row 1 / column 1 of the dashboard.
- We will load a DB file from the instrument configuration areas into an IOC which is always running (e.g. instetc), which will define the consistently named dashboard PVs
- We will need to write an upgrade script which adds appropriate definitions for the neutron instruments, so that they continue to see that same information as usual
