### ISSUE TITLE
Script Generator: Set up config management

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5088]
As an instrument scientist I would like to be able to distribute and use my configs.

This is a ticket to have a discussion about how we should store configs and allow them to be distributed.

Configs should be able to be accessed from any computer that the script generator can be used on. Configs should in some way be separated out by instrument or technique.

One possibility is having a config repository and when the script generator is deployed or downloaded onto a computer including these. We can then point a gui preference to load from this folder (implemented as part of https://github.com/ISISComputingGroup/IBEX/issues/4167).

**Comment by kjwoodsISIS** [comment]
Some questions to think about:
1. If I distribute the Script Generator to another scientist, based elsewhere (e.g. another facility or at a university), how will this scientist be able to get access to configs?
1. Suppose I distribute the Script Generator  (including configs) to another scientist at a remote location (so that he can prepare scripts ahead of his planned visit).  What happens if I change the config on the NDX machine in the meantime (e.g. I might change the name of a block, or add a new block)?

**Comment by JamesKingWork** [comment]
I have realised that this ticket has already been created #5026. Closing and linking this ticket to the original.
