### ISSUE TITLE
MuSR: IOC & OPI to control Instrument Rotation

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5096]
As a muon scientist, I would like IBEX to provide a MuSR rotation control IOC & OPI, so that I can control the orientation of MuSR.

Behaviour of existing LabVIEW soluition is described in ticket #5178

#### Acceptance Criteria

1. The OPI must display the the following text at the top of the OPI:
   * "Use the buttons below to select the orientation when rotating the instrument.".
1. The OPI must display the status of the Zero Field controller.
   1. the status field should display the mode of the zero-field controller concatenated with the status of the zero-field controller.
1. The OPI must display the status of the magnet (the one powered by the Danfysik).
   1. the status field should display the status of the Danfysik PSU (powered on, interlock status).
1. The OPI must display the current orientation of MuSR (LONGITUDINAL or TRANSVERSE).
1. The OPI must provide a Go To Longitudinal button:
   1. On pressing the Go To Longitudinal button:
      1. If MuSR is in TRANSVERSE mode, it should be put in LONGITUDINAL mode
         * the magnet powered by the Danfysik is considered to be the longitudinal magnet
         * the magnet powered by the Thurlby is considered to be the transverse magnet
         * the zero-field controller settings should be replaced by default longitudinal mode settings
      1. If MuSR is already in LONGITUDINAL mode, IBEX should do nothing 
1. The OPI must provide a Go To Transverse button:
   1. On pressing the Go To Transverse button:
      1. If MuSR is in LONGITUDINAL mode, it should be put in TRANSVERSE mode
         * the magnet powered by the Danfysik is considered to be the transverse magnet
         * the magnet powered by the Thurlby is considered to be the longitudinal magnet
         * the zero-field controller settings should be replaced by default transverse mode settings
      1. If MuSR is in TRANSVERSE mode, IBEX should display a warning message, but otherwise do nothing
1. The 4th channel on the cDAQ IOC (the same cDAQ IOC used by the zero-field controller) detects a change in voltage, IBEX should change the orientation of MuSR according to the table below.
   * **Note:** If the user presses the Go To Longitudinal or the Go To Transverse buttons, they are, in effect, over-ruling what the 4th channel on the cDAQ is saying.  That's fine - it's allowed!

#### cDAQ Channel 4 - Orientation Table

Condition <br>(Channel 4 voltage)          | Action                                                                                  |
---------------------------------------|------------------------------------------------------------------------------|
voltage >= +4V                         | If orientation is not transverse,  set orientation  to transverse, and update the config files accordingly. <br> If orientation  is already transverse,  keep orientation  set to transverse          |
-4V < voltage < +4V                  | Do not change the current orientation                                                         |
voltage <= +4V                         |  If orientation is not longitudinal  set orientation to longitudinal and update the config files accordingly. <br> If orientation is already longitudinal, keep orientation set to longitudinal  |
voltage <= +4V AND voltage >= +4V   | This condition should not occur, but the original VI seems to cater for it (a hardware problem?). <br> Treat this as an ELSE-case after all the other conditions have been checked (i.e. adopt a belt-and-braces approach – just in case). <br> Set zero-field controller to manual mode. <br> Set orientation to INDETERMINATE.                                                                                                                         |

#### Notes
1. In SECI, the following `.ini` files, located in `C:\LabVIEW Modules\Muon Magnets`, are used to define the default longitudinal/transverse mode settings.
   * `conf_long.ini` defines the zero-field controller settings when MuSR is in longitudinal orientation
   * `conf_trans.ini` defines the zero-field controller settings when MuSR is in transverse orientation
   * `magnet_long.ini` defines the Danfysik PSU settings when MuSR is in longitudinal orientation
   * `magnet_trans.ini` defines the Danfysik PSU settings when MuSR is in transverse orientation
1. The LabVIEW MuSR rotation control VI is located here: `C:\LabVIEW Modules\Muon Magnets\Muon Rotation Control`
   1. It appears that all the VI does is to switch off the zero-field control and Danfysik magnet (presumably you don't want these running when rotating the instrument).
   1. It also appears that the MuSR rotation control VI does not actually perform any rotation (presumably the rotation is performed in some other fashion - maybe even manually?). 
   1. the screenshot below shows the MuSR rotation control VI in `C:\LabVIEW Modules\Muon Magnets\Muon Rotation Control`. 
![MuSR_Rotation](https://user-images.githubusercontent.com/7249337/72630495-5f73a900-394a-11ea-8d21-91b10b521bea.png)

**Comment by KathrynBaker** [comment]
For reference:

The motion is undertaken manually, but there are switches fed into the fourth channel of the 9215 card used for the zerofield, so that these change overs occur automatically when the system is rotated. Each button behaviour can also be triggered by changes to the values from the cDAQ.

The Zero Field VI status is simply whether or not it is running, open, or other situation (basically the state of a LabVIEW run arrow), Magnet VI status is the same information for the Danfysik Controller. These are displayed because the VIs are actually stopped and restarted in the code as mentioned below.

Whichever state is chosen it puts the zerofield controller into manual mode.
Go to Longitudinal stops the VIs for the zerofield controller and Danfysik, changes the config files to be used as there are different co-efficients by overwriting the standard file with the for longitudinal variables, starts the VIs up again.
Go to Transverse is the same as Longitudinal, but rewrites with transverse specific files instead.

The stop is all about changing the values in use the rotation can happen independently, but only by stopping and restarting the VIs can those values be changed. These values are probably macros in the IBEX implementations, and would similarly require an IOC to be stopped and started to pick up changes. Although we do have to think about how we manage that change.

**Comment by kjwoodsISIS** [comment]
@david, @Alistair-McGann-Tessella , @Tom-Willemsen 
Regarding Kathryn's comment above: does the current implementation of the zero-field controller read the 4th channel of the 9215 card?  Or would it be better to use information from the cDAQ card to determine the orientation of MuSR?

**Comment by kjwoodsISIS** [comment]
Required, if we are to migrate MuSR for Cycle 2020/04 (11th February 2021 - 27th March 2021).

**Comment by rerpha** [comment]
I think this is blocked by https://github.com/ISISComputingGroup/IBEX/issues/5178

**Comment by kjwoodsISIS** [comment]
No longer blocked - see #5178 and updated requirements (above).

**Comment by Tom-Willemsen** [comment]
Agreed solution to (5) and (6) in a meeting with @FreddieAkeroyd @DominicOram @John-Holt-Tessella @kjwoodsISIS :
- Write a standalone service which monitors the state of MuSR (longitudinal or transverse)
- On change, the standalone service will edit *all* configurations, swapping out the "longitudinal" component for the "transverse" component or vice-versa
  * Needs to edit all configurations, otherwise a rotation change followed by a config change will leave MuSR in the incorrect state
- Add a flag for configurations/components that are "dynamic"
  * If this flag is set, the configuration or component should display a warning message and a link to appropriate documentation when it is edited.
  * This flag should be settable from the GUI and should propagate through to the blockserver/disk etc.
  * The "longitudinal" and "transverse" components on MuSR should be marked with this flag.

**Comment by davidkeymer** [comment]
Suggest displaying current orientation in banner.

**Comment by Tom-Willemsen** [comment]
PRs:
- blockserver & componentswitcher https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/340
- GUI https://github.com/ISISComputingGroup/ibex_gui/pull/1236
- ZFMAGFLD support https://github.com/ISISComputingGroup/EPICS-zfmagfld/pull/5
- ZFMAGFLD ioc https://github.com/ISISComputingGroup/EPICS-ioc/pull/574
- Release nites https://github.com/ISISComputingGroup/IBEX/pull/6077

An appropriate `ComponentSwitcher` configuration file and `custom_records.db` are available on branch `Ticket5096` of the configurations repository (you will need this branch to be able to review the ticket)

**Comment by DominicOram** [comment]
Works well, thanks. Just some tidying up really. I've added some minor comments to the code. Some more general comments:
* Have you sent the OPI to the scientists? Maybe with a little GIF of it working? I think having to select two things on the OPI and them being drop downs rather than buttons is different enough to double check with them
* Can we document this feature in the user manual, I appreciate that you've labelled it as advanced and not in general use but I think we should at least have a mention on there
* You've currently let users label configurations as dynamic, not just components. Given that this is functionally useless I think it would be less confusing to not allow this

Happy to discuss any of this further if you like.

**Comment by Tom-Willemsen** [comment]
>     * Have you sent the OPI to the scientists? Maybe with a little GIF of it working? I think having to select two things on the OPI and them being drop downs rather than buttons is different enough to double check with them

No, but we have some testing time on MuSR coming up shortly so I was planning to demo it during that time (along with various other things we want to demo to them) rather than starting more email chains.

>     * Can we document this feature in the user manual, I appreciate that you've labelled it as advanced and not in general use but I think we should at least have a mention on there

Added to https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-And-Manage-Configurations#id2

>     * You've currently let users label configurations as dynamic, not just components. Given that this is functionally useless I think it would be less confusing to not allow this

Done

**Comment by DominicOram** [comment]
Happy to discuss with them as a group of items, I have made https://github.com/ISISComputingGroup/IBEX/issues/6112 to capture this. Feel free to add any more detail for what else to test with this ticket.

**Comment by Tom-Willemsen** [comment]
Scientists have now been shown the OPI for this and are happy with the workflow.
