### ISSUE TITLE
Configure IE to limit external internet access.

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5112]
As a support person, I would like IE on Instrument Servers to be configured to limit access to the external internet, so that we minimise the security risk to Instrument Servers.

#### Acceptance Criteria
1. The LAN settings in IE are configured to limit access to the external internet on all Instrument Servers.

#### Notes
1. IBEX depends on IE for some of its features.  All of these features use web-sites which are internal to ISIS.
1. In future, we may choose to permit access to a limited number of external web-sites.  This access list will be the control of the ISIS Experiment Controls team.

**Comment by Tom-Willemsen** [comment]
We have some buttons in the GUI which open documentation pages (on github) in the system default web browser. How will this change affect those buttons?

Examples of where this is done (not exhaustive):
- Matplotlib OPI
- Kepco OPI
- Fermi chopper OPI

**Comment by Kevin-Woods-Tessella** [comment]
We will need to adjust our configuration of IE to allow access to GitHub.  @ThomasLohnert has the details on how to do this.

**Comment by ThomasLohnert** [comment]
If we allow github to be accessed, is that not creating a vulnerability? I was going to whitelist internal sites only that we know to be safe. I think we should make users aware of the IE restrictions in some way, and then if they want to go to github they can do it from a different browser from NDH.

**Comment by Kevin-Woods-Tessella** [comment]
Yes, but Tom's point is that some features of IBEX actually contain links into GitHub.  If we deny access to GitHub, those links will break and we will get support calls.  Provided we control the whitelist (which we do), we can limit the risk.
Alternatively, we could copy those specific help items to the User Manual (which is hosted on shadow).
Long term, the best solution is to do away with IE altogether - but that's not a quick fix.

**Comment by KathrynBaker** [comment]
I’m inclined to say we let them be blacklisted at this point in time, and see who asks for them – I’m willing to bet, in the same way that our users rarely read text in dialogue boxes, they aren’t using them that often. The one exception might be EMU as new users who might play a little more and explore such things more thoroughly.

Although I am slightly intrigued that we have user facing documentation not in the user manual – which is what this dependency implies. Surely the user manual is where user documentation should be, by it’s very definition. If it isn’t user facing information – why are we linking to it from the user interface? However, these are actually questions not related to IE so if anyone else feels they are important enough to be considered then a ticket shud be created so that at least we do eventually consider why the user manual isn’t the source of all user documentation.

**Comment by ThomasLohnert** [comment]
I agree with Kathryn, I think the implications of exposing ourselves to this vulnerability are much more serious than breaking some help links. They are device specific and don't seem essential and we can solve such support calls in a minute by telling users to just copy and paste the url into another browser.

@KathrynBaker I think it's because those links lead to documentation provided by vendors rather than anything written by us.

**Comment by Kevin-Woods-Tessella** [comment]
OK.  Can someone provide me with a list of the links to the GitHub wiki in IBEX.  I will take care of re-creating the material in the User Manual.  Then we can switch the links.

**Comment by Tom-Willemsen** [comment]
@Kevin-Woods-Tessella here are the places where we link to github from the GUI repository: https://github.com/ISISComputingGroup/ibex_gui/search?q=%22github.com%22&unscoped_q=%22github.com%22

**Comment by ThomasLohnert** [comment]
PRs:
- [ ] https://github.com/ISISComputingGroup/ibex_utils/pull/50
- [ ] https://github.com/ISISComputingGroup/ibex_gui/pull/1030

There is also a file documenting the solution in ICPDiscussions under "Security"

**Comment by Kevin-Woods-Tessella** [comment]
I have updated the links, so that the source is in the User Manual.  The developer manual now contains links to the User Manual (so that the content is not duplicated).  The new links can be seen from here: https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Device-Specific-Guidance (note: in practice, the user sees the mirrored content on shadow, rather than this particular github address).

**Comment by ThomasLohnert** [comment]
Sorry, must have branched off the wrong branch on ibex_gui initially.

PRs:
- [ ] https://github.com/ISISComputingGroup/ibex_utils/pull/50
- [ ] https://github.com/ISISComputingGroup/ibex_gui/pull/1033
