### ISSUE TITLE
HIFI: Control of Stanford DG645 Digital Delay Generator

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5154]
As a HIFI scientist, I want IBEX to support the Stanford DG645 Digital Delay Generator on my instrument, so that I can use it with IBEX in my experiments.

#### Acceptance Criteria
1. Solution provides equivalent functionality to existing solution in SECI.
1. I can control the Stanford DG645 Digital Delay Generator on HIFI via the IBEX GUI
1. I can control the Stanford DG645 Digital Delay Generator on HIFI via genie_python

#### Notes
1. The _**same**_ physical DG645 unit is used primarily by HIFI and EMU (other muon instruments use it too, but not as frequently).  However, HIFI uses it in a different configuration to EMU.  The purpose of this ticket is to make sure we cater for both configurations.
1. The SECI VI is located here: `C:\LabVIEW Modules\Drivers\Stanford DG645`.  Please consult the VI to ensure the IOC and OPI provide equivalent functionality.
1. Consult the [HIFI instrument wiki](https://github.com/ISISComputingGroup/IBEX/wiki/HIFI-Instrument-Details) page for additional documentation
1. The DG645 is used in RF experiments on muon instruments.  Check `C:\LabVIEW Modules\Muon RF` and `C:\LabVIEW Modules\Instruments\MUSR\RF Experiment` to see how the DG645 driver is used.  Also ask the scientists how they use the RF equipment.
1. The DG645 is used as part of the Muons RF Kit.  It may be that the OPI needs to be incorporated into a custom OPI (involving other RF devices - ticket #6083 )

**Comment by JamesKingWork** [comment]
Also required for EMU RF Kit

**Comment by JamesKingWork** [comment]
@davidkeymer was looking at an already existing IOC for this originally

**Comment by rerpha** [comment]
https://github.com/epics-modules/delaygen will control the DG535 and DG645

**Comment by ChrisM-S** [comment]
Thanks @rerpha,  I can see that this driver contains code for the NI RS232-GPIB Interpose connector (https://github.com/epics-modules/delaygen/blob/master/delaygenApp/src/nigpibInterpose.c).  This is an NI hardware RS232-GPIB converter/connector which can be ordered [here](https://www.ni.com/en-gb/shop/hardware/products/gpib-instrument-control-device.html?modelId=120480).  It's quite expensive and we would need to buy 2 (for a swap in spare).  It is likely that this is the place where code for the NI GPIB-Ethernet 1000 code would go - although as @FreddieAkeroyd point's out we might use VISA for this - not 100% sure that it's essential to use VISA to talk to the GPIB ethernet box directly, but it may be easier not to code all this manually.

**Comment by FreddieAkeroyd** [comment]
Do we need GPIB? There is a DG645 plugged directly into a moxa via serial in the R2/R3 link office

**Comment by ChrisM-S** [comment]
This is just for the DG535 which generates delays for the muon kickers which only has a GPIB port.  The DG645 looks like an upgrade in all ways (including RS232, Ethernet & GPIB), but it also has an upgraded price...

**Comment by FreddieAkeroyd** [comment]
I'm not convinced we can use the version in `delaygen` without an NI GPIB-RS232 converter, may be better to use the NSLS-II one and then hook it up to the asyn-visa connecter we have.

**Comment by ChrisM-S** [comment]
Could we add control of this device via the NI-GPIB interface to the acceptance criteria?  This could be done in the office at the same time and would make this very likely also suitable for a Muon DG535 on the FE Kickers.

**Comment by Adam-Szw** [comment]
Pull requests (hope I didnt miss any)
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6840
IOC master: https://github.com/ISISComputingGroup/EPICS-ioc/pull/646
Delaygen mirror: https://github.com/ISISComputingGroup/EPICS-delaygen/pull/1
IBEX GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1369
Support module: https://github.com/ISISComputingGroup/EPICS-DG645/pull/1
EPICS top: https://github.com/ISISComputingGroup/EPICS/pull/275
WIKI page added: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Stanford-DG645

DG645 is connected in the office currently for testing + I have a correctly setup VI to help with review, if needed.

**Comment by JamesKingWork** [comment]
I may not get time in the next few days or so to do this review, so am taking myself off it so others can pick it up if they get the chance. I didn't get too far with it, but if I get the chance I may pick it back up again.

**Comment by JamesKingWork** [comment]
I have reviewed the code and style quite heavily and less on the functionality side. I think someone other than me should sit down and learn about the functionality after the rework, in order to properly review that this IOC meets the needs of the scientists. This would be easier if the IOC tests and documentation were a bit more explanatory about the functionality of the device. We should also demo a simulated version to the muon group when complete and get feedback. Good work in general but needs a bit of a tidy and the documentation here https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Stanford-DG645 could be a bit more fleshed out.

**Comment by ThomasLohnert** [comment]
Tests, emulator, functionality look good as far as I can tell! I think the OPI could use a little bit of polish though:
- [ ] DG645 front panel OPI should be kept in the folder along with the linked OPIs
- [ ] There's a typo in the title: "Standford" should be "Stanford"
- [ ] I think you only need 1 OPI each for Graph... / SP... / RB... instead of one for each channel (other than Trigger, which is slightly different). As far as I can tell the only difference between those is channel (A-F) and in the case of setpoint groups, the title. You can pass as a macro via the linking container properties e.g. `CHANNEL = A`  and then use it in a generic widget e.g. PV= $(PV_ROOT):DG645_01:$(CHANNEL)DELAY:SP. (Do this first, then you only have to make all the changes below once)
- In general, the OPI is pretty large - do we know whether this is a concern at all? In any case, I think there is a lot of wasted space, I think we can make everything a bit more compact and readable. Some suggestions:
    - [ ] Get rid of the group boxes around setpoints, readbacks, and start/width/end panels. Put horizontal separators in between the channels instead (I have put a mockup how I imagine this to look at the end of this comment). Make sure the separators align. This will also help the SP OPIs to fit inside the SPs group horizontally, at the moment they get slightly downsized which makes it look a bit off
    - [ ] Do we really need 8 digits precision on the delay and start,width,end readbacks or can this be reduced a bit? It seems to me they can just change the unit which changes the readback unit too. Sorry if I've missed something here!
    - [ ] Disable "Show Legend" property on graphs - don't think this adds anything of value
- Some other details:
    - [ ] Can we make all LEDs the same size? (unless this is on purpose)
    - [ ] TTL, NIM and NR labels are not properly horizontally aligned, same for + and - for polarity readbacks
    - [ ] Make the title for each channel a bit bigger

![image](https://user-images.githubusercontent.com/18398579/157667781-7aa283b0-1c11-40ce-b9fa-b586cdd7b01d.png)

**Comment by Adam-Szw** [comment]
@ThomasLohnert  Thanks for reviewing and suggestions! Some of the things I can't change:
- 'Get rid of the group boxes around setpoints, readbacks, and start/width/end panels.' - This box comes from linking container which is part of acceptence criteria so sadly I cant make it look like your sketch, but I will improve how it looks in a different way
- 'Do we really need 8 digits precision on the delay and start,width,end readbacks' - This is the precision from VI so it's safe to assume the scientists would like this to remain. I spent quite a bit of time with James to make it hide trailing 0s and it turned out impossible without implementing complicated logic in the OPI (which we want to avoid) so decision was made to leave it like this. If you think it's a big issue I could drop a message to scientists what kind of precision they would like.

The rest of the stuff I'm currently implementing.

**Comment by ThomasLohnert** [comment]
> This box comes from linking container which is part of acceptence criteria so sadly I cant make it look like your sketch, but I will improve how it looks in a different way

You should be able to do this by editing the linked OPI (not the top level OPI, those changes won't stick). Change property "Border Style" from "Group Box Style" to "None"

> This is the precision from VI so it's safe to assume the scientists would like this to remain. I spent quite a bit of time with James to make it hide trailing 0s and it turned out impossible without implementing complicated logic in the OPI (which we want to avoid) so decision was made to leave it like this. If you think it's a big issue I could drop a message to scientists what kind of precision they would like.

You might be able to just change the `.PREC` field in the relevant PVs, but don't worry about it if this is what the scientists want.

**Comment by Adam-Szw** [comment]
> Change property "Border Style" from "Group Box Style" to "None"

Yeah I know, just thought that linking container has a box but just realised that it's actually the OPI its linking to has box on it so I can deal with it no problem 👍 

> You might be able to just change the .PREC field in the relevant PVs 

It's not the problem that I can't change precision (I consciously made it to PREC 8 when making IOC because that's how precise values can be according to existing VI). The problem is that when a value is let's say 2.534, it will show 2.53400000 (trailing 0s) and this can't be rid of without scripted logic to be implemented in OPI (which we want to avoid) . If trailing 0s could be cut off easily we could have precision of 100 and it would always show 2.534. Upon revisiting this I think there is a possibility of implementing CALC record logic that would write to PREC field and dynamically set this to cut off trailing 0s so I will investigate if it's feasible but that would still only visually make it less cluttering as space still has to be reserved for potentially 8 decimal values.

**Comment by ThomasLohnert** [comment]
Ok, don't worry about it too much - I think this is less important for readability. We can always revisit it if the scientists are not happy with the size of the OPI.

**Comment by ThomasLohnert** [comment]
@Adam-Szw  Ok, don't worry about it too much - I think this is less important for readability. We can always revisit it if the scientists are not happy with the size of the OPI.

**Comment by Adam-Szw** [comment]
@ThomasLohnert In that case feel free to check out latest commit and see how it looks now and if there is anything more I could improve
