### ISSUE TITLE
Periodically appearing git window

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5159]
As a user I do not want a window to periodically pop up on my instrument. The window is running a git command but further investigation is required as to where it's getting run from.

This issue can be (somewhat) reliably reproduced by causing the client to take a lot of CPU by exploiting https://github.com/ISISComputingGroup/IBEX/issues/5136. The window then pops up more regularly.

**Comment by aaron-long** [comment]
I was able to find the cause of this with help from @Tom-Willemsen as we encountered it "in the wild". It related to the Python 3 NICOS server being out of date and failing to start while the client repeatedly attempts to open a connection to the process. 

I wrote a short [wiki entry](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/NICOS-notes) for troubleshooting this and since we have updated our builds with the latest Python 3 + included NICOS in the pip requirements.txt it should be fixed.
