### ISSUE TITLE
BUG: Enum format converter and mbbi/mbbo's behaviour has changed between versions.

### ISSUE THREAD

**Issue by aaron-long** [ISISComputingGroup/IBEX#5257]
While investigating the System IOC test failures, I noticed that the Icefridge had consistent failures that seem to have been instigated since we updated dependencies [#5152]. This is most likely from updating to Stream Device 2.7.7 although I cannot find the specific change in the (release notes)[https://github.com/paulscherrerinstitute/StreamDevice/releases] that has caused this behaviour.

NDXDEMO is currently running the pre-updated version of the dependencies and the Icefridges IOC tests run, however on an updated specific tests fail. The cause of the failure is due to the pattern used in the Icefridges mbbi/mbbo records fields for values and the protocol files format converter enum.

In protocol methods such as `setExcVoltageRange` the enum format converter is used `%{01|02|03|04|05|06|07|08|09|10|11|12}`  etc. This is read into an mbbi and paired against a redefined index `field(ZRVL, "1")`. The specific pattern used in this record causes issues, but can be fixed by removing the index value definitions in the record.

You can use the following grep to search for db's in support or IOC to identify if this same pattern is used elsewhere: `find . -iname "*.db" -exec grep -H "ZRVL, \"1" {} \;`.

After some testing of the IOC's that use ENUM format converters AND have existing test coverage I haven't yet found another IOC that suffers this same breaking behaviour. However, it might be that our test coverage is not sufficient to catch all cases.

Acceptance criteria:

- [ ] ICE fridge tests now pass

- [ ] The reason this has suddenly become a problem is fully understood and documented.

**Comment by aaron-long** [comment]
- https://github.com/ISISComputingGroup/EPICS-icefrdge/pull/5

**Comment by Alexandru-Dascalu** [comment]
We are not sure why the behaviour of mbbo records have changed, so we should ask on Tech-Talk.

**Comment by Alexandru-Dascalu** [comment]
I have added a trace mask to the st.cmd and found that when running the valid value tests (not the ones for testing invalid values) for the Lakeshore heater range and voltage range on the new EPICS build, the voltage range test fails because the IOC sends the value 3 instead of 2 to the emulator. The heater range test still passes.

For the voltage range, I used an input of  "6.32 uV" , which is the value of ONST. According to the current EPICS mbbo record reference documentation, the given value should be matched with the string in ONST, which would make the VAL field be 1 (index between 0 and 15), which would make the RVAL field be set to 2, which is the value in ONVL. The value of RVAL should then be sent to the device. However, looking at the devsim log after putting a trace mask shows us that instead the mbbo record writes 3 to the device. If I run the same tests on an old PICS build, before the dependency updates, the tests pass and the IOC sends 2 to the device.

I have also discovered that on the new EPICS, build, the tests pass if in the protocol file I replace the %{01|02|..|12} formatter with a %d formatter.

The heater range test appears to be unaffected because the ZRVL, ONVL, TWVL, etc. are set to 0, 1, 2, etc., so the index matches with the value.

**Comment by Alexandru-Dascalu** [comment]
@FreddieAkeroyd said they might have changed something in EPICS bas, in Stream Device or in the mbbo record. He said they may have changed something so it did what the documentation said it should, or changed both the behaviour and the documentation. Unfortunately, old versions of Stream Device Documentation can still be found online.

**Comment by Alexandru-Dascalu** [comment]
Confusingly, on the new EPICS build, and on the master branch, if you use caput to write to the voltage range setpoint with a string, the readback will return that exact string. But on the same build the test fails if it writes that same value.

https://github.com/ISISComputingGroup/genie_python/blob/fd8053e90354c106a5222cfa2b3fc8d679e1d8b5/Lib/site-packages/genie_python/genie_cachannel_wrapper.py#L278 is a method in genie python that replaces string input with the corresponding index.

We should investigate why on the master branch writing using a caput works, but the tests fail. It may be that the above genie python method no longer works correctly, and we should know why.

**Comment by Alexandru-Dascalu** [comment]
Moved comments with extra info about the issue to https://github.com/ISISComputingGroup/IBEX/issues/5263 .
