### ISSUE TITLE
Check scan library for Python-3 incompatibilities

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5271]
As a developer using the scan library, I want to check the scan library for Python-3 incompatibilities, so that scientists can be confident it will run when we  migrate to Python-3.

#### Acceptance Criteria
1. scan library is run through Python-3 checker
1. Incompatibilities, if any, are listed.  Include both "errors" and "warnings".

#### Notes
1. The purpose of this ticket is just to check the scans library.  If changes are needed, they will be done later.
1. Ask @ThomasLohnert if you need to know the location of the scans library.

**Comment by RaiBishal** [comment]
**Errors:**

- In `larmor/scans.py` line 128 change `semsans_pol = generic_pol(range(40971, 41226 + 1), preconfig=setup_dae_semsans)` to `semsans_pol = generic_pol(list(range(40971, 41226 + 1)), preconfig=setup_dae_semsans)` and add `from builtins import range` on top to make it backwards comaptible with Python 2.`range` does not return a list anymore so, we need to explicitly  make it a list.

**Notes:**

- After importing `from __future__ import division`  we do not need a floating-point number to do a floating-point division for e.g. `5/2` instead of `5/2.0`.
