### ISSUE TITLE
Alarm History: discuss potential implementations

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5422]
It was asked at the SAG if it was possible to access alarm history, a value may go into alarm and then it may clear and the scientist would be unaware the next day there had been a problem.
 
It looks like CS Studio has support for this http://cs-studio.sourceforge.net/docbook/ch31.html which would require us to run a jms2rdb service. Running the service would be easy, how easy would incorporating this view into IBEX be? Or could it this be run as a standalone app for the scientist just to start when needed?

We should also consider, especially if we think about a standalone app, whether the phoebus alarm view provides the details. However I believe the phoebus system uses Kafka, so this may lead into a longer discussion of how to provide a reliable Kafka service. 

# Acceptance Criteria
- There is a meeting to discuss how this is done
- There is a document describing how we want to do this going forward
- Tickets are created for implementation

**Comment by John-Holt-Tessella** [comment]
Is this just if blocks go into alarm or if there is an alarm on the alarms view or both?

**Comment by kjwoodsISIS** [comment]
Some scientists would like to know "was there a transient alarm on my instrument".  This particular case was sparked by a discussion with the muon scientists.  They came in one morning and suspected that something had happened overnight (on RIKEN front-end, I think) and they wanted to investigate further.  However, when they look at the Alarm View, there was no alarm.  The suspicion was that the condition corrected itself and the alarm was cleared.  However, because the event happened overnight, no-one noticed at the time.  if there was a log that they could consult, they could have allayed/confirmed their suspcions.

Fundamentally, all the scientists need to be able to do is check if there was a transient alarm during some defined period (i.e. can I look in a log file to see if there was a transient alarm overnight?).  They don't necessarily need to be warned that a transient alarm occured (although that might be a nice things to do).  In fact, I would be very careful about generating such warnings - some scientists might like it, others might not.  And it could confuse users.

**Comment by ChrisM-S** [comment]
I'm wondering whether an alarm that, say, turned on briefly overnight should also be coupled with an alert (e.g. via Nagios) so that something could be done at the time - if it mattered that is?

Would a record of the alarm be sufficient for any diagnosis or would the record of this be better if it also listed the inputs of the alarm (e.g.  temp1 > 10.0 - what was temp1 at the time?).

**Comment by FreddieAkeroyd** [comment]
@ChrisM-S the alarm would have to be on for a while for nagios to notice, unless the alarm was pushed to nagios. It may be "x in alarm" could be added to other sorts of alerts like "x > 10" that we could add notifications for from within ibex.

**Comment by FreddieAkeroyd** [comment]
The alarms view currently contains items that we have marked as alarm in the DB file plus blocks, it would need jms2rdb running to create an alarm log (which might be useful). If an item is being logged to either the instrument or block archive, the alarm status is recorded there along with the value. So we actually have information already in MySQL, but there may be additional things we want to log alarms for which are not archived.

**Comment by davidkeymer** [comment]
If we are to make more use of the alarm view as part of this ticket, then we should make sure that each IOC has an alarm record as per the instructions [here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches#3-alarm-pvs).

Does the DBchecker script highlight these?  If so, then maybe only as warnings and perhaps they should now be made errors.

**Comment by FreddieAkeroyd** [comment]
Need to confirm from scientists if alarm history rather than latching is sufficient, if so then potentially spin out new ticket rather than #6682   new ticket woudld be to add product referred to to cs-studio build, and then include in part of ibex like alarm server. There is then a alarm history view that would need including in the client

**Comment by FreddieAkeroyd** [comment]
Have added both latching and history in ticket #7943
