### ISSUE TITLE
Remote access for IBEX: discuss 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5423]
As discussed at the SAG, an ISIS cycle in September may involve potential remote user interaction, this is not to control the experiment, but to monitor it and then potentially request instrument scientist intervention. The web dashboard does not provide sufficient information, it has been asked if the remote user could run something like the IBEX client read-only.

Remote users have fed ids but do not generally have VPN access, so running an IBEX client directly would require some port forwarding / firewall holes. One potential option may be to run the client on the IDAAS cloud as the network forwarding should be easier and ibex could be pre-installed and configured on the cloud image, it could also be run alongside Mantid with kafka live view. The main issue for is here is that the cloud images are Linux only, so we would need to make sure the Linux client build was working sufficiently well. As we are not allowing control this way, a working genie python may not be critical, but that would require further checking.

Another option might to be provide users with remote access to a windows machine instead, but this could require additional infrastructure to be put in place.  

# Acceptance Criteria
- Send a message to gather requirements from scientists
- Have a meeting to discuss how we would give users remote access
- Document how we are going to do this

**Comment by kjwoodsISIS** [comment]
I think we should take a broader view.  We should define the use-cases we envisage.  These will help us identify all the things we can do to help remote scientists interact with instrument scientists running experiments on their behalf.

**Comment by KathrynBaker** [comment]
Whilst slightly more focussed I would recommend at least reading the document at http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/Control%20of%20a%20Beamline%20from%20a%20Mobile%20Device.docx – this was a very early user story relating to control from mobile devices, there are opinions and requirements in there which are still likely to be sound and it includes remote access more generally as well, so awareness is probably helpful for considering use cases some pitfalls etc. even if the content now needs revisiting and verifying as necessary.

This email and any attachments are intended solely for the use of the named recipients. If you are not the intended recipient you must not use, disclose, copy or distribute this email or any of its attachments and should notify the sender immediately and delete this email from your system. UK Research and Innovation (UKRI) has taken every reasonable precaution to minimise risk of this email or any attachments containing viruses or malware but the recipient should carry out its own virus and malware checks before opening the attachments. UKRI does not accept any liability for any losses or damages which the recipient may sustain due to presence of any viruses. Opinions, conclusions or other information in this message and attachments that are not related directly to UKRI business are solely those of the author and do not represent the views of UKRI.

**Comment by kjwoodsISIS** [comment]
The remote working scenario is roughly this.  I say roughly because no-one is quite sure how all this is going to work in practice - so we may need to be flexible.  
1. ISIS accelerator has started up again
1. ISIS is able to run a limited user programme (perhaps from September)
   1. Strict social distancing will apply
   1. Reduced levels of on-site staffing
   1. No users will be allowed to travel to ISIS
1. Some but not all instruments will be running
   1. Instrument scientists will run experiments on behalf of users
      1. Users WILL NOT have remote control of instruments
   1. Instrument scientists would like users, and users will want, to see how experiments are progressing.
      1. Users may want to discuss progress, events, etc. with instrument scientists
      1. Users might wish to change what they do in run N+1, based on the outcome of run N, etc.
      1. The web-dashboard does not provide sufficient information for this style of working.
   1. Instrument scientists might ask users to write their own scripts, which can then be executed by the instrument scientist.
1. Users will need to analyse their data from remote locations (not strictly an IBEX problem, it's more in Mantid's line).

**Comment by ChrisM-S** [comment]
Maybe worth noting that scientists will likely be users and will likely have remote control of instruments from home as normal - and I guess may be encouraged to work from home has much as possible.  Bringing in users with view/readonly rights might be more of a Zoom sort of thing than a web dashboard/client sort of thing...

**Comment by FreddieAkeroyd** [comment]
I guess the scientists could zoom with a user from home and share an ibex client window with them and discuss.

**Comment by FreddieAkeroyd** [comment]
To add to Kevins list:
* From the SAG, better read-only remote user access seemed a must
* related 3(ii)(b) user control in a limited way may be desirable e.g. start/stop collection, change number of periods, move to next sample. Whether software limits could be applied to allow further control of sample environment equipment would need to be considered carefully. 
* data analysis has often been done with a copy of the nexus file on a local analysis computer, maybe after updatestore. Working remotely, we may need to make sure either Mantid liveview is working on all instruments for example, or make sure data files can get to e.g. IDAaaS in good time.

**Comment by DominicOram** [comment]
> The web-dashboard does not provide sufficient information for this style of working.

What is the additional information required?

The original text of this ticket discusses how we can make IBEX run for remote users, which may be the solution, but we should evaluate it against making the webdashboard provide the information that is required to run remotely.

**Comment by kjwoodsISIS** [comment]
Yes, but the discussion at the SAG meeting was more about remote working in response to the current Coronavirus situation and what can we (the Experiment Controls group) do to facilitate remote working.  Web dashboard could be part of the solution, remote running of IBEX could be another.  We should explore the problem space (i.e. make sure we understand remote working) before jumping into solution space.

**Comment by DominicOram** [comment]
I think @FreddieAkeroyd has started this ticket and is drafting the email, just going to assign it to him so that someone else doesn't pick it up

**Comment by FreddieAkeroyd** [comment]
Feedback from scientists in folder in MS Teams, meeting with IBEX team scheduled for Tuesday 23/6

**Comment by FreddieAkeroyd** [comment]
Initial tickets created

**Comment by kjwoodsISIS** [comment]
Each acceptance criterion has now been addressed:
1. Send a message to gather requirements from scientists
   - e-mail sent, responses gathered (stored in General/Files/Remote Users Sep 2020 in MS-Teams).
1. Have a meeting to discuss how we would give users remote access
   - meeting held 23/06/2020
1. Document how we are going to do this
   - plans/proposals documented (also stored in General/Files/Remote Users Sep 2020 in MS-Teams).
This ticket now believed to be complete.

**Comment by DominicOram** [comment]
Agree with @Kevin-Woods-Tessella that this is done.
