### ISSUE TITLE
Reflectometry: Nesting Components

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5449]
As a POLREF / OFFSPEC scientist, I would like to be able to designate components to be "on" other components (e.g. detector "on" bench), so it takes the position and angle of the component it is sitting on into account for its own position as an offset.

#### Acceptance Criteria
- Components can be designated to be "on" other components
- Component Z is relative to bench Z
- When the position of a base component changes, the offset on nested components is updated
- Propagate alarms, moving state, etc. from underlying component

**Comment by John-Holt-Tessella** [comment]
Having revisited the ticket this is almost all accomplished through direct axes. They are relative to the bench. The bench is usally alligned to the beam and therefore these parameters are offsets from the beam. It is possible that the bench could not be aligned to the beam but in this case you don't want to move the components anyway and it is not all that helpful to know how far off the beam they are. On top of this the maths is hard because of the 3D nature. I am going to refactor the configuration so that it uses direct parameters and then close this ticket.
I think we understand more about the bench now so I think that is why we didn't think about this earlier.
There is a branch https://github.com/ISISComputingGroup/EPICS-refl/tree/Ticket5449_nested_components which I will leave open for now with the start of this ticket on.

Aleterred config is in normal place.
