### ISSUE TITLE
IMAT: Assistance with Migrating to Python-3

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5516]
One of the IMAT instrument scientists (Anna Fedrigo) has encountered problems using Futurize to migrate instrument scripts.  Please provide advice & assistance 

> I’ve been trying to convert IMAT scripts into python 3, but I could not get futurize installed. I tried both INES instrument computer (as IMAT one is off) and my personal laptop, but I got the attached errors. I wroto to IT to get NDXIMAT restarted, but I haven’t received a reply yet.
>  
> Could you help me please?
>

**Comment by kjwoodsISIS** [comment]
![IMAT_1](https://user-images.githubusercontent.com/7249337/85751091-2d891e80-b702-11ea-828a-6f211f0346a7.jpg)
![imat_2](https://user-images.githubusercontent.com/7249337/85751109-2feb7880-b702-11ea-9893-017ea2ad6082.png)

**Comment by DominicOram** [comment]
@RaiBishal Can you please document the solution either on this ticket or in the wiki? Are IMAT now happy?

**Comment by RaiBishal** [comment]
@DominicOram Futurize was already installed on the IMAT machine when I checked so didn't think documenting it was necessary. However, there was another issue with pip which has been fixed with this PR: https://github.com/ISISComputingGroup/genie_python/pull/270. 

I also gave Anna on instructions on how to install futurize on her personal laptop as she was having an issue with it too.  Should this be documented?

Yes, last time I checked in with Anna, she was happy with it.

**Comment by DominicOram** [comment]
I think this is enough of documentation and sounds like a good resolution, thanks Bish!

**Comment by kjwoodsISIS** [comment]
How many points was this?

**Comment by RaiBishal** [comment]
@kjwoodsISIS roughly 2 points.

**Comment by kjwoodsISIS** [comment]
Then please add a 2 points label.
