### ISSUE TITLE
Cloud VNC: Deploy on viewing machines

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5517]
As an user I would like to be able to view/control my experiment whilst not on site and not on a VPN. #5507 is investigating a cloud VNC solution that could provide this functionality. Assuming positive results from this we should deploy the solution.

Notes:
* We expect to deploy this on NDC/NDL machines rather than NDX machines
* We should approach FIT about putting the VNC program in software center and getting either them or scientists to do the actual deployment

## Acceptance Criteria
* The software is available in software center and there is documentation for scientists in how to install and use it
* If we cannot put the software in the software center then it has been deployed by us on the instruments that require it
* There is an instrument with this on as a test

### Notes
* Follows on from [investigation and testing ticket](https://github.com/ISISComputingGroup/IBEX/issues/5507)

**Comment by davidkeymer** [comment]
#### Notes for reviewer:

- Still waiting for an answer from the Service Desk as to whether the RealVNC server and client applications can be made available in the Software Centre.  In the meantime, they can be downloaded from the RealVNC website.
- Instructions have been written (but not widely published to date) so that instrument scientists can install the server on their chosen machines themselves, which the Muon Group have done (see discussions and link to instructions in #5507).
- A test server was set up for this (repurposed LMX machine).

**Comment by kjwoodsISIS** [comment]
Can we chase the Service Desk - it's been a few days since you asked.

**Comment by DominicOram** [comment]
As Kevin said, it would be good to chase service desk but I know they're busy. But given the workaround of downloading from the website I don't think this ticket needs to be blocked on that.
