### ISSUE TITLE
Document physical cabling for migrating Galils to Ethernet 

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#5525]
As a technical support person, I would like to have a guide available for how to physically connect Galils to an instrument machine via Ethernet for when we migrate an instrument from SECI to IBEX. This resource will be useful for non-group members doing this task on our behalf when on site (i.e. FIT doing the cabling for POLREF, INTER, SANS2D)

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrating-Galil-motors-from-SECI-to-IBEX#physical-cabling

Thanks for reviewing this @DominicOram

**Comment by DominicOram** [comment]
Looks good, only minor comment is that in the diagram of the counting house the NDH will already have a second cable to the public ports on the switch. It might be worth including that in the diagram to be clear that this cable should stay where it is and not be moved over to the private port and you should end up with two cables rather than one.

**Comment by DominicOram** [comment]
@ChrisM-S and @FreddieAkeroyd, SANS2D have a DAE3, I can't remember if that changes anything about how we do this setup?

**Comment by DominicOram** [comment]
Discussed DAE3 differences with Freddie/Chris in person, I was incorrect that they had a DAE3. In which case I'm calling this done, thanks.

**Comment by FreddieAkeroyd** [comment]
There was talk of POLREF getting a DAE3 for September, but I haven't heard if that is still going ahead - amongst other things it depended on whether DAE3 support for the spin flipper was going to be ready in time.
