### ISSUE TITLE
Galil / motor record:  negative backlash causes moves in negative direction to run at BVEL instead of VELO

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5657]
As a developer I would like galils to move at the correct speed when doing a move.

For a motor with the following setup, negative moves (much larger than BDST) are done using the backlash speed (BVEL) as opposed to the normal movement speed (VELO). Positive moves use the correct speed.

![image](https://user-images.githubusercontent.com/24375813/91164991-dda9e200-e6c7-11ea-9162-a072ebd7e5dd.png)

# Acceptance criteria

1. Negative moves larger than BDST are run at VELO rather than BVEL for a motor with a setup similar to above (in particular with negative BDST)
1. There is a test that proves this.

**Comment by JamesKingWork** [comment]
It does not occur in simulated motors

**Comment by FreddieAkeroyd** [comment]
I believe this is fixed in above PR. The issue does occur with simulated motors, but only for relative moves. If the simulated motor test was done without motor retries enabled then moves are absolute and it would not show a problem. We enable retries on the galils and so they always do relative moves (when they have an encoder)
