### ISSUE TITLE
SUPPORT: Scripting on MERLIN

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5685]
A MERLIN instrument scienitst needs help with scripting.

**Comment by ChrisM-S** [comment]
Looks like the function

Inst.set_ei(20,150,’s’)

Works whereas what looks like a polymorphic version

Inst.set_ei(white=True)

Does not?

Possibly a phython 3 change

This email and any attachments are intended solely for the use of the named recipients. If you are not the intended recipient you must not use, disclose, copy or distribute this email or any of its attachments and should notify the sender immediately and delete this email from your system. UK Research and Innovation (UKRI) has taken every reasonable precaution to minimise risk of this email or any attachments containing viruses or malware but the recipient should carry out its own virus and malware checks before opening the attachments. UKRI does not accept any liability for any losses or damages which the recipient may sustain due to presence of any viruses. Opinions, conclusions or other information in this message and attachments that are not related directly to UKRI business are solely those of the author and do not represent the views of UKRI.
