### ISSUE TITLE
Support: HRPD Intermediate saves not be copied externally until end of run

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5707]
On HRPD the intermediate saves are not being copied externally so they can not be looked at by Mantid. Can we enable this feature for them?

Chris may have knowledge of how to do this based on MAPS.

### Acceptance Criteria

- HRPD intermediate saves are being exported after being written
- Someone other than Chris understand the process
- The process is documented on the wiki

**Comment by ChrisM-S** [comment]
The issue was down to configuring Mantid on the analysis machine without the local data path from the instrument PC being available.  See Page 3 [here](https://www.isis.stfc.ac.uk/Pages/muon-data-analysis-workbook.pdf) for details about setting Mantid search paths for the available data.

Intermediate and raw data files are kept available in the local instrument export area and should ideally be first in the search path, followed by local data cache areas kept on some instruments and then followed last by the path to the data archive - data takes longer to reach this area and may also be subject to network issues. [see teams here for more detail](https://teams.microsoft.com/l/message/19:4e381ff6b5674230a74878b1355eec22@thread.skype/1599840227704?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=d9946ec3-a454-424f-b673-5ffcb9f9ade0&parentMessageId=1599811527913&teamName=IBEX%20Developers&channelName=email-exp-controls&createdTime=1599840227704)

**Comment by DominicOram** [comment]
Good write up, thanks!

**Comment by kjwoodsISIS** [comment]
How many points was this?
