### ISSUE TITLE
SANS: Sample Changer - Reload Presets

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5725]
As a SANS scientist I need to be able to reload preset positions, so that I can use any that have been modified.

#### Acceptance Criteria
1. The following features are available on the advanced tab of the OPI (see #5719).
1. There is a "Reload Presets" button
1. On clicking a "Reload Presets" button, the OPI reloads the preset values and make them available for use.

#### Notes
1. None, so far.

**Comment by Tom-Willemsen** [comment]
Covered by #5720

**Comment by DominicOram** [comment]
Currently the available slots will update automatically when I update a file but the rest of the information only updates when you hit reload config. This can get you into a weird situation where it looks like you're up to date with what's on disk but you're not. Also, can we add some tests for this functionality? I added https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/Ticket5725_samplechanger_reload_configs but it currently fails due to the above issue

**Comment by Tom-Willemsen** [comment]
I think your comment above may have been caused because we were appending a second identical slot (just with a different name), which then gives duplicate positions and fails to write the file properly. I've added tests for all the cases I can think of (no changes to sample changer code).
