### ISSUE TITLE
Support: IMAT motor not moving

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#5767]
A call came in saying that the IMAT small tomography 3 axis stage was not able to move. When inputting a setpoint whilst using the encoder no move was reported by the encoder, when inputting a setpoint whilst not using the encoder IBEX thought it was moving but we could see the motor was not moving. 

After the Galil controller was restarted IBEX started to be able to move the motors with a correct encoder reading. However, when using the encoder the max retry amount was exceeded and IBEX often did not reach the setpoint. Furthermore, when the encoder was not used and IBEX reported it had moved a certain amount the encoder correctly gave values smaller than the expected move degrees. The motor resolution was halved and then on retrying the same steps IBEX moved the correct amount.

Whether this was due to microstepping being set in the controller or some other reason we are not sure.

Further concerns include
- We observed that the motor value and setpoint did not stay at the original setpoint for long after being initially set they tended to move around quite close to the original setpoint but sometimes as far as 2 degrees out. 
- The motor and encoder values drifted quite a lot after moves.
- Homes did not always jog to zero as was expected (however they did get to a repeatable value)

**Comment by JamesKingWork** [comment]
@DominicOram @FreddieAkeroyd not sure if there's anything I missed there

**Comment by DominicOram** [comment]
Sounds about right, thanks @JamesKingWork. Since then Jamie has sent 
[System_Setup_for_91000_and_92000_stages - 20181123.txt](https://github.com/ISISComputingGroup/IBEX/files/5300340/System_Setup_for_91000_and_92000_stages.-.20181123.txt) which actually gives the resolution as the 0.0036 now set on IMAT. We should make sure that the autosave files referenced in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IMAT-tomography-stages are corrected to have this value and whilst there we should also:
* Change the description on the first three axes to show them as A, B, C
* Set the other axes to disabled

The further concerns that you mention above should also be addressed in shutdown in a separate ticket.

@JamesKingWork are you happy to do all the above?

**Comment by JamesKingWork** [comment]
Further concerns ticket: #5768

**Comment by JamesKingWork** [comment]
DESC and MRES now set to the axis (a, b or c) and 0.0036 for motors 01, 02, 03 in GALIL_08_settings.sav in the galil_08_3_axis from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IMAT-tomography-stages. _able set for all unused axes in the same file.

**Comment by JamesKingWork** [comment]
How to disable motors in the motor view: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records#motors linked from https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motor-IOCs#other-info

**Comment by FreddieAkeroyd** [comment]
So the 2 axis stage has mres 0.0072 and eres  0.018 and the 3 axis stage mres 0.0036 and eres .01 - the 3 axis stage had the correct eres but double mres.

I've just looked at the autosave file for the 2 axis stage and it too has  eres correct but mres 0.0144 i.e also double!
Curiously the  autosave files date from September 2018 but the above document is from November 2018, so did something changed and the new values didn't get carried across?

**Comment by FreddieAkeroyd** [comment]
Sorry, 2 axis is correct - I was looking at a copy in instrument\var not instrument\var\autosave, i have removed this
