### ISSUE TITLE
EMMA-A: clock drift 

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5773]
The epics clock is drifting on emma-a, it started doing this around 14:00 on Saturday 3/10 and has lost 80 seconds in 24 hours. The system time looks fine, EPICS uses the windows high precision timer with periodic resyncs to system time. Looking at nagios record of inst etc time difference shows that the EPICS clock is less stable on emma than elsewhere, usually difference on instruments is always < 1s but on emma it has regularly got up to 7s before being reset and now is not being reset at all. Note has been sent to instrument scientist in case timestamps were being compared to external reference.   

## Aceptance criteria

* clock drift understood and fixed

**Comment by FreddieAkeroyd** [comment]
The system clock on emma seems less stable than other instruments, regularly oscillating between 1 and 3 seconds out. Maybe this confuses the epics sync loop? While writing (17:00 4/10) the time difference has just reset back to OK.

**Comment by ChrisM-S** [comment]
Hi Freddie,

I’ve just checked my suspicion when I saw your last message.  It’s because the Domain Time client has never been installed on EMMA – which means it is as stable as windows time on a VM - likely without updates from the host server enabled (that is about as stable as a jelly on a skateboard).

I’ll check it’s OK with them and push it out to them, I suspect it was never put on as the status of NDXEMM-A was was(/is?) a “just test machine” and also why it was not on Nagios.  Of course, the invariable rule is that any “test” machine on a neutron beamline becomes a critical resource after some time ☺.

Chris

**Comment by Tom-Willemsen** [comment]
Seems to have been done and we periodically get nagios alerts about dttray failing on ndxemma...
