### ISSUE TITLE
Reflectometry: Apply mode-inits on move all

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5781]
As a user I want the mode inits to be applied on move all so that the beamline goes to its default tracking state and I don't get confused. As an instrument scientist I want to turn this off so I can easily align.

### Acceptance Criteria

- On move all mode-inits are applied before move
- A PV exists that can turn off application of mode inits
- OPI has a method of turning this on/off before a move

**Comment by DominicOram** [comment]
I will do this but awaiting https://github.com/ISISComputingGroup/IBEX/issues/5806

**Comment by ThomasLohnert** [comment]
No longer impeded as training session has taken place

**Comment by DominicOram** [comment]
PRs at:
* [gui](https://github.com/ISISComputingGroup/ibex_gui/pull/1218)
* [refl](https://github.com/ISISComputingGroup/EPICS-refl/pull/22)

I wasn't sure where to put this in the documentation? It also only took me half a day so depending on review we should reduce the point estimate.

**Comment by John-Holt-Tessella** [comment]
1. Documentation: But this in the beamline model on the dev wiki and can you start a page on the user manual for the reflectometry front panel and describe it on there. We will put pictures etc after the slow OPI ticket that Thomas is working on is reviewed.
1. My opinion on changing the estimate is to try not to do this unless it is really problamatic; e.g. reallly under or over. We under and over estimate tickets all the time but on average it should work out over a sprint. The estimate for the work is not based on the actual work we get done but the amount of estimated points we do. So that next sprint we can tell how many tickets are going to be done based on their estimates. We repoint at the sprint boundary because we are estimating how many points we have for next sprint. (correct me if I am say off @Kevin-Woods-Tessella)

**Comment by kjwoodsISIS** [comment]
@John-Holt-Tessella  is correct.  Estimation is an imprecise science at best (the clue is in the name :-)).  Re-pointing is done at the boundary because we need to assess how much effort is required to complete the incomplete tickets.

In general, assuming there is no particular bias in our estimates, we expect to under-estimate as much as we over-estimate - meaning that things should balance out overall.  However, we should pay attention to our estimates, especially if we think we have under-estimated a task.  For example:
   * if we have under-estimated a 1-point ticket by, say, 100%, that's not much of a problem.  We can live with being 1-point out.
   * if we have under-estimated an 8-point or 13-point ticket by 100%, that could be a problem.  In this case, if we suspect that we have seriously under-estimated a ticket, the right thing to do is not to soldier on, but to flag it up and discuss what we want to do (maybe we would split it into two 8-point tickets, or three 5-point tickets, or even postpone it until we understand it better).

This also shows why 1-, 2-, 3 and 5- point tickets are better than 8- and 13- point tickets.  If you underestimate small tickets, the consequences are less serious.

If you consistently over-estimate tickets, then you will find that you complete all the planned tickets before the end of the sprint, meaning you can bring in additional tickets.  By the end of the sprint you will have exceeded the target, which feeds into the calculation for the next sprint and sets a slightly higher new target.  Over the course of a few sprints the calculation should self-correct for the over-estimates.

**Comment by ThomasLohnert** [comment]
Looks and works great! 

One thing I am concerned about is that the checkbox on the OPI is not very visible. I can imagine users being confused when they are in a different tab and wondering why their setpoints keep changing when they have not entered any values. 

Although from our perspective it makes sense to group the mode inits with the modes, I think from a user's perspective it would be more intuitive if the setting is grouped with the action it effects, i.e. next to the big move button (where it will also persist across all tabs. Happy to discuss this if you disagree!

Also, you accidentally committed the plugin_customization.ini showing the refl perspective - I have fixed it, just wanted to mention it as something to be aware of as it's so easily done without realising!
