### ISSUE TITLE
ZOOM: do_sans is not loading sans wiring tables

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5791]
The do_sans() command is no longer loading sans wiring tables on ZOOM

**Comment by John-Holt-Tessella** [comment]
NB When updating ZOOM is currently on there own branch on scans library until their other support ticket is finished

**Comment by DominicOram** [comment]
Wasn't really obvious what was going on or what the state of the scripts on ZOOM are in general. I've sent a couple of emails to the scientists for clarification.

**Comment by DominicOram** [comment]
The issue on ZOOM was due to the do_sans() and do_trans() commands in the InstrumentScripts caching whether you are in SANS or TRANS mode and skipping changing wiring tables if it doesn’t think you need to. When the IS changed wiring tables outside of using do_sans()/do_trans() the InstrumentScripts cache did not update and so continued skipping changing wiring tables. 
  
The reason it skips changing wiring tables is to try and save time when a change is not needed. However, there is already code [elsewhere in the library](https://github.com/ISISNeutronMuon/InstrumentScripts/blob/2b34d46d1f6da25846b17449ecfca3c60bd19dd0/technique/sans/instrument.py#L114) that does this check just before setting the wiring tables and so remembering whether you’re in SANS/TRANS is not useful anymore. 
  
The code that does the storing of the mode and skipping is the @dae_setter decorator. [I have removed these decorators on ZOOM](https://github.com/ISISNeutronMuon/InstrumentScripts/commit/417ec1e793e58c81995506b50c91b66694ede2b2) and so it should now work fine. I will do the same on the rest of the library so that we don’t fall into this trap again.

**Comment by DominicOram** [comment]
Didn't remove the decorators as I missed they do some wacky stuff to the title/measurement type so just removed caching.

**Comment by FreddieAkeroyd** [comment]
@DominicOram  "the reason it skips changing wiring tables is to try and save time when a change is not needed. " - how much time does that save, the ICP does not load a wiring table if it is unchanged?

**Comment by DominicOram** [comment]
Was that always the case?

**Comment by FreddieAkeroyd** [comment]
Looking at the commit log, the ISISICP code to do this was added 16 years ago. Given TS2 is younger than that, I would hope it was on all the TS2 instruments at least! The ISISICP will not load the file, but it does checksum it to determine if it has changed (it doesn't just rely on date). So it is a lot quicker, but not as quick as not calling the function at all.
