### ISSUE TITLE
Script Generator: Make proper use of setInput [Timebox: 2 days]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5811]
As a user I would like the script generator to be responsive regardless of how many rows I use in my script.

Users found the script generator had some odd bugs when there were many rows (see https://github.com/ISISComputingGroup/IBEX/issues/5708) where cells were being incorrectly given focus. A hot fix was put in for this which remembers which cells should have focus and correctly reapplies them after it is lost. This solution improves the issue but does not fix the underlying cause. Investigation of a better fix has been written on the ticket.

## Acceptance Criteria
* The better solution detailed in https://github.com/ISISComputingGroup/IBEX/issues/5708 is implemented
* The original remains fixed, hopefully more reliably

**Comment by JamesKingWork** [comment]
Agreed to pull this in, instead of https://github.com/ISISComputingGroup/IBEX/issues/6593

**Comment by JamesKingWork** [comment]
The solution has changed from simply making use of `setInput` and `refresh` because this simply did not work. Instead, I have implemented a custom refresh or `updateActions` mechanism which works out what actions need refreshing, adding and removing and then calls the correct methods on the TableViewer (add, remove, replace) to make sure the display is updated correctly. 

## To test:

- Add lots of rows very quickly and then try editing and tabbing between cells whilst the script generator validates and calculates an estimated time for all the actions
- Confirm that general actions still work such as changing script definitions, adding, removing, moving actions up and down, saving and reloading parameters

**Comment by JamesKingWork** [comment]
Check that this also fixes: https://github.com/ISISComputingGroup/IBEX/issues/5811 and close it if so
