### ISSUE TITLE
Support: Assist scientist in adding time estimation to genie simulation

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5821]
As an instrument scientist I would like to be able to estimate how long my scripts will take in genie_python. I am willing to add code into genie_python myself to do this but we need to agree on an architecture first.

## Acceptance Criteria
* A meeting has been had where the architecture of a simulation mode time estimation has been agreed upon
* This architecture and the decisions behind it are written up
* A ticket has been created for an instrument scientist to implement the work

**Comment by DominicOram** [comment]
@mducle FYI

**Comment by DominicOram** [comment]
See email chain in experiment controls for more context

**Comment by mducle** [comment]
@DominicOram 

### Overview

As discussed in the emails, the main changes would be made to the `waitfor` commands, since all other commands may be assumed to occur "instantaneously". `waitfor` waits on three different types of situations:

1. A specified time delay
2. A value of the integrated current (`uamps` or `frames`)
3. A specified block value

Situations 1 and 2 are straightforward to estimate for. For the integrated current, we should assume that the accelerator is running at its optimum current (e.g. 190 uAmp/hr for TS1 neutron instruments, 8 uAmp/hr for TS1 muon instruments and 40 uAmp/hr for TS2 instruments). Since the `waitfor` is for a specified value of `uAmps` rather than an incremental value of `uAmps`, if the simulated script is started when the instrument _not_ in the `setup` state, then we need to first get the current (actual) value of `uAmps` to accurate estimate the remaining time.

Situation 3 is more complex because it requires us to know the "current" value of the block as well as its "target" value - that is, the usual workflow for say cooling a sample would be:

```python
g.cset(T_float=2)
g.waitfor(T_float=2, highlimit=3, lowlimit=1)
```

Now before the `cset` command we would need to save the "current" value of `T_float` (which is say `300` K / room temperature if the sample was just inserted). `cset` would instantaneously set the `T_float` block value to `2` but this would be treated as a "target" value by `waitfor`. Thus the simulated `waitfor` knows that it should estimate the time the sample takes to cool from `300` to `2` (approximately 1-3 hours depending on the type of cryostat or instrument).

One way to implement this is to add an extra key into the block values in simulate mode only which stores the _previous_ value of that block. This previous value can be used as the "current" value by `waitfor` and the block value as the "target". This means that:

```python
# starting temperature is 300 K
g.cset(T_float=100)
g.cset(T_float=2)
g.waitfor(T_float=2, highlimit=3, lowlimit=1)
```

means that the simulation will only estimate the cooling time from `100` K to `2` K *but* in real life the actual waiting time is from `300` K to `2` K, since although in the simulator can only know about the cooling from `100` to `2` K, in reality cooling from `300` to `100` K is not instantaneous. However, it would be difficult to overcome this limitation without a lot of extra logic (and possibly storing _every_ value of a block set during the simulation), so we should allow this behaviour but note this case to users so they can avoid it in their scripts (at least as long as they want accurate time estimates!).

Alternatively instead of adding an extra key into the block dict, we could store an extra set of "previous" block values in the simulation API class (initialised to the same values as the blocks when the simulation starts).

In order to estimate the time taken for a block to reach a value, we would need instrument and configuration (e.g. equipment) specific information. It would probably be easiest to obtain this information piece-meal by working with individual instrument scientists. Until this information is obtained, the blocks can be assumed to reach their target values _instantaneously_. This means that the simulation time estimate will be an under-estimate but there is no feasible way to otherwise estimate these values. 

Storage of these instrument/configuration specific block timing information is not yet determined. It may be stored in a separate configuration file in each individual NDX machine (say in the `inst` folder), or we may chose to have a single global configuration file with entries for every instrument which is versioned in the main `genie_python` codebase. The format of this information is also to be determined. For each block there could several types of information:

1. A scalar value representing the unit per time change (e.g. motor speed in steps/seconds)
2. Two scalar values representing the unit per time when changing in either a positive or negative sense (e.g. a sample cooling rate in degrees/minute, and a sample warming rate in degrees/minute).
3. A list or array of block values vs temperatures, for changes which are not linear with time (cooling rates are usually inversely exponential, whereas warming rate is usually linear).

In each case the values would need an associated time unit (e.g. per second, or per minute etc). How to accomodate all this data is again to be discuss but a dedicated class might be suitable. The set of information can then be stored as a dict index by the block name.

Finally, there is the issue if users want to wait for multiple blocks. Consider the workflow:

```python
g.cset(Fermi_frequency=600)   # original frequency is 100 Hz
g.cset(T_float=2)             # original temperature is 300 K 
g.waitfor(Fermi_frequency=600)
g.waitfor(T_float=2, highlimit=3, lowlimit=1)
```

The time it takes for the Fermi chopper to speed up is a few minutes (~<5 minutes) whereas the time it takes for the sample to cool from `300` K to `2` K is a few hours (say 2h). If the simulation mode is implemented as described above, then it would estimate that the time taken to execute that script is 2h and 5 min, whereas in real life it would only be 2h because change the chopper frequency and cooling the sample occurs simultaneously.

Another example which would result in much greater time over-estimation is:

```
# original temperature = 300
g.cset(T_head=2)
g.cset(T_float=2)
g.waitfor(T_head=2, highlimit=3, lowlimit=1)
g.waitfor(T_float=2, highlimit=3, lowlimit=1)
``` 

This represents a common situation where there is a separate temperature sensor on the cold head of a cryostat (`T_head`) and and one on the sample stick (`T_float`). The cold head will reach the desired temperature faster than the sample stick but only by a few minutes, because they are both cooled by the same physical mechanism (by the cooling power of the cold head). Whereas, the simulation will estimate that it would take the total time for `T_head` to cool (1.5h say) plus that for `T_float` to cool (2h say), totalling 3.5h when it real life it would only be 2h.

Therefore the simulation API class needs some method of chaining consecutive `waitfor` commands and to treat this similarly to the case of `wait_all=True` if multiple blocks is specified.

An added complication to this case is where two blocks are not physically _independent_ - for example the `T_float` and `T_head` example above. Consider the slight change:

```
# original temperature = 300
g.cset(T_head=2)
g.waitfor(T_head=2, highlimit=3, lowlimit=1)
g.cset(T_float=2)
g.waitfor(T_float=2, highlimit=3, lowlimit=1)
```

Even with a mechanism which treats consecutive `waitfor` blocks together, this workflow would result in an overestimation of the time taken by a factor of 2. This is because in the simulation mode, after the first waitfor, the simulator considers that `T_head` is at `2` K but `T_float` is still at `300` K. Thus it then waits for `T_float` to cool as well, and estimates a total run time of 3.5h. However, if there is _no heater_ installed on the sample stick, there is essentially no physical way for `T_float` to be regulated _except_ by changing `T_head` (if there _is_ a heater installed then the 3.5h estimate would be correct as the heater would keep the sample stick temperature high). The reason to have both temperature sensors is because the `T_float` sensor is closer to the physical sample and records a more accurate temperature - there is often an offset of a few degrees between the two. 

So, in these cases, what the simulator should do is to recognise that `T_float` is dependent on `T_head` so that after the first `waitfor` it should also set the `T_float` temperature to be the same as the `T_head` temperature (perhaps with a small offset). The dependencies between blocks would also need to go into the instrument/configuration specific information somehow.

**Comment by DominicOram** [comment]
> ### Overview
> As discussed in the emails, the main changes would be made to the `waitfor` commands, since all other commands may be assumed to occur "instantaneously". `waitfor` waits on three different types of situations:
> 
> 1. A specified time delay
> 2. A value of the integrated current (`uamps` or `frames`)
> 3. A specified block value
> 
> Situations 1 and 2 are straightforward to estimate for. For the integrated current, we should assume that the accelerator is running at its optimum current (e.g. 190 uAmp/hr for TS1 neutron instruments, 8 uAmp/hr for TS1 muon instruments and 40 uAmp/hr for TS2 instruments). Since the `waitfor` is for a specified value of `uAmps` rather than an incremental value of `uAmps`, if the simulated script is started when the instrument _not_ in the `setup` state, then we need to first get the current (actual) value of `uAmps` to accurate estimate the remaining time.

This means we would need to know whether we were a TS1/TS2/muon instrument. At the moment I don't think we store this value anywhere that's easy to obtain, but obviously could. Can the case of doing a simulation whilst running be put into a further ticket? Or do you think it's critical? I would envisage there may be times you would want to simulate whilst running and ignore the current running state, e.g. I want to simulate my next experiment before this one is finished.

> Situation 3 is more complex because it requires us to know the "current" value of the block as well as its "target" value - that is, the usual workflow for say cooling a sample would be:
> 
> ```python
> g.cset(T_float=2)
> g.waitfor(T_float=2, highlimit=3, lowlimit=1)
> ```
> 
> Now before the `cset` command we would need to save the "current" value of `T_float` (which is say `300` K / room temperature if the sample was just inserted). `cset` would instantaneously set the `T_float` block value to `2` but this would be treated as a "target" value by `waitfor`. Thus the simulated `waitfor` knows that it should estimate the time the sample takes to cool from `300` to `2` (approximately 1-3 hours depending on the type of cryostat or instrument).
> 
> One way to implement this is to add an extra key into the block values in simulate mode only which stores the _previous_ value of that block. This previous value can be used as the "current" value by `waitfor` and the block value as the "target". This means that:

Yes, this could be a good solution.

> ```python
> # starting temperature is 300 K
> g.cset(T_float=100)
> g.cset(T_float=2)
> g.waitfor(T_float=2, highlimit=3, lowlimit=1)
> ```
> 
> means that the simulation will only estimate the cooling time from `100` K to `2` K _but_ in real life the actual waiting time is from `300` K to `2` K, since although in the simulator can only know about the cooling from `100` to `2` K, in reality cooling from `300` to `100` K is not instantaneous. However, it would be difficult to overcome this limitation without a lot of extra logic (and possibly storing _every_ value of a block set during the simulation), so we should allow this behaviour but note this case to users so they can avoid it in their scripts (at least as long as they want accurate time estimates!).

Agreed that this is outside the scope of the ticket, we should make sure it's well documented to scientists though

> Alternatively instead of adding an extra key into the block dict, we could store an extra set of "previous" block values in the simulation API class (initialised to the same values as the blocks when the simulation starts).
> 
> In order to estimate the time taken for a block to reach a value, we would need instrument and configuration (e.g. equipment) specific information. It would probably be easiest to obtain this information piece-meal by working with individual instrument scientists. Until this information is obtained, the blocks can be assumed to reach their target values _instantaneously_. This means that the simulation time estimate will be an under-estimate but there is no feasible way to otherwise estimate these values.
> 
> Storage of these instrument/configuration specific block timing information is not yet determined. It may be stored in a separate configuration file in each individual NDX machine (say in the `inst` folder), or we may chose to have a single global configuration file with entries for every instrument which is versioned in the main `genie_python` codebase. 

I would prefer storing them local to the instrument, I imagine that to start with scientists will want to tweak them often.

The format of this information is also to be determined. For each block there could several types of information:
> 
> 1. A scalar value representing the unit per time change (e.g. motor speed in steps/seconds)
> 2. Two scalar values representing the unit per time when changing in either a positive or negative sense (e.g. a sample cooling rate in degrees/minute, and a sample warming rate in degrees/minute).
> 3. A list or array of block values vs temperatures, for changes which are not linear with time (cooling rates are usually inversely exponential, whereas warming rate is usually linear).
> 
> In each case the values would need an associated time unit (e.g. per second, or per minute etc). How to accomodate all this data is again to be discuss but a dedicated class might be suitable. The set of information can then be stored as a dict index by the block name.

For the third point here it may be better to generalise to "the scientist can provide a lambda function that given the current value and the set point gives the time estimate". Then we can leave it up to individual scientists to tweak.

> Finally, there is the issue if users want to wait for multiple blocks. Consider the workflow:
> 
> ```python
> g.cset(Fermi_frequency=600)   # original frequency is 100 Hz
> g.cset(T_float=2)             # original temperature is 300 K 
> g.waitfor(Fermi_frequency=600)
> g.waitfor(T_float=2, highlimit=3, lowlimit=1)
> ```
> 
> The time it takes for the Fermi chopper to speed up is a few minutes (~<5 minutes) whereas the time it takes for the sample to cool from `300` K to `2` K is a few hours (say 2h). If the simulation mode is implemented as described above, then it would estimate that the time taken to execute that script is 2h and 5 min, whereas in real life it would only be 2h because change the chopper frequency and cooling the sample occurs simultaneously.
> 
> Another example which would result in much greater time over-estimation is:
> 
> ```python
> # original temperature = 300
> g.cset(T_head=2)
> g.cset(T_float=2)
> g.waitfor(T_head=2, highlimit=3, lowlimit=1)
> g.waitfor(T_float=2, highlimit=3, lowlimit=1)
> ```
> 
> This represents a common situation where there is a separate temperature sensor on the cold head of a cryostat (`T_head`) and and one on the sample stick (`T_float`). The cold head will reach the desired temperature faster than the sample stick but only by a few minutes, because they are both cooled by the same physical mechanism (by the cooling power of the cold head). Whereas, the simulation will estimate that it would take the total time for `T_head` to cool (1.5h say) plus that for `T_float` to cool (2h say), totalling 3.5h when it real life it would only be 2h.
> 
> Therefore the simulation API class needs some method of chaining consecutive `waitfor` commands and to treat this similarly to the case of `wait_all=True` if multiple blocks is specified.
> 
> An added complication to this case is where two blocks are not physically _independent_ - for example the `T_float` and `T_head` example above. Consider the slight change:
> 
> ```python
> # original temperature = 300
> g.cset(T_head=2)
> g.waitfor(T_head=2, highlimit=3, lowlimit=1)
> g.cset(T_float=2)
> g.waitfor(T_float=2, highlimit=3, lowlimit=1)
> ```
> 
> Even with a mechanism which treats consecutive `waitfor` blocks together, this workflow would result in an overestimation of the time taken by a factor of 2. This is because in the simulation mode, after the first waitfor, the simulator considers that `T_head` is at `2` K but `T_float` is still at `300` K. Thus it then waits for `T_float` to cool as well, and estimates a total run time of 3.5h. However, if there is _no heater_ installed on the sample stick, there is essentially no physical way for `T_float` to be regulated _except_ by changing `T_head` (if there _is_ a heater installed then the 3.5h estimate would be correct as the heater would keep the sample stick temperature high). The reason to have both temperature sensors is because the `T_float` sensor is closer to the physical sample and records a more accurate temperature - there is often an offset of a few degrees between the two.
> 
> So, in these cases, what the simulator should do is to recognise that `T_float` is dependent on `T_head` so that after the first `waitfor` it should also set the `T_float` temperature to be the same as the `T_head` temperature (perhaps with a small offset). The dependencies between blocks would also need to go into the instrument/configuration specific information somehow.

These use cases are getting increasingly complicated, maybe we could think about them for later extensions rather as a minimal viable product (MVP)?

**Comment by Tom-Willemsen** [comment]
Code from meeting:

```
total_time

def time_taken(func, something):
    def wrapper():
        total_time += something(args)
        return func(args)


def waitfor_time(*args):
    if defined(seconds)
        return seconds


class SimulateAPI(object):


    def waitfor(self, *args):
        pass


    def begin(self, *args):
        total_time += self.user_timings.get("begin", lambda: 0)()

        do simulate begin as usual

    def waitfor_time(self, *args):
        pass

    is it a block?
        time_for_block = dict.get(block_name, None)
        if time is not None:


            try:
                time_for_block(initial, *args[1])
            except CanNotExecute:
                totoal_timne +=time_for_block


def specific_for_block(blocks) :
    def _wrapper(*args, **kwargs):
        if has block:
            total_time += blocks.get()

        total_time += SimulateAPI.waitfor()
    return _wrapper
---



# class MARISimulate(SimulateAPI):
#     @time_taken(lambda something)
#     def waitfor(self, *args):
#         if block == "crtostat":
#             return 5
#         else:
#             return super.waitfor()



def ramping_temperature(start, stop):
    return stop-start

time_dict = {"begin": lambda *args: 5,
             "waitfor": specific_for_block({
                 "bigblovk":constant(5),
                 "moveblock": ramping_temperature
             })}

with g.sim.Simulate(initial_block_values={'TEST_BLOCK': 42.42}, waitfor_lambdas=blockOnly("Block1"=lambda, "block2"=})):
    test_block_data = g.cget("TEST_BLOCK")
    print(test_block_data['value'])

g.sim.SimulateTime(SimulateAPI(), time_dict)

```

**Comment by DominicOram** [comment]
Meeting was had with @mducle, @DominicOram, @Tom-Willemsen, @JamesKingWork and @John-Holt-Tessella. Above psudeocode was agreed upon along with the following general points:
* Only the `genie_python` API is in scope for simulation
* Whilst `waitfor` is likely where most time is spent we should create a framework for allowing scientists to specify times for other functions
* The simulate api will need to keep track of the last setting for each block so that scientists can be given it to calculate timings
* The framework should generally expect lambdas for calculating the time taken to allow flexibility, we can add helper lambdas if required
