### ISSUE TITLE
SANS2D: collision avoidance: alternative solution for fast deceleration

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#5894]
On testing https://github.com/ISISComputingGroup/IBEX/issues/5735 with real hardware, it became apparent that we can't actually do a fast deceleration on a specific galil axis (or at least, not easily).

### Acceptance criteria
- Have a meeting with a few interested parties to figure out an alternative solution (e.g. applying the limits on setpoints instead of readbacks)
- Problem is understood and written up
- Investigation and documentation of why SECI does not have this problem

**Comment by DominicOram** [comment]
See https://github.com/ISISComputingGroup/IBEX/issues/5735#issuecomment-712911230 for a better description of the problem

**Comment by rerpha** [comment]
Firstly, we don't think decelerating before a collision worked because the motor record can't do it and also the Galil won't accept a command before finishing a move - it will just queue the deceleration speed change and apply to the next move.

SANS2D want the SECI way of doing it rather than decelerating before a collision - they want users to set all moves then send after figuring out if something will not collide.

The table of motors does not need to obey the collision avoidance stuff - it is a manual control that should be able to override it.
- but in the future we could make it obey the CA script but require manager mode for moving it 
- Bump strips are the equipment safety so anyone who moves via the ToM should just beware that they are bypassing the collision avoidance

We need to discuss all of this with the scientists to make sure it fits their requirements.

**Comment by rerpha** [comment]
Can confirm meeting was had and that the ticket covers the requirements we discussed
