### ISSUE TITLE
Easily create aliases in IOC

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#5912]
As a developer I would like an easy way to create aliases in an IOC, this could be an alternative for configuring a gateway.

## acceptance criteria

In the IOC it is possible to do a command to globally replace a prefix like:
```
dbAliasRecordsPrefix("ME:", "$(MYPVPREFIX)")
```
and to do more fancy regular expression rewriting
```
dbAliasRecordsRE("ME:(.*)", "$(MYPVPREFIX)\1")
```
To create aliases for a group of specified PVs

**Comment by ChrisM-S** [comment]
Does this that mean aliased PVs are accessible (I assume R/O) to anywhere on the network where block PVs are not?
i.e. does a gateway pattern match trap them into export only via the gateway mechanism?
I might not be reading this correctly, just curious

This email and any attachments are intended solely for the use of the named recipients. If you are not the intended recipient you must not use, disclose, copy or distribute this email or any of its attachments and should notify the sender immediately and delete this email from your system. UK Research and Innovation (UKRI) has taken every reasonable precaution to minimise risk of this email or any attachments containing viruses or malware but the recipient should carry out its own virus and malware checks before opening the attachments. UKRI does not accept any liability for any losses or damages which the recipient may sustain due to presence of any viruses. Opinions, conclusions or other information in this message and attachments that are not related directly to UKRI business are solely those of the author and do not represent the views of UKRI.

**Comment by FreddieAkeroyd** [comment]
We do not currently do access control in the IOC, it runs on loopback and so all its PVS are not visible off computer. The block gateway runs on loopback too and creates aliases, then read-only external access is applied via the external gateway running on the NDX.  So both block gateway and dbAliasRecords pvs have the same access rules applied (external gateway) and we do not apply any rules in the block gateway, if we did apply rules in the block gateway then they would differ. As the wildcard and aliases are applied at ioc load time and per ioc, I would expect performance to be better than in a running gateway - there would be no RE to parse at runtime.

**Comment by ChrisM-S** [comment]
Thanks @FreddieAkeroyd, that's a lot clearer, so a gateway is ultimately most useful when you have a bunch of IOCS running which you perhaps do no know so much about and you then need to just export what is  useful to the wider network.  I guess the choice to let the IOC control it's own access has fewer layers as well as being able to configure itself statically and even by sharing a subset of the gateway rules.
