### ISSUE TITLE
MuSR: Dual ITC-503 OPI and Configuration

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5958]
As a muon scientist using MuSR I would like an OPI & configuration/component to control two ITC-503 temperature controllers.

#### Acceptance Criteria
1. IBEX provides an OPI showing two ITC-503s side by side. (check whether it is fine to do this with 2 OPIs in device screens)
1. IBEX provides dual ITC-503s configuration/component.

#### Notes
1. Although the ITC-503s are used together, they operate independently.  It's just convenient to have them displayed on the same OPI.

**Comment by rerpha** [comment]
PR: 
https://github.com/ISISComputingGroup/ibex_gui/pull/1241


still need to do config

**Comment by rerpha** [comment]
Have added this to the release notes:
https://github.com/ISISComputingGroup/IBEX/pull/6134

**Comment by davidkeymer** [comment]
The OPI has horizontal scroll bars with widgets out-of-place and the wrong size.  This is probably because the recommended 800x600 dimensions have been strictly adhered to.

The scroll bars (per linking container) may cause trouble and probably not what the scientist wants.  I expect they'd want to see the values from each ITC on one screen, rather than having to scroll left-and-right.  So it may be better to have the two linking containers full size and just have a wide OPI.

**Comment by davidkeymer** [comment]
Made a few changes to simplify layout and added macros for naming each ITC.
