### ISSUE TITLE
SANDALS: New Jaws

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6097]
As a SANDALS scientist I want to use IBEX to control the new jaws that will be installed on SANDALS during the long shutdown.

#### Acceptance Criteria
1. Using the IBEX client, I can control the new jaws
1. Using genie_python, I can control the new jaws

#### Notes
1. At the time of writing (January 2021):
   * it is expected that the new jaws will be controlled by Beckhoff controllers
   * it is expected that the new jaws will be installed in May/June 2021

**Comment by rerpha** [comment]
Online commissioning happening on 06/04/22

**Comment by rerpha** [comment]
Some notes I've added on Jaws.cmd loading: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Beckhoff-commissioning#jaws

**Comment by rerpha** [comment]
The jaws have been wired (and configured/coded) differently to our normal way of doing them, as in 2 of the axes are driving differently as they are paired in direction (E+W go the same way, as do N+S, rather than being opposed per pair driving outwards) 

I have asked the motion team to add a flag to allow our way of doing it, but it requires a rewrite of some code and won't be ready to deploy on SANDALS. What I am thinking of doing is modifying the jaws_header db to look for LLM rather than HLM for the axes that are driving the wrong way and commenting out the cartesian conversion involved. This will get them a nice looking visual for the OPI, but I do not like this as a permanent solution, and for future slit sets this isn't viable.

**Comment by rerpha** [comment]
on test plc: 
![image](https://user-images.githubusercontent.com/14823767/211000878-0ecf2aa0-cd79-4792-901a-166f8748c758.png)

so think we are not far off SANDALS jaws completion

**Comment by rerpha** [comment]
SANDALS jaws are now working with Simon's code, so any future changes should be beckhoff code. the new method of communicating through ADS seems to be working well and made the v12.0.1 release so no code change is needed in this ticket. I am going to close as the scientists are happy
