### ISSUE TITLE
MuSR: IBEX Testing [2.5d Timebox]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6112]
As an instrument scientists on MuSR I would like to test that the beamline functions as expected using IBEX. Specifically I would like to test/confirm the following work functionality and give a good user experience to the scientists:
- [x] https://github.com/ISISComputingGroup/IBEX/issues/5096
- [x] https://github.com/ISISComputingGroup/IBEX/issues/5949 - specifically starting and stopping the magnets
- [x] https://github.com/ISISComputingGroup/IBEX/issues/5099
- [x] Check with scientists whether they use "dead reckoning" mode on the zero field system (EMU do not and it is not currently implemented in IBEX, the MuSR genie scripts support it as an option)
- [x] Explain differences in how to physically connect cryogenic kit (ISOBUS expander box no longer in use - com ports may need adjusting in their configs the first time they set up this equipment in the IBEX style)

**Comment by Tom-Willemsen** [comment]
Plan:
- Test the currently connected temperature controller (ITC503) on friday 29th, and finish setting up temperature configs as far as possible
- Mark will rotate the instrument for us on Monday (1st) morning
- Monday afternoon set up the ZF system with the instrument in transverse mode
- Wednesday 3rd & Friday 5th - Peter will be available on site to help test things which require physical presence:
  * Instrument rotation
  * Use hall probe to verify magnet TF and LF magnets
  * Use external magnetometer to verify ZF system
  * Connect various temperature kit for us to test

**Comment by Tom-Willemsen** [comment]
We've now reached a sensible stopping point with this.

Done as part of this ticket:
- Set zero field offsets correctly so that zero in ibex corresponds to zero on a fixed magnetometer probe
- Ensure zero field axes have the same signs & orientations as in SECI
- Check the instrument rotation change process
- Check the configs for king_hight and king_lowt with input from scientists
  * Checking comms with mercury, itc503, ilm, triton
- Check the TF (TTIEX355P) calibration factors
- Verify that steering magnets set correctly on hardware
- Setup `BGSCRPT_01` so that the background graphs work

Remaining to be done:
- Test remaining cryo equipment. Both uDR3 and uDR4 are scheduled to be cooled down on MuSR before cycle, we can piggyback onto those tests to check comms
- Test the danfysik [once slew rate ticket is complete and PSU group clear interlocks]
- Test the ZF stability [once kepco write rate ticket is complete]
- Test booster heater scripts [when cryostat with boost heater is available - scientists hope this will be sometime before cycle]

**Comment by JamesKingWork** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6196

**Comment by JamesKingWork** [comment]
Dead reckoning to be implemented in long shutdown. Ticket: https://github.com/ISISComputingGroup/IBEX/issues/6156

**Comment by JamesKingWork** [comment]
Remaining testing tickets: 

- https://github.com/ISISComputingGroup/IBEX/issues/6198
- https://github.com/ISISComputingGroup/IBEX/issues/6199
- https://github.com/ISISComputingGroup/IBEX/issues/6200
- https://github.com/ISISComputingGroup/IBEX/issues/5990
