### ISSUE TITLE
KEPCO: can no longer be set to negative currents

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6151]
As an instrument scientist on muon beamlines I need to be able to drive a kepco to a negative current for the zero-field compensation systems.

This appears to have been a behaviour change since the last release - possibly since incorporating ramping functionality into the kepco.

Workaround is to use PV sets to explicitly set `...:KEPCO_01:CURRENT:SP.DRVL` to the correct value.

### Acceptance criteria

- Kepcos can be driven to negative currents
- Test exists for this case

**Comment by kjwoodsISIS** [comment]
It may be worth checking how the ramping functionality handles +ve and -ve currents, because the same problem might appear on other PSUs.  Is the ramping functionality common to other PSUs, or does each PSU need its own ramping feature?

Also, is the polarity set explicitly (i.e. with a switch on the OPI) or inferred from the sign of the current?

**Comment by rerpha** [comment]
Note: when this is fixed we should remove the `DRVL` field on KEPCO 1,2,3 on MuSR
