### ISSUE TITLE
IOC: meeting - If autosave fails on Galil default are safe

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#6170]
As a POLREF instrument scientist I want it to be obvious if the autoave file has been corrupted on by instrument, so that if we have an issue like #6169 again a user can not accidentally move a motor.

### Acceptance Criteria

1. If the autosave can not be loaded the motor can not be moved (maybe by setting high and low limits to be 0)
2. If possible I would like a visual indication that this has been done on the OPI

**Comment by FreddieAkeroyd** [comment]
If the autosave file is not loaded, then the values will default to whatever is in the DB files. So we may be able to set these "defaults"  such that the problem is obvious and no damage can subsequently be done e.g. VAL=0 with HLM and LLM to cause limit violation, SPMG at "stop", maybe even something with DISP or DISA/DISV/SDIS (a readonly ASG may risk conflicting with something else).  If we use DISP or DISA/DISV/SDIS check they are autosaved and add if not

**Comment by John-Holt-Tessella** [comment]
I think DISPs and SPMG are too subtle and not easily set whereas the limits are shown on the OPI so it should be clear why the motor isn't moving. Maybe we should also have a field which has the default value Autosave not loaded, do not move this motor which we autosave to "" so that we can give the user a message.

**Comment by FreddieAkeroyd** [comment]
The high and low limits are settable on the first motor screen, but to get at e.g. SPMG you need to go to "more details" that is greyed out by default. It depends on how hard we want to make it for a user to do the wrong thing e.g just think the limits have come back wrong and then to go ahead and reset them. There are also autosave status PVs e.g. `SR_rebootStatus`, `SR_status` that we might be able to use to flag problems earlier.

**Comment by DominicOram** [comment]
Make sure it still works for simulated motors easily

**Comment by DominicOram** [comment]
In a meeting today the IS stressed that when this happens they want it to be very obvious something is wrong

**Comment by rerpha** [comment]
meeting scheduled for next thursday

**Comment by rerpha** [comment]
## Autosave corruption meeting notes
### what happened 
- POLREF ran out of disk space nad the autosave files got corrupted 
- the galil came back online and came on with default values not autosave values - it then thought it was in the wrong place 
- this is dangerous because the users could move the galils incorrectly
- After this we restored the autosave values - worked for some motors but not others, some of which were still confused on their location. 
  - Autosave was restored from the archive
  - The bench motor started off at -1000, the restored autosave value was -100 

This occasionally happened on SECI as well - sometimes it would start with random numbers.
- This suggests the galil itself isn't reporting the right figures?


### What should we do when an autosave file cannot be loaded by an instrument - how should we disable users moving motors
- We should set defaults in the db file 
- We could set the high and low limits to 0 to make sure no one can move it
  - 0 for both will mean ignore the limits - maybe setting DISP and SPMG or DISABLE field would be better
  - Need to look into the disable record as we're not sure what it does exactly 
  - There is another PV called PV:DISABLE which might be able to do it - we could make this the default so if the autosave doesn't work we could use this as the value
  - implementation should be up to the developer - doesn't really matter how its done as long as we can disable the affected motors

- We should add another string to make sure the user is aware that the autosave was not restored/loaded 

- Autosave has a status variable to say whether or not it has loaded properly - we could use this to let the user know. 

- This should be propagated into the motors OPI so the user is aware - one on each motor in the table of motors should be sufficient. Greying the motor out would be a good idea. 

The symptom for this issue is that the galil has moved a large amount - usually its when the IOC is off.
- when the define changes there might be a moving flag on the motor record - not sure
- Could warn that it has moved a large amount and that something may now be corrupt
- to do this we could store the previous value in a pv or field and then compare it with the new one
- for example, if the readback has changed but the setpoint hasn't, within a tolerance
  - how do we define the tolerance? what makes a sensible amount? 
- even if they knock it we should probably warn

- could also check the times of the moves - if it jumped quickly we could warn?

### On autosave failure if the autosave is corrupt 
We could add a checkbox to enable/disable this warning if the user goes and moves them by hand often as it'll keep disabling the motors otherwise. 
- similar to the alarm acknowledgement system - but we want an action to either keep going, restore the default or restore autosave value.
- or just "restore the position"


### Do we need to warn the users or just monitor it ourselves? 
- Users dont necessarily care (other than reflectometry maybe) but we do - maybe we should just monitor it ourselves rather than warn users every time
- We have a meeting next week, we could ask whether they want an alert or if they're happy us just monitoring it. 


#### When we set the galil motor we should log the current and new positions.
- might already be there but didnt do the define
  - this might mean the galil played up and didn't work properly
  - power cycle could be the reason - we don't currently have a ticket for this.
  - we do actually, alert when power down - #4745

#### Also talking about what we do if the motors are reading weird positions
- does this actually ever happen - we're not sure if it does

- Funny positions during boot/after autosave or during the lifetime of the IOC? 
  - the lifetime of the IOC


### Ultimately we don't really know what causes the numbers to go weird. We might have experienced it before but not certain. 
- We think it's just after an autosave so we should fix that for now and see if it reappears. 
- We could just try this on the db for now. 

We can fix the autosave issue but things that happen like power cycles we can't really do much as its not our fault or in our control. disk space filling up we can take responsibility for however so the problem on POLREF is probably our fault. 

### Outcome actions and priorities
1. make a ticket for sorting out the autosaves if theyre corrupt on startup
1. then do #4745
1. when you come back up from an ioc restart and youve got a position that is very different to the autosave position then warn/alert
1. when you move without thinking you are moving (rb being different to sp) then warn/alert 
1. make a ticket for checking whether we are logging the define position on the motors

**Comment by rerpha** [comment]
Have created #6251, #6252 , #6253 and #6254 from the outcome of this meeting. Please feel free to add anything i've missed in those tickets.

**Comment by DominicOram** [comment]
Notes as tickets look good, made some minor clarifying edits in places but otherwise fine.
