### ISSUE TITLE
IMAT: Set up dilution fridge experiment [needed before 22/04/21]

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6328]
As an instrument scientist on IMAT I want to be confident that my dilution fridge experiment will work. As such I would like to test it on my beamline before hand.

## Acceptance Criteria
* IMAT has a configuration for a dilution fridge
* The test on 08/04/2021 is a success

**Comment by JamesKingWork** [comment]
Component (TritonDilution) containing Triton, ITC503 and ILM200 has been created and added to IMAT_DilutionFridge config. 

The triton is talking happily. I have asked if there is anything we need to help with regarding setting up PID lookup files and ramping. I have asked cryogenics to confirm that the name <-> channel mapping is as expected (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Triton#configuration).

The ITC503 is also talking happily. The IOC is currently not liking the protocol the ILM200 is using, partially because we are expecting it to be on ISOBUS and it isn't, but also another reason which I am investigating now.

**Comment by JamesKingWork** [comment]
The ILM200 had two protocol issues. One that we were expecting to use ISOBUS and another that we missed expecting a reply in part of the protocol.

Hotfix added to https://github.com/ISISComputingGroup/IBEX/wiki#instrument-information--hotfixes at IMAT.

PRs:
- https://github.com/ISISComputingGroup/EPICS-ILM200/pull/4
- https://github.com/ISISComputingGroup/EPICS-upgrade/pull/57/files
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/613

**Comment by JamesKingWork** [comment]
Use of the setup is planned for the 26th of May

**Comment by JamesKingWork** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6448
