### ISSUE TITLE
Manual System Tests: Reduce and make easier

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6372]
As a developer I would like the release process to be as smooth as possible. Currently the bulk of the work required in creating a release is running the manual system tests. There are a number of issues with them that slow things down:
* Poorly worded tests that cause confusion. Some of these are listed in https://github.com/ISISComputingGroup/IBEX/issues/5567
* Repeated tests e.g. create a config with a block in it, now create a new config with a block that is under runcontrol
* Tests in bad order causing repetition e.g. go into manager mode, go out of manager mode, check that whilst you're in manager mode you can do X
* Tests that are known to be incorrect e.g. timings on some of the reconnection times
* Tests that are automated already
* A large number of tests that focus on not well used features e.g. IOC Log perspective

We could also make much better use of helper scripts/squish within the tests themselves. At this point it may be easiest to just re-write them all from scratch.

## Acceptance Criteria
* New manual system tests cover all functionality that they currently do
* New manual system tests can be performed in ~1 hour

**Comment by Adam-Szw** [comment]
New spreadsheet is called 'manual_system_tests_new' and can be found in technical -> files (will swap it out with old tests when ticket is reviewed)
New columns were added/changed:
- Under Test(Y/N) - everyone working on manual tests should put Y when they start working on the test so that others can know someone is testing this already
- Test Notes - you can use this area for your own notes about test, for example results, bugs discovered (after that you can review column to move things to bugs spreadsheet) or if test is confusing/broken in any way

Many tests which are automated/redundant/overlapping/duplicated were removed
Ordering and wording of tests was changed to accelerate going through tests/bundle tests together and
follow logical order
Wiki was linked for some difficult tests, many tests got additional (often more explicit) instruction
New tests section was added and some tests moved there - Synoptics and Configs. This is because these tests are using both perspectives

**Comment by rerpha** [comment]
can't review just yet, but could you add the new template to the wiki (you'll have to clone and add the excel file) to where it's linked on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-System-Tests 

it should be in `ibex_developers_manual/wiki/testing/`

**Comment by Adam-Szw** [comment]
release notes PR https://github.com/ISISComputingGroup/IBEX/pull/6710

**Comment by Adam-Szw** [comment]
Updated wiki template

**Comment by JamesKingWork** [comment]
I heard mention before of some of the UI tests not being moved from the old system to squish, do we have a ticket to do this, or are we not going to automate those?

**Comment by Adam-Szw** [comment]
I'm not sure, I think @RaiBishal was keeping track of this

**Comment by RaiBishal** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/3251. There is already a ticket for it. But maybe I should create new one instead.

**Comment by JamesKingWork** [comment]
Oh no that's fine if there's already one, I just couldn't find it before 👍

**Comment by JamesKingWork** [comment]
All the updates to the tests look fine to me. Far more explicit and understandable, substantially shortened! This is a good start to improving them, but we may want to continue to look at improving them further in the future by adding helper scripts, more squish tests etc.
