### ISSUE TITLE
script generator: VERSION.txt incorrect format

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6402]
The VERSION.txt for the script generator has incorrect format and messes up formatting on the auto-generated summary page. It is currently
```
Script_Gen_7.4.0
```
when it should be just
```
7.4.0
```
as done in genie python, ibex gui and EPICS

## Acceptance criteria

* file generated in correct format

**Comment by DominicOram** [comment]
So at the same time as https://github.com/ISISComputingGroup/IBEX/issues/6478

**Comment by JamesKingWork** [comment]
The reason for this is because we create a separate release branch for the script generator named `Release_Script_Gen_<X.x.x>` as opposed to `Release_<X.x.x>` and jenkins_build_script_generator.bat only strips off `Release_`. This PR https://github.com/ISISComputingGroup/ibex_gui/pull/1296 now removes `Release_Script_Gen_` but we could think about our process and actually not go through the bother of creating separate release branches for the client and script generator.

**Comment by rerpha** [comment]
> The reason for this is because we create a separate release branch for the script generator named `Release_Script_Gen_<X.x.x>` as opposed to `Release_<X.x.x>` and jenkins_build_script_generator.bat only strips off `Release_`. This PR [ISISComputingGroup/ibex_gui#1296](https://github.com/ISISComputingGroup/ibex_gui/pull/1296) now removes `Release_Script_Gen_` but we could think about our process and actually not go through the bother of creating separate release branches for the client and script generator. Release notes: #6520

Worth making a ticket for the discussion?
