### ISSUE TITLE
Correct bumpstrips for LARMOR and POLREF

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6436]
As an instrument scientist on LARMOR and POLREF I would like to be accurately informed as to whether my bump strips are tripped and for the GUI to prominently warn me if this is the case. Currently the GUI is showing the bumpstrips are tripped when they are in fact not. However, it is not certain if this is a software or hardware issue.

## Acceptance Criteria
* Test the bumpstrips on POLREF/LARMOR and confirm if an appropriate signal is being sent to the Galil
* If it is spend a short amount of time (1 hour) trying to work out why this is not getting forwarded to IBEX correctly
* If a signal is not present in the Galil or we are unsure why the signal is not being routed to IBEX then remove remove the prominent, incorrect, message on the GUI

**Comment by DominicOram** [comment]
On 22/04/21 we confirmed that the bumpstrips on POLREF were communicating correctly and showing in the GUI.

**Comment by ThomasLohnert** [comment]
Chased it up with LARMOR. They said the problem was hardware based and so not for us to fix. I have offered to disable the bump strip warnings for the time being, but they said they'd like to keep it as a reminder to get the problem fixed but they might change their mind if users start complaining.

In case someone gets a support call about this at some point: 
You can disable the bump strip warning by renaming `/configurations/galil/bumpStop.cmd` to something else and restarting `GALIL_01` IOC. This will make the Galil think no bump strips are configured and the relevant PV will default to not tripped.

Don't think there is anything else for us to do here so moving this to review.

**Comment by ThomasLohnert** [comment]
Chased it up with LARMOR. They said the problem was hardware based and so not for us to fix. I have offered to disable the bump strip warnings for the time being, but they said they'd like to keep it as a reminder to get the problem fixed but they might change their mind if users start complaining.

In case someone gets a support call about this at some point: 
You can disable the bump strip warning by renaming `/configurations/galil/bumpStop.cmd` to something else and restarting `GALIL_01` IOC. This will make the Galil think no bump strips are configured and the relevant PV will default to not tripped.

Don't think there is anything else for us to do here so moving this to review.

**Comment by DominicOram** [comment]
Don't think there's much more to do here.
