### ISSUE TITLE
CHIPIR (SECI): Collimator slow to move

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6504]
As an instrument scientist on CHIPIR I would like my collimator to start moving as soon as I tell it to. Currently there is a long delay between me telling it to move and getting a response. Prior to the work done in https://github.com/ISISComputingGroup/IBEX/issues/6496 there was no delay.

Notes from troubleshooting over the weekend:
* In general SECI seems slower than usual
* I saw that there were numerous comms error messages from a number of Galils, as well as an "incorrect firmware" message on one of them
* I disabled Galil 1 and 3 to try and increase the speed, which seemed to help somewhat but it's still not as fast as usual
* The TTI VI was also stopped to try and improve speed

## Acceptance Criteria
* CHIPIR's motion is as responsive as it was before https://github.com/ISISComputingGroup/IBEX/issues/6496 was done

**Comment by davidkeymer** [comment]
The problem turned out **not** to be related to the collimator, Galil controllers nor the MOXA NPort they are connected to.  The additional NPort that is in the screened room had had its network cable unplugged at the main switch, and because VIs were trying to talk to devices via it (including the PSU in #6496), slowed down the rest of LabVIEW system.  It is not currently understood why, nor why the front panel of said NPort failed to show any errors - it even still had a green ready LED and displayed a valid ISIS IP address.

Performance was restored to usual levels once the cable had been reconnected, and remained so when all Galil controllers had been re-enabled.

**Comment by ChrisM-S** [comment]
I suspect that someone had set the MOXA to a fixed IP address? - whether as part of some attempt at diagnosis or just in the belief that it would be more reliable - I wouldn't expect the MOXA to complain about being off a network with a red light if it considered itself to be the network :-).

**Comment by davidkeymer** [comment]
> I suspect that someone had set the MOXA to a fixed IP address? - whether as part of some attempt at diagnosis or just in the belief that it would be more reliable - I wouldn't expect the MOXA to complain about being off a network with a red light if it considered itself to be the network :-).

No, definitely still set to DHCP.  After reconnecting the network cable and power-cycling the MOXA, it came back with a recognisable ISIS IP address.

**Comment by ChrisM-S** [comment]
OK, that's good.  I now think I remember that after testing this explicitly in my office a few years back, the MOXAs do keep their DHCP address if they have no access to the DHCP server (and only lose it if they are restarted).  This does work if the DHCP server is lost for some reason - but I guess keeping the address is not so much use if the MOXA is no longer connected at all!

**Comment by davidkeymer** [comment]
Have added a [note](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SECI-Troubleshooting/_edit#vis-slow-and-unresponsive) to the SECI Trouble-Shooting page, although this may also apply to IBEX instruments.

**Comment by DominicOram** [comment]
Great, thanks @davidkeymer
