### ISSUE TITLE
HIFI Cryomag: Cryogenic Power Supply IOC

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#651]
As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the power supply will improve that module of code

**Acceptance Criteria**
1. Write an IOC for communicating with a cryogenic made power supply
1. Write an emulator for the cryogenic made power supply
1. Write the IOC test framework for the cryogenic made power supply
1. Create an OPI for the cryogenic made power supply

**Notes**
1. This will be a standard stream/asyn driver
1. There is a copy of the manual in http://www.facilities.rl.ac.uk/isis/projects/ts1/HIFICryomagnetSoftwareImprovement/Manuals/Forms/AllItems.aspx
1. This will cover the X/Y/Z Power Supplies
1. The main magnet power supply (SMS) is covered by #650

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 652.  Created by kvlb23 on 2015-02-06T13:25:29, last modified: 2015-02-06T13:25:29_

**Comment by KathrynBaker** [comment]
Original content of ticket:


As a support person I want the cryomag on NDXHIFI to be robust and maintainable, rewriting the magnet control for the X,Y and Z axis will improve that module of code
#### Acceptance Criteria
1. Write an IOC for communicating with a Magnet PSU
2. Set up to run 3 of these relating to each magnet X,Y and Z
3. Alter the existing LabVIEW code to reference the IOC
#### Notes
1. The existing GUI interface should be maintained until all changes are complete, although the code underneath should be updated to use the PVs from the IOC
2. When altering the LabVIEW GUIs care should be taken over the existence of hidden datasocket links
3. The lvDCOM IOC referring to the DS and EI VI will need to have the PVs now being generated from an IOC removed from it's listing
4. Some extra reverse engineering may be required before undertaking this.
5. Each magnet PSU works in the same way, and so the code cab loaded multiple times rather than replicated

**Comment by esouthren** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/172

(Links to other pull requests required for IOC/Emulator/OPI in pull request comments)

**Comment by esouthren** [comment]
https://github.com/ISISComputingGroup/EPICS-ioc/pull/176

Pull request for master IOC makefile - added HFMAGPSU

**Comment by esouthren** [comment]
Pulled this from 'review' to 'in progress' following meeting with James and some recommendations from him

**Comment by esouthren** [comment]
Updated list of pull requests. 

https://github.com/ISISComputingGroup/EPICS-ioc/pull/172

Quite a few changes made, but is working against the hardware which is in the mezzanine of TS1.

**Comment by John-Holt-Tessella** [comment]
If it is needed I have copied some code from @KathrynBaker from the laptop used against HIFI cryomag. I have put it is `...ISIS_Experimental_Controls\HIFI_Chromagnet_From_laptop`.

**Comment by Rory-Potter-Tessella** [comment]
The IOC does not launch in its current state. See specific pull requests for further comments on what needs to be fixed.

**Comment by ChrisColeExpControl** [comment]
For posterity, noting here that the IOC is being rewritten, will update this comment as new tickets are made.
https://github.com/ISISComputingGroup/IBEX/issues/4826
https://github.com/ISISComputingGroup/IBEX/issues/4831

**Comment by KathrynBaker** [comment]
Given that this has been superseded, I'm closing the ticket
