### ISSUE TITLE
genie_python: Add function to get runtime

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6519]
As an instrument scientist on Larmor (RD) I would like to be able to get the current runtime of the run through genie_python. This function should return an integer of how many seconds I have been running.

## Acceptance Criteria
* There is a `get_runtime` function in genie python that does the above
* There are system_tests for this function

**Comment by FreddieAkeroyd** [comment]
Should we look to returning a float for better accuracy?

**Comment by FreddieAkeroyd** [comment]
There is already a `get_run_duration` function the the genie python dae api , it also has optional period support

**Comment by FreddieAkeroyd** [comment]
It seems RD requires something slightly different, he would like a duration since run start that does not take into account pause/waiting etc.   get_run_duration  above does allow for this, and is what is displayed on the dashboard as "run time".  What RD requires is (time now - time run started) - we may need to give this a different name to "runtime" to avoid confusion.

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/system_tests/pull/82

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/genie_python/pull/348

**Comment by daryakoskeroglu** [comment]
https://github.com/ISISComputingGroup/IBEX/commit/94dac47c4fdd06b426795045c649b40d6c1ce708

**Comment by DominicOram** [comment]
Works great, minor comments on the PRs, sorry. Also, can you drop an email to the instrument scientist to let them know it will be there next cycle?
