### ISSUE TITLE
OFFSPEC: Confirm the numbers from the configuration match those in SECI

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6526]
As an instrument scientist I would like to be able to use IBEX on OFFSPEC. As of https://github.com/ISISComputingGroup/IBEX/issues/6245 there is a draft config for OFFSPEC but we should confirm this by building up a table of where the reflectometry server positions axes under certain conditions and pass test these against the instrument.

## Acceptance Criteria
* A spreadsheet is created that shows where axes go when parameters are set for the offspec config
* This is sent to the scientist for confirmation

**Comment by ThomasLohnert** [comment]
I have finished my investigation of the differences. Based on CK's (POLREF) replies I believe the IBEX code will work for OFFSPEC without the need of further changes. SH (OFFSPEC) is in the email chain and has not raised any concerns. Explanation of the differences in value and table for reference below:

- IBEX corrects jack height for the difference in height of the beam above the bench surface at different angles (Diff BC in the table). In the SECI code, I believe this is only taken into account for the bench slide i.e. the IBEX numbers are more correct.
- The numbers produced by SECI assume the bench is aligned to the natural beam (i.e. when motor axes are at 0, the device they move is centered on the intersection of the movement axis with the natural beam at -2.3 deg) whereas IBEX assumes the bench is aligned to optical level. CK has explained that they have chosen this convention for the POLREF bench for pragmatic reasons, as it allows them to set the jacks to 0 and then place a precise optical level on the bench to confirm alignment. We can cover this difference by applying a static user offset to the axes (see “Diff AB” in the table below)
- The numbers for horizontal slide (moving the bench further or closer to the sample to maintain constant time of flight) are computed in completely different ways in both sets of code. CK has confirmed that the OFFSPEC code is an older version, and the IBEX code is based on an improved version that addresses some systemic errors and ensures the radius (and ToF) remain constant, i.e. IBEX is correct. He has tested this with the POLREF bench.

![image](https://user-images.githubusercontent.com/18398579/218438692-811d90f0-e637-4d28-a99c-b1be7880dda5.png)

I hope this makes enough sense to be reviewed, otherwise please let me know if anything needs clarification! I can also provide a spreadsheet that

**Comment by KathrynBaker** [comment]
Given that the scientists have confirmed or not raised queries, and I can see at least part of the spreadsheet, I am going to mark this as complete, the acceptance criteria are met, and the explanation is enough for me.
