### ISSUE TITLE
Discussion: Move OPIs to server

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6562]
As a developer I might like to move OPIs to the server and get them remotely from the GUI. This has the advantage that the OPI and IOC will be next to each other and so kept up to date together. We briefly discussed this in https://github.com/ISISComputingGroup/IBEX/issues/6131 but had some concerns about:
* What mechanism we would use to transmit the OPIs between client and server
* How we would deal with OPIs that communicate with multiple IOCs

## Acceptance Criteria
* Look into mechanisms CSS has for looking at remote OPIs
* Discuss whether we want to do this

**Comment by FreddieAkeroyd** [comment]
According to http://cs-studio.sourceforge.net/docbook/ch15.html   "The files could be in a network file system location, but since the detailed path name syntax for such shared file system location often differs between operating systems, a web location might be more practical. BOY can read files from http://, https:// and ftp:// URLs." It was unclear if this just meant font etc. files but later on the page it says "The default for the Top OPIs will point to the BOY example files like /BOY Examples/main.opi. You probably want to adjust them to load certain top-level OPI files of your site, like http://my_opi_server/opis/start_screen.opi" which suggests OPIs could all be loaded via the web

**Comment by ThomasLohnert** [comment]
We have a githook on the ibex_gui repo which adds a dummy button to each OPI as a hack to ensure the autofocus after entering a value does not jump to anything dangerous. We need to think about how best to retain this check after moving the OPIs to individual support modules

**Comment by KathrynBaker** [comment]
I have created tickets #7088, #7089. #7090, #7091 and #7093 to cover this work when the time comes. Closing without adding to the sprint, or seeking a review, as a discussion was had, a plan defined, and an initial path to try.

**Comment by FreddieAkeroyd** [comment]
even if step 0 is not possible, steps 1-3 are likely worth doing anyway
