### ISSUE TITLE
multiple GUI/clients running: give warning  

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6577]
As a user i would like to be warned if i accidentally start a second instance of the ibex GUI - this is similar to #5084

## Acceptance criteria

* if a second GUI is started, a warning dialogue notifies the user and asks if they wish to continue
* (optional) if it is easy/possible. one of the options could be "switch to existing gui"

**Comment by FreddieAkeroyd** [comment]
Look at process list to see if second instance

**Comment by Adam-Szw** [comment]
Code PR: https://github.com/ISISComputingGroup/ibex_gui/pull/1344
Release notes PR: https://github.com/ISISComputingGroup/IBEX/pull/6731
Wiki page added: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Local-files-and-start-up

Unfortunately optional goal would seem to require adding more dependencies since switching between windows/tabs is more of a system thing than something easily controllable from Java app.

The solution required programming in creation of a folder and temporary files in user directory (this directory could be easily changed to anywhere else) so I added a wiki entry with some more explanation.

To test this when reviewing:
- Either build/deploy client or run from Eclipse (it shouldn't matter)
- In eclipse Run -> Run Configurations ->Launch Group -> add ibex.product a couple of times

Since this process seems difficult to automate, I propose that a manual test is added for this if it passes review.

**Comment by Adam-Szw** [comment]
Also note: We might discover that some tests which have 2 clients running at the same time don't work anymore since prompt has to be accepted first.

**Comment by JamesKingWork** [comment]
Code works correctly but I have requested a few improvements, documentation looks good. Please do add to the system tests and I'll review that too in the rereview

**Comment by Adam-Szw** [comment]
While I was reworking this I tried a different method of testing and discovered that this actually doesn't work reliably so I will be re-doing it with a different method to make it more robust.
File locking only works if locking happens:
- in two threads of same program
- if two programs are running on same JVM (which is the case when using eclipse testing method from before hence it was not discovered before)
This is not very well documented.

To reproduce:
- Create a second workspace of ibex gui and go through all setup steps again
- Run the ibex from two different eclipse instances
- It's not working 👎

**Comment by Adam-Szw** [comment]
New, more robust solution: https://github.com/ISISComputingGroup/ibex_gui/pull/1344/commits/ddf9fa964e370109d06c086b28267f326c4affb8
Addressed all feedback from previous review
Wiki page updated https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Local-files-and-start-up

@JamesKingWork Do you mean normal system tests or squish tests? This seems to me more like a squish thing.
