### ISSUE TITLE
IMAT: Sample Stack naming and ordering is inconsistent

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6632]
As an IS on IMAT I would like the naming and ordering of my sample stack axes to be consistent. Currently the naming on the table of motors does not match that on the synoptic, which also does not match that on the Sample Stack OPI. The ordering of items on the synoptic and on the OPI are also different.

## Acceptance Criteria
* The axes are in the same order in Synopitic view and in OPI
* The axes have same name in ToM, Synoptic and Sample Stack OPI
* Axes have been renamed in accordance with presentation table

**Comment by rerpha** [comment]
related to https://github.com/ISISComputingGroup/IBEX/issues/6424 ?

**Comment by DominicOram** [comment]
No, the other ticket is the generic SANS sample changer, this is a sample stack, subtly different. A sample changer is a bit of kit allowing you to select many samples, the sample stack is a place to put one sample where you can rotate it, translate it etc.

**Comment by rerpha** [comment]
Sorry, was thinking more for the ordering side of things

**Comment by DominicOram** [comment]
The ordering issue from #6424 comes from reading the xml that the sample changer code uses. The sample stack doesn't have any configuration files like that, it's just some dumb axes, we would just need to rearrange things on the OPI

**Comment by Adam-Szw** [comment]
Changes pushed to branch of NDXIMAT config here: https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXIMAT_Ticket_6632_Update
- Axes re-ordered to be consistent between syntoptic and OPI
- I left ChiUpper, PsiUpper, PHI2 and PHI1 as it is since these are different PVs and thus not inconsistent but moved them below
- Motors cannot be renamed until IMAT is online (TODO later)
- Names in synoptic changed to fit names in OPI so it's consistent. There was no preference to this in presentation so I decided to do this instead of renaming PVs for safety and consistency of PV naming. Example: ZLower -> Z, ThetaUpper -> Theta

**Comment by Adam-Szw** [comment]
Release notes PR https://github.com/ISISComputingGroup/IBEX/pull/6711

**Comment by DominicOram** [comment]
I think in the follow up email discussion I sent to you @Adam-Szw the scientists wanted to change Tomo Phi Low to Tomo Phi X and Tomo Phi High to Tomo Phi Y, not sure if you caught that or not but it's not in the table you linked. For clarity I've added the full presentation and email conversation to https://www.facilities.rl.ac.uk/isis/computing/instruments/Instrument%20Documents/IMAT_SampleStack_RenamingAxes.pptx and https://www.facilities.rl.ac.uk/isis/computing/instruments/Instrument%20Documents/FW%20IMAT%20Motion%20Recommissioning.msg. Also, the ordering should all match the diagram in Slide 4 of the presentation.

**Comment by Adam-Szw** [comment]
Changes Branch: https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXIMAT_Ticket_6632_Updated

**Comment by Adam-Szw** [comment]
Changes Branch: https://control-svcs.isis.cclrc.ac.uk/git/?p=instconfigs/inst.git;a=shortlog;h=refs/heads/NDXIMAT_Ticket_6632_Updated
