### ISSUE TITLE
Alarms: Latching [Timebox: 4.5 Days]

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6682]
As a user and/or instrument scientist, I would like my alarms to be able to latch. When a value goes into alarm and subsequently goes out of alarm a non-latching alarm will then release the alarm, a latching alarm however will not release the alarm until it is reset. This is particularly desired by muon scientists who have been plagued by alarms going in and out making recognising and diagnosing alarms particularly difficult. 

## Acceptance criteria:

- [ ] Alarms can latch and latched alarms display in the IBEX client and web dashboard
- [ ] When in manager mode you can set latching to on or off (defaults to off)
- [ ] Latched alarms show the number of times the alarms has gone in and out whilst latched
- [ ] Latched alarms show the amount of time the PV has spent in alarm whilst latched

## Notes

- One solution would be to monitor alarms of PVs for that instrument using an IOC (or possibly an inst server) and have the latch/release logic in there
- Another solution which may require us to modify EPICS (I am not sure the details of how alarms work in EPICS) to allow for latching directly in EPICS

**Comment by FreddieAkeroyd** [comment]
EPICS supports alarm latching and acknowledgement via the Db ACKS and ACKT fields - there are some details of how this works in the old Alarm handler manual https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/AlarmHandler/alhUserGuide-1.2.34/ALHUserGuide.html

The CS Studio alarm view also supports this http://cs-studio.sourceforge.net/docbook/ch14.html however for it to work i believe you need to log into the system, see #3594 It may also we worth thinking about #5422 too

It migth be running the phoebus alarm server rather than the CS Studio eclipse one

**Comment by KathrynBaker** [comment]
When this ticket is picked up, make sure to have a discussion in the technical channel.

Note specifically from Kathryn: we need this, we can't keep waiting to try something new

**Comment by FreddieAkeroyd** [comment]
It should be checked whether this ticket is actually necessary - alarm history as per #5422 may be sufficient and easier to implement. To be able to acknowledge alarms etc. required logging into the cs-studio system,  which on the one time we tried seemed awkward, maybe because of how we were encapsulating it. If we can do it easily all good, but alarm history may be much easier to add and is potentially more generally useful too

**Comment by KathrynBaker** [comment]
Superseded by #7943
