### ISSUE TITLE
Danfysik: Hide features not currently in use on OPI

### ISSUE THREAD

**Issue by JamesKingWork** [ISISComputingGroup/IBEX#6718]
As a user/scientist, I do not want to see disconnected pink boxes for features that are not in use on my danfysik device screen. Optional features that aren't in use should be removed.

## Acceptance criteria:

- [ ] Optional features on the danfysik are defined
- [ ] If the optional features aren't in use they are removed from the IOC

## Notes:

- This was reported by the muons

**Comment by boeuf-codes** [comment]
I am struggling to recreate this issue: assuming the optional features are those made visible/invisible by the four macros `USE_SLEW`, `POLARITY`, `CALIBRATED` and `DISABLE_AUTOONOFF`, I haven't been able to invoke the pink disconnection boxes. 

Could these 'optional features' be defined specifically (or the issue closed if this has since been fixed) please?

**Comment by Tom-Willemsen** [comment]
I think just close this issue as "can't reproduce"  or similar - we can create a new issue and link to this one if we find out the specific circumstances.

**Comment by KathrynBaker** [comment]
I had a quick look at POLREF (who have a Danfysik set up with all the "extras" turned off") and I couldn't see the extras or any pink borders, so it looks like it we can close this ticket.
