### ISSUE TITLE
WISH: Deploy IBEX and test hardware on beamline

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6738]
### Acceptance criteria
- Someone organises a week (or more?) of time on the WISH instrument for testing 
- A test plan is created for all of the hardware to be tested
- In this time IBEX is deployed on WISH (we could create a minor/patch release for this if there are other changes that need to be on the machine for testing?) 
- testing is undergone and any tickets for fixes are created

**Comment by ChrisM-S** [comment]
WISH is due for a machine upgrade.  It may be worth doing this first so that the tests are all carried on on the final configuration of the machine.  The WISH computer is currently off for work to be done on power sockets in the counting house - may already be finished - it was switched off a couple of weeks ago.

**Comment by rerpha** [comment]
Closing, this was done at the end of the long shutdown and we found issues with the ORC which have since been fixed.
