### ISSUE TITLE
Experiment Database Populator: Update to latest version

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#6771]
As a developer I would like the experiment database populator to not give me errors e.g. https://github.com/ISISComputingGroup/IBEX/issues/6465. This has been fixed in the linked ticket but needs deploying, there are instructions on the wiki on how to do this

Run Cron job using changes implemented as part of [6894](https://github.com/ISISComputingGroup/IBEX/issues/6894)

## Acceptance criteria 
- [ ] The latest version of the Experiment DB Populator is deployed
- [ ] The latest Version of Experiment DB Populator runs successfully with no problems.

**Comment by JackEAllen** [comment]
To review this, follow deployment instructions which can be found [HERE](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Experimental-Database#deployment) to ensure that cron job is running correctly and that problems fixed in #6465 are resolved in [Control SVCS](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/control-svcs)

**Comment by RaiBishal** [comment]
Seems to have latest changes in control svs however, the cron job is failing due to syntax error in https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/blob/master/exp_db_populator/gatherer.py#L59. `f` strings are not supported in the python version < 3.6 which is what control control-svcs is on. You will either need to update python or make syntax compatible with  python version < 3.6

**Comment by JackEAllen** [comment]
> Seems to have latest changes in control svs however, the cron job is failing due to syntax error in https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/blob/master/exp_db_populator/gatherer.py#L59. `f` strings are not supported in the python version < 3.6 which is what control control-svcs is on. You will either need to update python or make syntax compatible with python version < 3.6

I will have a look and likely upgrade to python 3. Upgrading Python versions should have ideally been written up as a part of this issue if work in previous tickets were written in Python 3 and it was known that Control SVCS ran Python 2. Is there anything else running on Python 2 I should be aware of before upgrading?

**Comment by JackEAllen** [comment]
Impeded until #6894 passes review.

**Comment by JackEAllen** [comment]
Removing impeded label as #6894 has passed review.

**Comment by RaiBishal** [comment]
Looks good and there is a venv for this service present. You will have to provide absolute path in https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/blob/master/rb_number_populator.sh#L5 for it to work.

**Comment by JackEAllen** [comment]
> Looks good and there is a venv for this service present. However, you will have to provide absolute path in https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/blob/master/rb_number_populator.sh#L5 for it to work.

From testing manually on [Control SVCS](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/control-svcs), using the relative path worked fine as I believe the cron job is running from here. However, it is good practice to use the full path which I've place in a  [PR](https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/pull/10).

**Comment by JackEAllen** [comment]
Redeployed after pulling recent changes made by [#10](https://github.com/ISISComputingGroup/ExperimentDatabasePopulator/pull/10#event-5632548670)
