### ISSUE TITLE
WISH (and others): OPI for the automatic needle valve

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6777]
As a scientist using the Eurotherm based automatic needle valve I want to be able to set and read appropriate values.

### Acceptance Criteria

- [ ] There is an OPI which displayed the read values related to the needle valve (TBC what these are, but expect PID and a temperature readback at least - KB awaiting the information from JN)
- [ ] There is a control on the OPI which allows for the system to be in manual mode or automatic mode
- [ ] In Manual Mode the flow value can be set on the OPI, but the temperature can only be read
- [ ] In Automatic mode the temperature can be set on the OPI, but the flow can only be read
- [ ] The records outlined in [Kathryn's comment](https://github.com/ISISComputingGroup/IBEX/issues/6777#issuecomment-1371249338) have been implemented as PVs

### Notes
1. #4240 handles the IOC that is needed for this, this is just the interface
2. After discussing with Jamie, both `FLOW_SP_HILIM` and `IP_ADDRESS_1` -`IP_ADDRESS_4` **have been removed from the requirements** as we are lacking sufficient information to implement these; they not sure they will be using the linear table moving forward, and the IP addresses need Jamie to assign them addresses before they may be implemented.

**Comment by daryakoskeroglu** [comment]
Simple OPI is implemented, however, either MODBUS Control IOC needs to be implemented (#4240) or MODBUS Eurotherm driver written by the Diamond Light Source (DLS) needs to be tested if it is suitable to be used in the IBEX system (#6846). Hence, putting this ticket to the Impeded column

**Comment by ThomasLohnert** [comment]
PVs need to be connected to buttons once the other ticket is completed, followed by testing.

**Comment by rerpha** [comment]
whoops,sorry

**Comment by ThomasLohnert** [comment]
Can't find the ticket branch for the original OPI implementation,  I don't suppose anyone knows where to find this? If not, do  we have some kind of idea what it should look like or are we back to talking to the scientists?

**Comment by KathrynBaker** [comment]
This isn't a talk to the scientists situation, and after a meeting this morning we are waiting to get the information as to what this needs to include.

**Comment by KathrynBaker** [comment]
There are 10 items to consider, items should only be writable under manager mode, there may need to be some changes to the IOC to support accessing these items

| Item | Description/Details | Address | Read/Write | Notes |
| -- | -- | -- | -- | -- |
| PV (Have asked to rename to `flow`) | "Flow" Flow readback from transducer | 1025 | Read | |
| Valve Direction | 0 = Closing; 1 = Opening | 4827 | Read | |
| Flow Setpoint Select | 0 = Auto setpoint mode; 1 = Manual setpoint control | 1300 | Write | |
| Manual Flow Setpoint | Manual flow setpoint; Reliant on 1300 being at 1 | 1509 | Write | |
| Flow Setpoint Low Limit | Low setpoint limit for flow control | 1136 | Write | |
| Flow Setpoint High Limit | Flow setpoint high is derived from a look up table to ensure a max flow SP is sensible for different temperatures | Multiple | Write | See picture below |
| IP Address Monitor | First set of IP address numbers. | IP_address_1 | Read | |
| IP Address Monitor | First set of IP address numbers. | IP_address_2 | Read | |
| IP Address Monitor | First set of IP address numbers. | IP_address_3 | Read | |
| IP Address Monitor | First set of IP address numbers. | IP_address_4 | Read | |

![image](https://user-images.githubusercontent.com/10552381/210619981-10f34263-24dd-44d3-887e-464477bf9e16.png)

**Comment by boeuf-codes** [comment]
**PRs:**
- IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/781
- Device emulator: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/163
- IOC test framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/593
- GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1543
-  Release notes: https://github.com/ISISComputingGroup/IBEX/pull/7705

**Documentation:** 
[Automatic Needle Valve Controller](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Automatic-Needle-Valve-Controller)

Linked to from: 
 - [Eurotherm](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eurotherm)
 - [Temperature Controllers](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Temperature-Controllers)

**Comment by boeuf-codes** [comment]
All rework I've done is pushed and marked as 'resolved', and below is what I couldn't finish:

- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/163#discussion_r1175408380
    - I wasn't very sure what this meant
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/593#pullrequestreview-1398205233
    - This test is unstable: it mostly passes, and only rarely doesn't pass (and always seems to pass on the first test). There was no changes to the `TEMP:SP:RBV` PV so I'm not sure why it would be failing after the NV changes.
- https://github.com/ISISComputingGroup/ibex_gui/pull/1543#discussion_r1175515272
    - This was an unintentional change; I tried fixing it but couldn't manage to reload the target platform without errors.

**Comment by esmith1729** [comment]
This ticket is a rework of some strands left off from awhile ago: 

## Summary:

- https://github.com/ISISComputingGroup/EPICS-ioc/pull/781 
  - Due to using modbus comms for the needlevalve, a phone "NUL" port was added to the IOC, st-comms-modbus.cmd, to run in RECSIM, as modbus was interfering with records in RECSIM otherwise.
  - Created fields to make no alarm go off on a UDF alarm, if the record is a Setpoint. This is because a setpoint might not be set, and we don't want to necessarily initialise it to a value, but we also don't want it to be invalid. This handles that. 
  
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/593
  - Many tests were failing after merging master back into this branch, as significant time had passed, and relevant changes were made nearby. These test failures were solved by adding "A01" to the prefix of every PV in the needlevalve_modbus.py test file, as the names of these PVs is created with A01 prefix. 
  - The Temperature ramp rate test which was commonly failing, was attributed to this "A01" prefix thing, in the end.
  - Some IOC property names, such as "flow", were changed to "needlevalve_flow", and this change wasn't made in the test module as well. Renaming these variables fixed the issues of not connecting to those PVs.
  - Some abstract classes, in eibisynch test module, were not included. Those have been included now, and the error of not able to initialise should be resolved. 
  
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/163
  - I've merged this already, but basically the only change was having a try/except clause to return "None", as otherwise an error raised would still return the command, when it should return *something* else, to signify an error, or an inability to write.
  
  
## Release Notes: 

- https://github.com/ISISComputingGroup/IBEX/pull/7705/

**Comment by esmith1729** [comment]
New branch created for some emulator changes that were also required: 

- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/171
