### ISSUE TITLE
Client install: check for install errors

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6991]
As a developer I would like a client install to fail on error. Currrently i do not believe this is the case, just a message will be printed.

### Acceptance Criteria
- client install error terminates install, or prompts to retry

### Extra Information
install_client.bat in ibex_gui directory will need to return an error code, also python ibex_upgrade script will need to check this. At the moment the upgrade scripts run the bat file with a "prompt" option that does not check error codes returned

**Comment by FreddieAkeroyd** [comment]
I believe the first part of "extra information" (ibex_client) was fixed previously during deployment, so just the second part (upgrade script) remained which may be  covered by existing above PR

**Comment by JackEAllen** [comment]
The changes to install_client.bat in https://github.com/ISISComputingGroup/ibex_gui/commit/8e1c00d effectively renames the error branch from FINISH to ERROR and returns a non-zero code. 
The main purpose if this issue is to ensure that if an error occurs such as during robocopying, it is propagated to the user executing the script.  
The ticket was created as an error had been printed from one of these but the ibex install python continued anyway
You could try placing a `set errcode=5` after the robocopy in the client_install.bat script and setting source path `%BASEDIR%Client` to an invalid path.

Without the [PRs](https://github.com/ISISComputingGroup/ibex_utils/pull/122) you should get an error printed to log/screen, but ibex install continues.
With just the the run_process.py PR it should spot the error and stop.
The client_tasks.py PR was just to make it run in non-interactive mode, which then bypasses the logic added in the run_process.py PR, however other install tasks may use the added logic

**Comment by FreddieAkeroyd** [comment]
The 8e1c00d commit makes the error message clearer, but it looks like the old code still lead to a failure on error - the errorlevel was propagated down and did not require an explict exit /b. 

The main issue is governed by the PR  https://github.com/ISISComputingGroup/ibex_utils/pull/122  in particular the checking of `output.returncode` - in the old code this was not checked, so if  `RunProcess(source_dir, "install_client.bat", press_any_key=True).run()` encountered an error while running install_client.bat  an exception was not raised in python, compare this to the code after this branch where `return_code = process.wait()` is used
