### ISSUE TITLE
Technix PSU: Hardware Testing 

### ISSUE THREAD

**Issue by daryakoskeroglu** [ISISComputingGroup/IBEX#7129]
As a developer, I would like to do hardware testing on Technix PSU as a part of [#5874](https://github.com/ISISComputingGroup/IBEX/issues/5874)

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Hardware is working as required - see acceptance criteria as #5874
- [ ] scientist/technician has seen it, anything bigger than minor tidy ups create new ticket

#### Notes

1. Technix manual is here: \\isis\shares\ISIS_Experiment_Controls\Manuals\Technix power supply
2. The RIKEN front-end will feature 6 Technix PSUs.
3. IBEX should support at least 6 Technix IOC instances.
4. Note sections 1.7 & 1.8 of the Technix manual: 
    * 1.7 Maximum Frequency (define maximum frequency of communication)
    * 1.8 Use and Safety
7.  Installation/Commissioning Timescales (as of 06-11-2020, subject to change)
    * The Technix PSUs are due on-site in May 2021.
    * They will be installed and commissioned in Jan 2022.

**Comment by davidkeymer** [comment]
@daryakoskeroglu 
PSU now set up in lab ready for testing.  Available until early July when it will be installed in the RIKEN area.  Lab is access controlled, so will need to contact relevant person when ready.

**Comment by Tom-Willemsen** [comment]
Issues found in testing:
- [ ] Interlock open/closed, closed is currently red (bad) in OPI but should be good.
- [ ] Mains status LED is wrong due to inconsistent PDF/paper manuals. The correct statuses should be `F001` -> "Arc present" and `F000` -> "No arc"
- [ ] The macro pattern in `config.xml` doesn't allow floating-point numbers for max current, but it is in Amps and the max current for the PSU in 4mA
- [ ] To turn HV on, need to send local mode, remote mode, hv on
- [ ] Power supply group would like the units to be `kV` and `mA`, not `V` and `A` as these units make more sense for this type of HV power supply. The power supply is rated to 150kV

**Comment by Tom-Willemsen** [comment]
PRs:
- https://github.com/ISISComputingGroup/EPICS-Technix/pull/1
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/706
- https://github.com/ISISComputingGroup/ibex_gui/pull/1448

**Comment by Tom-Willemsen** [comment]
Had to revert change to send local mode, remote mode, set HV on as this didn't work nicely on hardware. Will note this as a quirk on the wiki instead.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/7252/files
