### ISSUE TITLE
Push changes to multiple machines outside of a release cycle

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#72]
As a support user I would like to be able to push files as required to multiple, or single machines, potentially outside of a release cycle, so that alterations are reflected immediately when necessary.

E.G At present Eurotherm calibration sensor files are updated periodically with new ones, whilst the information is updated into the source control, as there is no guarantee when a new sensor will be used on a beamline a manual process is employed to update every machine with the new files when they become available.

Success criteria:

A single command/button press on a GUI will distribute the named file(s) to the named location(s)

It would also be nice to automate the conversion of the files into the format we use, there are instructions in the LabVIEW location for the files

This could make a good work experience task: Code to do the automation, code to deploy the files, somewhere for the files to be put so that they can be just automated and pushed without interaction from the computing group

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 72.  Created by kvlb23 on 2013-02-13T16:10:29, last modified: 2015-09-21T11:16:51_

**Comment by kjwoodsISIS** [comment]
This is really an operational ticket - not directly relevant to development of IBEX.
While it would be a nice thing to do, it seems unlikely that it will get done at any time in the foreseeable future, therefore, this ticket will be closed.

**Comment by ChrisM-S** [comment]
I can see that pushing multiple updates (for example due to a security concern) is potentially operational but I am concerned that there is a lack of good automatic tools within the IBEX project to even allow this, essentially we need remotely automatable tools

1. bring an ibex version up to date
2. to check it's consistency (is there a missing or damaged file? etc.)
3. to raise or lower the installed version on an existing installation.
4. to remove an installed version cleanly.
5. to Install a version of IBEX automatically.
6. to confirm and test the proper functioning of an installed system.

From my own experience (installing and testing even a clean IBEX suite is really very complicated, even after successfully installing all the pre-requisite apps).  I think I have only found a SharePoint installation more difficult!

The development project would benefit massively itself if these tools existed because they could be used to create and remove testing scenarios reliably, guarantee that deployments were functioning correctly and could be tested under regression (we will have machines that have to work with a previous version!)

Chris

**Comment by kjwoodsISIS** [comment]
I agree that these 6 proposed tools would be very useful indeed, but they are not within the scope of the ticket as originally proposed.  For example, the original ticket uses pushing Eurotherm calibration files as an example.  In fact, now that I come to think of it, we have addressed this particular issue in ticket #1425.

Creating a tool that automates the entire installation process is on a totally different scale to that envisaged by the original ticket.  That's not to say that such a thing is not important - it clearly is.  But it is not within the scope of the original ticket.

Each of the 6 tools described above probably warrants a ticket of its own (in some cases, perhaps more than one ticket).  Furthermore, we should have a review of the recent installations & upgrades on LARMOR, IRIS & IMAT to make sure we **_document and learn_** what went well, what did not go well (and why), what was difficult, what was easy, what was complex, what was simple, and what we want to do to improve the process.  We also need to think about whta it will take in terms of hardware resources to support activities like comprehensive regression testing.  Then we can start creating tickets to create automated tools.
