### ISSUE TITLE
WISH: set up mclennan driven centre stick

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7209]
WISH's centre stick has been fitted with an encoder and the motor is now geared differently. This ticket is for recommissioning it for an upcoming experiment on 8/7/22

Hints: 
- CMODx will need to be CLOSED to utilised the encoder 
- ERESx will need to be set to whatever the resolution is

This will be commissioned in the sample env lab to obtain numbers and smoke test etc. then it will be moved over to WISH.

### Acceptance criteria
- [ ] centre stick is correctly configured on WISH

**Comment by rerpha** [comment]
We have come to the conclusion that after trying to brute-force every serial setting the mclennan can cope with (and some that it likely can't) the mclennan itself is just not talking. We are going to try and use a different mclennan crate to drive the centre stick and see if that works instead.

**Comment by Tom-Willemsen** [comment]
Having been given access to a ~new~ different mclennan controller, we've been able to control it open-loop, with `MSTP=11.1111` and `9600/7/even/1` serial settings.

Controlling it closed loop is giving us issues because the encoder seems to think both motor directions are positive. There might be a setting we can send to the mclennan in software for this, or it might be physical switches/wiring on the mclennan or motor. We will ask electronics for more details here.

**Comment by Tom-Willemsen** [comment]
Eventually comissioned offline in SELAB, in closed-loop mode. Key issue seemed to be that motor was not getting enough amps, causing a bunch of stalls. It's not clear to me why this would have previously caused the mclennan to report weird encoder readings.

After electronics increased amps to motor, motor was tested with a variety of moves and worked fine.

Settings (anything not listed here should be left as default):

```
			<macro name="AXIS1" value="yes"/>
			<macro name="BAUD" value="9600"/>
			<macro name="BITS" value="7"/>
			<macro name="DHLM1" value="9999"/>
			<macro name="DLLM1" value="-9999"/>
			<macro name="ERES1" value="400/4000"/>
			<macro name="JVEL1" value="5"/>
			<macro name="MSTP1" value="11.111111"/>
			<macro name="MTRCTRL" value="2"/>
			<macro name="PORT" value="COM53"/>
			<macro name="STOP" value="1"/>
			<macro name="UNIT1" value="deg"/>
			<macro name="VELO1" value="2.5"/>
```

**Comment by Tom-Willemsen** [comment]
Comissioning on WISH tomorrow morning.

**Comment by Tom-Willemsen** [comment]
This is now all sorted on WISH.

- The communication issue with the old crate (not getting *any* bytes back at all) was caused by a missing RS232 termination thing which looks a bit like a null modem, and is required to be in the daisy chain port for it to work. Wish are using their old mclennan for axis 1 now as there was no physical problem with this - just the comms issues which are now sorted as described above.
  * Have added this to wiki at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/McLennan-motors
- Axis 2, which originally had an issue on WISH, has been replaced by a new (old) single axis mclennan, comissioned on WISH with the settings described above.

The scientists are now happy that all relevant axes have appropriate control.
