### ISSUE TITLE
ConfigChecker: warn if a mclennan has all AXISx macros set to 'no'

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#7260]
On WISH a mclennan motion controller powered motor axis suddenly stopped showing up in the table of motors and the cause of this was due to all of the AXISx (eg. AXIS1) macros being set to 'no'. If this is the case no motor records are loaded, as the mclennan IOC thinks there are no motors, which leaves a scientist thinking something has gone drastically wrong when actually its just that a macro needs to be set. This isn't immediately obvious as there are so many macros to set for a mclennan that the AXIS macros can get lost in between the others eg ERES, MRES etc. 

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Config checker warns when all of the AXIS[x] macros are set to 'no' on an instrument. 

### Extra Information
_Why it is needed?_

_Where required files/links are_

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by Tom-Willemsen** [comment]
Note that:
- The default value for `AXIS_x` is `NO` - so if no value is specified this should be assumed to be `NO`
- Macros may be defined either in the configuration/component, or in `globals.txt`
- We need to check all `AXIS_x` macros, not just `AXIS_1`, because single-axis mclennans can be set up to report their single axis as any axis number (via a physical rotary switch in the hardware)

I think the minimal logic for this test is:
- For each configuration and component on an instrument:
  * For each `MCLEN_xx` ioc present in the configuration/component:
    * If at least one `AXIS_x` macro is present in this config/component and set to `YES`, this IOC is valid
    * If at least one `AXIS_x` macro exists in `globals.txt` for this IOC and is set to `YES`, the IOC is valid
    * Else, the IOC is invalid - the test should fail in configchecker

---

Ideally, this would be a generic utility function where we can specify that for any arbitrary IOC prefix, at least one of a list of macros matches a specified pattern. For example for the eurotherm we would want a similar test to look at the `AO1..AO10` macros and at least one of them should be set to a number (see https://github.com/ISISComputingGroup/IBEX/issues/7152#issuecomment-1161781284)
- Pattern can be implemented as a regex, for mclennan we would just match `^YES$`, for eurotherm `^[0-9]+$`. At least one macro should match the provided pattern for an IOC to be valid
- Macro list can be hard-coded per ioc in the tests (they rarely change anyway) or use a prefix (e.g. `AXIS_` for mclennan, `AO` for eurotherm)
- IOC name should be a prefix so that we run the test on `IOC_01`, `IOC_02`, etc.

**Comment by boeuf-codes** [comment]
Found a number of **Mercury iTC IOCs with outdated macros** from version ~6; have skipped testing these instruments for mercury specifically, so new issues can be found and 'new' invalid mercury IOCs still fail.

See below for a list of the instrument + config/component the outdated IOCs belong to:

| **Instrument**  | **Configuration/Component** |
| ------------- | ------------- |
| LET  | LET_Mercury  |
| OSIRIS  | OSIRIS_Mercury | 
| MAPS | mercury_itc |
| GEM | Mercury_cryostat |
| SANDALS | GEM_mercury |
| IRIS | triton |
| ZOOM  | isistat |
| LARMOR | ISISTAT |
