### ISSUE TITLE
System Tests: Running `create_virtual_env.bat` in system_tests can corrupt python installation

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7312]
## Where?
Running the System Tests using `run_tests.bat`.

## How?
- Running the script gives error `ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: \\system_tests\\my_venv\\lib\\site-packages\\pyhamcrest-2.0.4.dist-info` and warns about `METADATA` missing.
- `INSTALLER`, `METADATA`, `RECORD`, `REQUESTED`, `WHEEL`, and `LICENSE` are missing from `system_tests\my_venv\Lib\site-packages\pyhamcrest-2.0.4.dist-info\`.
- Python fails to import module `configobj` in `test_setup_teardown.py` line 3.
- Tests crash.

## Reproducible?
Yes

### To Reproduce
- Start the script.
- Stop the script before it completes.
- Run the script again.

Sometimes the script just fails outright.

To fix the script delete the `pyhamcrest-2.0.4.dist-info` folder and run again. Now the script should continue as normal and run all the tests.

## Acceptance criteria
- [ ] Cause of issue is understood.
- [ ] Issue is fixed.

**Comment by boeuf-codes** [comment]
### Bug description
Triggered by any run of `create_virtual_env.bat`, which corrupts all files and folders contained in `system_tests\my_venv\Lib`.
As `create_virtual_env.bat` is run from `run_tests.bat`, the bug is triggered _every_ time `run_tests.bat` is run, irregardless of whether it runs to completion or not.

### Fix
The corruption of `system_tests\my_venv\Lib` (the bug described in the above ticket) seems to be fixed by updating dependencies, specifically **updating Python to Python 3.10** - thus no pull request is needed here.

### To test

1. First, **update dependencies** - for specific instructions, see Thomas W's message on the **dev-changes-memo channel** on teams.
2. Second, to test the error, run `run_tests.bat` **twice**;  if the bug is rectified, the _second_ time `run_tests.bat` is run, the virtual environment libraries will not be corrupted by the previous run.
