### ISSUE TITLE
Move Away From CS Studio Eclipse: Compatibility Layer Proof of Concept [TIMEBOX: 8 days]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7578]
As someone using IBEX I want my UI to be easily maintained, and as CS Studio Eclipse is used by fewer systems, I want to see if a compatibility layer between IBEX (Eclipse) and CS Studio Phoebus (JavaFX) is possible

## Acceptance Criteria
- [ ] Attempt to migrate either the alarm view or log plotter (the simplest views we have) into JavaFX and continue to display them in IBEX
- [ ] Documentation exists detailing the compatibility layer, and how to migrate the view
- [ ] #7577 is updated to reflect the findings and likely next steps
- [ ] A next step ticket is created/proposed/started as appropriate

## Notes
- As this is a proof of concept it should be timeboxed to a reasonable duration
- Documentation of failures may be as vital as documentation of successes

**Comment by Tom-Willemsen** [comment]
The compatibility layer to investigate first is https://www.eclipse.org/efxclipse/index.html

There is an old branch here: https://github.com/ISISComputingGroup/ibex_gui/compare/master...Ticket4722 which added in a JavaFX log plotter from CSS to IBEX via e(fx)clipse. It was never merged as we found an alternative solution at that time, but it may be a useful reference point to understand how to use the e(fx)clipse layer in IBEX and what libraries/flags/configurations need adding. It is not suitable to use as-is, as the branch is out of date so dependencies will have moved on.

**Comment by Tom-Willemsen** [comment]
Native phoebus alarm-tree view rendering inside IBEX via efxclipse:

![image](https://user-images.githubusercontent.com/24375813/222435825-430a14b9-ab37-421d-8788-3b8134227b0f.png)

---

### Overall approach
- We are getting phoebus directly from maven currently - this seemed the lowest-friction route to getting a proof-of-concept running. 
  * If we end up using the compatibility layer, we should consider setting up our own repository to get phoebus from, as we have historically needed to make patches in CSS/phoebus code periodically
- We are getting javafx via `.jar` files copied into the client, downloaded from gluon. I tried getting javafx directly from maven but this doesn't work for reasons I don't fully understand - the downloaded jars are empty.
  * May be related to dependency between the "normal" jfx jars and `javafx-swt.jar`, which isn't available via maven anyway.
- efxclipse is coming from a standard eclipse P2 update site.
- The branch is branched from the dependency updates branch, as I have fiddled with *many* dependencies as part of this work and didn't want to conflict too much.

### Caveats
- The phoebus alarm view connects via kafka, I haven't set this up so the view doesn't do anything useful currently. To make this useful, we would also need to configure the newer (kafka-based) alarm server etc - that didn't seem in scope for this ticket.
  * It is functionally equivalent in native phoebus and IBEX currently - which happens to be very little/no functionality because we don't have the right alarm server setup.
- It's not possible to simultaenously add dependencies from "old" cs-studio and phoebus, due to conflicting libraries. Therefore it will not be possible to ship a client with (for example) log plotter from old CSS but alarm view from new CSS. Instead, if we want to use this approach, we need to migrate *all* cs-studio related views at the same time.
- At some point in moving the `diirt` dependency from css to phoebus, I've broken all channel access from the client. The dependency is there so it can all theoretically work, I think it might just be missing a config file or something similar.
  * ```12:59:31.318 [main] ERROR Instrument - Error whilst reading instrument list: Channel CS:INSTLIST uses default data source ca which was not found.```
- Due to having to remove *all* of the old CSS dependencies to get allow any phoebus functionality to work, I've had to "hack out" log plotter + anything that references OPIs on my branch. I've currently done this in a *very* hacky way (just removing/commenting out large chunks of code). My feeling is that we should tackle this as-and-when we get to migrating each item - I don't feel it's worth trying to remove this in a "clean" way, only to need to re-add it later.
- I had to disable our CSS stylesheet - because the CSS parser that we were using came from CSS, and I ran out of time understanding how to get it from elsewhere. This means that we currently have minimise/maximise icons on each view, which we shouldn't usually.
  * This shouldn't be *too* hard to fix, just fiddling with dependencies somewhere.
- The logic to highlight and show numbers of alarms on perspective button has been removed on my branch, as it was complicating this ticket and my goal was a simple PoC. This will need to be readded later.
