### ISSUE TITLE
LSI Correlator: Investigate whether or not it is possible to get the waveform from the correlator [TIMEBOX: 1.5 days + 0.5 for reviews etc.]

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7603]
Sub-ticket of #7566 

As someone supporting this system within IBEX I want to verify that we can provide the information requested by the scientists using the device in #7566 

## Acceptance Criteria
- [ ] The use of the API has been looked at for getting the waveform information

**Comment by rerpha** [comment]
we can get it through each repetition at the very least https://github.com/ISISComputingGroup/EPICS-LSICorrelator/blob/master/correlator_pcaspy.py#L299

**Comment by rerpha** [comment]
it's very difficult to tell how often we can retrieve the data but we seem to only call update() at the end of a repetition. I am unsure if this would work several times per run but it certainly looks to be possible. at the very least we could plot at the end of a repetition which is much better than just at the end when the data file has been written. 

here we call update() when taking a measurement, not sure if this could be done more than once per repetition: https://github.com/ISISComputingGroup/EPICS-LSICorrelator/blob/96c92ce5f39ac93e1b95dfd546c02817a4a23e30/correlator_driver_functions.py#L150 

the API just seems to poll as fast as it can when updating, so im not sure it's got any sort of throttle - might just be as fast as the correlator can provide the data. obviously the vendor software does it fairly quickly so i can't see a reason we wouldn't be able to either.

**Comment by pheest** [comment]
The real issue here is that the manufacturer Python API does not make an event-driven capability available.
If had been enabled, it would be possible to process the data frames individually.

The onMessage callback handler https://github.com/ISISNeutronMuon/LSI-Correlator/blob/ea0d72bda7ced61e84eee92107afca86c992e882/ws_bridge_data.py#L22
calls processCorrData https://github.com/ISISNeutronMuon/LSI-Correlator/blob/ea0d72bda7ced61e84eee92107afca86c992e882/ProcessLVmessage.py#L12
when new data has been received; this could have been used to provide notification to the application code.

Within the existing design of the manufacturer API, it would be possible to poll the data state and update the UI more frequently.
But doing so isn't likely to provide a very satisfying user experience.

**Comment by rerpha** [comment]
> The real issue here is that the manufacturer Python API does not make an event-driven capability available. If had been enabled, it would be possible to process the data frames individually.
> 
> The onMessage callback handler https://github.com/ISISNeutronMuon/LSI-Correlator/blob/ea0d72bda7ced61e84eee92107afca86c992e882/ws_bridge_data.py#L22 calls processCorrData https://github.com/ISISNeutronMuon/LSI-Correlator/blob/ea0d72bda7ced61e84eee92107afca86c992e882/ProcessLVmessage.py#L12 when new data has been received; this could have been used to provide notification to the application code.
> 
> Within the existing design of the manufacturer API, it would be possible to poll the data state and update the UI more frequently. But doing so isn't likely to provide a very satisfying user experience.

I agree. I think our answer to this question is yes we can do it, but only update after every repetition

**Comment by pheest** [comment]
I would tend to suggest contacting the manufacturer to ask whether an event-driven Python API could be made available. It would certainly be possible to implement it.

**Comment by rerpha** [comment]
will type up notes on main ticket
