### ISSUE TITLE
Use compiled LabVIEW VIs on instruments

### ISSUE THREAD

**Issue by ChrisM-S** [ISISComputingGroup/IBEX#7680]
See ticket https://github.com/ISISComputingGroup/ControlsWork/issues/729

**Comment by KathrynBaker** [comment]
The following IBEX Repos mention or use LVDCOM or LabVIEW:

EPICS-lvdcom 
EPICS-NimaTrough
EPICS-MuonJaws 
EPICS-MercuryCryo 
EPICS-Magnet3D 
EPICS-Stanford_SR400
EPICS-FMR
EPICS-Agilent_53220A
EPICS-Stanford_PS350

The IOCs in the table below contain the `lvDCOMConfigure` command, and some insights as to how much they are used and how easy it may be to deal with them.

IOC | In a config on | Needs editing before building | ISIS or manufacturer VI | Which other instruments are likely | Easily migrated to IBEX | Notes |
-- | -- | -- | -- | -- | -- | -- |
SAMPOS | ENGINX | Yes | ISIS | None | No | Safety implications, do not want to change the motion setup if at all possible |
NIMATRO | SURF, INTER | Yes | Manufacturer | Unsure | No | 
HIFIMAG | None | N/A | ISIS | None | N/A | 
INSTETC - commented out | N/A | N/A | N/A | N/A | N/A | 
DELFTSHEAR | None | Likely - DELFT software | Manufacturer | Unsure | Unknown | 
FMR | None | N/A | Manufacturer | Unsure | Unknown | Has the VIs in git
DELFTARDUSTEP | None | Likely - DELFT software | Manufacturer | Unsure | Unknown | 
SCIMAG3D | LARMOR, ZOOM | Yes | Manufacturer | Unsure | No | 
COUETTE | LARMOR, DEMO | Yes | ISIS | LOQ | Possibly  | Uses a McLennan
EGXCOLIM | ENGINX | Yes | ISIS | None | No | Safety implications, do not want to change the motion setup if at all possible
STSR400 | None | Yes | ISIS | Unsure | Yes | 
DELFTDCMAG | None | Likely - DELFT software | Manufacturer | Unsure | Unknown | 
AG53220A | None | Yes | ISIS | Unsure | Yes | 
MUONJAWS | EMU, MUSR | Yes | ISIS | HIFI | No | This sets local variables in Galils based on a look up table, convoluted rather than hard
STPS350 | None | Yes | ISIS | Unsure | Yes | 
SECI2IBEX | N/A | N/A | N/A | N/A | N/A | 

Note that only 9 instruments are named (including the 2 with the "likely to be used on" classification).

**Comment by KathrynBaker** [comment]
Given these limited aspects and the amount of work needed to achieve this it is likely to be uneconomical for the time it will take.
