### ISSUE TITLE
LET: Make Collimator Sweep Angle Adjustable

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7696]
As a: LET Instrument Scientist / User I would like the angle of the oscillating radial collimator to be adjustable.

### Acceptance Criteria
_What is the acceptance criteria?_
- [ ] Ensure that the expected behaviour is understood by the scientists and ourselves
- [ ] If code changes are needed create a new ticket to detail them clearly

### Extra Information

Email from LET:
> The sweep angle of the LET ORC is not adjustable via IBEX.  We need this functionality in order to:
> 1) properly adjust the sweep angle to the pitch of the collimator blades on LET for different sample geometries
> 2) avoid running the ORC motor to the end of it's range, hopefully increasing the lifetime of the motor.
>
> Severity: MAJOR - Nuisance, potential for lost beamtime
>  Priority: P1 - Urgent, no workaround

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by KathrynBaker** [comment]
The angle is settable, but there may be some other issues possible with this situation, so there will need to be some observance of the problem to figure out exactly what is needed.

**Comment by rerpha** [comment]
LET collimator indeed not actually setting a swept angle other than 2.000 degrees. weirdly, patching over the latest motorextensions fixed the issue, suggesting that either: 
a) a deploy overwrote a fix for it which didn't quite make the release
b) some changes hadn't been patched over after i'd tested them on my laptop
c) (unlikely) the win10 migration stuff overwrote it  

While on LET I patched over #7625 and tested and found an issue with the MODE:_CALC which was showing stopped when oscillating. I added a clause for this to check USE_LASR on WISH but otherwise use MODE:_READ on LET+MERLIN: 
https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/53

**Comment by rerpha** [comment]
spoke to scientists, they are happy with changes from IBEX but are going to measure the swept angle and make sure it sweeps more or less with a bigger or smaller angle. going to put in review and create another ticket if there are further issues
