### ISSUE TITLE
MOXA IOLogik - Add support for E1242 module

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7875]
As an instrument scientist, I would like to be able to use a MOXA IOLogik device fitted with an E1242 module.

### Acceptance Criteria:

- Support for the E1242 module is added to the MOXA IOLogik IOC
- Additional value to select E1242 module added as macro to IOC configuration
- Macro for current configuration of channels is provided (see notes)
- Simple indication of logic state for DIO displayed on OPI (see notes)

#### Notes:

- The E1242 module has 8 digital inputs and 4 analogue inputs
- Four of the eight digital inputs _can_ be configured as outputs (via jumper).  However in practice on EMU, they are **inputs** (8x DI, 4x AI)
- Check code for other supported modules, particularly DIO, for how logic states are displayed.  Do not alter, but add to, existing functionality
- No units for digital inputs, but Volts for analogue inputs (0-10V range)
- Required for logging amplifier status during an experiment on EMU
- Initial testing confirms that the current IOC connects to the 'chassis' but does not read useful data

**Comment by davidkeymer** [comment]
Required for September cycle.  Some work on the hardware is still required, so propose this ticket be started in the August sprint.

**Comment by KathrynBaker** [comment]
If there is a desire to check this against hardware it may be an option, speak to one of those involved or an appropriate IS to get an address.

To test:
* Run up the IOC and make sure the names get populated to the new IOC (Note, there are AICHAN and DICHAN names which are for use with the 1242, the others as yet do not use those names, or have an option to do so)
* Run the tests for this and the existing IOCs to ensure all is well (Note, there is something odd in the DI tests for the 1242, the counter tests fail in a way that has been hard to diagnose or remove on my PC, the 1210 works as expected, and which channels fail varies each time, and may pass at other times, if this is viewed as unhelpful from the perspective of the testing of the larger system, it is probably best to skip that test)

Follow on tickets:
https://github.com/ISISComputingGroup/IBEX/issues/7964 - To correct the st.cmds and macros so that there is only one style of naming not 2, this has been spun out in favour of completing a ticket needed for a release
https://github.com/ISISComputingGroup/IBEX/issues/7963 - This is because there wasn't enough time to refactor the tests sensibly

Pull Requests:
Release Notes: https://github.com/ISISComputingGroup/IBEX/pull/7965
GUI: https://github.com/ISISComputingGroup/ibex_gui/pull/1585
IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/804
Support Module: https://github.com/ISISComputingGroup/EPICS-MOXA-IOLOGIK-E12XX/pull/5
IOC Test Framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/607
Emulator changes: https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/172
