### ISSUE TITLE
Aeroflex Signal Generator - Remove control for modulation type

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7880]
As an instrument scientist, I would like the control for the modulation type on the Aeroflex signal generator OPI to be removed.

Comment from IS:

> "At present the IOC has a control for setting the type of modulation. It’s not quite clear what this is doing and in any case remote control of this function isn’t required. I’d suggest this control is simply removed."

### Acceptance Criteria:

- Investigate current functionality and inform IS (check which commands are being used)
- Control of modulation type is removed from the OPI

#### Notes:

- Suggest leaving functionality in the IOC and do not expose it in the OPI.
- IOC startup must **_not_** alter the state of the modulation type

**Comment by esmith1729** [comment]
Have had a longer look at the IOC for this device, to ensure that functionality won't be impacted by removing user ability to set modulation mode/type; and it seems that for the 2030 model (and perhaps also for the 2023A) functionality could be restored by a refactoring of those IOCs, possibly. It seems like the states for the mbbo mode setpoint and mbbi mode record do not match with each other for the 2030's .db file, and also do not match the format expected by the .proto file. Additionally, pre-existing tests are run by setting a PV value over self.ca.set_pv_value(), and then checked with an assert_that_pv_is(), rather than setting them on the device, and checking that the PV was read by the device, which seems a bit dubious. 

Should this be a "remove this for now, investigate fully later" sort of solution? It seems like the emulators have undefined behaviour with the IOCs, and many tests already written should be failing but are passing.

**Comment by zsoltkebel** [comment]
We had some issues with merge conflicts with another aeroflex ticket. This will probably happen with future tickets too regarding aeroflex.
