### ISSUE TITLE
SANS Instruments: Investigate and correct behaviour of scripts when arguments not supplied [TIMEBOX: 2.5 days]

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#7908]
As a SANS instrument scientist working on SANS2D, ZOOM and LOQ, I would like to be clear about how the `do_sans` and `do_trans` scripts behave when no arguments are supplied, and that _no_ default values are used.

It seems that at the moment, default values are used, but it is not clear where these are defined.

### Acceptance Criteria
- Scripts behaviour is made clear to the instrument scientists
- Default values are _not_ used when no arguments are supplied.  Current values should remain unchanged.

#### Notes
- See details in 'Support-Issues' Teams channel for details 04/07/2023
- This confuses scientists and users, and could potentially cause loss of beam time.

**Comment by KathrynBaker** [comment]
Query whether to make it questions to get people to choose, or consider forcing a "use arguments" default.

**Comment by LilithCole** [comment]
It seems the source of the original support call was that thickness was defaulted to 1mm. Removed the default and made it only set when a value is provided, as is the case for all other values.

Additionally a default blank title was being provided, so that has been removed and some extra logic put in to make sure that it doesn't override anything if no title is provided (the desired behavior fed back by instrument scientist

**Comment by LilithCole** [comment]
https://github.com/ISISNeutronMuon/InstrumentScripts/pull/110
