### ISSUE TITLE
Script Generator: Investigate Application Size [timebox: 2 days]

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISComputingGroup/IBEX#7933]
As a user of the script generator, I would like this application to be lightweight and portable so I can easily download or be sent the Script Generator application, in order to create scripts in preparation to my visit to ISIS.

Currently, the size of  the script generator is >1GB, the vast majority of this (880mb) is the bundled IBEX python instance including all dependencies.

We should review how much of this is needed for the script generator to function and reduce its size if possible.

### Acceptance Criteria
_What is the acceptance criteria?_
- [x] Size of the Script generator application is reviewed and either:
    - Significantly reduce size of the Script Generator (if the amount of work needed is reasonable)
    - [x] Create a spin out ticket to reduce the size of the Script Generator (if the amount of work needed exceeds the scope of this ticket)
    - Show/reason why a significant reduction in application size is not feasible

### Extra Information
- Muon group has assigned "crucial" priority to this issue.
- Due to the open ended nature of the work, this may be suitable for timeboxing

## How to Test
_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

**Comment by LilithCole** [comment]
Given the first thing it looks for is instrument/apps/python3 to use, then defaults to the packaged file, it may be worth it to create a setup script which:
- checks for genie python at the usual location
- checks for a python install to create a venv for with an ipython profile
and if either of those work, removes/doesn't unpack the python install.
Sadly I ran out of the timebox for this ticket investigating whether poetry would handle the heavy lifting, but it just turned out to cause more issues if anything, spinning off another to carry on the work, probably simplest is to use standard venv and pip tools.

**Comment by will2201** [comment]
Spin-out ticket has been created - closing this issue.
