### ISSUE TITLE
control svcs going down causing CaChannel(?) hangs

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#8142]
During dec 2023 several instruments had issues within their scripts where some PVs weren't reachable from their own machine from genie python. This was mostly GOODUAH for waitfor_uah calls, but also some user parameters and other PVs. 

This gave lots of errors and lost a lot of beam time, and eventually crashed some scripting consoles in clients after the PV could be eventually reached. 

We traced this down to being CaChannel/genie python as the genie python consoles, BSKAFKA and dataweb all fell over, which are all linked to the use of CaChannel  - we _think_ everything else was reachable from Channel access or we'd see loads of errors in the client about observable PVs.  

In the shutdown we should try and reproduce this by killing control-svcs when doing a waitfor_uah or similar and see if the same behaviour occurs - if so there may be some reliance on it. It could be a central PV ie the beam current pv or could be gateway related. 

### Acceptance criteria
- [ ] During shutdown control svcs is killed while doing a waitfor_uah to see if we can reproduce this issue. 

Note: this happened on EMU, POLREF, INTER, MAPS, MARI, NIMROD, SANS2D and POLARIS, if more info needed check logs from about 00:06 on the 12/12/23 or again at 10:47 - errors are present in the genie python log

**Comment by FreddieAkeroyd** [comment]
I believe the issues were caused by a gateway loop resulting in multiple replies to a PV search. Things on monitors were probably unaffected, waitfor in genie python polls and hence searches each time.  Maybe we were unlucky with some of the replies and it caused a crash - it shouldn't, but maybe we were just unlucky on a few instruments.

**Comment by FreddieAkeroyd** [comment]
The error message from a genie python log was
```
[2023-12-12T00:26:27] [39312:22408] [ERROR]	CAException: type=-1 state=200 op=5 file=C:\Instrument\Apps\EPICS\base\master\modules\ca\src\client\cac.cpp lineNo=1320
```
This is in function `cac::pvMultiplyDefinedNotify` as per https://github.com/ISISComputingGroup/EPICS-base/blob/f9bda724b20b69d776075e0053fa01bbd802da85/modules/ca/src/client/cac.cpp#L1311

The duplicate pvs were caused by the epics gateway on control-svcs, our gateway setup currently relies on firewall rules on control-svcs to control some of the access from non isis networks, such as VPN or eduroam. Suggest move investigation to separate ticket #8168
