### ISSUE TITLE
DAE view: axes reported to reset [TIMEBOX:1.5 days]

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8307]
## Where?
On the Combined spectra and spectra plot tabs of the DAE view in the GUI, it is reported that when a log axis is selected (or other customisation), this resets after a few minutes to the defaults.

## How?
Lamor (RD) reported in the release feedback session that this behaviour exists.

## Reproducible?
I have not been able to reproduce it on my local instance

### To Reproduce
May require further information from LAMOR instrument scientists

## Acceptance criteria 
- [ ] The behaviour is confirmed to exist (if neccercery asking the instrument scientist to demonstrate the issue)
- [ ] It is understood how to reproduce the behaviour
- [ ] The bug is fixed so that behviour no longer occours

## How to Test 
Instructions for reproducing the bug are followed and when the fix is applied the behaviour stops

_verbose instructions for reviewer to test changes
(**Add before making a PR**)_

Discussed ~1:27 20/06/24

**Comment by Tom-Willemsen** [comment]
I've been able to find 3 ways to cause this, but none of which I think users would be doing "every few minutes":
- Reset layout (implicitly reloads OPIs in the current perspective)
- Explicit right click in OPI and refresh (by design this should reset in-OPI customizations to default)
- Switch instrument ("refresh PVs" doesn't cause it, only a full instrument switch does)

Have sent an email to RD asking exactly when this occurs / whether we can come and troubleshoot it if it's happening consistently every few minutes on LARMOR.

**Comment by Tom-Willemsen** [comment]
Haven't been able to reproduce locally, RD has not got back to me about seeing this on LARMOR after chasing a couple of times.

Going to close off this issue for now - can be reopened if the issue recurs (preferably with _precise_ reproduction steps if so)
