### ISSUE TITLE
OPI descriptions: add default macro values

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#844]
Extend the XML for the opi_info.xml file to allow default/recommended values to be added where appropriate.

== Notes ==
1. See also #769 (do it at the same time).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 845.  Created by mjc23 on 2015-07-17T08:28:22, last modified: 2015-08-28T15:03:16_

**Comment by IsabellaRey** [comment]
NOTE: Ticket #769 was done while doing #1289.

The current ticket was not done, because it adds new functionality which is worth discussing separately as a team:
do we really want the macro values to be pre-filled with a default? This would make it impossible to distinguish where the macro was set intentionally and where it was forgotten and it simply retained the default.
Maybe a better way would be to have a "Use Default" button in the GUI that populates the macro with a default value set in the opi_info.xml. This way any setting is intentional.

**Comment by KathrynBaker** [comment]
This has been included at some point - closing this ticket
