### ISSUE TITLE
Mysql - update on instruments not being deployed to

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#8482]
We need to separately update MySQL on instruments that are not having a new ibex deployment in #8467

there is a `summer_update.bat` script to do this

IMAT
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete
	
IMAT-UCBDETECT (32-bit)	
- [ ] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

ENGINX	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

ENGINX_SETUP	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

ENGINX-STRESS1 (32 bit)	
- [ ] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

CRISP
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

INTER	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

OFFSPEC	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

POLREF	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SURF	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

LARMOR	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

LOQ	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

SANS2D	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

ZOOM	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

GEM	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

HRPD	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

HRPD_SETUP	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

INES	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

PEARL	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

PEARL_SETUP	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

POLARIS	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

WISH	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

WISH_SETUP	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

EMMA	
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

CRYOLAB_R55	
- [ ] NDX and NDH patches done
- [ ] In Progress
- [ ] Complete

CRYOLAB_R80
- [x] NDX and NDH patches done
- [x] In Progress
- [x] Complete

**Comment by Tom-Willemsen** [comment]
It would also be good to deploy the log rotation script at the same time.

The log rotation script can simply be copied in from a recent build (it's located in `c:\instrument\apps\epics\utils\logrotate.py`)

The scheduled task has an upgrade step which can set it up, since we'll be running the script anyway for mysql it makes sense to do the log rotation too.

**Comment by FreddieAkeroyd** [comment]
cryolab_r55 may no longer exist, engginx-stress1 and imat-ucb-detect both seem to be powered off at the moment

**Comment by Tom-Willemsen** [comment]
Spun out imat-ucbdetect and enginx-stress-1 into a task so that we can get this ticket through - they're both "weird" machines in that they're both 32 bit and will require some coordination with scientists to ensure these PCs are plugged in but hardware is in a safe state etc.

cryolab_r55 seems to no longer exist.
