### ISSUE TITLE
GUI looks bad on Windows 10

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#880]
The Dashboard and Spangle Banner don't look right on Windows 10. It may be that it also looks bad on linux.

Perhaps the UI containers used to construct the Dashbaord and Spangle Banner are not set up correctly.

The DAE UI, for example, renders perfectly on !WinTen (as all the cool kids are calling it).

**Comment by kjwoodsISIS** [comment]
_Imported from trac issue 881.  Created by mjc23 on 2015-08-26T11:41:02, last modified: 2015-08-28T15:03:16_

**Comment by kjwoodsISIS** [comment]
_Trac comment by whb43145 on 2015-08-26 17:15:31:_

For testing this might be useful http://dev.modern.ie/tools/vms/windows/.

**Comment by Tom-Willemsen** [comment]
This is caused by high(er) screen resolutions than expected and scaling of fonts.

Temporary fix is to change display resolution to 1920x1080 or less and ensure font scaling is set to 100%.

This information has been added to the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-the-GUI)

**Comment by kjwoodsISIS** [comment]
This issue can, perhaps, be addressed by move to E4.  No further need for this ticket to remain open.
